### ISSUE TITLE
[Server] hatohol server finishes soon with an error message when failed to connect with NDOUtils.

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#1]
[cen]~/tmp $ HATOHOL_DB_DIR=~/tmp/ hatohol --config-db hatohol-config.db
[INFO] <main.cc:101> started hatohol server: ver. 0.0.2
[INFO] <DBClientConfig.cc:277> Configuration DB: hatohol-config.db
[INFO] <FaceRest.cc:102> started face-rest, port: 33194
[INFO] <ArmZabbixAPI.cc:900> started: ArmZabbixAPI (server: localhost)
[INFO] <FaceRest.cc:151> exited face-rest
[INFO] <FaceRest.cc:110> FaceRest: stop process: started.
[INFO] <FaceRest.cc:116> FaceRest: stop process: completed.
[ERR] <main.cc:151> Got exception: <DBAgentMySQL.cc:48> Failed to connect to MySQL: udoutils: Access denied for user 'udoutils'@'localhost' (using password: YES)

**Comment by ashie** [comment]
It doesn't reproduce in the current master.
The thread for the NDOUtils continue to work (show errors on every polling).
