### ISSUE TITLE
[request]Format of the HAPI-JSON

### ISSUE THREAD

**Issue by satomi-0929** [project-hatohol/hatohol#1009]
When I register an event in HAPI-JSON, I want to appoint the status.

I want you to add the variable of "the status" to the following items to notify manager of the event (ex.OK, unknown) except the problem.

https://github.com/project-hatohol/hatohol/wiki/HAPI-JSON

event
event type message must has the following format:

{
  "type": "event",
  "body": {
    "id": ${Event ID as an integer},
    "timestamp": ${Event occurred time as UNIX time in float or ISO 8601 format string},
    "hostName": "${Host name where event is occurred as string}",
    "content": "${Event detail as string}",
    "severity": "${Severity of the event (optional) (default: unknown)}"
  }
}

**Comment by kz0817** [comment]
Thank you for the suggestion.
You mean you want to add an event that is not a abnormal thing (recovery or just information), don't you ?

**Comment by satomi-0929** [comment]
Yes,I do.

**Comment by kou** [comment]
It's reasonable.

What about the following API?

```text
{
  "type": "event",
  "body": {
    ...,
    "type": ${"good" OR "bad" OR "unknown",
    ...
  }
}
```

If you specifies `"type": "bad"`, it's the current behavior.

**Comment by satomi-0929** [comment]
Thank you for your comment.
I try it.

**Comment by kou** [comment]
Ah, it's not implemented yet.
It's just new API idea.

**Comment by kou** [comment]
I implemented the feature at #1011.
(It's not merged yet.)

**Comment by kou** [comment]
It's merged.
You can try it on master.

Thanks for your request!

**Comment by satomi-0929** [comment]
I'm sorry for the late response.
Thank you for correspondence！　:-)
