### ISSUE TITLE
[server] HAPIの自己監視トリガが重複して表示される

### ISSUE THREAD

**Issue by ashie** [project-hatohol/hatohol#1046]
環境:

  * Hatoholのバージョン: #1036 Use new host management rebase 7のマージ以後

再現手順:

  * Zabbix (HAPI)の監視サーバを一つ追加する
  * トリガーページを開く
  * 自己監視ホスト名でフィルタをかける

期待する結果:

  * トリガーが6個表示される

実際の結果:

  * トリガーが12個表示される(自己監視トリガーが全て重複している)

備考:

  * DB内には6つのみ登録されている(重複していない)

![duplicate-triggers](https://cloud.githubusercontent.com/assets/135104/6438551/85b63e94-c10d-11e4-8d6c-5a856d3e7f0e.png)

**Comment by ashie** [comment]
> 自己監視ホスト名でフィルタをかける

確認しやすいようにフィルタをかける手順を加えているが、実際にはフィルタをかけなくても重複している。

**Comment by ashie** [comment]
トリガー取得のSQL文 (フィルターはかけていない):

```
SELECT triggers.server_id,triggers.id,triggers.status,triggers.severity,triggers.last_change_time_sec,triggers.last_change_time_ns,triggers.host_id,triggers.hostname,triggers.brief,triggers.extended_info FROM triggers LEFT JOIN server_host_def ON (triggers.server_id=server_host_def.server_id AND triggers.host_id=server_host_def.host_id_in_server) WHERE triggers.server_id IN (1) AND server_host_def.status!=1 LIMIT 50
```

`LEFT JOIN`で、`triggers.host_id=server_host_def.host_id_in_server`をキャストすると重複しなくなる。

```
triggers.host_id=cast(server_host_def.host_id_in_server as unsigned)
```

全てのホストIDを文字列で管理する修正が入ると解消されるのかもしれませんが、一応報告しておきます。

**Comment by kz0817** [comment]
報告ありがとうございます。対応します。

**Comment by kz0817** [comment]
#1054のマージで解決されました。closeします。
