### ISSUE TITLE
[web]Query language from the UI has not been unified.

### ISSUE THREAD

**Issue by o-wakabayashi** [project-hatohol/hatohol#1052]
UIで操作を行った際に、ユーザに操作の確認を行う問い合わせ文言が統一されていない。
【現状】
client/static/js/actions_view.js:56 / client/static/js/servers_view.js:61 / 
client/static/js/log_search_systems_view.js:53 / client/static/js/incident_settings_view.js:56 /
client/static/js/users_view.js:57
 en： Do you delete the selected items ?
 ja： 選択項目を削除してもよろしいですか？

client/static/js/hatohol_incident_trackers_editor.js:79:    
 en： Are you sure to delete incident tracking servers?
 ja： インシデント管理サーバーを削除してもよろしいですか？

client/static/js/hatohol_user_roles_editor.js:80:
 en： Are you sure to delete selected items?
 ja： 選択項目を削除してもよろしいですか？

en：”Do you ～”と”Are you sure ～”の2種類が存在する
ja：”～よろしいですか？”と”Are you sure ～”に近い訳になっている

【変更案】
en：”Do you ～”で統一
ja：”～しますか？”で統一

**Comment by cosmo0920** [comment]
こちら #1061で対応が入っているのでクローズします。
