### ISSUE TITLE
[server] It takes a long time (few minutes) to exit a server.

### ISSUE THREAD

**Issue by t-miyazawa** [project-hatohol/hatohol#1060]
Hatoholサーバに終了シグナルを送ったが、停止するまで数分かかる場合がある。
この時のログは https://github.com/project-hatohol/hatohol/issues/160 参照

**Comment by t-miyazawa** [comment]
mysql_real_connect() 内で自動リトライしていて、タイムアウトするまで127秒程かかっている。
MYSQL_OPT_RECONNECTをfalseに設定するとmysql_real_connect() は2,3秒でタイムアウトする。
Hatohol自身でエラー時はリトライしているのでmysql_xxx()内の自動リトライは行わなくても良いのではないか？

**Comment by kz0817** [comment]
> MYSQL_OPT_RECONNECTをfalseに設定する

これは、セッション毎の設定ですか？それとも、システムワイドですか？

**Comment by cosmo0920** [comment]
https://github.com/project-hatohol/hatohol/issues/160#issuecomment-76120228 にあるように、
DBAgentMySQLの `DBAgentMySQL::sleepAndReconnect` を interruptible sleep な実装に変えてみたこのブランチ https://github.com/project-hatohol/hatohol/compare/interruptible-wait-db-agent ではhatoholサーバーは終了シグナルを送るとすぐに終了するようになっているでしょうか？
（テストがどこかこけてくれる事を期待したのに全部通ってしまっていまいち自信がありません）

**Comment by cosmo0920** [comment]
上記ブランチだとMySQLへのコネクションのリトライに適切な時間待っていないですね。。

**Comment by cosmo0920** [comment]
適切な時間待つようにしたコミット https://github.com/project-hatohol/hatohol/commit/d29ea7ad4303f8223750f2a11abb087d43a2ee0a で適切な時間待ちつつ、SIGHUPを送るとすぐに終了するようになった。

```log
$ ps -aux | grep hatohol
hhatake    441  0.1  0.0 928660 12844 pts/9    Sl+  14:04   0:00 /home/hhatake/Github/hatohol/server/src/.libs/lt-hatohol --db-server localhost -n hatohol -f --test-mode --log-level=DBG
hhatake   1801  0.0  0.0  16908   940 pts/34   S+   14:04   0:00 grep --color=auto hatohol
$  kill -SIGHUP 441 
```


```log
[ERR] <DBAgentMySQL.cc:640> Failed to query: SELECT host_object_id,display_name FROM nagios_hosts: (2006) MySQL server has gone away.
[INFO] <DBAgentMySQL.cc:651> Try to connect after 0 sec. (1/5)
[ERR] <DBAgentMySQL.cc:578> Failed to connect to MySQL: ndoutils: (error: 2003) Can't connect to MySQL server on '192.168.1.42' (111)
[INFO] <DBAgentMySQL.cc:651> Try to connect after 10 sec. (2/5)
[DBG] <ZabbixAPI.cc:232> authToken: 066c15faabd65b0196f928a51148c495
[DBG] <ZabbixAPI.cc:496> The number of hosts: 2
[DBG] <ZabbixAPI.cc:535> The number of groups: 2
[DBG] <ZabbixAPI.cc:232> authToken: 7bd3d7a55ed887f5a240b95bd4155e31
[DBG] <ZabbixAPI.cc:277> The number of triggers: 0
[DBG] <ZabbixAPI.cc:316> The number of trigger expanded descriptions: 0
[DBG] <ZabbixAPI.cc:664> The last event ID in monitoring server: 1028
[DBG] <ArmZabbixAPI.cc:130> The last event ID in Hatohol DB: 1028
[DBG] <ArmBase.cc:174> lastPollingTime: 1426827929
[DBG] <ZabbixAPI.cc:496> The number of hosts: 10
[DBG] <ZabbixAPI.cc:535> The number of groups: 2
[DBG] <ZabbixAPI.cc:277> The number of triggers: 0
[DBG] <ZabbixAPI.cc:316> The number of trigger expanded descriptions: 0
[DBG] <ZabbixAPI.cc:664> The last event ID in monitoring server: 15543
[DBG] <ArmZabbixAPI.cc:130> The last event ID in Hatohol DB: 15543
[DBG] <ArmBase.cc:174> lastPollingTime: 1426827929
[INFO] <main.cc:103> recieved stop request.
[INFO] <main.cc:78> start exit process on the dedicated thread.
[INFO] <ArmBase.cc:326> ArmZabbixAPI [1:..]: requested to exit.
[INFO] <ArmBase.cc:254> ArmZabbixAPI [1:..]: destruction: completed.
[INFO] <ArmBase.cc:326> ArmZabbixAPI [2:..]: requested to exit.
[INFO] <ArmBase.cc:254> ArmZabbixAPI [2:..]: destruction: completed.
[INFO] <ArmBase.cc:326> ArmNagiosNDOUtils [3:..]: requested to exit.
[INFO] <ArmBase.cc:254> ArmNagiosNDOUtils [3:..]: destruction: completed.
[INFO] <ArmBase.cc:326> ArmNagiosNDOUtils [4:nagios..]: requested to exit.
[ERR] <DBAgentMySQL.cc:578> Failed to connect to MySQL: ndoutils: (error: 2003) Can't connect to MySQL server on '192.168.1.42' (111)
[DBG] <HatoholException.cc:74> HatoholException: <DBAgentMySQL.cc[50]:662> Failed to connect to MySQL: ndoutils: (2006) Can't connect to MySQL server on '192.168.1.42' (111)

[ERR] <ArmNagiosNDOUtils.cc:828> Error Connection: <DBAgentMySQL.cc:662> Failed to connect to MySQL: ndoutils: (2006) Can't connect to MySQL server on '192.168.1.42' (111)

 50
[DBG] <ArmBase.cc:174> lastPollingTime: 1426827933
[INFO] <ArmBase.cc:254> ArmNagiosNDOUtils [4:hhatake-nagios.local]: destruction: completed.
[INFO] <FaceRest.cc:220> exited face-rest worker
[INFO] <FaceRest.cc:220> exited face-rest worker
[INFO] <FaceRest.cc:220> exited face-rest worker
[INFO] <FaceRest.cc:220> exited face-rest worker
[INFO] <FaceRest.cc:415> exited face-rest
[INFO] <FaceRest.cc:278> FaceRest: stop process: started.
[INFO] <FaceRest.cc:285> FaceRest: stop process: completed.
```

**Comment by t-miyazawa** [comment]
mysql_real_connect()の動作について訂正： 
* mysql_real_connect() はMYSQL_OPT_RECONNECTの設定によらず3～127秒でタイムアウトする
* MySQL Server virsion: 5.5.41-0ubuntu0.14.04.1 のデフォルトはMYSQL_OPT_RECONNECTがfalse
* 初回エラー検出時は127秒かかり、その後mysql_real_connect()が連続で失敗するとタイムアウトが3秒まで短くなる模様
* 接続時のタイムアウト時間を短くしたい場合はMYSQL_OPT_CONNECT_TIMEOUTでT.O.秒を指定する。有効範囲は1～127秒 (範囲外だとデフォルト動作になる模様）

**Comment by t-miyazawa** [comment]
終了時ブロックする箇所
* Nagios監視時： DBAgentMySQLのconnect()失敗時のリトライ(0,10,60,60,60)
* Nagios監視時： mysql_real_connect()完了待ち
* Zabbix監視時:  soup_session_send_message()完了待ち
* HAPI, Ceilometerは未確認

**Comment by t-miyazawa** [comment]
soup_session_send_message() は soup_session_abort(m_impl->session); でキャンセル(アボート)可能

**Comment by kz0817** [comment]
調査ありがとうございます。

> 接続時のタイムアウト時間を短くしたい場合はMYSQL_OPT_CONNECT_TIMEOUTでT.O.秒を指定する。有効範囲は1～127秒 (範囲外だとデフォルト動作になる模様）

Hatohol側でリトライのロジックを持っているので、MySQLそのものタイムアウト時間は短くした
ほうが使い勝手が良さそうですね。値については、次回のFace2Faceミーティングで決定しましょう。
私の提案は、デフォルト10秒 (＋できれば設定ファイルで可変）。

**Comment by kz0817** [comment]
> soup_session_send_message() は soup_session_abort(m_impl->session); でキャンセル(アボート)可能

libsoupのAPIのabortは、まだ、Hatoholに実装されてないですよね？
さくっとやっちゃいましょうよう。

**Comment by t-miyazawa** [comment]
> Hatohol側でリトライのロジックを持っているので、MySQLそのものタイムアウト時間は短くした
> ほうが使い勝手が良さそうですね。値については、次回のFace2Faceミーティングで決定しましょう。
> 私の提案は、デフォルト10秒 (＋できれば設定ファイルで可変）。

接続タイムアウト時間はMySQLの設定ファイルで設定可能です。
<pre>
[client]
connect-timeout=10
</pre>

**Comment by kz0817** [comment]
> 接続タイムアウト時間はMySQLの設定ファイルでも設定可能です。

なるほど。MySQLの設定ファイルってmy.confですか？
そうするとシステムワイドになりますよね。
セッション毎にAPIとかでも、設定できそうですか？

**Comment by ashie** [comment]
ちなみにHatoholはmy.cnfのhatoholセクションも読み込むので

```
[hatohol]
connect-timeout=10
```
でもいけると思います。

**Comment by kz0817** [comment]
> ちなみにHatoholはmy.cnfのhatoholセクションも読み込むので

なるほど。

**Comment by t-miyazawa** [comment]
MySQLの設定は my.cnf でも良いですし、/etc/mysql/conf.d/xxx.cnf でもubuntu14.04では読み込まれます。
[client]ではなく[hatohol]に記述にすればアプリケーション固有にできます。（既存のコードでこのグループを読み込むように指定しているためソース修正不要）
