### ISSUE TITLE
masterでceilometerを監視すると、以下のErrorが発生する。

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#1065]
2015/3/5のmasterでCeiloemterを監視すると以下のエラーが発生する。

Mar  5 20:38:06 hatoholVM1 hatohol[18809]: [ERR]
<HatoholArmPluginInterface.cc:743> Caught exception:
<../../server/common/ItemData.h:244> Undefined operation: 'cast to
const uint64_t &' (String) (ItemID: 127)#012

2015/3/4のmasterでは問題なし。
Host IDを文字列化した際にデグレしたと思われる。

**Comment by ashie** [comment]
受け側ではuint64_tを期待しているのに

https://github.com/project-hatohol/hatohol/blob/master/server/common/ZabbixAPI.cc#L1120

送り側ではstringを投げてるからですね。

https://github.com/project-hatohol/hatohol/blob/master/server/hap/HapProcessCeilometer.cc#L1040

**Comment by kz0817** [comment]
ただ、一連のID文字列化の流れのなかでは、ItemInfo内のHostIdもstringで扱うことになるので、そのように修正するパッチを作成します。その際、Ceilometer側（StringでHostIDを送信）をそのままにして、Zabbix側が文字列としてのHostIDを送信するようにします。

**Comment by ashie** [comment]
#1080、#1090、#1096 で修正された
