### ISSUE TITLE
Once initial connecting Zabbix and Nagios failed, self monitoring event table is not update.

### ISSUE THREAD

**Issue by cosmo0920** [project-hatohol/hatohol#1101]
ZabbixとNagiosへの初回接続に失敗すると、イベントのステータスが失敗したカラムの上に何も追記されない状態になってしまいます。
最初の接続の時しかSelf Monitoring のイベントステータスが追記されません。

わざとZabbixとNagiosへの接続が失敗するようにすると、イベントのステータスの表示が異常となったカラムが上部に残ったままとなります。

![screenshot from 2015-03-13 13 55 35](https://cloud.githubusercontent.com/assets/700876/6633239/f08d671e-c988-11e4-8b3d-4a11feeacaf5.png)

以下のようにZabbixとNagiosへの接続は成功しているので深刻度のカラムの色が消えたカラムがイベントテーブルに追記されることが期待されます。

![screenshot from 2015-03-13 13 55 50](https://cloud.githubusercontent.com/assets/700876/6633241/f38d6306-c988-11e4-9e86-23a0977b8dcd.png)

**Comment by cosmo0920** [comment]
こちらの現象は誤った情報を登録した時に、self monitoringサーバーの接続に失敗したイベントが記録され、再度正しい情報を登録した際に接続に成功したイベントが発生しないことによるものでした。
これは今のところ仕様の動作だそうです。

**Comment by ashie** [comment]
というわけで動作上は問題なさそう。

ただ`ArmBase::setServerConnectStatus()`で正常か障害かにかかわらず

```
m_impl->utils.updateTriggerStatus(type, TRIGGER_STATUS_PROBLEM); 
```

としているのが紛らわしい

**Comment by cosmo0920** [comment]
正常に登録されたself monitoringホストに対しては正常に動作するので特に問題はなさそうです。

ただ、登録するのに失敗したホストを編集して登録に成功した時に、
失敗したイベントが残り続けて成功したイベントが追記されないため、
イベントページに残り続けるのにギョッとしました。。

**Comment by ashie** [comment]
このissueとしては、ユーザーがサーバ設定を修正して正常状態に戻した場合にも正常復帰のイベントを
発生させた方がよい、という問題としておく。

ただ現在の実装では設定を変更したときにセルフトリガーの状態を管理しているArmBaseインスタンスを
削除してしまうので、修正は少し面倒そう。

**Comment by Mnakagawa** [comment]
We will reconsider around early June.

**Comment by Mnakagawa** [comment]
組み込みの両者は16.04で削除予定なので、このIssueもクローズする
