### ISSUE TITLE
サーバの削除権限が無いユーザーでは「監視サーバートリガー再読込」ボタンを使用できない

### ISSUE THREAD

**Issue by ashie** [project-hatohol/hatohol#1108]
サーバの削除権限が無いユーザーで「監視サーバー」ページを見たとき、「監視サーバートリガー再読込」
ボタンは表示されるが、各サーバのチェックボタンは表示されないため、ボタンを有効化することができない。
（上記チェックボックスはサーバの削除権限が無いと表示されない）

**Comment by ashie** [comment]
![disabled-trigger-reload](https://cloud.githubusercontent.com/assets/135104/6635282/8cf9ef5a-c9a7-11e4-9ad1-085389b06a63.png)

**Comment by o-wakabayashi** [comment]
すみません、いろいろ考慮不足です。
どういう権限で何ができるか検討します。

若林的には、更新権限があるユーザの場合は表示するようにしたい。
なんの権限もない -> 表示しない
更新権限がある -> 表示する
削除権限がある -> 表示しない
更新＆削除権限がある -> 表示する

2015-03-13 17:37 GMT+09:00 Takuro Ashie <notifications@github.com>:

**Comment by cosmo0920** [comment]
> 若林的には、更新権限があるユーザの場合は表示するようにしたい。

という事は若林さん案では新たに更新権限が増えるという事ですね。

**Comment by ashie** [comment]
トリガー再読み込みの権限が既存のどの権限に該当するかというのは微妙なところですね。
(閲覧権限以外の)どの権限にも該当しないような。
どうすべきなのか、今のところ私もよくわかってません。

**Comment by o-wakabayashi** [comment]
（こっち忘れてた）

トリガー再読み込みの権限が既存のどの権限に該当するかというのは微妙なところですね。
(閲覧権限以外の)どの権限にも該当しないような。
→う～ん、そうですね。妥当な気がする。

トリガーの再読込は通常の監視の範囲だし、とくに設定が変わるわけではない。
何か作業（監視対象側で）したら必要な操作でもあります。もっと言うと、
トリガーの再読込は権限に関係なく、自動（サーバの増減を検出）でも実施される
ので、閲覧権限があれば再読込ができるがよいと思います。
→監視の権限があればじっしできる。 ★


2015年3月16日 11:27 Takuro Ashie <notifications@github.com>:

**Comment by ashie** [comment]
#1122 で対応済み

**Comment by o-wakabayashi** [comment]
魚、そうだったんですね。
失礼しました。

2015-03-17 7:40 GMT+09:00 Takuro Ashie <notifications@github.com>:
