### ISSUE TITLE
Probably events aquisition by ArmNagiosNDOUtils doesn't work well.

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#1114]
getMaxEventId(), recently added method as a replacement of getLastEventId(),
just returns the result of max(eventID) in an SQL statement.

To make it work correctly, all the event IDs should have the same digit number
with zero padding as ArmZabbixAPI does.

See also
ZabbixAPI::parseAndPushEventsData()
pushString(parser, grp, "eventid",      ITEM_ID_ZBX_EVENTS_EVENTID, EVENT_ID_DIGIT_NUM, '0');

**Comment by ashie** [comment]
#1121 で対応済み
