### ISSUE TITLE
JSON形式で送られてきたイベントを表示する際にエラーが発生する

### ISSUE THREAD

**Issue by Mnakagawa** [project-hatohol/hatohol#1177]
#1175 を適用済みのパッケージで「サーバータイプ：JSON」から発生したイベントを表示する際に画像のようなダイアログが表示されエラーが発生する。Zabbixサーバーから発生したイベントのみの場合はこのような現象は発生しなかった。

また，この現象発生後はイベントページのみならずトリガーページや最新アイテム，アクションなどダッシュボード以外のほぼすべてのページで同様の現象を確認した。

![screenshot from 2015-03-27 14 15 26](https://cloud.githubusercontent.com/assets/7106792/6862922/0a61bfa6-d48c-11e4-890e-017eb781b4c5.png)

**Comment by Mnakagawa** [comment]
憶測の域を出ないが，なにもアクションを登録していないアクションページで同様の現象が発生するということは，
serversオブジェクトになにか問題があるのではないかと思った。
以下はサーバーのオブジェクト（zabbixサーバーは取り除いている）。

```
"servers" : {"2" : { "name" : "fluent", "nickname" : "fluent", "type" : 4, "ipAddress" : "", "baseURL" : "", "hosts" : { { "name" : "nakagawa" } }, "triggers" : { }, "groups" : { } } } 
```

恐らくhostsオブジェクトに問題がある。ホスト番号に対応した｛｝の中身はキーとバリューの組になっている必要があるはずだが，上記のhostsオブジェクトではオブジェクトの中にキーが存在していない。ここでのキーは各ホストのhosts_id_in_serverのはず。ここにキーが存在していないため，jsがエラーを起こしているのではないだろうか。

**Comment by Mnakagawa** [comment]
現在のログモニタリングシステムでは，そもそもhostという概念が無いため，このhosts_id_in_serverは空白としてデータベースにデータが格納されている。

解決策としてはログモニタリングシステムの方に手を入れる（hosts_id_in_serverに適当な値を入れてイベントを発行する）か，jsの方でキーがないオブジェクトが来た時の処理を入れるか，の2つがあると思う。
これから新機能を追加していくにあたって，ホストが存在しないイベントというのは増えていくと思われるので，そういったものに対応していくためにも後者の解決法が望ましいのではないかと思う。

**Comment by ashie** [comment]
HAPI JSONかどうかに関係なく、IDが空のホストを登録すると確かにそうなる。

**Comment by o-wakabayashi** [comment]
（見当違いなこと言ってたらごめんなさい）
IDが空のホストっていうのはhosts_id_in_serverがNULLってことですか？。

自己監視（__SELF_MONITOR）みたいに、「IDが空」を表すようなIDを用意するとか。
（HAPI JSON用のIDを用意する）

2015-03-27 16:21 GMT+09:00 Takuro Ashie <notifications@github.com>:

**Comment by ashie** [comment]
hosts_id_in_serverがNULLか""の場合ですね。

**Comment by ashie** [comment]
もともとHAPI JSONはhostName毎にIDを振っているので、IDをhostNameにするので良さそう。
ただし、空のhostNameではホストの登録を許さない。

仮にeventに空のhostIdが入っている場合、ホストの表示は`不明 (ID:)`となるので、これで問題ないはず。

**Comment by ashie** [comment]
> 仮にeventに空のhostIdが入っている場合、ホストの表示は不明 (ID:)となるので、これで問題ないはず。

ただし、IDが空のホストでフィルターをかけることはできない。
