### ISSUE TITLE
Firefox clashed when monitoring server has many  trigger.

### ISSUE THREAD

**Issue by Mnakagawa** [project-hatohol/hatohol#1188]
I take a report from my coagent.
He says, 
"When I access to overview:Triggers by Firefox(36.0.4) on Windows, Firefox clashed.
Then I am monitoring Zabbix only. Zabbix has 1000~2000 triggers."

We need to research a this problem.

**Comment by Mnakagawa** [comment]
We don't have as previous environment.
So, we need to make dummy datum of trigger.

**Comment by Mnakagawa** [comment]
I confirm this problem by to insert two thousand dummy datum into triggers table of hatohol DB.
But Firefox didn't clash in my environment.

**Comment by Mnakagawa** [comment]
I confirmed it not only Ubuntu but also Windows 7.

**Comment by bynnchapu** [comment]
> I confirmed it not only Ubuntu but also Windows 7.

Please tell us that more your environment.
It is good to have every possible information.

Example:
- Firefox Version
- CPU architecture

and more...

**Comment by Mnakagawa** [comment]
> Please tell us that more your environment.

Sure.

I confirmed there by Firefox(36.0.4 & 17.0.1) on Windows 7 & Firefox(37.0.1) on Ubuntu.
CPU architecture is x86_64 both Windows 7 & Ubuntu .

**Comment by Mnakagawa** [comment]
I verify  amount of using memory.

2000 triggers = 165KB
20000 triggers = 260KB

I think , this problem is caused by my coagent environment.
It is possibility that is they activate a browser on low spec evnrironment. (ex. Memory, CPU)
Should we write recommended environment about machine that activate browser?

**Comment by Mnakagawa** [comment]
I could not  reproduce this issue, so I won't fix.
