### ISSUE TITLE
An RPM package for CentOS7 doesn't create the directory for the pid file.

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#1191]
The RPM package for CentOS6 creates $localstatedir/run/hatohol for putting PID file. However, the one for CentOS7 doesn't.

Is there any reason why the creation is not included for CentOS7 ?

From hatohol.spec.in
<pre>
%if %is_el6
install -D -m 644 %{buildroot}/%{_libexecdir}/hatohol/client/conf/apache/hatohol.conf.package6 %{buildroot}/%{_sysconfdir}/httpd/conf.d/hatohol.conf
install -D -m 755 %{buildroot}/%{_datadir}/hatohol/hatohol.centos %{buildroot}/%{_sysconfdir}/init.d/hatohol
install -d -m 755 %{buildroot}/%{_localstatedir}/run/hatohol
%endif
%if %is_el7
install -D -m 644 %{buildroot}/%{_libexecdir}/hatohol/client/conf/apache/hatohol.conf.package7 %{buildroot}/%{_sysconfdir}/httpd/conf.d/hatohol.conf
install -D -m 644 %{buildroot}/%{_datadir}/hatohol/hatohol.service %{buildroot}/%{_unitdir}/hatohol.service
install -D -m 644 %{buildroot}/%{_datadir}/hatohol/hatohol.conf %{buildroot}/%{_tmpfilesdir}/hatohol.conf
%endif
</pre>

**Comment by bynnchapu** [comment]
Because, CentOS7 has ```tmpfiles.d``` component which creates a directory for putting PID file when system is booted.
So, we set to use ```tmpfiles.d``` component when user use Hatohol installing as RPM packages.

**Comment by kz0817** [comment]
Thank you for the reply.

> when system is booted.

So should we need to reboot a machine after the RPM is installed ?

**Comment by bynnchapu** [comment]
See also: 
- [data/systemd/hatohol.conf](https://github.com/project-hatohol/hatohol/blob/master/data/systemd/hatohol.conf)
- [Man of tmpfiles.d](http://www.freedesktop.org/software/systemd/man/tmpfiles.d.html)

Supplement:
```/run``` directory is mounted as ```tmpfs```.
CentOS7 uses ```systemd``` as init daemon.
So, we can not create directory for putting PID file as usual.
Because, service file is not shell script.

**Comment by bynnchapu** [comment]
>> when system is booted.

> So should we need to reboot a machine after the RPM is installed ?

No, we should not.
```systemd-tmpfiles``` creates directory for it when Hatohol RPM is installed on the system.

See: [L157 in hatohol.spec.in](https://github.com/project-hatohol/hatohol/blob/master/hatohol.spec.in#L157)

See also:
[Man of systemd-tmpfiles](http://www.freedesktop.org/software/systemd/man/systemd-tmpfiles.html)

**Comment by kz0817** [comment]
Thank you for the reply.

In my local CentOS7 as a LXC container on the host of CentOS7,
/var/run/hatohol was not created although I installed the RPM.
So I asked this topic.

I'll look into that a little bit more.

**Comment by kz0817** [comment]
In my environment described above, /run and /run/hatohol surely exist. However, /var/run is not a sym. link to /run.

If %{_tmpfilesdir} in the spec. file is replaced to /run, the Hatohol server should use the directly, not LOCALSTATEDIR "/run".
