### ISSUE TITLE
TravisでRabbitMQを扱いたい

### ISSUE THREAD

**Issue by cosmo0920** [project-hatohol/hatohol#1211]
TravisのUbuntuにインストールできるrabbitmq-cのバージョンがかなり低いです。

rabbitmq-cのバージョンがUbuntu Precise(12.04 LTS)では[0.0.1と古く](http://packages.ubuntu.com/source/precise/librabbitmq)、configureの https://github.com/project-hatohol/hatohol/blob/master/configure.ac#L96 のチェックを通りません。

今のTravisのビルドインフラを使う前提でこのissueを扱うのであれば、
例えば、Ubuntu Precise向けのlibrabbitmq(rabbitmq-c)の0.4.1以上のバージョンのdebパッケージを作る必要があります。

**Comment by cosmo0920** [comment]
https://launchpad.net/~cosmo0920-oucc/+archive/ubuntu/rabbitmq-c
librabbitmq 0.5.0のPPAを作ってみました。

```bash
$ sudo apt-add-repository ppa:cosmo0920-oucc/rabbitmq-c
```

でUbuntu Preciseへインストールできるハズ。

**Comment by cosmo0920** [comment]
Gotcha! Travis CIでrabbitmq 0.5.0のインストールに成功してきちんと checking for LIBRABBITMQ... yes が出せました！ https://travis-ci.org/project-hatohol/hatohol/jobs/70910811#L1043

**Comment by cosmo0920** [comment]
…と思ったらもう一仕事必要みたいでした…。

**Comment by cosmo0920** [comment]
現状：

- [x] librabbitmq-dev 0.5.0のSSLサポートありのppaは作成完了。
- [x] Travisでもlibrabbitmq-dev 0.4.0以降のライブラリがインストールされているものとして認識させることに成功。
- [x] AMQP周りもビルドできていることを確認。
- [ ] testHatoholArmPluginGateHAPI2::testProcedureHandlers::test_procedureHandlerPutItemsでテストが頻繁に失敗する。https://travis-ci.org/project-hatohol/hatohol/jobs/71012500#L3378
- [ ] testHatoholArmPluginGateHAPI2::testCommunicationのテストを動かすためにTEST_AMQP_URLを設定する必要がある。

**Comment by cosmo0920** [comment]
hap2側もテスト通りました。https://travis-ci.org/project-hatohol/hatohol/jobs/71023810

**Comment by cosmo0920** [comment]
All green :green_heart:  : https://travis-ci.org/project-hatohol/hatohol/builds/71023809

**Comment by Mnakagawa** [comment]
Good job:+1::+1::+1:
I'm proud of you!

**Comment by cosmo0920** [comment]
:yum:

**Comment by ashie** [comment]
> librabbitmq-dev 0.5.0を使っているせいなのかhap2側のテストも不安定になってしまう

Travisで以下がセットされていないのが原因だった

```
# Workaround: probably due to amqp-tools bug.
if [ `cat /etc/issue | grep "^Ubuntu 14.04" | wc -l` = "1" ]; then
  export RABBITMQ_CONNECTOR_TEST_WORKAROUND=1
fi
```

本当にバグならlibrabbitmq-cの方を修正すべきか。
