### ISSUE TITLE
AutoMutex implementation is replacable with C++11 <mutex> ?

### ISSUE THREAD

**Issue by cosmo0920** [project-hatohol/hatohol#1233]
This is not **issue**, but **future work**.
Hatohol has mutex utility class which is named with `AutoMutex`.
But now, C++11 provides `<mutex>` header which contains [Mutex](http://en.cppreference.com/w/cpp/thread/mutex) and [TimedMutex](http://en.cppreference.com/w/cpp/thread/timed_mutex)  classes.

This classes provide slightly more abstract functions than provided from `libpthread`.
Although, functions' signatures and return types are different from provided from `libpthread`....

**Comment by kz0817** [comment]
OK. Let us it !

**Comment by cosmo0920** [comment]
Note that `AutoMutex` is already replaced with C++11's `<mutex>` except for compiler ICE generating code.
