### ISSUE TITLE
FYI: specファイルでのdist-packageパスを示すマクロ

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#1355]
CentOS6.5では、次のようなPython関連のRPMマクロが用意されているpython_sitelibを使えば、pythonのdistutilsでインストールしたパスのファイルを指定できると思われる。
<pre>
 $ rpmbuild --showrc | grep -i python
-14: __python   /usr/bin/python
-14: __python_provides  %{_rpmconfigdir}/pythondeps.sh --provides
-14: __python_requires  %{_rpmconfigdir}/pythondeps.sh --requires
-14: python_sitearch    %(%{__python} -c "from distutils.sysconfig import get_python_lib; import sys; sys.stdout.write(get_python_lib(1))")
-14: python_sitelib     %(%{__python} -c "from distutils.sysconfig import get_python_lib; import sys; sys.stdout.write(get_python_lib())")
-14: python_version     %(%{__python} -c "import sys; sys.stdout.write(sys.version[:3])")
</pre>

**Comment by kz0817** [comment]
マクロは、次のようなパスに展開されると思われる。
<pre>
$ python -c "from distutils.sysconfig import get_python_lib; import sys; sys.stdout.write(get_python_lib())"  
/usr/lib/python2.6/site-packages
</pre>

**Comment by kz0817** [comment]
参考：automakeにもdist-packagesを示すマクロがある。

http://www.gnu.org/software/automake/manual/html_node/Python.html#Python

**Comment by Mnakagawa** [comment]
例えばMakefile内でsetup_xxx.pyを実行し、このコマンドを実行すれば、setup_xxx.pyでのインストール先のパスは確かに得ることができます。
ただこれをどうやってhatohol.spec.inと共有するかがわかりません。

configure.ac内で新しく定義する必要があるという認識でよいでしょうか…

**Comment by kz0817** [comment]
> ただこれをどうやってhatohol.spec.inと共有するかがわかりません。

specファイルの%filesセクションで%{python_sitelib}を%{_bindir}等と同じように
使えばいいのではないかと思います。
単純にinstallするかぎりconfigure.acの変更は不要かと思います。

**Comment by kz0817** [comment]
本件とは少し違いますが、*.pycがあることでrpmbuildがエラーになる場合、
%installセクションで、それらをrmしておく必要があります。

**Comment by Mnakagawa** [comment]
無事にrpm作成できたのでクローズします。
助かりました。

**Comment by kz0817** [comment]
> 本件とは少し違いますが、*.pycがあることでrpmbuildがエラーになる場合、
%installセクションで、それらをrmしておく必要があります。

参考：本件の中でわかったこと。
RPMでは、pyc, pyoを含めてパッケージを作ることが流儀のよう。

**Comment by Mnakagawa** [comment]
> RPMでは、pyc, pyoを含めてパッケージを作ることが流儀のよう。

rpmbuildコマンド内で，installセクション（不要なファイルなどをBUILDROOTから削除する）の後に，
pythonスクリプトのコンパイルが行われ，pyc, pyoが生成されているため含めないパッケージ作成が
まず不可能なのではないかと思われる。
