### ISSUE TITLE
[15.06] hap2_fluentd: Host is shown as Unknown

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#1363]
![unknown-host-id-fluentd-plugin](https://cloud.githubusercontent.com/assets/2610513/8514833/81082196-23d2-11e5-89e3-f80c62fac759.png)

**Comment by ashie** [comment]
HatoholArmPluginGateJSON doesn't have API to register hosts.
It registers unknown hosts in events, but HatoholArmPluginGateHAPI2 doesn't it.

**Comment by Mnakagawa** [comment]
It will be fixed in 15.06? or future version?

**Comment by kz0817** [comment]
I want to fix it in 15.06.

**Comment by kz0817** [comment]
I'm working on it by using JS plugin mechanism.
One problem is that FaceRest::ResourceHandler::addServersMap() doesn't push 'uuid'.
So plugin object cannot be obtained in JS. I'm fixing addServersMap() in order to include uuild.

**Comment by kz0817** [comment]
I close this issue since the patch was merged.

**Comment by Mnakagawa** [comment]
I do not confirm to fixed this bug on test rpm.
So, I reopen this issue and will close after to confirm fixed this bug.

**Comment by kz0817** [comment]
> So, I reopen this issue and will close after to confirm fixed this bug.

That makes sense.

**Comment by Mnakagawa** [comment]
I confirm to fixed it on test.
