### ISSUE TITLE
Fields for TLS are shown only for hap2_fluentd in WebUI. 

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#1364]
These fields (TLS client certificate path, TLS client key path, TLS CA certificate path, and TLS: Enable verify) are used to connect between Hatohol server and an AMQP broker. So these should be needed for hap2_zabbix, hap2_nagios_ndoutils, and hap2_ceilometer.

**Comment by kz0817** [comment]
![server-setting-hap2-fluentd](https://cloud.githubusercontent.com/assets/2610513/8515522/427c31da-23df-11e5-81e2-a9b6ce9ae26c.png)

**Comment by ashie** [comment]
Fixed in #1385
