### ISSUE TITLE
[HAP2] プラグインの終了方法

### ISSUE THREAD

**Issue by ashie** [project-hatohol/hatohol#1372]
プラグインの起動・終了スクリプトを書こうとしていたが、単に大元のプロセスを kill するだけでは
子プロセスが残ってしまう。正しい終了方法がよく分からない。

あと、プラグイン側でデーモン化した方が良さそう。

**Comment by kz0817** [comment]
a678d9c6d27では、大元のkillだけですべて終了する場合もあるが、そうでない場合もあるように見える。

**Comment by kz0817** [comment]
> a678d9c6d27では、大元のkillだけですべて終了する場合もあるが、そうでない場合もあるように見える。

上記、誤り。他のプロセスは残る。

**Comment by kz0817** [comment]
以下の２つの処理が必要そう。
(1) 大元のplugin (main plugin)以外のプロセスがひとつでも終了したら、最初からやり直す。
(2) main pluginが死んだ場合、すべての子プロセスを終了する

**Comment by kz0817** [comment]
#1389は、上記(1)を実現する。

**Comment by kz0817** [comment]
(2)は結構面倒なので、#1396でPRしたように、プロセスグループ(main pluginのPID)にSIGTERMが届いたら各自SystemExitをraiseして、すべてのプロセスを終了するようにしました。

SIGHUPとか他のシグナルでも同様の動きをするようにしてもいいかも。

**Comment by kz0817** [comment]
(2)をOSの機能で実現するためには、main pluginをセッションリーダーにして、端末に関連付けておく必要があるはず。しかし、HAPの場合、端末への関連付けを必須にするのは不自然な気がする。

あとは、各子プロセスが、親プロセス(main plugin)とパイプで接続しておいて、子プロセス内の一つのスレッドがそれを読み出しブロックしておいて、その切断をもって、親が死んだとみなすか。

**Comment by kz0817** [comment]
あとは、外部からMainPluginの死活を監視しておくか？そういう子プロセスを自動で生成するのはありかもしれない。

**Comment by kz0817** [comment]
とりあえず、the main plugin（大元）にTERMシグナルを送ると、全体が終了するようになりました。ただ、Receiverプロセスがpikaのライブラリの中でスタックしてる場合がたまにあります。TERMして、念の為にぷプロセスグループにSIGKILLを送信するような終了方法が必要かもしれません。

**Comment by ashie** [comment]
通常の使用方法で子プロセスが残ることは無くなった。
また、子プロセス終了時はメインプロセスごと立ち上げ直すようになった(#1729)
