### ISSUE TITLE
[15.06] [HAPI2.0] ImportErrorが発生する

### ISSUE THREAD

**Issue by Mnakagawa** [project-hatohol/hatohol#1374]
rpmでインストールした場合に，
/usr/libexec/hatohol/hap2/zabbix_api.py
/pythonのsite-packages/haplib.py
にスクリプトがそれぞれ配置されるため，
haplib.py内の
```
    @staticmethod 
    def define_transporter_arguments(parser): 
        parser.add_argument("--transporter", type=str, 
                            default="RabbitMQHapiConnector") 
        parser.add_argument("--transporter-module", type=str, default="haplib") 
 
    @staticmethod 
    def load_transporter(args): 
        (file, pathname, descr) = imp.find_module(args.transporter_module) 
        mod = imp.load_module("", file, pathname, descr)
        transporter_class = eval("mod.%s" % args.transporter)
        return transporter_class

```

が正常に動作しない。原因はload_transporter関数内の以下のセンテンス。
```
(file, pathname, descr) = imp.find_module(args.transporter_module) 
```
上にあげたとおり，haplib.pyとzabbix_api.pyのディレクトリが違うため，
argsに格納されているデフォルトのtransporter-module(つまりhaplib)をインポートできない。
ビルトインで使用する場合は両スクリプトは同ディレクトリに存在するため，問題なくインポートできる。
ちなみに，スクリプト起動時に--transporter-module=hatohol.haplib（hatoholモジュール内のhaplib）
と指定してみたが同様にインポートできなかった。

**Comment by kz0817** [comment]
PYTHONPATHをhatoholにも通せば、とりあえず見つかると思う。ただ、スマートではない。

**Comment by kz0817** [comment]
修正パッチがmasterにマージされました。@Mnakagawaさんにアサインを変更します。RPMの新版作成時に確認して、問題なければ、クローズしてください。
