### ISSUE TITLE
[15.06] [HAPI2.0] hap2_zabbixで取得したアイテムに無効となっているアイテムが混ざっている

### ISSUE THREAD

**Issue by Mnakagawa** [project-hatohol/hatohol#1380]
hap1や通常の監視しているアイテム数は一致しているのに，hap2_zabbix_apiのアイテム数はそれらより多い。
zabbixapi.pyを修正するだけで良いと思われる。

**Comment by Mnakagawa** [comment]
トリガーは問題無し

**Comment by Mnakagawa** [comment]
無効なアイテムではなく，internal itemsだった。
アイテムのタイプが5のアイテム。
https://www.zabbix.com/documentation/2.2/manual/api/reference/item/object#item

**Comment by Mnakagawa** [comment]
でも無かった。引き続き調査

**Comment by Mnakagawa** [comment]
```
state 	integer 	(readonly) State of the item.

Possible values:
0 - (default) normal;
1 - not supported. 
```

これが1のものが混じっているらしい。
と思ったけど，それだけじゃないらしい。
複合的な条件っぽい

**Comment by Mnakagawa** [comment]
現状のitemのAPIとhap2のapiを見比べてみる

**Comment by Mnakagawa** [comment]
APIには問題なさそう。
というか同名のアイテムを省略する，みたいな機能がサーバー側にあったような…
はっきりと覚えていないですが。

この省略する機能ってJavaScriptでやっていたような記憶があるんですが，
サーバー側でもDB保存時に同名アイテムは弾いている？

**Comment by Mnakagawa** [comment]
```
SoupMessage *ZabbixAPI::queryItem(HatoholError &queryRet)
{
	JSONBuilder agent;
	agent.startObject();
	agent.add("jsonrpc", "2.0");
	agent.add("method", "item.get");

	agent.startObject("params");
	agent.add("output", "extend");
	agent.add("selectApplications", "refer");
	agent.addTrue("monitored");
	agent.endObject(); // params

	agent.add("auth", m_impl->authToken);
	agent.add("id", 1);
	agent.endObject();

	return queryCommon(agent, queryRet);
}
```
paramsは
{"output": "extend", "selectApplications": "refer", "monitored": True}
で間違いないはず。このクエリで得られるアイテム件数は私の環境だと131件だったんですけど，
実際にHatoholDBに保存されているのは93件だったので，なんやかしらの処理がサーバー側であるはず。
hap2のzabbixapi.pyのアイテム取得クエリでも同様に131件取得できていたので，
単にDBへの保存時の処理が違うのか。

**Comment by Mnakagawa** [comment]
hap2だと与えられたアイテムを全てDBへ突っ込み，それ以外のZabbixでは与えられたアイテムに
処理を加えて弾いてDBに突っ込んでるって感じでしょうか。
ソース見てきます。

**Comment by Mnakagawa** [comment]
hap2のzabbixapiはitemオブジェクトの中のkeyを展開しないままHatoholサーバーに送っていますねコレ…
本来であれば$2,とか$4にkey_オブジェクトの中の値をそれぞれ置き換えてからHatoholサーバーに送らないといけない。

**Comment by Mnakagawa** [comment]
数が合わないこととは別問題だけども

**Comment by Mnakagawa** [comment]
#1392 でアイテムのマクロを展開することには成功したが，
依然として数が合わない問題の原因がわからない。
上にもあげたようにビルトイン&HAP1.0では，受け取ったアイテムに
なにかしらのフィルターをかけていると思うのだが，その場所がわからない。

**Comment by Mnakagawa** [comment]
#1395 でフィックス。
ビルトインやHAPI1.0では時間が0==監視していないアイテムとして判別し，
フィルターをかけていたので，hap2でもそれを踏襲した。

**Comment by Mnakagawa** [comment]
https://github.com/project-hatohol/hatohol/blob/e6ba5612e09c6343387c4a0990e3e6bee90e8fa5/server/src/HatoholDBUtils.cc#L455

ここらへん

**Comment by kz0817** [comment]
> ここらへん

ソース示すのいいね！
