### ISSUE TITLE
Is the unused variable going to be used in the future ?

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#1383]
The follwoing unused value causing the warning is going to be used in the future extension ?
   
<pre>
  CXX      HatoholArmPluginGateHAPI2.lo
HatoholArmPluginGateHAPI2.cc: In member function 'std::string HatoholArmPluginGateHAPI2::procedureHandlerPutHostParents(JSONParser&)':
HatoholArmPluginGateHAPI2.cc:1624:7: warning: unused variable 'checkInvalidHostParents' [-Wunused-variable]
  bool checkInvalidHostParents = parseUpdateType(parser, updateType, errObj);
</pre>

**Comment by ashie** [comment]
Yes, this warning is intentionally remained, it will be used in the future.

**Comment by kz0817** [comment]
OK. Thank you for your answer.
