### ISSUE TITLE
[15.06] 稼働中にAMQPブローカーを再起動した場合、動作不良になる

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#1384]
Hatohol server, pluginともに正常復帰しないように見える。

**Comment by Mnakagawa** [comment]
プラグイン側の解決策はエラーの内容に関わらず（エラーが起こったら最初からやり直すため），
最初に戻るたびにトランスポーターの設定をやり直す方法があると思う。
具体的には以下のもの。コネクションを再度設定しなければ正常復帰は望めない。
```
connection = pika.adapters.blocking_connection.BlockingConnection(param)
```

**Comment by kz0817** [comment]
> プラグイン側の解決策はエラーの内容に関わらず（エラーが起こったら最初からやり直すため），
> 最初に戻るたびにトランスポーターの設定をやり直す方法があると思う。

今は、MainPluginごとObjectを再作成するので、自動的にconnectionオブジェクトも
再度作成されます。

**Comment by ashie** [comment]
サーバ側は @cosmo0920 が調査中

**Comment by ashie** [comment]
> サーバ側は @cosmo0920 が調査中

リトライ処理は元々存在するが、それがうまく動作していない模様

**Comment by ashie** [comment]
server exceptionの件、以下のブランチでもう少し情報が出るようにしたので参考にして下さい @cosmo0920 

https://github.com/project-hatohol/hatohol/tree/issue-1384-show-more-error-messages

**Comment by ashie** [comment]
と言ってもあまり参考にならなそうだけど...

接続復帰後の一回のamqp_basic_consume()で以下のエラーが発生
```
[ERR] <AMQPConnection.cc:245> Channel close: NOT_FOUND - no queue 'test.zabbix-S' in vhost 'hatohol'
```

2回目のamqp_basic_consume()でselect()で刺さる。

**Comment by ashie** [comment]
いや、そんなことは無いか?
再起動後にqueueのリストを見てみたら、queueが無くなってる。
再接続時に作ってるはずなのだが...

切断前
```
l$ sudo -u rabbitmq -H /usr/sbin/rabbitmqctl list_queues -p hatohol
Listing queues ...
test.zabbix-S	0
test.zabbix-T	1
...done.
```

RabbitMQ再起動後
```
$ sudo -u rabbitmq -H /usr/sbin/rabbitmqctl list_queues -p hatohol
Listing queues ...
...done.
```

**Comment by ashie** [comment]
切断したときに`m_isConsumerQueueDeclared`と`m_isPublisherQueueDeclared`をクリアしていない。
これが犯人か。

**Comment by kz0817** [comment]
HAP側も#1410で、修正されたように思う。最新パッケージで、確認できたらクローズしてよい。
