### ISSUE TITLE
[15.06] 障害イベントに対する正常イベントが立ち上がらない

### ISSUE THREAD

**Issue by Mnakagawa** [project-hatohol/hatohol#1388]
Redmineのテストを行っている時に発見した。

意図的にイベントを引き起こすために，監視サーバー(Zabbix)のIPアドレスを
存在しないものに変え，更新した。
すると指定されたIPは存在しないので，イベントが発生する。（「Failed in connecting to Zabbix.」の障害ステータス）
無事にインシデント登録は完了したのだが，その後にIPアドレスを本来のものに戻すと，
監視サーバーのステータスエラーから正常に戻ったにも関わらず，先ほど立ち上がった
「Failed in connecting to Zabbix.」の正常ステータスのイベントが発生しない。

これって仕様でしたっけ

**Comment by cosmo0920** [comment]
今のところ仕様だったはずです。

Duplicate of https://github.com/project-hatohol/hatohol/issues/1101.

**Comment by Mnakagawa** [comment]
Thank you for your comment!
6月に検討する，とコメントしてありましたし，15.09には入れたいですね！
クローズします。
