### ISSUE TITLE
[Server] Trigger ID is not quoted in SQL statement.

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#1412]
I got the following error message (129ea03fd3d).
It seems that the ID is not quoted.
<pre>
[ERR] <HatoholThreadBase.cc:237> Got Hatohol Exception: <DBAgentMySQL.cc:667> Failed to query: DELETE FROM triggers WHERE id in (ec18db72-c90f-4e47-a55b-c26582cba88a) AND server_id=4: (1054) Unknown column 'ec18db72' in 'where clause'
</pre>

**Comment by kz0817** [comment]
And after this happened, HAP plugin failed to send data (putTriggers).

**Comment by ashie** [comment]
https://github.com/project-hatohol/hatohol/blob/master/server/src/DBTablesMonitoring.cc#L1595

@cosmo0920, please check all other sync* functions.

**Comment by cosmo0920** [comment]
https://github.com/project-hatohol/hatohol/blob/master/server/src/DBTablesHost.cc#L913

DBTablesHost sync* functions use above line.

**Comment by ashie** [comment]
OK, thanks.
I'll fix the problem.

**Comment by kz0817** [comment]
The patch in #1421 fixed the problem on the environment on which I found this issue.
