### ISSUE TITLE
[RPM] server-type-hap2-*.sql はserverではなく各プラグインパッケージに入れるべき

### ISSUE THREAD

**Issue by ashie** [project-hatohol/hatohol#1415]
server-type-hap2-*.sql は理想的にはserverパッケージではなく各プラグインパッケージに入れるべき
ただしhatohol-db-initiatorも直さなきゃいけなそうなので、15.06時点ではserverに入れとくのが無難か。

**Comment by teruo-oshida** [comment]
I read hatohol-db-initiator. I think we should decide what is the illegal case.
My idea is that hatohol-db-initiator may work with exist sql files without any warn and may say an error when specified sql is absent.

**Comment by Mnakagawa** [comment]
静的なリストを持たない方針で進めるのであれば，
db-initiatorからtargetオプションを削除するしか無い？

**Comment by Mnakagawa** [comment]
また，データをロードするテーブル名の指定をどうするかといった問題もある。
actions.sqlなどはそのまんまactionsテーブルではあるが，hap2のzabbixはserver_typesにロードしなければならないから，どうやってserver_typesテーブルを指定するのか悩みもの。。。

sqlファイルに命名規則を付ける？

**Comment by teruo-oshida** [comment]
sql ファイルに命名規則を設けるのは、他の要件を別としても、良いかもしれないと思います。

で、件の sql ファイルは sql ファイル中に対象テーブルが書いてあるので、テーブル指定は要らないと思うけれど、何かしらのメタ情報を埋め込む的な事を発想するのであれば、いっそ sql をやめて、「sql を出力する能力あるいは情報を持った」ファイル形式を創造したら良いかもしれないと思いますよ。

もちろん sql ファイルそのものであった当時（現在）より大きくファイル内容が乖離しないことは理想的だけれど。例えば JRE 等のインストーラのように、tar.gz の前に shell script が付いているファイル、とか。


そういう工夫をすることで target 機能は存続させられると思うけれど、そもそも「任意のファイルを用意する」ということは概ね「対象を指定する」と近い意味を持つので、冗長のような気もする。
