### ISSUE TITLE
[HAP2] AMQPアカウント情報

### ISSUE THREAD

**Issue by ashie** [project-hatohol/hatohol#1420]
現在のHAP2はAMQPのアカウント情報をコマンドライン引数で受け取っているが、環境変数で受けとるべき

**Comment by Mnakagawa** [comment]
同意見です。
15.09のマストですね

**Comment by kz0817** [comment]
hap2-control-functions.sh、および、それを使用するstart-stop-hap2-nagios-ndoutils.shなどで、環境変数で受け取れるようになっている。これで良しとするか？

**Comment by ashie** [comment]
いや、そこから hap2_zabbix_api.py などを起動するときにコマンドライン引数でパスワードを渡しており、
`ps ax` したときにパスワードがモロ見えなので、プラグインも環境変数で受けとるようにしないとダメです。

**Comment by kz0817** [comment]
I see. Thank you for the comment.

**Comment by kz0817** [comment]
#1528がマージされたので、クローズします。
