### ISSUE TITLE
[Server] [HAPI2.0] 大量のデータを受け取った際，サーバーでエラーが発生する

### ISSUE THREAD

**Issue by Mnakagawa** [project-hatohol/hatohol#1425]
```
Jul  9 12:17:05 localhost hatohol[3863]: [ERR] <AMQPConnection.cc:230> failed to consume message: connection closed unexpectedly
Jul  9 12:17:05 localhost hatohol[3863]: [ERR] <AMQPConnection.cc:230> failed to close channel: a socket error occurred
Jul  9 12:17:05 localhost hatohol[3863]: [ERR] <AMQPConnection.cc:230> failed to close connection: a socket error occurred
```

ログは以上の通り。この時のAMQPからのメッセージのbodyのデータサイズは108312。
イベントの送信時に遭遇したエラーです。
その他のデータサイズが小さいリクエストに関しては（putTriggersなど）は問題なく受け入れ，
かつログも吐きだされておらず，レスポンスも返っているのですが，このエラーが発生した場合は
レスポンスがかえらず，プラグイン側でタイムアウトが発生します。

**Comment by Mnakagawa** [comment]
failed to closeとあるように。メッセージに対する処理は完了していて，
イベント自体はDBに格納されています。

**Comment by ashie** [comment]
#define AMQP_DEFAULT_FRAME_SIZE 131072
(128kb)

**Comment by ashie** [comment]
上記はEvent 500件程度とのこと、仕様上1000件は許容したいとのことなので、
とりあえず4倍くらいにしてみますかね。
1000件というのはZabbix APIの通信で経験的にそれくらいが限界だったからとい
うくらいの意味なのできっちりそれを守る必要はないと思うけど、さすがにこの
程度だと限界が低すぎる気がする。

**Comment by ashie** [comment]
Kbってことはもっと必要か?

```
/**
 * \def AMQP_DEFAULT_FRAME_SIZE
 *
 * Default frame size (128Kb)
 *
 * \sa amqp_login(), amqp_login_with_properties()
 *
 * \since v0.4.0
 */
#define AMQP_DEFAULT_FRAME_SIZE 131072
```

**Comment by Mnakagawa** [comment]
サイズ的にはデフォルトで問題ない気がします。
上にもあげていますが，メッセージのサイズは108312byteだったわけですし，
デフォルトのサイズを超えていません。
また， pikaモジュールの限界も131072byteなので，そこを変更する必要はないのではないでしょうか。

**Comment by ashie** [comment]
```
/**
 * Login to the broker
 *
 * After using amqp_open_socket and amqp_set_sockfd, call
 * amqp_login to complete connecting to the broker

...

 * \param [in] frame_max the maximum size of an AMQP frame on the wire to
 *              request of the broker for this connection. 4096 is the minimum
 *              size, 2^31-1 is the maximum, a good default is 131072 (128KB), or
 *              AMQP_DEFAULT_FRAME_SIZE
...
```

ただし、まだこれが原因と決まったわけではない。
つーかこっちはKBになってるな...

**Comment by ashie** [comment]
> 上にもあげていますが，メッセージのサイズは108312byteだったわけですし，

body以外で何か食ってるのかもと思ったのですが

> また， pikaモジュールの限界も131072byteなので，そこを変更する必要はないのではないでしょうか。

だとしたら違いそうですね。

**Comment by Mnakagawa** [comment]
確かに，おっしゃるとおりbodyのサイズとは別に食っている部分はあるのですが，
その点はpikaはframe_maxからしっかり引いているので，問題ないかと思います。

**Comment by ashie** [comment]
amqp_api.c:

```c
static const char *base_error_strings[] = {
   ...
  "connection closed unexpectedly",     /* AMQP_STATUS_CONNECTION_CLOSED        -0x0007 */
   ...
};
```

**Comment by ashie** [comment]
このエラーが返り得るのはたぶんこの辺くらい。

amqp_socket.c:

```c
static int recv_with_timeout(amqp_connection_state_t state, uint64_t start, struct timeval *timeout)
{
  int res;

  if (timeout) {

　...

    fd = amqp_get_sockfd(state);
    if (-1 == fd) {
      return AMQP_STATUS_CONNECTION_CLOSED;
    }
```

amqp_tcp_socket.c:

```
static ssize_t
amqp_tcp_socket_recv(void *base, void *buf, size_t len, int flags)
{
  struct amqp_tcp_socket_t *self = (struct amqp_tcp_socket_t *)base;
  ssize_t ret;

start:
  ret = recv(self->sockfd, buf, len, flags);

  if (0 > ret) {
    self->internal_error = amqp_os_socket_error();
    if (EINTR == self->internal_error) {
      goto start;
    } else {
      ret = AMQP_STATUS_SOCKET_ERROR;
    }
  } else if (0 == ret) {
    ret = AMQP_STATUS_CONNECTION_CLOSED;
  }

  return ret;
}
```

**Comment by ashie** [comment]
> また， pikaモジュールの限界も131072byteなので，そこを変更する必要はないのではないでしょうか。
> だとしたら違いそうですね。

AMQPのプロトコルは全然知らないけど、consumeとpublishでメッセージサイズは変わりそうな気が。
試す価値はあるか。

**Comment by ashie** [comment]
メモ:

手っ取り早く任意のデータを食わせる方法としては、amqp-publishが使えそう。

```
$ amqp-publish -u amqp://user:pass@localhost/hatohol -r test.1-S < data.json
```

**Comment by ashie** [comment]
1MB程度のデータを食わしてみたところ、確かに同様の症状となる。
ただし、リクエスト自体は全部受け取っているようだ(デバッグメッセージに切れずに
全部表示される)。

**Comment by ashie** [comment]
接続は復帰しているようなので、復帰後にレスポンスを返してやる方法はあるかもしれない。

**Comment by ashie** [comment]
今の実装では、レスポンスの送信は一回失敗したらすぐに諦めている。
これはリトライすべき。

**Comment by Mnakagawa** [comment]
むむむ…次は pika側がキューにメッセージを入れれなくなった…
イベント件数，byteはそれぞれ条件は同じはずなのに…

**Comment by Mnakagawa** [comment]
間違えて閉じちゃいました。すみません。

**Comment by ashie** [comment]
あ、私も今まさにそれが起こりました。

**Comment by ashie** [comment]
送り側はpikaではなくamqp-publishだけど

**Comment by ashie** [comment]
よくわからないが復帰した。

> AMQPのプロトコルは全然知らないけど、consumeとpublishでメッセージサイズは変わりそうな気が。
> 試す価値はあるか。

試したが、やはり発生する。

**Comment by Mnakagawa** [comment]
pika曰く
「The AMQP specification states that a server can reject a request for a frame size larger than the value it passes during content negotiation.」
だそうです。
でも接続を確立している段階できちんとframeのサイズを指定しているはずなんだけどなぁ…

**Comment by Mnakagawa** [comment]
> 試したが、やはり発生する。

送り先と受信先でメッセージのサイズが違うということでしょうか

**Comment by Mnakagawa** [comment]
50000byte強でも最初に挙げた3行のエラーは発生した。

**Comment by ashie** [comment]
そもそも、frame sizeが越えているから本来は接続が切れるべきでは無いと思います。
単純にバグか何か使い方に問題があるか。

**Comment by ashie** [comment]
> 1MB程度のデータを食わしてみたところ、確かに同様の症状となる。

DBGメッセージを表示していると上記のような症状になるが、DBGメッセージを表示しないと、
なんと症状が発生しない。なんだこれ。

**Comment by Mnakagawa** [comment]
マージ後も引き続き同様のログの発生，またプラグイン側でのタイムアウトを確認した。
RabbitMQ関連のライブラリの使い方がなにか間違っている？それとも他に認識していない問題があるのか。

**Comment by Mnakagawa** [comment]
とりあえず，プラグイン側で送信するイベントの件数を絞って，
今回のリリースでは応急処置とした。引き続き調査の必要ありかと思われる。

**Comment by ashie** [comment]
今のmasterで調査しようとしたら、まったく再現できなくなってしまった。
うーむ....

**Comment by ashie** [comment]
と思ったら再現した。
やるたびに限界サイズが変わっている?

**Comment by ashie** [comment]
>> 1MB程度のデータを食わしてみたところ、確かに同様の症状となる。
>
> DBGメッセージを表示していると上記のような症状になるが、DBGメッセージを表示しないと、
> なんと症状が発生しない。なんだこれ。

やはり、DBGメッセージを表示しなければ10MBのデータでも発生しない。

**Comment by ashie** [comment]
> やはり、DBGメッセージを表示しなければ10MBのデータでも発生しない。

大量のデータを流すと、そのデータをDBGメッセージで表示するために長時間ブロックされる。
ブロック時間によって左右されるのか?

**Comment by ashie** [comment]
> マージ後も引き続き同様のログの発生，またプラグイン側でのタイムアウトを確認した。
> RabbitMQ関連のライブラリの使い方がなにか間違っている？それとも他に認識していない問題があるのか。

リプライが返されない問題については、AMQPConnectionのエラーハンドリングにまだ問題が残っている
ことがわかった。まずはこれについて修正する。

**Comment by ashie** [comment]
コネクションが切れたとき、RabbitMQ側で以下のようなエラーが出ている

```
=ERROR REPORT==== 23-Jul-2015::14:24:04 ===
closing AMQP connection <0.5251.1> (127.0.0.1:54425 -> 127.0.0.1:5672):
{heartbeat_timeout,running}
```

RabbitMQ(AMQP?)では死活チェックが動いていて、

> 大量のデータを流すと、そのデータをDBGメッセージで表示するために長時間ブロックされる。

こういったときに死活チェックに応答できなくてRabbitMQ側から切られているようだ。

**Comment by ashie** [comment]
下記に情報がある。

https://www.rabbitmq.com/heartbeats.html

そして、Hatoholサーバではamqp_login()でhearbeatを1秒にセットしている。
原因はこれか!

**Comment by ashie** [comment]
ただ、DBGメッセージを表示しているときは仕方ないとして

> ログは以上の通り。この時のAMQPからのメッセージのbodyのデータサイズは108312。

DBGメッセージを表示していないのに本当にこの程度で1秒も応答できないのだしたら、
妙に時間がかかりすぎている気はする。
(手元ではDBGメッセージさえ表示しなければ、10MBでも大丈夫だが)

**Comment by ashie** [comment]
とはいえ heartbeat １秒は短すぎるので、もう少し長めにセットするようにする。

以上2点を修正したら本issueは閉じる。

**Comment by ashie** [comment]
> とはいえ heartbeat １秒は短すぎるので、もう少し長めにセットするようにする。

1秒とした理由は特にないと思う。
AMQP_DEFAULT_HEARTBEAT が 0 (死活チェック無効化)なので、
それ以外の値にした、というだけだと思う。

**Comment by ashie** [comment]
heartbet時間を60秒にすると、 DBGメッセージあり、10MBのデータでもコネクションが
切れないことを手元の環境で確認した。

**Comment by ashie** [comment]
#1488 と #1490 で修正した!

**Comment by ashie** [comment]
#1488 でpublishが再試行されない問題を修正
#1490 でコネクションが切れる問題を修正
