### ISSUE TITLE
Internal release 15.07

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#1451]
@ashie
Could you make packages for the test including fixes in July ?
Tentative date: 7/31
TargetOS: CentOS7 and CentOS6 (Hap2.0 only)

**Comment by ashie** [comment]
I see.

**Comment by ashie** [comment]
I uploaded them to hatohol-packages repository:

https://github.com/project-hatohol/hatohol-packages/commit/664d80aee06afead43e0a4acd000a857b167866c

**Comment by kz0817** [comment]
Thank for the creation. I close this issue.
