### ISSUE TITLE
Internal release 15.08

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#1457]
@ashie 
Cloud you please create packages including Event UI enhament.

Tentative date: 9/4 (Fri) 
Target OS: CentOS7 and CentOS6 (hap2 only)

**Comment by ashie** [comment]
I see.

**Comment by kz0817** [comment]
As we discussed the schedule in the F2F meeting, we will hear requirements about the event UI from various people mainly in August. So the release with the improved UI is delayed one month.

The target date: 10/02 (Fri)

**Comment by kz0817** [comment]
The plan is now re-planning. So I close this issue once.
