### ISSUE TITLE
hap2: RabbitMQConnector process sometimes doesn't terminate

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#1465]
It seems that it ignores SIGTERM.
The main plugin should send SIGKILL if the child process doesn't terminate by SIGTERM.

**Comment by kz0817** [comment]
The new plan to address #1729 will also be expected to resolve this problem.

**Comment by kz0817** [comment]
Have we already resolved this issue ?

**Comment by Mnakagawa** [comment]
When main process get a siganl from its processes, hap2_starter send SIGKILL to all process.
So I think this issue is resolved.
