### ISSUE TITLE
[HAPI] Remove HAPI1

### ISSUE THREAD

**Issue by ashie** [project-hatohol/hatohol#1469]
HAPI2 plugins and HatoholArmPluginGateHAPI2 should be stable enough in the next version (15.11).
So it's time to remove HAPI1.

**Comment by cosmo0920** [comment]
In next version, we also need to remove Qpid dependency?

**Comment by Mnakagawa** [comment]
I know that.

> In next version, we also need to remove Qpid dependency?

That's right!

**Comment by kz0817** [comment]
Can we close this issue ? If so, please do it.

**Comment by cosmo0920** [comment]
For now, we just disable HAPI1. For closing this issue, we must remove it.

**Comment by kz0817** [comment]
When the HAPI1 code is removed, ArmUtils which is used only from HatoholArmPluginGate should also be deleted.

**Comment by cosmo0920** [comment]
When the HAP1 code is removed, we should use rabbitmq-server and clients(Hatohol Server/HAP2) with default port.

If we use rabbitmq-server with default port, it makes easier to migrate container based Travis CI build.
(In container-based build, we can use ppa packages with ppa addons syntax in .travis.yml).

**Comment by cosmo0920** [comment]
> When the HAPI1 code is removed, ArmUtils which is used only from HatoholArmPluginGate should also be deleted.

`ArmBase` is still using `ArmUtils`. We should replace it with `SelfMonitor`.

**Comment by ashie** [comment]
Although HAP1 has been removed at #1873, following enum items still remain to keep
binary compatibility:

* MONITORING_SYSTEM_HAPI_ZABBIX
* MONITORING_SYSTEM_HAPI_NAGIOS
* MONITORING_SYSTEM_HAPI_CEILOMETER

Should we add "obsolete" mark to them?
