### ISSUE TITLE
if server not running, show that is not running in the webpage

### ISSUE THREAD

**Issue by aliceinwire** [project-hatohol/hatohol#1501]
if server is not running, as now is just deny the login with no other information and showing the drop-down menu for changing password.
Would be nice to have a "server is not running" information on the webpage or similar.

**Comment by ashie** [comment]
Than you for your report. I think so too.
I'll implement it when I have time to spare.

**Comment by kz0817** [comment]
I work on this issue as #1581. So I close this issue.
