### ISSUE TITLE
Zabbixでのトリガー取得にバグの可能性

### ISSUE THREAD

**Issue by Mnakagawa** [project-hatohol/hatohol#1503]
知人にレビューしてもらった時に発見された。
トリガーを取得した際、正常なものと異常のあるトリガーに分かれるが、
この異常のあるトリガーの中で、閾値を超えているアイテムをZabbix側 で無効にしたとき、
トリガーのステータスは正常になり、Zabbixのダッシュボードでは正常なトリガー扱いとなる。

だが、Hatohol側での「監視サーバー画面」でトリガーの再取得を行っても、その変更が反映されずに、
件のトリガーのステータスが異常のままとなる。

その知人のレビューをもとにIssueを立てたため、再現の確認はしていない。

**Comment by ashie** [comment]
組込み・HAP1・HAP2のどれを使用したのかわかりますか?

**Comment by Mnakagawa** [comment]
組み込みだそうです。
ただHAP2のAPIも組み込みのものを持ってきているので、同様の現象が起きる可能性は高いと思います。
というかHAPI1も同じライブラリを使用しているから（ZabbixAPI.cc）発生する？

**Comment by ashie** [comment]
まだ試してないけど、全取得でも駄目ということだと、Zabbix APIの問題である可能性も捨てきれない。

**Comment by Mnakagawa** [comment]
私も同様の意見です。
そうなった場合、本当にどうしようもないのでZabbixのフォーラムに投げるくらいしかできることはないですね…
とにもかくにも、再現させることがまず最初ですね。そのうちやります。

**Comment by kz0817** [comment]
これ進展ありますか？
なければこれ以上調査できないのでクローズします。
