### ISSUE TITLE
MySQLの文字コードがUTF8の場合に、hatohol-db-initiatorで失敗する。

### ISSUE THREAD

**Issue by szktoshiki** [project-hatohol/hatohol#1517]
HatoholのDBはlatin1固定でしょうか。
UTF-8に設定したMySQL環境（★）でhatohol-db-initiatorを実行しましたところ
以下のように失敗してしまいます。

★my.cnfの[mysqld]に"default-character-set=utf8"を設定。（MySQL 5.1）

[root@localhost ~]# hatohol-db-initiator --db_user root --db_password *******
Created DB: hatohol
[INFO] <DBAgent.cc:708> Created index: ServerTypeUniqId (table: server_types)
[INFO] <DBAgent.cc:708> Created index: serverId (table: arm_plugins)
[INFO] <DBAgent.cc:708> Created index: name (table: host_list)
[INFO] <DBAgent.cc:708> Created index: host_id (table: server_host_def)
[INFO] <DBAgent.cc:708> Created index: server_id (table: server_host_def)
[INFO] <DBAgent.cc:708> Created index: host_id_in_server (table: server_host_def)
[INFO] <DBAgent.cc:708> Created index: name (table: server_host_def)
[INFO] <DBAgent.cc:708> Created index: status (table: server_host_def)
[INFO] <DBAgent.cc:708> Created index: HostServerDefIdx (table: server_host_def)
[INFO] <DBAgent.cc:708> Created index: host_id (table: host_access)
[INFO] <DBAgent.cc:708> Created index: ip_addr_or_fqdn (table: host_access)
[INFO] <DBAgent.cc:708> Created index: host_id (table: vm_list)
[INFO] <DBAgent.cc:708> Created index: hypervisor_host_id (table: vm_list)
[INFO] <DBAgent.cc:708> Created index: id_in_server (table: hostgroup_list)
[INFO] <DBAgent.cc:708> Created index: name (table: hostgroup_list)
[INFO] <DBAgent.cc:708> Created index: HostgroupListUniqId (table: hostgroup_list)
[INFO] <DBAgent.cc:708> Created index: host_id_in_server (table: hostgroup_member)
[INFO] <DBAgent.cc:708> Created index: host_group_id (table: hostgroup_member)
[INFO] <DBAgent.cc:708> Created index: host_id (table: hostgroup_member)
Failed to create DBHatohol object
[root@localhost ~]#

latin1でgrepしてみたところ以下のファイルにてlatin1が指定されていました。
文字コードを変更することは難しいでしょうか。

/usr/share/mysql/mysql_fix_privilege_tables.sql
/usr/share/mysql/fill_help_tables.sql
/usr/share/mysql/mysql_system_tables.sql

**Comment by kz0817** [comment]
ご報告ありがとうございます。

再現できないので、実行環境の詳細について、以下の点を教えてください。

> ★my.cnfの[mysqld]に"default-character-set=utf8"を設定。（MySQL 5.1）

[mysql]セクションではなく、[mysqld]で、あっていますか？
私の環境(Ubuntu 14.04）のMySQLでは、mysqldに上記を記述した場合、
mysqldの起動時にエラーが発生しました。

使用したOSは、何でしょうか？CentOS6.5?

**Comment by szktoshiki** [comment]
情報が不足しておりすみません。

■OS情報
# cat /etc/redhat-release
CentOS release 6.5 (Final)

■MySQL
MySQL 5.1.73です。
以下のように設定しています。
# cat /etc/my.cnf
[mysqld]
datadir=/var/lib/mysql
socket=/var/lib/mysql/mysql.sock
user=mysql
# Disabling symbolic-links is recommended to prevent assorted security risks
symbolic-links=0

default-character-set=utf8

[mysqld_safe]
log-error=/var/log/mysqld.log
pid-file=/var/run/mysqld/mysqld.pid
#

MySQL起動後文字コードについては以下のようになっていました。
mysql> show variables like 'character_set%';
+--------------------------+----------------------------+
| Variable_name            | Value                      |
+--------------------------+----------------------------+
| character_set_client     | latin1                     |
| character_set_connection | latin1                     |
| character_set_database   | utf8                       |
| character_set_filesystem | binary                     |
| character_set_results    | latin1                     |
| character_set_server     | utf8                       |
| character_set_system     | utf8                       |
| character_sets_dir       | /usr/share/mysql/charsets/ |
+--------------------------+----------------------------+
8 rows in set (0.00 sec)

mysql>


上記の状態で「hatohol-db-initiator」を実行しています。

なお手順は以下を参考にしています。
https://github.com/project-hatohol/website/blob/master/contents/docs/install/15.03/en/index.md

**Comment by Mnakagawa** [comment]
参考になされているドキュメントのバージョンは15.03に見受けられます。
実際にインストールされている Hatoholのバージョンも15.03でしょうか？

**Comment by kz0817** [comment]
CentOS6.5に15.03を入れて再現することが出来ました。
指摘いただいたように[mysqld]にdefault-character-set=utf8を追加すると再現し、削除すると不再現（成功）でした。

**Comment by kz0817** [comment]
DBGレベルログにMySQLが返したエラーが含まれる。
<pre>
$ MLPL_LOGGER_LEVEL=DBG /usr/bin/hatohol-db-initiator --db_user root --db_password ''
Created DB: hatohol
*** 省略 ***
[INFO] <DBAgent.cc:708> Created index: host_id (table: hostgroup_member)
[DBG] <HatoholException.cc:59> HatoholException: <DBAgentMySQL.cc:625> Failed to query: CREATE UNIQUE INDEX HostsHostgroupUniqId ON hostgroup_member (server_id,host_id_in_server,host_group_id): (1071) Specified key was too long; max key length is 1000 bytes

Failed to create DBHatohol object
</pre>

**Comment by kz0817** [comment]
server_id,host_id_in_server,host_group_idの各列の幅が、11, 255, 255で、合計512。
latin1なら、512Bだが、UTF8にすると、その3倍で1000を超えるので、失敗していると思われる。

**Comment by kz0817** [comment]
my.confの[mysqld]セクションに以下を記載し、データベースエンジンをInnoDBにすると、hatohol-db-initorは成功する。
default-storage-engine=InnoDB

Hatoholは、Transactionでロールバックされることが前提に設計されているのでは、InnoDBが使われるべき。それが手順書に書かれていないことが問題のひとつ。

**Comment by szktoshiki** [comment]
情報ありがとうございます。

ひとまずmy.cnfで以下の設定を加えてインストールを実施して起動し、
対象サーバとしてZabbixを登録できるところまで確認できました。

[mysqld]
default-storage-engine=InnoDB

**Comment by kz0817** [comment]
では、このissueをクローズします。

**Comment by cosmo0920** [comment]
hatohol.orgの手順を更新しなくて良いのでしょうか？

**Comment by cosmo0920** [comment]
あ、更新というより補足、ですかね。

**Comment by kz0817** [comment]
> hatohol.orgの手順を更新しなくて良いのでしょうか？

そうですね。
すぐできますか？できないなら、別Issueをたてよう。

**Comment by cosmo0920** [comment]
別Issueを立ててWebsiteを更新する事にしましょう！

**Comment by kz0817** [comment]
#1562を立てたのクローズ
