### ISSUE TITLE
ReleaseNoteに対応OSを書くべき

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#1518]
各リリースに対して、対応するOS (リリーステストを実施したディストロや構成）の記載があるほうが親切だと思う。

**Comment by Mnakagawa** [comment]
現在は各バージョンのリリースメールにしか，そのような情報は記載していないですからね。
同意です。次回以降のアップデートはそのようにしたほうが良いと思います。

このIssueは，その反映を持ってしてクローズとしますか？
それとも他のメンバーの同意を得られた時点でクローズとしますか？

**Comment by kz0817** [comment]
合意が得られた後、15.06についてはReleaseNoteにその情報を追加し、それを持ってクローズでどうでしょう。次版の内容を作成する際、前バージョンを雛形にするでしょうから。

**Comment by Mnakagawa** [comment]
OK:ok_hand:

**Comment by cosmo0920** [comment]
現在だとREADMEに少し情報がある程度なので表示できるならしたほうが良いと思います。テストを実施した環境をひとまずの推奨環境とするのでしょうか？

**Comment by cosmo0920** [comment]
https://github.com/project-hatohol/hatohol/pull/1950 にて反映。masterにマージされたら閉じる。
