### ISSUE TITLE
イベント数統計

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#1546]
保存したイベント数の統計機能をつける。ロードテスト時にも役立つし、簡易的な性能指標にもなるはず。

・監視サーバーごと：MonitoringServerInfoにカウンタ機能を追加。
・SystemWide: DBTablesMonitoringにカウンタ機能を追加。

測定期間は、３つぐらい用意する。
- 10秒
- 1分
- 10分

**Comment by kz0817** [comment]
データの取り出しは、監視サーバーごとも従来のREST APIでOK。SystemWideの方は、そういうREST APIを作る。

**Comment by kz0817** [comment]
精度と低レイテンシーを求めるなら、測定時間のデータをすべて保存しておいて、データ要求時に計算するのが理想だが、イベントの頻度が多い場合、メモリ使用量と演算量が気になる。

なので、２つのカウンタ用スロットを用意して、なるべくオーバーヘッドを少なくする。
例えば、測定時間Tが10秒の場合、次のようにT(n〜n+1)とT(n+1/2〜n+3/2)の時刻の測定結果を交互に保存し続ける。
スロット1: 0〜10s、10〜20s、20〜30s、...
スロット2: 5〜15s、 15〜25s、25〜35s、...

最大T/2の遅延で前スロットのすべての時刻のデータを使ったの統計が取得可能。

また、データの更新は、書き込みと読み出し時のみに行う。タイマーやスレッドを使用しない。イベントがなく、統計情報読み出しもなければ、ゼロオーバーヘッドになるようようにする。

**Comment by kz0817** [comment]
スロット間で測定時刻の重複をもたせなくてもよい気がしてきた。遅延時間が最大Tになるが、致命的でもないだろう。

**Comment by kz0817** [comment]
統計情報は、REST APIの/server-conn-statに含めるようにしようか。Connection Statusのひとつであるとも言えるし。

**Comment by kz0817** [comment]
当初、HAPインスタンごとの統計情報をArmInfoに格納しようと考えたが、基本的にプラグインの稼働状況をいれる構造体に思える。PluginGateの情報をいれることも可能だが、見通しが悪くなりそう。

**Comment by kz0817** [comment]
System WideなEvent統計については、新たにHatohol Server StatusのようなREST APIを作って、そこから取得できるようにする。

各PluginGateの稼働状況も、その中もしくは、そのサブディレクトリにあるほうがよいか。

**Comment by kz0817** [comment]
REST APIの/system-infoで統計情報を取れるようになった。
誤って、直接、masterにマージしてしまったが。。。

**Comment by cosmo0920** [comment]
save temp. コミットがmasterにあるのが渋いですね。。。

**Comment by Mnakagawa** [comment]
kz0817さん、前も確かありましたよね。
差し出がましいですが、気を付けたほうがいいと思います。

**Comment by kz0817** [comment]
> 差し出がましいですが、気を付けたほうがいいと思います。

気をつけてはいるんですが、間違いは起こります。頻度は人によって違いますが。

**Comment by cosmo0920** [comment]
気をつけるのにも限界があるので、この際masterへのpushを禁止するpush-hookを入れてしまうのはどうでしょう。
例えばこんな感じに http://d.hatena.ne.jp/thinca/20150306/1425639218 書いて .gitのhooksに実行権限を付けて置いておくと良いと思います。

**Comment by kou** [comment]
GitHubにはprotected branchという機能があってな。。。
https://help.github.com/articles/defining-the-mergeability-of-pull-requests/


間違いがあるのはそういうものなので、みんなが他の人の間違いに寛容になれるといいんじゃないかなぁと思いました。もし、中川さんが間違っても、そういうこともあるよね、代わりに直しておくね、みたいな感じで行動する、とか。

**Comment by ashie** [comment]
私は現在の作業ブランチだけをpushするようにしているので、
間違えてmasterにpushすることは無いです。
（間違ったブランチをpushしてしまうことはたまにありますが）

```
$ git push -u origin events-view-config-ui
```

ブランチ名はbash-completionが補完してくれるので手間ではないし、
自分がどのブランチで作業しているのかを意識する良い機会にもなると
思っているので、あえてそうしています。

**Comment by kz0817** [comment]
これまで、以下の手順でやっていた。
(1) branchを作って、それをcheckout
(2) 新しいブランチで作業
(3) $ git push
(4) gitが、git push --set-upstream origin hogehogeにしなよって、表示するでそれを入力

今回は、(1)が抜けていたのだと思う。次のようなフローにすると、間違いがへるのか
(1) branchを作って、それをcheckout
(2) $ git push -u origin hogehoge
(3) 作業
(4) push
