### ISSUE TITLE
マニュアルにdefault-storage-engine=InnoDBを記載

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#1562]
MySQLのmy.confに掲題の設定が必要なことを明記する。

参考： #1517

**Comment by kz0817** [comment]
RPM (CentOS向け）を使ったDocumentでは、触れなくてもいいと思う。
デフォルトでInnoDBなので。

**Comment by kz0817** [comment]
一般的なドキュメント用に、#1732としてPRを出した。

**Comment by ashie** [comment]
merged.
