### ISSUE TITLE
eventなどデータ実体とlastInfoの保存がatomicでない。

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#1569]
HAPI2.0の仕様では、eventなどので実データと、それに伴うlastInfoは、同時に更新されることになっている。実装の観点からは、これら両方の操作がトランザクションで行われるべきだが、
master:b71a832dcのsrc/HatoholArmPluginGateHAPI2.ccでは、これらが別々に行われている。

もし、upsertLastInfo()が成功した後、addEventList()がなんらかの失敗で例外を発生すると、不整合が生じる。

**Comment by kz0817** [comment]
DBTablesMonitoring::addEventInfoList()などに、transaction中に追加で実行する関数をオプションを追加する感じで、実現するか。

**Comment by cosmo0920** [comment]
:+1:
