### ISSUE TITLE
ProxyPassは、どのような目的で設定されている？

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#1576]
Apache上でWebUIを動かすためと思われる設定 /etc/httpd/conf.d/hatohol.confの中に、次の行があります。
<pre>
    ProxyPass /tunnel/ http://localhost:33194/
</pre>
これって、localhost:33194/が/tunnelにリバースプロクシされるための設定ですよね。けど、そもそもReverseProxyは、WebUIの一部であるhatohol/forwardview.pyが行うはず。
なぜ、必要かご存知の方がいれば教えてください。

**Comment by kz0817** [comment]
ProxyPassの行をコメントアウトしても動作する。

**Comment by ashie** [comment]
当時の某氏の内部作業記録を確認しました。
試行錯誤の過程であてずっぽうで入れたもののようで、
入れた前後で特に動作は変わらなかったようです。
消して大丈夫かと。

**Comment by kz0817** [comment]
情報ありがとうございます。
じゃあ、削って動作確認してPRしますね。そうしたら、このIssueを閉じましょう。

**Comment by kz0817** [comment]
マージされたのでクローズ
