### ISSUE TITLE
[HAPI2] プラグインが予期せず終了しても、Hatohol側で問題が報告されない

### ISSUE THREAD

**Issue by ashie** [project-hatohol/hatohol#1590]
プラグインが予期せず終了しても、Hatohol側で問題が報告されない(セルフトリガーが働かない)。
また、Hatohol起動直後やHAP2の設定追加後にexchangeProfileが成立していない場合は
「初期状態」のままで、やはり障害イベントは発生しない。

HatoholArmPluginGateHAPI2で、

* 通信が途絶えても何もしない
* プラグイン側メソッドのタイムアウト時に、ログにエラーを書き込むだけでセルフトリガーを発火させていない

ことが原因。

後者は実装すれば済む話

前者については更新間隔等の実装詳細がプラグイン側にまかされているという仕様上の
問題もあるが、更新間隔は一応サーバ側も認知しているので、この値を大きく越えて通信が
途絶している場合はイベントを発生させるべきか。

**Comment by kz0817** [comment]
とりあえず、今日、明日ぐらいで大和がやる

**Comment by kz0817** [comment]
セルフトリガのあり方について、今の仕様は、不自然というか誤解を招く気がしていて、従来のセルフトリガの仕組みを踏襲するのに気が引ける。

**Comment by kz0817** [comment]
コンソールログに似た感じで、トリガーに紐づかない
イベントを生成するだけでいいかもしれない。

**Comment by kz0817** [comment]
新しい自己監視の仕組みSelfTriggerで、HAP2からの応答が正常にあるというトリガーを追加する。

**Comment by kz0817** [comment]
#1880でPRしたパッチでは、Exchange ProfileとFetch系のリクエストの結果を監視している。
ポーリングで取得したデータの受信間隔も監視したほうが、コンサバティブであるが、プラグイン依存の部分もあるため、そこまで踏み込んでいない。

**Comment by kz0817** [comment]
#1880がマージされたのでクローズする
