### ISSUE TITLE
[HAPI2] Hatoholサーバ起動時にHAPI2セルフトリガーの回復イベントが毎回発生する

### ISSUE THREAD

**Issue by ashie** [project-hatohol/hatohol#1591]
Hatoholサーバ起動時に、HAPI2セルフトリガーの回復イベント（ステータスが「正常」の
イベント）が毎回発生する。障害が発生したものと勘違いしてしまって紛らわしい。

そもそも対応する障害イベントが存在しないので、こういった場合は回復イベントは発生させ
ない方が良い。

**Comment by ashie** [comment]
「正常」イベントと「障害」イベントの違いが分かり辛いというのも一因かもしれない。
特に画面上に障害イベントが一つも無い場合は。
「正常」ではなくて「回復」とかならまだ分かりやすいかもしれないが...

**Comment by kz0817** [comment]
ステータスのカテゴリを通知にするのも手ですね。

**Comment by kz0817** [comment]
起動時は、回復より、「正常に動作開始しました」のような通知になると親切ですね。

**Comment by kz0817** [comment]
続きを#1591で議論します。このIssueはクローズ。
