### ISSUE TITLE
[client][Servers] It takes a long time (approx. 30 to 60 sec) to remove a server.

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#160]
A deletion of a server sometimes takes a long time (30 to 60 sec).
This is especially when the server that settings is wrong.

The reason is considered to wait for a timeout of ArmBase subclasses instance.
The operation is designed to be synchronous. So the UI waits for the completion.
However, when the setting is wrong (e.g. an IP address is for a non-existing host), an ArmBase subclass instance typically stuck in the network library or the system like libsoup.

**Comment by t-miyazawa** [comment]
再現方法：
　1) 監視サーバとしてZabbixを登録する時、存在しないIPアドレスを指定する。
　2) 初期状態中に1で登録したZabbixサーバを削除する。
現状、初期状態の期間は短く、該当期間中に削除を行っても数秒で完了し、30秒以上かかるようなことはありませんでした。
この程度の時間であれば対処は不要ではないでしょうか。

**Comment by kz0817** [comment]
> 現状、初期状態の期間は短く、該当期間中に削除を行っても数秒で完了し、30秒以上かかるようなことはありませんでした。
約30秒、要するケースもあるということですよね？
であれば、対処したほうがいいですね。

**Comment by t-miyazawa** [comment]
数十回再現試験をしましたが、1度だけ10秒程度かかった事がありました。
削除中ダイアログが数秒以上表示される事自体あまり起こらず、起きたときも殆ど２、３秒で削除が完了します。

**Comment by kz0817** [comment]
Hatohol serverを終了させる場合も、長時間のブロックが発生しないか確認していただけますか？

**Comment by t-miyazawa** [comment]
監視中のNagiosサーバを停止後Hatoholサーバを停止したところ、長時間ブロックが発生する事を確認しました。
以下がその時のログです。
[ERR] <DBAgentMySQL.cc:601> Failed to query: SELECT nagios_services.service_id,nagios_servicestatus.current_state,nagios_servicestatus.status_update_time,nagios_servicestatus.output,nagios_hosts.host_object_id,nagios_hosts.display_name FROM nagios_services INNER JOIN nagios_servicestatus ON nagios_services.service_object_id=nagios_servicestatus.service_object_id INNER JOIN nagios_hosts ON nagios_services.host_object_id=nagios_hosts.host_object_id WHERE nagios_servicestatus.status_update_time>='2015-02-25 20:29:16': (2006) MySQL server has gone away.
[INFO] <DBAgentMySQL.cc:610> Try to connect after 0 sec. (1/5)
[ERR] <DBAgentMySQL.cc:559> Failed to connect to MySQL: ndoutils: (error: 2003) Can't connect to MySQL server on '192.168.122.112' (111)
[INFO] <DBAgentMySQL.cc:610> Try to connect after 10 sec. (2/5)
^C[INFO] <main.cc:103> recieved stop request.
[INFO] <main.cc:78> start exit process on the dedicated thread.
[INFO] <ArmBase.cc:300> ArmNagiosNDOUtils [50:centos6-nagios]: requested to exit.
[ERR] <DBAgentMySQL.cc:559> Failed to connect to MySQL: ndoutils: (error: 2003) Can't connect to MySQL server on '192.168.122.112' (110)
[INFO] <DBAgentMySQL.cc:610> Try to connect after 60 sec. (3/5)
[ERR] <DBAgentMySQL.cc:559> Failed to connect to MySQL: ndoutils: (error: 2003) Can't connect to MySQL server on '192.168.122.112' (113)
[INFO] <DBAgentMySQL.cc:610> Try to connect after 60 sec. (4/5)
[ERR] <DBAgentMySQL.cc:559> Failed to connect to MySQL: ndoutils: (error: 2003) Can't connect to MySQL server on '192.168.122.112' (113)
[INFO] <DBAgentMySQL.cc:610> Try to connect after 60 sec. (5/5)
[ERR] <DBAgentMySQL.cc:559> Failed to connect to MySQL: ndoutils: (error: 2003) Can't connect to MySQL server on '192.168.122.112' (113)
[DBG] <HatoholException.cc:62> HatoholException: <DBAgentMySQL.cc[50]:621> Failed to connect to MySQL: ndoutils: (2006) Can't connect to MySQL server on '192.168.122.112' (113)

[ERR] <ArmNagiosNDOUtils.cc:771> Error Connection: <DBAgentMySQL.cc:621> Failed to connect to MySQL: ndoutils: (2006) Can't connect to MySQL server on '192.168.122.112' (113)

 50
[DBG] <ArmBase.cc:150> lastPollingTime: 1424864151
[INFO] <ArmBase.cc:235> ArmNagiosNDOUtils [50:centos6-nagios]: destruction: completed.
[INFO] <FaceRest.cc:209> exited face-rest worker
[INFO] <FaceRest.cc:209> exited face-rest worker
[INFO] <FaceRest.cc:209> exited face-rest worker
[INFO] <FaceRest.cc:209> exited face-rest worker
[INFO] <FaceRest.cc:398> exited face-rest
[INFO] <FaceRest.cc:261> FaceRest: stop process: started.
[INFO] <FaceRest.cc:268> FaceRest: stop process: completed.

**Comment by kz0817** [comment]
MySQL clientライブラリが接続できない192.168.122.112は、Naigos Serverのことですよね？

**Comment by t-miyazawa** [comment]
MySQLのリクエスト自体は直ぐにエラーで返ってきていると思います。

リトライをしているメソッド
DBAgentMySQL::sleepAndReconnect(unsigned int sleepTimeSec)
内に以下のコメントがありました。

TODO:
add mechanism to wake up immediately if the program is
going to exit. We should make an interrputible sleep object
which is similar to ArmBase::sleepInterruptible().

**Comment by kz0817** [comment]
じゃあ、それ(TODO)をやりましょう。

**Comment by kz0817** [comment]
Zabbixのほうは、不再現ということですよね？であれば、Won't fix（というかどこかで治った）でいいと思います。

**Comment by t-miyazawa** [comment]
監視サーバ（Zabbix）削除は不再現で終了とします。
サーバ終了までに時間がかかる問題は別途 Issue 1060 としました。
