### ISSUE TITLE
WerckerのビルドをDockerベースインフラに対応させる

### ISSUE THREAD

**Issue by cosmo0920** [project-hatohol/hatohol#1615]
WerckerのビルドインフラがDockerベースになったとのアナウンスが公式ブログに出ている。
http://blog.wercker.com/2015/04/02/Introducing-our-docker-stack.html

このインフラを使えばboxに例えばcentos6.6のDockerイメージを使うことができるようになる上に、
wercker-labs/dockerのAMIスタックでは難しかったビルドアーティファクトの保存が可能となる見込みがある。すなわち、rpmを毎ビルド毎に保存できる可能性がある。

もしもこれができればnightlyビルドとしての提供が可能となるし、ビルドリソースを気にする必要がなくなるのでこれはぜひとも行いたい。

**Comment by cosmo0920** [comment]
> すなわち、rpmを毎ビルド毎に保存できる可能性がある。
> 
> もしもこれができればnightlyビルドとしての提供が可能となるし、ビルドリソースを気にする必要がなくなるのでこれはぜひとも行いたい。

より簡単にDockerイメージを使い、CentOS向けのビルドは気軽にできるようになったが、ビルドの成果物の保存はうまく動かなかった。これからはS3とか使えということなのだろう、ということで深追いはしていない。

Dockerイメージを直接持ってきてCIをする形になるので、これまでのAMIのデプロイを待つ時間がなくなる。そのため、WerckerでのCIの時間が短縮でき、ビルド時間の軽減が期待できる。

**Comment by cosmo0920** [comment]
こちらマージされたため、クローズします。after-stepsでビルドの成果物を保存出来そうですが、一旦ここまでにしておきます。

**Comment by Mnakagawa** [comment]
:+1:

**Comment by cosmo0920** [comment]
これで @Mnakagawa さんでも wercker.ymlのメンテナンスが出来るようになりますね！ :yum: 

あとWerckerでのビルド時間が15分から10分に短縮出来ました。
