### ISSUE TITLE
Create detailed documents about contribution

### ISSUE THREAD

**Issue by phanect** [project-hatohol/hatohol#163]
Currently there is a page about contribution on Hatohol website: http://hatohol.sourceforge.jp/contrib/

I, @kz0817, @bynnchapu, @mshiina, and some other members discussed and decided that contribution information on the web site should be minimum and detailed information should be placed on Github. (maybe on wiki?)

I wrote minimum information on the web page and am considering to add link to the document on Github, but there is no detailed document currently.
So detailed document is required.

**Comment by kz0817** [comment]
This issue is duplicated with #199. So I close this one.
