### ISSUE TITLE
イベントコンソールの配色

### ISSUE THREAD

**Issue by Mnakagawa** [project-hatohol/hatohol#1638]
主に「致命的な障害」の色についてなのですが、あまりに原色に近く、
視認性がよくないとの意見をいただきました。
議論の余地があるのではないかと考え、このIssueを立てました。

**Comment by cosmo0920** [comment]
彩度が強すぎる/明度が明るすぎるという事でしょうか？

試しに色をぐりぐりいじってみたのですが、こんな感じの配色はどうでしょうか：

![screenshot from 2015-10-30 16 06 25](https://cloud.githubusercontent.com/assets/700876/10840235/5bc794bc-7f20-11e5-961e-8fc827a74256.png)

ColorPickerで上の辺（彩度）と下の辺（明度）に接してしまって彩度と明度が極端にならないように調整してみました。

あくまでも一例で、元の配色から離れているので注意してください :)

**Comment by Mnakagawa** [comment]
このPRを見たときに「これならユーザーが自由に変更できるので、このIssueは不要だな」という
結論に至ったままCloseするのを忘れていました。
Good job。ありがとうございます:+1:

**Comment by Mnakagawa** [comment]
Related #1657

**Comment by cosmo0920** [comment]
いや、デフォルトの配色がそのままなのでOpenしておきたいですが…。デフォルトの配色を議論するのが些末な問題と言うのであればCloseで良いです。

**Comment by Mnakagawa** [comment]
早とちりでした。すみません。
個人的な感想ですが、やはり光の３原色に近い色（上記の画像でいえば致命的な障害の部分）は
避けたほうがいいのではないかと思います。

**Comment by Mnakagawa** [comment]
ただ致命的な障害が起こる頻度にもよると思うので、
致命的な障害が起こる頻度が高いと想定するのであれば、見やすい色に変えるべきだと思いますし、
頻度が低いと想定するのであればcosmoさんが提案してくださった上記の配色はとてもいいと思います。

これもまた私個人の考えですが、一般的に致命的な障害はそうそう起こらないという前提で
デフォルトの色設定は作ってしまっていいのではないでしょうか。
（つまり上の画像のcosmoさんの画像の配色）

**Comment by ashie** [comment]
> このPRを見たときに「これならユーザーが自由に変更できるので、このIssueは不要だな」という

ちなみに、現状はトリガー画面には反映されないという問題があります...

**Comment by cosmo0920** [comment]
> 一般的に致命的な障害はそうそう起こらないという前提で

想定していなかった問題が起きるから障害なのであって、致命的な障害の視認性も重視したほうが良いと思いました。 ;)

**Comment by BlueSkyDetector** [comment]
16.01向けにデザイナーさんに作成してもらった範囲に含まれていると勘違いしてました。
ただ、デフォルトのカラーがより良いものの方が良いと思うので、16.04に向けてデザイナーさんに提案してもらうようにしたいと思ってます。

**Comment by BlueSkyDetector** [comment]
> ちなみに、現状はトリガー画面には反映されないという問題があります...

上記は issue 登録されていますか？

**Comment by cosmo0920** [comment]
>> ちなみに、現状はトリガー画面には反映されないという問題があります...
> 上記は issue 登録されていますか？

すみません、こちら #1773 で対応済みです。

**Comment by BlueSkyDetector** [comment]
了解です。
ありがとうございました。
