### ISSUE TITLE
イベントビュー刷新 残りTODO

### ISSUE THREAD

**Issue by ashie** [project-hatohol/hatohol#1645]
## 未実装機能

* [x] 重要度のカスタマイズ
    * [x] ラベルのカスタマイズ
* [x] 「対応」のカスタマイズ
    * [x] 対応のカスタマイズに関連するREST APIに関連する機能を作成する
    * [x] ユーザーが対応の表示をカスタマイズできる設定画面を作成する
    * [x] WebUI側でユーザーが入力した対応のラベルを表示出来るようにする
    * [x] サーバー側でユーザー定義の対応も受け取れるようにする
* [x] メニューバーのメニュー項目を設定で制御できるようにする(設定UIはいらない)
* [ ] ブランディング(ロゴの入れ替えなどをできるように)
* [x] イベントの「概要」の切り詰め/展開機能(余裕があれば)
* ~~コピペ機能(本当に必要か?)~~
    * ブラウザのコピペで任意範囲をTSVで出力できるので、それでよしとする

### 不具合等

短期間に機能を詰め込みすぎたので、デバッグや機能の整合性の検証等が十分で無いと思われる。
色々精査が必要。

* [x] サマリービュー内のインシデントが絡む値は、インシデント設定が無い場合は表示しない
* ~~サマリービュー用のデフォルトフィルターは「障害」のみに制限する~~
    * 正常イベントも運用の現場では結局は人間が確認しないといけないことが多いので、重要イベントであることに変わりは無い。デフォルトでは正常も含めて全てカウントする（実装変更なし）。
* [x] イベント一覧用のフィルターに対して、クイックフィルターがANDになるのか上書きになるのかの対応がフィルター種別によってまちまち
    * ~~「対応」は今のところ上書きになっている。デフォルトフィルターでは「対処済み」は表示しない一方で、クイックフィルターで「対処済み」を選んだらそれが表示されるようにしたいという要求があるから。現状では他はANDになっているが、他もそれに倣うのが良いか?~~
    * ANDに統一する。クイックフィルターには、選択しても意味が無い選択肢は出ないようにする。
* ~~デフォルトフィルターで「対応」の「対処済」は表示されないようにする~~
    * 対処済みを非表示にしたい場合には、ユーザー自身でそういうフィルターを登録してもらうこととする（実装変更なし）。
* [x] 「対応」を複数同時変更しようとするとクラッシュする場合がある（再現条件不明）
    * @ashie の環境では再現していない。 今のところ @cosmo0920 の環境でのみ再現
* [x] 「対応を変更」したあと、選択がそのままなのが気持ち悪い。「-------」を追加して、選択後にそこに戻すべき
  * 「未対処」に戻すと「未対処」に変更できないため
* [x] 対応(インシデント)は障害イベントにしかDB行がアサインされないが、正常イベントでも出すべきか?
    * 正常イベントも結局は人間が確認しないといけないので、重要イベントであることに変わりは無い。正常イベントもインシデント登録できるようにする。
* [x] 「最小の重要度」フィルターにラベルを追加する。数値は頭に残しておいて良いと思う。
* [x] ウィンドウをリサイズしたときに円グラフがリサイズされない
* [x] 「最新イベント」を「フィルタ適用」の隣に移動
* [x] 「最新イベント」押下時に「終了時刻」を空にする
* [x] サイドバーの表示・非表示は状態を覚えておきたい
* [x] ~~OPPRVLG_GET_ALL_SEVERITY_RANKの権限がないとサマリビューがまともに動かないと思う~~
    * 今のコードではサーバ側では使われていないので、残り作業としては権限そのものを削除する
* ~~イベント数カウントのREST APIはサーバ側で何らかの制限をかけるべきではないか? (条件が空だと全てのイベントが対象になるので負荷がとんでもないことになる）~~
    * ユーザーが不用意に/tunnel/summaryと打ち込んでもNot found session IDになるし、不正でないユーザーがわざわざ苦労してsession IDを与えてそれをやるとも思えない。不正ユーザーにやられるとしたらそれ以前の問題なので、当面は特になにもしなくていいか。
* [x] サマリのイベント数・ホスト数のカウント 仕様および実装再度チェック。
    * 「対応」が空白のものは対応済みにも未対応にもカウントされていない

### 要仕様検討

皆で評価したうえでどう対応するか検討が必要。

* ~~クイックフィルタ適用時にはサマリーにも同じクイックフィルターを適用すべきではないか? クイックフィルターを適用してもサマリーが変化しないのは不自然。~~
    * ~~ただ、現状の仕様ではデフォルトフィルターとして別々のフィルターが適用できてしまう。デフォルトで表示されている期間がサマリーの条件と一致するとは限らないのにクイックフィルター適用で揃えるのはそれはそれで不自然。どういう仕様にすべきなのかよくわからない。~~
    * 今回はサマリーはクイックフィルターと連動しない仕様として実装変更無し
* [x] サマリーがどういう条件で集計されているのかぱっと見分からない。
    * 時間があればフィルター名くらいは出すようにする
    * デフォルトフィルターを設定できる一方でイベント画面からフィルターを変更できないというのもどうかと思うので、イベントリストと同じフィルター選択メニューを追加してみる
* [x] ユーザー定義の「対応」を追加できるようにした場合、それらが「対応済」か否かはどう判断するのか?
    * 未対応にカテゴライズされるユーザー定義をいくつも追加するとは思えないので、今回はユーザー定義は全て対応済とする。要望があれば別途考える。
* [x] フィルター設定が使いづらい(ひとまずペンディング)
    * うっかり意図しないフィルターを変更してしまう(ドロップダウンメニューでフィルターの選択を忘れたまま編集してしまう)。
    * 「◯◯を条件に含める」チェックボックスにチェックを入れるのを忘れやすい
    * 変更にかかる手数が多すぎる
    * 設定名が短いものはBootstrapのアコーディオンを開きにくい
* イベント画面と他の画面の乖離が激しい（ひとまずペンディング）

**Comment by ashie** [comment]
あるいは/event/summaryか、/summary/eventか

**Comment by ashie** [comment]
> イベント一覧用のフィルターに対して、クイックフィルターがANDになるのか上書きになるのかの対応がフィルター種別によってまちまち

実装するまえは当然ANDにすべきと思っていたのだが、今は上書きの方が良い気がしている。
見えているフィルタの方が優先される方が直感的に感じたので。
と言うより、フィルタを指定したのに何も出ないのが不自然に感じた。

**Comment by ashie** [comment]
> イベント画面と他の画面の乖離が激しい

特に似たようなデータであるトリガーページとの乖離が酷い。

**Comment by ashie** [comment]
> OPPRVLG_GET_ALL_SEVERITY_RANKの権限がないとサマリビューがまともに動かないと思う

この権限はいらないんじゃないかなぁと思っている。
全てのユーザーが取得できていいと思う。

User role(ユーザー種別)についても、とりあえず誰でも取れないと面倒そうだったので
権限は追加しなかった。

**Comment by ashie** [comment]
> ユーザーが不用意に/tunnel/summaryと打ち込んでもNot found session IDになるし、不正でないユーザーがわざわざ苦労してsession IDを与えてそれをやるとも思えない。不正ユーザーにやられるとしたらそれ以前の問題なので、当面は特になにもしなくていいか。

別issueにある古いイベント削除である程度解消できるかもしれないけど、やはり軽い気持ちで長め
の期間を指定した場合などには、手元の非力な環境ではつらい。

**Comment by cosmo0920** [comment]
>> ユーザーが不用意に/tunnel/summaryと打ち込んでもNot found session IDになるし、不正でないユーザーがわざわざ苦労してsession IDを与えてそれをやるとも思えない。不正ユーザーにやられるとしたらそれ以前の問題なので、当面は特になにもしなくていいか。

> 別issueにある古いイベント削除である程度解消できるかも

homekeeperのような何かほしいですね。。

**Comment by ashie** [comment]
ステータスのフィルターに仕様および実装上のバグがあった。

本来はEventTypeでフィルターすべきなのに、TriggerStatusでフィルターしていた。
EventTypeのフィルターはすっぽり実装が抜けている。

typeとstatusは本当に紛らわしい。

**Comment by ashie** [comment]
> 「ステータス」のフィルターに仕様および実装上のバグがあった。

これについては直してpull requestを出した(#1678)。
他にも、イベントリストの列の処理のところも「status」になっているが、これもtypeに直しておきたい。
できれば表示の方も紛らわしいので直したい。
あと「status」と「state」が随所で混同されているような気がする。

**Comment by ashie** [comment]
DBがUTF-8になっていないと、日本語フィルター名を保存しようとしたときにエラーとなる。
それは仕様ということで問題ないが、何も設定しないでREADMEの通りセットアップすると
distroの標準設定によっては普通に起こり得るので、READMEに何かしら記述が必要。

**Comment by ashie** [comment]
「重要イベント発生ホストの割合」の分母は今はイベント発生ホストの数になっているようだが、
分母は全ホストにすべきではないか?

**Comment by cosmo0920** [comment]
> 「重要イベント発生ホストの割合」の分母は今はイベント発生ホストの数になっているようだが、
> 分母は全ホストにすべきではないか?

#1686 で修正しようと試みています。

**Comment by ashie** [comment]
> #1686 で修正しようと試みています。

マージした。

**Comment by ashie** [comment]
> DBがUTF-8になっていないと、日本語フィルター名を保存しようとしたときにエラーとなる。
> それは仕様ということで問題ないが、何も設定しないでREADMEの通りセットアップすると
> distroの標準設定によっては普通に起こり得るので、READMEに何かしら記述が必要。

クライアントのデータベース作るときに明示的に指定するのであれば以下:

```
CREATE DATABASE hatohol_client DEFAULT CHARACTER SET utf8;
```

**Comment by cosmo0920** [comment]
mysql>  ALTER DATABASE hatohol_client CHARACTER SET utf8;

でも大丈夫ですね :)

**Comment by ashie** [comment]
> でも my.cnf でまとめてデフォルトをセットしておく方が良いと思う。

とはいえDjangoがUTF-8を期待しているようなので、やっぱり作るときにも明示的に指定した方が良いかも。
(client/README.md を修正)

**Comment by cosmo0920** [comment]
>     mysql>  ALTER DATABASE hatohol_client CHARACTER SET utf8;

> でも大丈夫ですね :)

作りなおしたほうが確実に動作するようです。。

**Comment by ashie** [comment]
あー、でもリリース時にアップグレード手順は示さないとダメかも。

**Comment by cosmo0920** [comment]
ID不明のホストがある場合はAllHostsにカウントしない方が良さそう。

こうなってしまう：
![screenshot from 2015-11-09 16 25 12](https://cloud.githubusercontent.com/assets/700876/11028071/7adfa728-86fe-11e5-8a3a-3f2decbba8d0.png)

**Comment by ashie** [comment]
フィルター設定で「表示するサーバ(orホストorホストルグループ)」を有効にし、かつ何もサーバ)orホストor
ホストグループ)を選択しないと、全てのサーバ(orホストorホストグループ)が選択されてしまう。

何も表示しないという設定をわざわざするとは思えないのでこのままの仕様でも良いと思うが、直感的では
無いとも思う。

**Comment by ashie** [comment]
> メニューバーのメニュー項目を設定で制御できるようにする(設定UIはいらない)

もともとJavaScriptで動的生成しているのでjsファイルを一個置いておくのがコード的には楽だが、
設定箇所はまとめた方がわかりやすいので、client/hatohol/settings_common.pyに入れておくのが
良いか。

**Comment by cosmo0920** [comment]
> 設定箇所はまとめた方がわかりやすいので、client/hatohol/settings_common.pyに入れておく

:+1:

賛成です。DBを持ち出すのは何か違うかなぁと言う気がしてました。

**Comment by ashie** [comment]
> 設定箇所はまとめた方がわかりやすいので、client/hatohol/settings_common.pyに入れておくのが

base_settings.pyの間違い。

**Comment by ashie** [comment]
> メニューバーのメニュー項目を設定で制御できるようにする(設定UIはいらない)

#1715で対応済み

**Comment by ashie** [comment]
重要度設定やインシデントラベル設定で、設定を変更したあとに保存を忘れて他のページに
移動してしまいやすい。ページ遷移時にダイアログを出した方が良い。

**Comment by ashie** [comment]
最近の修正で`OPPRVLG_*_CUSTOM_INCIDENT_STATUS`という権限が追加されたが、
`OPPRVLG_UPDATE_INCIDENT_SETTING` できないだろうか?

権限を細分化しても、使いにくいだけで実際にそれを利用するシーンが思い浮かばない。
また、細分化するのであれば、テナント毎にインシデントラベルを個別に設定できるように
しないとほとんど意味が無いと思う。

**Comment by ashie** [comment]
> 最近の修正で`OPPRVLG_*_CUSTOM_INCIDENT_STATUS`という権限が追加されたが、
> `OPPRVLG_UPDATE_INCIDENT_SETTING` できないだろうか?

異論が無ければ私の方でそのように修正します。

**Comment by ashie** [comment]
> OPPRVLG_GET_ALL_SEVERITY_RANKの権限がないとサマリビューがまともに動かないと思う

これもついでに削除することにする。

**Comment by ashie** [comment]
> フィルター設定が使いづらい(ひとまずペンディング)

アコーディオンを止めて、単にチェックボックスと連動して表示/非表示にしたほうがまだマシか?

**Comment by ashie** [comment]
> アコーディオンを止めて、単にチェックボックスと連動して表示/非表示にしたほうがまだマシか?

手元でやってみたが、全部開くとやっぱりかなりウザい感じになる。

**Comment by ashie** [comment]
> 手元でやってみたが、全部開くとやっぱりかなりウザい感じになる。

とはいえ、デフォルトの表示はシンプルだし、チェック入れ忘れも無くなるので、現状よりはマシか。

**Comment by kz0817** [comment]
> とはいえ、デフォルトの表示はシンプルだし、チェック入れ忘れも無くなるので、現状よりはマシか。

かなり、シンプルでいい感じだと思います。
ただ、デザインに強い人を交えて、チェックボックスの代替がないかや文言をブラッシュアップできる余地はまだあるかなと思います。

**Comment by ashie** [comment]
#1754 で以下の2つ

> * サーバー側でユーザー定義の対応も受け取れるようにする
> * ユーザー定義の「対応」を追加できるようにした場合、それらが「対応済」か否かはどう判断するのか? 

および以下の一部を修正

> サマリのイベント数・ホスト数のカウント 仕様および実装再度チェック。

**Comment by ashie** [comment]
今のIncidentの仕組みはActionに乗っかっているため、アクションが実行されないケースでは
Incidentを登録することができない。これが発生した場合

> * ユーザー定義の「対応」を追加できるようにした場合、それらが「対応済」か否かはどう判断するのか?

永遠に「対応済」にすることができない。
現時点で把握しているアクションが実行されないケースは

* そもそも設定したアクション実行条件を満たしていない
* 長期間Hatoholサーバを落としていた場合、古いイベントはアクションが実行されない

**Comment by ashie** [comment]
今回追加したIncident絡みの機能は、ほとんどHatohol以外のIncidentTrackerを考慮していない。
一応、Redmineを混ぜた場合には矛盾する機能を非表示にするようにしているが、ちゃんと検証していない。
また、できれば非表示にするのではなくて併用できるようにしたい。

**Comment by ashie** [comment]
>>    OPPRVLG_GET_ALL_SEVERITY_RANKの権限がないとサマリビューがまともに動かないと思う
>
>この権限はいらないんじゃないかなぁと思っている。

OPPRVLG_SYSTEM_OPERATION というのが追加されているので、編集系の権限もそっちに
集約してしまった方が良さそうに見える。

**Comment by ashie** [comment]
> OPPRVLG_SYSTEM_OPERATION というのが追加されているので、編集系の権限もそっちに

いや、これはOPPRVLG_GET_SYSTEM_INFOと対になるもので、名前が不適
(SYSTEM_INFO_OPERATION となるべき)なのか?

**Comment by ashie** [comment]
ただシステム関連設定の権限はある程度集約した方がよいとは思う。
という話は別issueにした方が良いか。

**Comment by ashie** [comment]
> 今のIncidentの仕組みはActionに乗っかっているため、アクションが実行されないケースでは
> Incidentを登録することができない。これが発生した場合
> 
>>  ユーザー定義の「対応」を追加できるようにした場合、それらが「対応済」か否かはどう判断するのか?
> 永遠に「対応済」にすることができない。

今の実装では、IncidentStatusが空の場合は「対応済み」にカウントされるようになってしまっていた。
空の場合は未対応としてカウントするように修正する。

**Comment by ashie** [comment]
> サマリのイベント数・ホスト数のカウント 仕様および実装再度チェック。

重要度設定と、SeverityフィルタがANDになっていないようなので、これも合わせて修正する。

**Comment by ashie** [comment]
いや、そもそもIncidentが作成されなかったケースもケアするのであれば、
やはり未対応をカウントするのではなく、対応済みをカウントすべきなのか。

**Comment by ashie** [comment]
> 重要度設定と、SeverityフィルタがANDになっていないようなので、これも合わせて修正する。

インシデントの条件もANDになっていないので、これも合わせて修正する。

**Comment by ashie** [comment]
> /summaryというパスは何のサマリだか区別が付かないので、他で同様のものが追加されるとまずい。
> /event-summaryとすべきか。

> あるいは/event/summaryか、/summary/eventか

summaryというよりはstatisticsにしたい。
また、「important」も入れたい(ここでは基本的に重要イベントにしか着目していないので)。

/statistics/important-events か。

**Comment by ashie** [comment]
> summaryというよりはstatisticsにしたい。

が、クラス名その他と不一致になってまた面倒くさいのでsummaryのままでいいか。

**Comment by ashie** [comment]
> が、クラス名その他と不一致になってまた面倒くさいのでsummaryのままでいいか。

あ、でもstatisticsにしたいと思った動機の一つとして

  /summary/important-events

だと中身にeventが詰まってそうな雰囲気を感じたからだった。

  /statistics/important-events

なら統計情報(イベント数とかパーセンテージとか)だけでイベントそのものが詰まっているイメージを
避けられそう、と思った。

ま、どっちでもいいけど...

**Comment by cosmo0920** [comment]
/summary/event-statistics という案もなきにしもあらずですけど、どうなんでしょうね。。

**Comment by ashie** [comment]
もうコミットしちった。

**Comment by ashie** [comment]
> /summary/event-statistics という案もなきにしもあらずですけど、どうなんでしょうね。。

importantを入れたいので

/summary/important-evnet-statistics

となると、なんかくどい。

**Comment by ashie** [comment]
というか "summary" と "statistics" の両方が入るのがくどい。

**Comment by ashie** [comment]
> ブランディング(ロゴの入れ替えなどをできるように)

これは当issueとは関係ないので、それを除けば挙げていたTODOはほぼ完了。
当issueは長くなりすぎたということもあるので、残りの課題は別issueで扱うこととしていったんcloseする。

**Comment by ashie** [comment]
サマリーでカウントされる「重要イベント」のみをイベントリストで表示されるようにするフィルタが、
デフォルトでは用意されていない。サマリーではデフォルトのフィルター設定に加えて「重要度設定」
で設定する「重要フラグ」とのANDフィルタになっているのだが、イベントリストの方ではこのフラグ
が使われていない。

デフォルトでは両者が一致するように絞り込むことができないため、感覚的に分かりにくい。

**Comment by ashie** [comment]
> サマリのイベント数・ホスト数のカウント 仕様および実装再度チェック。

今の実装では「重要イベント発生ホスト数」とその割合は、対応済かどうかでフィルターしていない。
期間が長いと、100%にまっしぐらな気がする。
