### ISSUE TITLE
[Client] Unify the notation of the monitoring servers

### ISSUE THREAD

**Issue by bynnchapu** [project-hatohol/hatohol#165]
In current implementation, Nickname is shown in the Dashboard page to distinguish the server.
But, in the other pages (e.g. Triggers, Items, etc...), Hostname is shown to distinguish the server.

**Comment by cosmo0920** [comment]
@Mnakagawa san's pull request #957 is already merged into master.
This issue seems to be able to close, right?

**Comment by Mnakagawa** [comment]
@cosmo0920 san
Yes, this issue able to closing.
I close it.
