### ISSUE TITLE
When privileges enums are defined greater than or equal to 32, JavaScript side codes do not handle privileges properly

### ISSUE THREAD

**Issue by cosmo0920** [project-hatohol/hatohol#1694]
Hatoholの権限周りはC++ではenumによる定数、JavaScriptではhatohol_def.jsで定義されていて、権限を持っているかの判定にはどちらもビット演算を用いています。

JavaScriptではビット演算をする時に32bitの符号付き整数にキャストが行われるため、演算結果がおかしくなってしまいます。 https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Bitwise_Operators
32個以上の権限を定義したい時にはどのようにすれば良いのか相談させてください！

C++では`1`(32bit整数リテラル)を用いていた事により、32個以上の権限の定数を定義した時にテストが失敗していました。こちらは https://github.com/project-hatohol/hatohol/pull/1696 にあるように `1ULL` (64bit非負数リテラル)を用いる事で回避できました。

**Comment by ashie** [comment]
> JavaScriptではビット演算をする時に32bitの符号付き整数にキャストが行われるため、演算結果がおかしくなってしまいます。 https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Bitwise_Operators

今の手持ちの作業が終わったら修正にチャレンジしてみます。
(上位ビットを分割してチェックorセットする関数追加)

**Comment by ashie** [comment]
一応ECMA-262を確認

http://ecma-international.org/ecma-262/5.1/#sec-11.7.1

やはり符号付き32bit整数

```
The result is a signed 32-bit integer.
```

**Comment by cosmo0920** [comment]
うーん…64bitのビット演算がJavaScriptで出来るようになったとしても残り32個(31個?)の権限の定義までしか出来ないので早めに他の方式に移行したいですね…。（そのまで権限が必要なのかと言われるとそうでも無さそうにも思いますが。）

**Comment by ashie** [comment]
JavaScriptは浮動小数点でしか扱えないので、指数部を引くと残り32も無いです。

**Comment by cosmo0920** [comment]
確かに51桁か52桁程度になりますね。

**Comment by ashie** [comment]
52bitまでは扱えるようにした (#1707)
サーバから文字列で渡すようにしてJavaScript側でも頑張れば多分何bitでもいけるけど、
そこまで頑張らなきゃならなくなる前に他の形式に移行したい...

**Comment by cosmo0920** [comment]
蛇足ですがgcc or clangには `__uint128_t` という型も使えます。128bit付近まではなんとか頑張れる感じです。そこまで引っ張る前に他の方式に移行したいですね。。

**Comment by cosmo0920** [comment]
実はまだ問題があった。 hatohol-def-src-file-generatorで32bit以上の整数値を文字列に変換できない問題があるので修正した #1710

**Comment by cosmo0920** [comment]
#1711 で32個以上の権限を定義してもWebUIのテストは完走した。
