### ISSUE TITLE
User defined severity colors are not used in event console

### ISSUE THREAD

**Issue by cosmo0920** [project-hatohol/hatohol#1717]
### Environments

* Mac OS X 10.9.5
* Safari 7.1.6
* Used Hatohol revision 49f9db5

--

* Mac OS X 10.11.1
* Firefox 42.0 and Safari 9.0.1
* Used Hatohol revision 49f9db5

### Screenshot

In some cases, user defined severity colors are not used in event console on Safari Mac OS X like this:

![hatohol_event_console_severity_color_not_set](https://cloud.githubusercontent.com/assets/700876/11143139/53d1d0e4-8a36-11e5-9692-fa02793dcaa6.png)

This phenomenon is sometimes happened.

**Comment by ashie** [comment]
Could you test events-view-refine-load-order branch?

**Comment by cosmo0920** [comment]
Latest commit https://github.com/project-hatohol/hatohol/commit/a725d5f0881691307f7e31c48c13f64c723c4274 works fine in my environment.

**Comment by ashie** [comment]
Merged.
