### ISSUE TITLE
[HatoholServer] HAP2から送信されたアイテムのグループがDBに保存されない

### ISSUE THREAD

**Issue by Mnakagawa** [project-hatohol/hatohol#1721]
HAPI-2.0の仕様に従い，アイテムの所属するグループ名を
itemGroupNameにStringの配列にし，Hatoholサーバーに送った場合に
それがDBに保存されない。
(exe. {"itemGroupName": ["group1", "group2"]})
このグループ名がひとつの場合でも保存されないため，
Hatoholサーバー側が，配列ではなく文字列が来ることを期待しているのではないかと推測。

**Comment by ashie** [comment]
あ、配列だということを今知りました。
仕様は「String255配列」になっていますが、サンプルは文字列になっていますね。

https://github.com/project-hatohol/HAPI-2.0-Specification#putitemsmethod

また、HAPI-2.0以前の実装としてはitemGroupNameは文字列だったと思います。
このためitemGroupNameのテーブル定義は文字列になっており、すぐに直すのは厳しそうです。

**Comment by Mnakagawa** [comment]
「複数のグループに所属する場合」を考慮した結果，現在のような仕様になったと記憶しています。
当面はhap2の方を配列ではなく，文字列にして対応させるのがいいかもしれません。
16.01リリース後に直すべきか，リリース前に直すべきか考える必要がありますね。

**Comment by ashie** [comment]
REST APIの改訂も必要だ。

**Comment by kz0817** [comment]
> 当面はhap2の方を配列ではなく，文字列にして対応させるのがいいかもしれません。

Hatohol Serverで完全に対応するのがすぐにできないなら、２つ目以降のitemGroupNameを
無視するという暫定実装にしておくのはどうでしょうか。
仕様に妥当性があるなら、実装に合わせて、仕様を変更するのは本末転倒だと思います。

**Comment by kz0817** [comment]
> ２つ目以降のitemGroupNameを無視するという暫定実装にしておくのはどうでしょうか。 

これに異論なければ、私がサクッとやります。

**Comment by ashie** [comment]
> ２つ目以降のitemGroupNameを無視するという暫定実装にしておくのはどうでしょうか。

はい、私もHAPI-2.0の仕様を変更することは考えていませんでしたので、それが良いと思います。

> これに異論なければ、私がサクッとやります。

よろしくお願いします。

**Comment by Mnakagawa** [comment]
> これに異論なければ、私がサクッとやります。

よろしくお願いします。仕様書のサンプルの方はこっちで直しておきます。

**Comment by kz0817** [comment]
あ、仕様書の変更もいまやってます。

**Comment by Mnakagawa** [comment]
助かります！お願いします〜

**Comment by kz0817** [comment]
修正がMergeされたのでクローズ

**Comment by Mnakagawa** [comment]
#1739 はあくまで暫定実装ですし，クローズしないほうがいいのでは

**Comment by cosmo0920** [comment]
このIssueはあくまでも保存されない事を問題にしているのでクローズは妥当だと思います。
暫定実装をより良くするのは別Issueでやりましょう。
