### ISSUE TITLE
Zabbix (HAPI2)からexperimentalを削除する

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#1728]
[experimental]という文字列を削除するとともに、品質も実用レベルにする！

<img width="481" alt="2015-11-17 12 06 09" src="https://cloud.githubusercontent.com/assets/2610513/11201707/d5640952-8d23-11e5-9bd5-dc7cbd1eaf62.png">

**Comment by kz0817** [comment]
品質はがんばるとして、[experimental]という文字列を取り除きましょう。

**Comment by teruo-oshida** [comment]
Please tell me which plugin is still experimental.
Can I remove every strings for all plugin?

Ceilometer (HAPI2) 
Nagios (HAPI2) 
Zabbix (HAPI2) 
Fluentd (HAPI2) 
Zabbix (HAPI) 
JSON (HAPI)

**Comment by kz0817** [comment]
> Can I remove every strings for all plugin?

Yes, please remove the string in all plugins.

**Comment by teruo-oshida** [comment]
I see, I will.

**Comment by kz0817** [comment]
修正マージされたようですし、作業完了なら、クローズしてください。
