### ISSUE TITLE
[hap2] パッシブモードのOnOffが反映されない

### ISSUE THREAD

**Issue by Mnakagawa** [project-hatohol/hatohol#1733]
パッシブモードのチェックボックスにチェックを入れ，
一度保存した後に再度編集画面に移行すると，チェックボックスが外れている。
Hatoholサーバーとのやりとりを見ると，onに設定した場合でも，offに設定した場合でも
"passiveMode":false，と返ってきている。

ここの実装は，パッシブモードをoffにした場合，DB内のarm_pluginsテーブルの
pathカラムにそれそれのプラグインに対応したスクリプトが指定される。
offにした場合は，空になる。Hatoholサーバーはこのカラムの状況を見て，
WebUIに passiveModeがtrueかfalseか返している。

パッシブモードをonにして，サーバー情報をWebUIから更新した場合，
上の通り，pathカラムが空になることを期待しているが，実際にDBを見て見ると
スクリプトは指定されっぱなしだった。

**Comment by ashie** [comment]
確かに以下の箇所でHAPI2の場合は何もやってないので、そういう動作になりそう。

https://github.com/project-hatohol/hatohol/blob/master/server/src/RestResourceServer.cc#L487

**Comment by kz0817** [comment]
ちょっと、これも私の方で引き取ります。進捗によっては、誰かに誰かにお願いするかもしれませんが。

**Comment by ashie** [comment]
いったん @cosmo0920 さんの方で引き取ります。

**Comment by kz0817** [comment]
はい、よろしく、お願いします。

**Comment by ashie** [comment]
Fixed.
