### ISSUE TITLE
Hatoholサーバのセルフトリガについて

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#1745]
セルフトリガについて、もやもやと感じていること

1. セルフトリガが一次元的な依存をもつと仮定されている。ArmUtilsのupdateTriggerStatus()あたり。一般には、独立であったり、複数の他のトリガに依存する。

2. HAPI2PluginCollectTypeなど、Collectという語がしばしば用いられているが、Internal errorやAMQPブローカーとの接続失敗など、収集と直接関係のない項目もあり、ミスリードな感じがある。

3. (実装の問題だが）ArmUtilsを生成するときに、ArmTriggerの配列をセットして、使うものだけ、あとからenableにするというのがなんか引っかかる。動的に追加したり、削除できるほうが実装もスマートにならないか。

4. セルフトリガのホストの扱い。hostnameが関連する監視サーバの末尾に_SELFを付加したものなっているが、WebUIで見た時、視認性がよいとは言い難い。（表示だけなら、WebUIで変更も可能だが。。。)

**Comment by kz0817** [comment]
> セルフトリガのホストの扱い。hostnameが関連する監視サーバの末尾に_SELFを付加したものなっているが、WebUIで見た時、視認性がよいとは言い難い。（表示だけなら、WebUIで変更も可能だが。。。)

トリガ画面にしろ、イベント画面にしろ横の列に監視サーバ列があるので、監視サーバ名をセフルトリガのホストに含める必然性は少ないと思う。

**Comment by kz0817** [comment]
もうひとつ

5. すべての事象をZabbixのようにトリガとして扱うか？
  
例えば、AMQP Brokerのコネクションや、プラグインが監視サーバにアクセスできているかは、トリガのような概念で表現しやすが、パースエラーなど、状態でないものは無理にトリガとしてなくてもいいのではないの？特にこのようなものは、トリガの回復をどうするかの設計が難しい。

**Comment by kz0817** [comment]
具体的な例で考えていくとHAPI2関連の関連の場合、すべてトリガでいいのかもしれない。詳細な情報は、Hatohol Serverやプラグインがイベントを生成してイベント画面で、その内容を確認するのがよいかもしれない。つまり、セルフトリガの遷移だけで自動的にイベントの発生することはない。（コードを削減するために自動的に行うオプションはあってもいいが）

トリガ候補
  1. AMQP Brokerとの接続
  2. プラグインと監視サーバとの接続
    - 監視サーバから応答がない、経路がない
  3. プラグインの監視サーバから応答解析時の問題
    - HTTP500などのエラーが返る
    - 応答のパースエラー
  4. プラグインの内部状態
  5. PluginGateの内部状態

実際、これらは、すでに定義されている HAPI2PluginCollectTypeと、ほぼ同じ。
<pre>
        NG_PARSER_ERROR = 0,
        NG_DISCONNECT,
        NG_PLUGIN_INTERNAL_ERROR,
        NG_HATOHOL_INTERNAL_ERROR,
        NG_PLUGIN_CONNECT_ERROR,
        NG_AMQP_CONNECT_ERROR,
</pre>

**Comment by kz0817** [comment]
ユーザーからの見えとしては、次の点が変更になる。

- 自己監視トリガが変化した時のイベントのメッセージは、トリガ画面の説明とは異なることがある（一般にはより詳しい情報が記載される）
- トリガが存在しない自己監視イベントが発生することがある。

***
最初に挙げた自己監視のためのホスト名は、もう少し考える

**Comment by kz0817** [comment]
とりあえず、内部実装を整理してみる。

**Comment by ashie** [comment]
関連issue:
* #1591 
* #1585 

ここにまとめてしまった方が良いか?

**Comment by kz0817** [comment]
> ここにまとめてしまった方が良いか?

そうですね。提案ありがとうございます。

**Comment by cosmo0920** [comment]
#1803 がマージされたため、クローズします。

**Comment by kz0817** [comment]
もう少しブラッシュアップしたいのでReopenします。

**Comment by kz0817** [comment]
Internal Errorは、トリガ画面に表示しないほうが自然だと思う。内部的にメモリーが足りないなどの突発的な事象が発生した場合に発動するので、イベントとしてそれらを記録するほうがよいと考える。

**Comment by kz0817** [comment]
PluginGateHAPI2で、pluginから受け取ったメッセージのパース失敗も、状態として、常にトリガー画面に出しておくのになじまないと考える。これも、そのような事象が発生したときにイベントとして出力する。

**Comment by kz0817** [comment]
Pluginのエラーもイベント画面で通知するようにした。リトライし続けると少しうるさいが、何も表示されないよりはいいはず。

![erros](https://cloud.githubusercontent.com/assets/2610513/11999463/00e87d8c-ab02-11e5-9522-d6592c8212f5.png)

**Comment by kz0817** [comment]
主要な改善が取り込まれたのでクローズする。
