### ISSUE TITLE
イベント画面のグラフが表示されない

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#1747]
最近のmasterでビルドして、動作させると、イベント画面で、円グラフが表示されません。以前は表示されていたと思うのですが、思い当たる原因ありますか？

commit ead94433b2adf77ae5e102979349cee8633bc7c7
Merge: 78b4466 80a050c
Author: Kazuhiro Yamato <kz0817@gmail.com>
Date:   Thu Nov 19 09:48:37 2015 +0900

    Merge pull request #1742 from project-hatohol/simplify-filter-config-ui
    
    [EventsView] Simplify the filter config UI

![hato-graf](https://cloud.githubusercontent.com/assets/2610513/11267036/46b4f304-8eec-11e5-88ff-e6049482db4a.png)

**Comment by ashie** [comment]
うーん、再現してないです。
JavaScriptコンソールに何かエラーログとか出てますか?

**Comment by kz0817** [comment]
CSSがたりない？make installじゃ、インストールされない?
<pre>
http://hdev3long/hatohol/static/css.external/spectrum.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://hdev3long/hatohol/static/js.external/jquery.flot.pie.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://hdev3long/hatohol/static/js.external/jquery.flot.resize.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://hdev3long/hatohol/static/css.external/spectrum.css Failed to load resource: the server responded with a status of 404 (Not Found)
</pre>

**Comment by ashie** [comment]
なるほど、gitリポジトリで直接実行していたので気がつきませんでした。
確かにMakefile.amに入って無いですね。

**Comment by kz0817** [comment]
修正がマージされたのでクローズ
