### ISSUE TITLE
WebUIのログインに失敗する

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#1761]
最近のmaster(少なくとも 06c9843 ）で、WebUIでログインしようとすると
失敗して、ログインダイアログが出つづける状態になることがある。

そのようになった場合でも、シークレットブラウズモードにして、ログインを試みると成功する。クッキーなどが関係しているのではないだろうか？しかし、最近そこにかかわる修正はなかったと記憶している。

**Comment by ashie** [comment]
c3818a90 でトップパスを弄ったのはクッキーに影響あるかも。

**Comment by kz0817** [comment]
最近、再現しないので、一旦クローズ。

**Comment by kz0817** [comment]
再現したので、再オープン。
manage.pyでは、発生の経験がない。
apacheを使っている環境のみで今のところ発生している。

**Comment by kz0817** [comment]
<pre>
apiVersion: 4
errorCode: 0
sessionId: "9070833c-0e6f-40eb-9117-ef6c4f70e0d7"
</pre>
ログインで、上記のsessionIdを得たにもかかわらず、次の/meリクエストに
含まれるsessionは、次のものだった。
<pre>
X-Hatohol-Session:0d611791-072f-4eb5-a621-c66c3227475f
</pre>

**Comment by kz0817** [comment]
<pre>
"hatoholSessionId=0d611791-072f-4eb5-a621-c66c3227475f",
" csrftoken=f3a1vGdL7nzVMKeVP0p8epd9pJt1BTQd",
" hatoholSessionId=0edc87a3-ffb2-4b44-93ca-f4efff05380c"
</pre>

cookieを見ると、新しいSessionIDは、上記の3行目、空白がついて始まっている。なぜ？

**Comment by kz0817** [comment]
いっそのこと、HTML5のlocalStorageの方がパースも不要でそっちのほうがいいか。
でも、この問題の原因は解明したい。

**Comment by ashie** [comment]
昔 manage.py でも同様の問題が発生することがあったのを 37c44ec1 で修正しましたが、
何か考慮が足りていない?

**Comment by kz0817** [comment]
足永さんの初期の指摘のようにことなるパスで、２つブラウザが記憶しているみたい。
![cookie](https://cloud.githubusercontent.com/assets/2610513/12115096/8c1c8a62-b3f2-11e5-9d98-f589f63c11e9.png)

**Comment by kz0817** [comment]
set/get時にドメインとパスも明示すべきか？

**Comment by kz0817** [comment]
単純にはパスを"/"に固定して、set/getするだけでよいか？
実用上、異なるパスで２つのHatoholを運用することは、あまりない気がする。
でも、試験とかではあるかも。

**Comment by kz0817** [comment]
http://hdev3long/hatohol
と
http://hdev3long/hatohol/ajax_events
にアクセスした時にloginを行うと、それぞれ/と/hatoholで２つ、cookieが登録されるのが原因。

**Comment by kz0817** [comment]
#1888では、/hatoholへのアクセスを/hathol/ajax_dashboardにリダイレクトするようにして、常にpath=/hatoholとなるようにした。

**Comment by kz0817** [comment]
修正がマージされたのでクローズ。
