### ISSUE TITLE
[HAPI2] アイテムグループの全てを保存する。

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#1765]
#1721 からの派生案件。
現在は、暫定的に一つだけ、アイテムグループを保存しているが、これをすべて保存できるようにする。

**Comment by kz0817** [comment]
当初は、いまのアイテムグループ用のカラム（文字列）に複数のアイテムを記載すればよいとか思ったが、
- 幅256なので、所属グループが多いアイテムでは、新たな問題を生じる可能性がる。
- アイテム名をセパレートするための仕組みが必要で、SQLによる検索性や、データを人がみる場合の可読性が低下する

上記のような考察から、アイテムとそのグループを紐付ける別テーブルを用意するのが、結局よさそう。

**Comment by kz0817** [comment]
server_id, item_id, item_group_nameみたいな表をつくればいいのカナ。

item_group_nameは、たぶん、かなり重複があるだろうけど、それだけのテーブルをさらにつくって、joinするほうが煩雑になりそう。また、削除の判定も面倒。

**Comment by kz0817** [comment]
どうせやるなら、小手先でやるより、今後のことも考えて、DBTablesMonitoringのmajor versionを上げて、次のようにテーブル設計を変更する。
COLUMN_DEF_ITEMSに対して
 - unique ID column列を追加
 - item_group_name列を削除
COLUMN_DEF_ITEM_GROUP_NAMESテーブルを追加
 uniq_item_id, item_group_nameの２列

**Comment by kz0817** [comment]
COLUMN_DEF_ITEM_GROUP_NAMES
より、COLUMN_DEF_ITEM_CATEGORY_NAMESにしよう。

というのはItemGroupというのが、内部的に別の汎用コンテナの名前として使われているので、混乱をさけるため。

**Comment by kz0817** [comment]
> より、COLUMN_DEF_ITEM_CATEGORY_NAMESにしよう。
NAMESは不要か。

**Comment by cosmo0920** [comment]
NAMESを取り除くならCATEGORYを複数形にしてCATEGORIESですかねー。

**Comment by kz0817** [comment]
マージされたのでクローズ
