### ISSUE TITLE
[server] House keeping tool

### ISSUE THREAD

**Issue by ashie** [project-hatohol/hatohol#1777]
In  #1287 @bynnchapu tries to add a house keeping tool, but this work isn't completed yet.
We should complete it.

**Comment by cosmo0920** [comment]
This is just a comment. Please ignore following things:

I've created another hatohol house keeping tool. https://github.com/cosmo0920/ya-hatohol-house-keeper
This is just a concept and toy code.  :confounded:

**Comment by cosmo0920** [comment]
#1786 and #1806 are merged into master.
If you encounter any problem about house-keeper, please re-open this issue.
