### ISSUE TITLE
Items of Hatohol recieve

### ISSUE THREAD

**Issue by tieulong042** [project-hatohol/hatohol#179]
Anybody here tell me list of items which Hatohol recieve from Zabbix or Nagios?
P/S: I'm sorry, i just research avout Hatohol, I can't find out another forum to ask question. Thanks for read.

**Comment by sparthe123** [comment]
I'm facing the same issue, I installed in Ubuntu , client web login is not working

**Comment by ashie** [comment]
Which version are you using?

**Comment by kz0817** [comment]
> I'm facing the same issue, I installed in Ubuntu , client web login is not working.

Thank you for your comment.

Which procedure or document  did you follow in the installation ?
Any there any error messages in /var/log/syslog and manage.py's output ?

**Comment by sparthe123** [comment]
Hatohol version: 15.07_dev1, build date: Nov 23 2015 14:12:49

I followed the instruction from below link and did the same.
https://github.com/project-hatohol/hatohol

I'm getting logs in manage.py when I hit  login button
[25/Nov/2015 05:24:37] "POST /tunnel/login HTTP/1.1" 500 0


Login I tried
Username : admin
Password : hatohol

Is there any document I can refer to sync with Zabbix server

thanks in advance

**Comment by kz0817** [comment]
> [25/Nov/2015 05:31:36] "POST /tunnel/login HTTP/1.1" 500 0
> [Errno -2] Name or service not known

The above is everything ?
Is there stack trace at the error point ?

**Comment by sparthe123** [comment]
![image](https://cloud.githubusercontent.com/assets/15688616/11416069/409950e8-9430-11e5-9177-dc2dea087cd8.png)

attached image here ..

**Comment by ashie** [comment]
Hmm, it seems that it fails to resolve the host name of Hatohol server.
By default Hatohol client uses the host name "localhost" to search Hatohol server.
Can you resolve "localhost" on your machine?
Please try `dig localhost` or `nslookup localhost` to confirm it.

**Comment by sparthe123** [comment]
yes, that was the issue, now I fixed that and I can able to login and check my zabbix server details there.

thank you very much.
