### ISSUE TITLE
Travis CI build failing due to new build infrastructure?

### ISSUE THREAD

**Issue by cosmo0920** [project-hatohol/hatohol#1791]
see: https://blog.travis-ci.com/2015-11-27-moving-to-a-more-elastic-future

We should investigate how amount of this migration impact.

**Comment by cosmo0920** [comment]
In new build infrastructure, I/O is quite slower than previous legacy blue box build infrastructure.
So, server side tests are failed due to exceeds build time limits.

This build is an example for `exceeding build time` in new build infrastructure : https://travis-ci.org/project-hatohol/hatohol/jobs/94801128

**Comment by kz0817** [comment]
Thank for the information.

Do you know the new infrastructure generates a core dump by default when a process receives a signal and exits?

    Failure: testActionManager::test_execResidentActionCrashInInit
    <failureCode == actionLog.failureCode>
    expected: <13>
    actual: <14>

**Comment by cosmo0920** [comment]
> Do you know the new infrastructure generates a core dump by default when a process receives a signal and exits?

Sadly, I'm not familiar with GCE. I'm not sure why they do it.

**Comment by kz0817** [comment]
Do we have to divide the test for server to make the test time short in order to work around the time limit ?

And should time out value also increase ?

**Comment by cosmo0920** [comment]
> Do we have to divide the test for server to make the test time short in order to work around the time limit ?

Probably, yes.

> And should time out value also increase ?

These running time exceeds caused by long test running time. So, we shouldn't do that.

**Comment by kz0817** [comment]
Currently, test code expects ACTLOG_EXECFAIL_DUMPED_SIGNAL instead of ACTLOG_EXECFAIL_KILLED_SIGNAL if rlimit.rim_cur > 0.
So if "rlimit -c unlimited" is executed, the test has to succeed.

Is there anything to mechanism that returns CLD_DUMP as a returned value of wait() ?

**Comment by kz0817** [comment]
I ran the following command on the new TravisCI infrastructure and got the result.
Using apport with the pipe may be the cause.

    $ cat /proc/sys/kernel/core_pattern
    |/usr/share/apport/apport %p %s %c

**Comment by kz0817** [comment]
Fortunately, failure of testLogger::test_syslogoutput was reproduced on my local machine. I'll look into it.

**Comment by kz0817** [comment]
<pre>
    clang -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Dversion_info=(1,2,5,'final',1) -D__version__=1.2.5 -I/usr/include/mysql -I/usr/include/python2.7 -c _mysql.c -o build/temp.linux-x86_64-2.7/_mysql.o -DBIG_JOINS=1 -fno-strict-aliasing -g
    unable to execute clang: No such file or directory
    error: command 'clang' failed with exit status 1
</pre>

**Comment by ashie** [comment]
> Why is clang not found although the clang version is shown just before ? PATH ?

I confirmed that it can be replaced with `apt-get install python-mysqldb`.

https://travis-ci.org/ashie/hatohol/builds/95949082

**Comment by kz0817** [comment]
> I confirmed that it can be replaced with apt-get install python-mysqldb.

GR8.

**Comment by kz0817** [comment]
greeeeeeeen after so long !

https://travis-ci.org/project-hatohol/hatohol/builds/96214230

**Comment by Mnakagawa** [comment]
> greeeeeeeen after so long !

:clap::clap::clap::clap::clap::clap:

**Comment by kz0817** [comment]
One test 'StandardHapTestee.test_normal_run()' seems to still fail sometimes.
However, it would not be due to the new TravisCI infrastructure.
In other words, the test may potentially have some problem.
So I close this issue.

**Comment by cosmo0920** [comment]
:+1:
