### ISSUE TITLE
Hatoholサーバーが動作していな場合、WebUIでエラーがでない。

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#1795]
ログイン時に関しては、#1581で対応している。
ログイン後（Session ID)を持っている状態で、エラーが返されるとエラーメッセージの表示などがされないため、なにが起こっているかわかない。

これは、比較的最初で呼ばれる'/user/me'のアクセスを行うhatohol_user_profile.jsのconnectErrorCallbackが空であることも一因である。
HatoholConnectorのdefaultのconnectErrorCallbackはエラーダイアログを表示する。
/user/meだけ、特別扱いする理由が思いつかないので、HatoholConnectorの標準の
振る舞いに準拠すればよいと思う。

**Comment by kz0817** [comment]
ただし、HatoholConnectorの標準の振る舞いは、エラーメッセージを表示するより、
リトライを繰り返すほうがよいと思う。GMailなんかで、ネットワークが不通になったときの
ようなイメージ。

**Comment by kz0817** [comment]
現在の実装では、HatoholConnectorのdefaultのconnectErrorCallbackはエラーメッセージを表示するが、そこで実行は異常停止する。ユーザーは、リロードボタンを押さなければならない。

**Comment by kz0817** [comment]
HTTP通信失敗時、次のようなダイアログを出力し、一定時間（30秒)経過後に、リトライを行う。

![retrymodal](https://cloud.githubusercontent.com/assets/2610513/11803674/613b2334-a340-11e5-9700-d892ac5b64a4.png)

**Comment by kz0817** [comment]
「今すぐリトライ」みたいなボタンがあったほうがよいと思うが、一旦のそれなしでマージする。

**Comment by kz0817** [comment]
複数のリクエストが非同期に行われているときの仕様をどうするべきか？
単純には、複数のリクエストを同時に投げないという制限を設けるのもある。
しかし、events_view.jsではすでに左側のサマリのためのデータリクエストのあと、イベント取得がすぐに行われており、制限を課すと、この部分の変更が必要になる。そもそも、プログラムの素直さと効率を考えると、あまりよい制限ではない。

リクエストをQueingしておいて、疎通した時にそれらを実行させるか。

**Comment by cosmo0920** [comment]
https://github.com/project-hatohol/hatohol/pull/1843 がマージ済み。
