### ISSUE TITLE
イベントコンソールで、表のヘッダもスクロールする。

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#1798]
以前、直したような気がするが、最近また、イベントコンソールの表のヘッダが、各イベント行と共にスクロールしてしまう。

**Comment by kz0817** [comment]
@ashieさんか、@cosmo0920さんで、すぐにちょっと見ていただくことできませんか？

**Comment by ashie** [comment]
> 以前、直したような気がするが、最近また、イベントコンソールの表のヘッダが、各イベント行と共にスクロールしてしまう。

githubで管理しているコードについては、初め(表を個別にスクロールできるようにしたとき)からずっとヘッダも
一緒にスクロールするようになっています。
表のヘッダは固定されていたのは、内々のモック版です。実際に実装してみるとレイアウト調整が難しいという
ことがわかったため、現在のような形になっています。このことはデモを行った時にも説明しており、その時の
結論としては、そこに時間をかけるよりは他の個所の実装を優先するということになりました。

**Comment by kz0817** [comment]
回答ありがとうございます。了解しました。

**Comment by ashie** [comment]
やっぱり固定したいという要望があるようなのでreopen
jQueryプラグイン等も検討しているが、やはり苦戦している。

**Comment by ashie** [comment]
どの方法も一筋縄ではいかない。
やはり費用対効果が悪すぎるので後回し。

**Comment by ashie** [comment]
jQuery.floatThead (http://mkoryak.github.io/floatThead/) 等でそれぽくなると言えばなるのだが、
ウィンドウリサイズの拍子でたまにタイトルが見えなくなる。
CSSで実現する場合は、各セルを細かくサイズ指定しなければいけない。
どちらもいまいち決定打に欠ける。

**Comment by ashie** [comment]
以下のブランチに jQuery.floatThead 版を置いておく。

https://github.com/project-hatohol/hatohol/tree/experimental/events-view-fixed-thead

**Comment by ashie** [comment]
気持ちとしてはなるべくCSSだけでやりたい。

**Comment by kz0817** [comment]
間違ってクローズしました。Reopenします。
