### ISSUE TITLE
Custom incident labelsとイベントフィルターの設定

### ISSUE THREAD

**Issue by Mnakagawa** [project-hatohol/hatohol#1834]
Custom incident labelsにて，新しいラベルを作成しました。
イベントコンソールのフィルタをかける部分においては問題なく表示，
ラベルの設定が出来るのですが(Figure.1)，
[設定]を開き，[フィルター]タブにて [「対応」の選択をフィルターの条件に含める]を見た際，
作成したラベルが表示されていない。(Figure.2)コレは仕様？バグ？
 仮に現在は仕様だとしても，表示され設定できるようにしたほうが良いと感じる。

![a](https://cloud.githubusercontent.com/assets/7106792/11832173/f22d7e06-a3f8-11e5-8bf6-df2165ee1e37.png)
[Figure.1]

![b](https://cloud.githubusercontent.com/assets/7106792/11832174/f24bcdca-a3f8-11e5-9d97-79f95981a734.png)
[Figure.2]

**Comment by ashie** [comment]
> 作成したラベルが表示されていない。(Figure.2)コレは仕様？バグ？

実装漏れですね。
修正します。

**Comment by cosmo0920** [comment]
メモです。

WebUI側のコードを確認したところ、現在は

* userConfig
  * 中でHatoholEventsViewConfigを呼ぶ
* severityRank
* customIncidentStatus

の3つを同時にリクエストして、EventsViewをレンダリングしている。

コンソール設定でカスタムインシデントラベルを扱えるようにするには

* userConfig
* severityRank
* customIncidentStatus

を読み込んだ後、

* HatoholEventsViewConfigを生成するようにしないといけない。最低限userConfigとHatoholEventsViewConfigが密に結合していないように修正する必要がある。

**Comment by cosmo0920** [comment]
または、HatoholEventsViewConfigの中でインシデントの候補を作りなおすことが必要。

**Comment by ashie** [comment]
> を読み込んだ後、
> 
>     * HatoholEventsViewConfigを生成する

必ずしもそうしなくても良いと思います。

severityRankやcustomIncidentStatusを読み込む責任を誰に負わせるかというのは
再考の余地はありますが、今回の対応としては

> または、HatoholEventsViewConfigの中でインシデントの候補を作りなおすことが必要。

HatoholEventsViewConfigを先行して作っておいて、EventsViewがcustomIncidentStatusを
読み込んだら、改めてHatoholEventsViewConfigセットし直すでも良いと思います。
