### ISSUE TITLE
自己監視項目のホスト名はどうあるべき？

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#1836]
現在は、以下のように不明になっている。
どのようにすべきか？ 
 
<img width="289" alt="2015-12-16 15 47 20" src="https://cloud.githubusercontent.com/assets/2610513/11834086/6c4b259a-a40c-11e5-8e0a-5d0902cad496.png">

**Comment by kz0817** [comment]
また、以前のセルフトリガーのようにDBに自己監視用のホストを登録することで、ここに名前を表示させる。

**Comment by kz0817** [comment]
以前とあまり変わらないけど、こんな感じでいいかな。

![_2015-12-18_09-28-56](https://cloud.githubusercontent.com/assets/2610513/11886103/cdf7945a-a569-11e5-8acf-02d97997ce74.png)

**Comment by Mnakagawa** [comment]
ユーザー視点での気持ち悪さはありませんし（個人的に），
わかりやすくて良いと思います。
