### ISSUE TITLE
[WebUI] イベント画面『対応』列の動作・デザインついて

### ISSUE THREAD

**Issue by BlueSkyDetector** [project-hatohol/hatohol#1850]
[hatohol対応処理のUI.pdf](https://github.com/project-hatohol/hatohol/files/66536/hatohol.UI.pdf)
「対応」部分ですが、添付PDFのようなUIを考えてみました。
webメールライクなので、操作に戸惑うことはないと思いますが、
checkBoxで行を選択した際に、次のアクションが促されると良い思いました。

すなわち、一つでもcheckBoxを選択した際に、
初めて上部に「対応処理のプルダウン」が表れるという制御を入れたいと考えております。

→こちらの方法で修正を進めてもよろしいでしょうか？

[質問を本人に代わり投稿しています]

**Comment by BlueSkyDetector** [comment]
これは CSS と簡単な HTML の変更で済む変更になるでしょうか？
JS 側の変更も出てくる場合、どの部分のどのような変更になりそうかお教えください。

**Comment by ashie** [comment]
:+1: いい感じです！

可能なら、タイトル列のところにもチェックボックスを入れて全選択も
できればなおいいと思いました。

**Comment by tksmatsunaga** [comment]
デザインとしてはOKです。
ただし、このデザインの実装に付随する細かい作業分担については別途調整を行いましょう。

**Comment by ucksts** [comment]
ありがとうございます。
作業分担について調整、承知しました！

**Comment by BlueSkyDetector** [comment]
この件は、JS 側の変更もそれほど大きな変更ではないということだったので、JS 側も含めて変更してもらうということで合意しました。

**Comment by tksmatsunaga** [comment]
確認しました。
「対応」の部分を「対処」に変更しましたので、以下の該当箇所も「対処」に変更してください。

・「未対応の重要イベント」 ⇒ 「未対処の重要イベント」
　※左側のサマリ画面内です。
・「対応を変更」 ⇒ 「対処を変更」
　※「対処」のチェックボックスをONにすると表示されるプルダウンメニューです。

**Comment by ucksts** [comment]
ご確認ありがとうございます。
[hatohol_UI修正_121225.pdf](https://github.com/project-hatohol/hatohol/files/72042/hatohol_UI._121225.pdf)
上記PDFのような修正を加える予定（本日夜）です。

また、プルダウン上の文言「対応を変更：」は、不要と考えておりますが問題ないでしょうか。
（天地スペースを喰ってしまうこともあり。。）

**Comment by tksmatsunaga** [comment]
「対処」の上のスペースが1/2になるのであれば、確かに不要かと思います。
文言を削除するということでお願いします。

**Comment by cosmo0920** [comment]
#1900 でmasterに取り込まれたため、クローズします。
