### ISSUE TITLE
[WebUI] ヘッダーのオレンジ化について

### ISSUE THREAD

**Issue by BlueSkyDetector** [project-hatohol/hatohol#1851]
![hatohol](https://cloud.githubusercontent.com/assets/210614/11896594/3278b9ac-a5cb-11e5-900e-dd4eabb5fd93.png)
デザインサンプルを作ってみたところ（添付png）、
さほどメニューテキストの視認性が損なわれる感じではなさそうなので
予定通り、オレンジ版で進めたいと思います。

[質問を本人に代わり投稿しています]

**Comment by BlueSkyDetector** [comment]
とても良いと思います。
この版でお願いします。

**Comment by ashie** [comment]
:+1: いいですね！

**Comment by cosmo0920** [comment]
:+1: ナイスです！

**Comment by tksmatsunaga** [comment]
オレンジ化でOKです。

**Comment by ucksts** [comment]
懸念のあった、テキストの視認性も担保されておりますので
オレンジ化を実装しました。
http://hatohol-github.cloudapp.net/ajax_events

*gitへの格納は少々お待ちください。
*代理投稿ありがとうございました。

**Comment by cosmo0920** [comment]
#1900 マージのため、クローズ。
