### ISSUE TITLE
[WebUI] イベント画面フィルタ機能のデザイン改善（js部分）

### ISSUE THREAD

**Issue by BlueSkyDetector** [project-hatohol/hatohol#1863]
![event_filter0](https://cloud.githubusercontent.com/assets/210614/11952026/dbecfbfa-a8d8-11e5-8458-6899708ec4c0.png)
・上記添付画像のように、「絞り込みを解除」（白ボタン）を追加する
![event_filter1](https://cloud.githubusercontent.com/assets/210614/11952030/e76ca494-a8d8-11e5-9962-b997b4f8bfb5.png)
・上記添付画像のように、絞り込み適用後に「すべてのイベント(23,980)」を「絞り込み結果(982)」になるよう表示を動的に変更する
・上記添付画像のように、絞り込み適用時の絞り込み条件を小さく表示。

**Comment by cosmo0920** [comment]
#1900 にてmasterへマージ。
