### ISSUE TITLE
[WebUI] タイトル周辺のスペース抑制について

### ISSUE THREAD

**Issue by ucksts** [project-hatohol/hatohol#1868]
[hatohol_title余白調整.pdf](https://github.com/project-hatohol/hatohol/files/71597/hatohol_title.pdf)
添付PDFのようなことを検討中です。
「イベント」タイトル部分の天地スペースがやや過剰に広いため、
低解像度PCでは画面あたりの表示件数が抑制されがちになります。

そこでタイトル周りのレイアウトを調整し、天地を省スペース化したいのですがいかがでしょうか？

**Comment by BlueSkyDetector** [comment]
わかりやすくて良いと思います :+1:

**Comment by tksmatsunaga** [comment]
かなりすっきりした印象ですし、わかりやすいです。
これでお願いします。

**Comment by ucksts** [comment]
はい、ありがとうございます。こちら進めてまいります。
おそらく共通ファイル?だと思いますので、他画面も連動して
修正がかかると思われます。適用後にまたお知らせいたします。

**Comment by ucksts** [comment]
http://hatohol-github.cloudapp.net/ajax_events
全画面共通で、デザイン修正完了しております。

**Comment by tksmatsunaga** [comment]
確認しました。ありがとうございました。

**Comment by cosmo0920** [comment]
HatoholのGitHubリポジトリに反映するまではオープンしておいて頂きたいです。

**Comment by cosmo0920** [comment]
もしくはGitHubリポジトリに反映するという別Issueを立ててください！

**Comment by tksmatsunaga** [comment]
不慣れですいませんでした。
リオープンしました。

**Comment by cosmo0920** [comment]
#1900 がマージされたため、クローズします。
