### ISSUE TITLE
Plugin (Zabbix)でパスワード間違い時のエラーメッセージが理解しがたい

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#1870]
現在、例外が発生して以下のようなメッセージが表示されるが、
ユーザーがこれでパスワード間違い（Zabbixへのログイン失敗）であることに気づくのは不可能に近い。

Plugin Error: <type 'exceptions.TypeError'>, 'NoneType' object is not iterable

**Comment by cosmo0920** [comment]
#1894 とブラッシュアップの #1902 がマージされたため、クローズ。
