### ISSUE TITLE
監視サーバ追加ダイアログのチェックボタンの位置が不正

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#1874]
結構以前から、そうであったようにも思うが、master: 72da4ab231581 でも
添付の画像のようにチェックボタンが説明の文字列と重なっている。

![button](https://cloud.githubusercontent.com/assets/2610513/12083600/8da825ee-b2e9-11e5-8915-5617bc7d6234.png)

**Comment by Mnakagawa** [comment]
私の環境では（Linux, Macのそれぞれgoogle chrome）、チェックボックスの位置は画像のように
特に問題はありません。ｋｚさんの使用OS,　ブラウザを記載しておいたほうが良いと思います。

![2016-01-04 15 52 01](https://cloud.githubusercontent.com/assets/7106792/12084846/0392dada-b2fc-11e5-8b35-659f1e015daf.png)

**Comment by cosmo0920** [comment]
Firefoxではどうなりますか？

**Comment by Mnakagawa** [comment]
すみません…私の勘違いでHEADの位置が違う状態で試していました。
現行のmasterのHEADで試したところ、firefox,chromeともにチェックボックスの位置がずれていました。

**Comment by ashie** [comment]
bisectっぽく調べてみたところ、 #1845 で各JavaScriptライブラリを最新にアップデートして以降に壊れているようだ。

**Comment by ashie** [comment]
Bootstrapの`.checkbox input[type="checkbox"]`のスタイルが変わっているようだ。
変更点を抽出すると

before:
```
float: left;
```

after:
```
position: absolute;
```

Firefoxのインスペクタで後者を無効化して前者を適用すると、以前と同じように表示された。
