### ISSUE TITLE
プラグインで名前衝突

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#1877]
hap2の標準プライグインには、以下のような構文がある。
これは、importさるhapとグローバル空間のhapが衝突して、インポートしたhapが使えない。
```python
from hatohol import hap 
...
if __name__ == '__main__':
    hap = Hap2ZabbixAPI() 
    hap()
```

**Comment by kz0817** [comment]
Hap2ZabbixAPI()()
だとちょっと変か？

こんな感じの修正が無難か。
<pre>
def main():
     hap = Hap2ZabbixAPI() 
     hap()

if __name__ == '__main__':
    main()
</pre>

**Comment by kz0817** [comment]
haplibの中でrun()を定義して、以下のようにしたほうが、各プラグインの記述が簡潔になる。
<pre>
 if __name__ == '__main__':
-    hap = Hap2ZabbixAPI()
-    hap()
+    Hap2ZabbixAPI().run();

[haplib.py]
+    def run(self):
+        self()
+
</pre>

**Comment by kz0817** [comment]
#1882で修正をPR

**Comment by ashie** [comment]
マージしたのでクローズ
