### ISSUE TITLE
トリガー画面で(self-monitor)を選んでも何も表示されない

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#1879]
<img width="1207" alt="self-trigger-none" src="https://cloud.githubusercontent.com/assets/2610513/12103416/8477cd16-b385-11e5-8a0a-e1f0f104a225.png">

**Comment by ashie** [comment]
手元の環境では再現しない。
@cost0920 さんの環境でも再現しない。

**Comment by ashie** [comment]
再現しないのでアサインを @kz0817 さんに戻します。

**Comment by ashie** [comment]
手元の環境での結果(現在のmasterで一からセットアップ):

![trigger](https://cloud.githubusercontent.com/assets/135104/12135791/8c0a4da2-b483-11e5-9578-a02d8ce33ff3.png)

**Comment by ashie** [comment]
この検証をしていて別のことが気になった。

監視サーバ、グループ、ホストの「--------」を選択しても、エントリに表示される文字列が空になっている。
実害は無いようだが、イベント画面の挙動と異なるし、以前はそんなことはなかった気がする。

**Comment by ashie** [comment]
> 監視サーバ、グループ、ホストの「--------」を選択しても、エントリに表示される文字列が空になっている。
> 実害は無いようだが、イベント画面の挙動と異なるし、以前はそんなことはなかった気がする。

どうも各種JavaScriptライブラリのアップデートで挙動が変わったようだ。これは別途対応する。

**Comment by kz0817** [comment]
んー、masterのHEAD(2bae6f46)で確認すると、再現しない。
これ以上、調査できないので、クローズする。
