### ISSUE TITLE
[16.01] Release note編集願い

### ISSUE THREAD

**Issue by Mnakagawa** [project-hatohol/hatohol#1907]
本格的に16.01のリリース作業に移ります。
そこで開発者各位にお願いです。表題の通り，Release noteの編集をおねがいします。

編集方法は従来同様，「16.01_releng/relnote」ブランチから
「16.01_releng/relnote/XXX」ブランチ（XXXは編集者名）にチェックアウトし編集後，pushするだけです。
以降のmergeなどの作業は私の方で行います。

主要開発者は主に以下のメンバーかと思います。
@kz0817 
@ashie 
@cosmo0920 
@BlueSkyDetector 
@Mnakagawa

よろしくお願いします。

**Comment by kz0817** [comment]
作業お疲れ様です。
16.01_releng/relnoteは、まだないようですが、これから作成しますか？

**Comment by Mnakagawa** [comment]
ご指摘ありがとうございます。作成しました。

**Comment by Mnakagawa** [comment]
16.01_releng/relnote/XXXとするとエラーが発生するので，16.01_releng/relnote-XXXといった形で大丈夫です。

**Comment by Mnakagawa** [comment]
期限を記載するのを忘れていました。期限は1/18(月)です。
