### ISSUE TITLE
[16.01][RPM] メニューバーの画像がない

### ISSUE THREAD

**Issue by Mnakagawa** [project-hatohol/hatohol#1909]
![a](https://cloud.githubusercontent.com/assets/7106792/12252888/9396e482-b91e-11e5-87f8-8a34b6768a0d.png)

画像のように，メニューバーの一番左上のHatoholロゴの画像が無い。
specファイルに書き忘れているか，mergeミスかのどちらかだと思う。

**Comment by cosmo0920** [comment]
リポジトリには存在する https://github.com/project-hatohol/hatohol/blob/master/client/static/images/logo_hatohol.png のでspecのミスかと思われます。

**Comment by ashie** [comment]
開発用Webサーバでは表示されるけどapacheでは表示されないので
staticファイルのパスが通ってないとかもあるかも。

**Comment by Mnakagawa** [comment]
specはclient以下全てを持ってきているので，私もパスが通っていないのではないかと思います

**Comment by cosmo0920** [comment]
確かにspecではそう記述されていますね。早とちりでした。

**Comment by ashie** [comment]
> 開発用Webサーバでは表示されるけどapacheでは表示されないので
> staticファイルのパスが通ってないとかもあるかも。

それ以前にclient/Makefile.amに記述されていないので、インストールされていないと思われる。
（なのでパッケージにも入らない）

**Comment by Mnakagawa** [comment]
ビンゴですね。ありがとうございます。

**Comment by ashie** [comment]
それだけではなく、CSSの中で絶対パス指定されていた。
パスにプレフィックスがつく場合(apacheの場合のデフォルト設定では「hatohol」がつく)に対応できない。

**Comment by ashie** [comment]
#1911 で修正した。
masterにマージされたら閉じる。
