### ISSUE TITLE
[Server types] 監視サーバー登録画面におけるサーバ一覧の順番が不揃い

### ISSUE THREAD

**Issue by Mnakagawa** [project-hatohol/hatohol#1915]
![screenshot from 2016-01-12 13 51 36](https://cloud.githubusercontent.com/assets/7106792/12255144/e8458ab4-b933-11e5-928d-eba5a4e3d81e.png)

２つのNagiosのHAP２プラグインにZabbixプラグインが挟まれているところが気になる。
server_typesテーブルのにあるデータの順番に表示されているので，
db-initiatorあたりを編集すれば良い？

**Comment by ashie** [comment]
今のHatoholサーバの実装では順番をケアしてなくて、実際にはUUIDの順番で並んでいるように見える。
（UUIDでインデックス作ってるから?）

**Comment by Mnakagawa** [comment]
あ〜…なるほど。
#1415 の修正に合わせて，このIssueも修正したほうがいいかもしれないですね。
明確なバグではないため，優先度低いですし，16.04にします。

**Comment by Mnakagawa** [comment]
Hatoholサーバーからブラウザへのデータ送信の前に名前でソートするしかなさそう

**Comment by cosmo0920** [comment]
名前のソートだと

Z -> Aの順の

* Zabbix (HAP2)
* Nagios NDOUtils (HAP2)
* Nagios Livestatus (HAP2)
* Fluentd (HAP2)
* Ceilometer (HAP2)

か　A -> Z順の

* Ceilometer (HAP2)
* Fluentd (HAP2)
* Nagios Livestatus (HAP2)
* Nagios NDOUtils (HAP2)
* Zabbix (HAP2)

の順にソートするのが考えられます。どっちがいいんでしょうねぇ。

**Comment by Mnakagawa** [comment]
今まで***っぽい***のは降順ですけど、
実際にソートするとなるとやはり昇順だと思うんですよね。

あとは文字列の長さ順とかも意外とアリ？

**Comment by cosmo0920** [comment]
もしくは優先度(Priority)をjs.pluginsに追加してそれでソートするなんてどうでしょう？

* Zabbix (HAP2) priority: 100
* Nagios NDOUtils (HAP2) priority: 90
* Fluentd (HAP2) priority: 85
* Ceilometer (HAP2) priority: 75
* Nagios Livestatus (HAP2) priority: 60

としておけば、並び順を制御できるかと。あとHAP2ユーザーが作ったプラグインの並び順を適当に決められるという効果も付いてきます。

**Comment by Mnakagawa** [comment]
とてもよさそう。
グッドアイデア

**Comment by kz0817** [comment]
> もしくは優先度(Priority)をjs.pluginsに追加してそれでソートするなんてどうでしょう？

WebUIの課題なので、Hatohol serverを巻き込まない点に好感がもてます。
