### ISSUE TITLE
[EventView][Filter] 対処状況が空白となっているもののフィルタを追加する

### ISSUE THREAD

**Issue by Mnakagawa** [project-hatohol/hatohol#1916]
![a](https://cloud.githubusercontent.com/assets/7106792/12255281/5154e47c-b935-11e5-941a-af54c3c3beec.png)

画像の通り，対処カラムが空白（何も設定していない）イベントのフィルタもできると良いのではないかと思った。

**Comment by BlueSkyDetector** [comment]
新規に発生したイベントには、初期値として何かしらの値が設定されていて、それでフィルタできるのが自然な気がしました。
最終的な判断は tksmatsunaga に意見聞くと良いと思います。

**Comment by tksmatsunaga** [comment]
イベントの中には基本的に何もしない（無視する）系のイベント（Informationなど）を含むことが想定されます。
そのようなイベントにも初期値を入れてしまうと、全体として見難くなってしまうかなとも思います。
ですので、初期値はあえて設けず、「対処カラムが空白」のイベントのフィルタを作るということで良いかと思います。

**Comment by Mnakagawa** [comment]
リアルで話し合い必須

**Comment by Mnakagawa** [comment]
対処カラムの初期値が「未対処」になった。
空白のものはインシデント管理サーバーがRedmineのもののみ。
それをフィルターする意味はないと思うし，このIssueはクローズでいいと思う。
