### ISSUE TITLE
[Pagination] 最新データ，トリガー画面でのイベント表示件数変更が不安定

### ISSUE THREAD

**Issue by Mnakagawa** [project-hatohol/hatohol#1917]
「ページ毎のxxx数」(最新データ or トリガー)を変更し，
Enterを押すとページのリロードは行われるが，
件数がデフォルトの50件のままであることが多い。

以前に@ashie さんによって修正が入った記憶があるのだが，
デザイン関連のmergeを行った段階で再度発生したのだろうか。
16.01に修正を入れるかどうかも話したほうが良いと思う。

**Comment by Mnakagawa** [comment]
なお，発生時の私の環境はChrome on Ubuntu

**Comment by ashie** [comment]
Firefoxでも同様。ページ自体をリロードしないと設定が反映されない。

**Comment by ashie** [comment]
これもJavaScriptライブラリの更新で挙動が変わったのだろうか?
ユーザー設定の読み込み完了を待たずにトリガーの読み込みを開始しているケースがある。

**Comment by ashie** [comment]
なんと、Deferredでpromise()していない。

https://github.com/project-hatohol/hatohol/blob/16.01_releng/master/client/static/js/triggers_view.js#L52

```
約束を破らないもっとも確実な方法は、約束をしないことだ - あるフリーソフトウェア開発者
```

**Comment by ashie** [comment]
それ以外にもいくつか問題がある。

* 存在しない要素("#num-triggers-per-page")に値をセットしようとしている: https://github.com/project-hatohol/hatohol/blob/16.01_releng/master/client/static/js/triggers_view.js#L147
* セットした値が反映されない(前回ロード時の値で上書きされる): https://github.com/project-hatohol/hatohol/blob/16.01_releng/master/client/static/js/triggers_view.js#L283

**Comment by ashie** [comment]
> セットした値が反映されない(前回ロード時の値で上書きされる)

こっちは半分勘違い。
問題の箇所は以下だった(値を更新するまえにロードしてる)

https://github.com/project-hatohol/hatohol/blob/16.01_releng/master/client/static/js/triggers_view.js#L114

**Comment by ashie** [comment]
#1929 で修正した。
masterへのマージ後にクローズする。
