### ISSUE TITLE
[16.01][Graph] アイテム追加時，文字やボタンが枠からはみ出す

### ISSUE THREAD

**Issue by Mnakagawa** [project-hatohol/hatohol#1918]
![a](https://cloud.githubusercontent.com/assets/7106792/12256080/df2018dc-b93d-11e5-9808-44d3e992ed64.png)

以前からある問題だが，16.04に合わせて修正したほうが良いと感じたため，
Issueとしてあげる。
EventViewのように，アイテムの文字列を省略する形で表示すれば発生しないはず。
プルダウンボックスの長さが可変であることも原因のひとつか。

**Comment by cosmo0920** [comment]
#1921で修正。masterにマージされたら閉じる。

**Comment by ashie** [comment]
今日まで気がついていなかったが、これは、追加したアイテムが変なところに挿入されるという
問題であった。jQueryを更新したときに動作が変わってしまったようだ。

**Comment by ashie** [comment]
つまりまだ直っていない。
