### ISSUE TITLE
[16.01] 変更した表示言語を維持できない

### ISSUE THREAD

**Issue by Mnakagawa** [project-hatohol/hatohol#1919]
例えばブラウザのデフォルトが日本語であれば，
「http://xxx.xxx.xxx.xxx/hatohol/ajax_dashboard」にアクセスした時に日本語で表示される。
このURLを「http://xxx.xxx.xxx.xxx/hatohol/en/ajax_dashboard」とすると表示言語を英語に変更できるが，
ページ遷移の際，URLの/en/が取り除かれ再び日本語に戻ってしまう。
ブラウザのデフォルトが英語であるなら/ja/を挟むことで日本語に変更できるが，
同様にページ遷移した時に英語に戻ってしまう。

15.06などでは，ページ遷移しても変更した言語を維持していた記憶があるのでIssueをあげた。

**Comment by Mnakagawa** [comment]
URLに関しての変更といえば直近だと @kz0817 さんの #1890 かと思ったが
ぱっとみ関連性があるのかわからない。

**Comment by ashie** [comment]
#1607 ですね。
相対パスで問題ないので #1607 のhatohol_navi.jsに対する修正が不要だったように思う。

**Comment by Mnakagawa** [comment]
メニューバーの「ヘルプ」にある「オンラインドキュメント」「バージョン」の２項目もクリックするとURL以前と違う。
オンラインドキュメントはhttp://IP ADDR/hatohol/http://www.hatohol.org/docs
バージョンはhttp://IP ADDR/hatohol/ajax_dashboard#version

とそれぞれなる

**Comment by kz0817** [comment]
> #1607 ですね。

本件の修正、@ashieさんか@cosmo0920さんにお願いしてもいいですか？

**Comment by Mnakagawa** [comment]
masterにmerge後，close

**Comment by cosmo0920** [comment]
#1920 で修正。

**Comment by cosmo0920** [comment]
#1920 で修正済み。
