### ISSUE TITLE
[HAP2] 監視サーバー登録画面のテキストボックス内のプレースホルダーテキスト表示の仕方

### ISSUE THREAD

**Issue by Mnakagawa** [project-hatohol/hatohol#1925]
HAP2の登録時，例えばブローカーURLのテキストボックスには「amqp://user:password@localhost[:port]/vhost」
といった表記が存在するが，何らかのテキストを入力した時点で消えてしまう。
ユーザー視点では，このヒントを再度確認するためにヒントを事前にメモしておくか，
入力した文字を消さなければならない。
手間もかかるし，ユーザーライクではないと感じるので，ヒントは吹き出しで表示すると良いのではないかと思った。
グラフ機能にはそのような機能が実装されているので，Bootstrapに変更すれば実現可能か。

**Comment by cosmo0920** [comment]
Bootstrapのモーダルダイアログにすればpopoverが使用可能なので使うことができます。
ただし、Hatoholに現状存在するBootstrapのモーダルダイアログを表示させるスクリプトはCSRFトークンを扱えないのでまずこちらから着手する必要があります。

**Comment by Mnakagawa** [comment]
コメントありがとうございます。
16.01に入れる時間はないと思うので，04に盛り込めたらなぁと考えています。

**Comment by Mnakagawa** [comment]
デフォルトでテンプレート文字列を入力されているようにする
