### ISSUE TITLE
[HAP2] グラフ機能利用時，hap2が落ちる

### ISSUE THREAD

**Issue by Mnakagawa** [project-hatohol/hatohol#1926]
hap2_zabbix_apiを利用時，グラフ機能を用いると

```
OverCapacity: 'The message size over the max capacity of pika module.'
```

のメッセージと共にプラグインが落ちる。
メッセージが大きすぎるとpikaモジュールが正常に動作しなくなるため,
メッセージサイズが一定値を超えるとユーザー定義のOverCapacity exceptionが発生させている。
意図した動作ではあるのだが，putEvents procedureではイベント群をいくつかに分けて
送信することにより，これを回避している。

https://github.com/project-hatohol/hatohol/issues/1466
では16.04での修正とあるが，引き続き16.04でよいでしょうか。

**Comment by cosmo0920** [comment]
Overcapacityではない場合でも落ちます。

**Comment by Mnakagawa** [comment]
なるほど。
それ自体はアイテムの過去データがないから落ちているだけなので，運用上あまり問題ではないと思います
（もちろんログとしてでるから対処はしたほうが良い）

**Comment by Mnakagawa** [comment]
その問題は，アイテムに限らず恐らく全てのputXXXにおいて，データがない場合に再現するものでしょうね。
仕組み自体を変えたほうが良さそう。

**Comment by cosmo0920** [comment]
↑の場合にどんなdistionaryが生成されているかを以下のパッチを当てて見てみました。

```diff
diff --git a/server/hap2/hatohol/zabbixapi.py b/server/hap2/hatohol/zabbixapi.py
old mode 100644
new mode 100755
index d937eee..7aac29b
--- a/server/hap2/hatohol/zabbixapi.py
+++ b/server/hap2/hatohol/zabbixapi.py
@@ -148,6 +148,10 @@ class ZabbixAPI:
         if not self.result:
             return
 
+        if not len(res_dict["result"]) > 0:
+            logger.error("Malformed response dictionary: %s" % res_dict)
+            return
+
         return res_dict["result"][0]["value_type"]
 
     # The following method gets not only hosts info but also host group membership.
```

```log
[DBG] <HatoholArmPluginInterfaceHAPI2.cc:221> message: <application/json>/<{"jsonrpc": "2.0", "result": "SUCCESS", "id": 2868958782}>
ERROR:17282:Malformed response dictionary: {u'jsonrpc': u'2.0', u'result': [], u'id': 1}
[DBG] <HatoholArmPluginInterfaceHAPI2.cc:221> message: <application/json>/<{"params": {"fetchId": "1816074841", "itemId": "23764", "samples": []}, "jsonrpc": "2.0", "method": "putHistory", "id": 281527623}>
```

確かにデータが空の場合に再現することがあるようです。

**Comment by cosmo0920** [comment]
> 仕組み自体を変えたほうが良さそう。

仕組みを変えるかエラー処理を厳格にするべきだと思います。

**Comment by cosmo0920** [comment]
変なレスポンスを返そうとしている場合はログに記録してreturnするようにしました。今後の方針と噛み合わない場合はその旨を書いて #1928 はクローズでも良いです。

**Comment by Mnakagawa** [comment]
16.04にて本格的な修正を入れます。Openのままで。

**Comment by Mnakagawa** [comment]
https://github.com/project-hatohol/hatohol/tree/issue1926-2

このブランチ上では落ちることはなくなり，全てのデータにおいて分割して送るようになった。
その弊害として，グラフの挙動が怪しくなっている。
例えば500件のヒストリーをhap2から送る場合，100件ずつ5分割して送るのだがWebUI上では100件しか描画されない。
intervalSec(60sec)が経過すると，次の100件が描画される。（合計200件分）

組み込みZabbixでデータ取得した場合は，1000件分割されるが一度に表示されるので，これに合わせたい。

**Comment by cosmo0920** [comment]
よくわかってないですが、mayMoreFlagがtrueの時はintervalSec分待たずに送るとか言うことって難しいんですかねぇ。

**Comment by Mnakagawa** [comment]
(putEvent以外にはmayMoreFlagないんですよねぇ…なんでないんだろ…
HAPI2.0決めたのは自分たちですけど記憶がない)

**Comment by cosmo0920** [comment]
（これは仕様から直すしか…！）

**Comment by Mnakagawa** [comment]
そうなんですよね。だから
https://github.com/project-hatohol/HAPI-2.0-Specification/issues/78
と上げてるように，色々見なおした2.1を作りたいんですよね。

**Comment by Mnakagawa** [comment]
これ考えるほど難しいｗ
server sideより，client sideをいじるほうが良いのか…？

**Comment by kz0817** [comment]
ただ、グラフに関しては闇雲に大量のデータを送っても、数カ月とか１年表示の壁を突破できないので、送信方法そのものを別途開発する必要がありますね。

**Comment by Mnakagawa** [comment]
サーバーをいじる場合：
hap2から複数回にわたって送られてきたhistoryをストックして，全て送られてきたと理解したらclientに送る。
しかしhap2から送られてきているhistory群がどの時点で全てなのか知る手段が無いから現実的じゃない。
現状のHAPI2.0の仕様では難しいという話

クライアントをいじる場合：
同様に，何を持ってしてHatoholサーバーから送られてくるhistory群が打ち止めかということを知る手段がない。
どのタイミングで読み込みを辞めるか，それともhistoryが指定したendTimeに到達していない場合は
busyループでHatoholサーバーからのデータを待って描画し続けるとか…？実装が汚い

**Comment by ashie** [comment]
> ただ、グラフに関しては闇雲に大量のデータを送っても、数カ月とか１年表示の壁を突破できないので、送信方法そのものを別途開発する必要がありますね。

ちなみに、Zabbixでは長期間のHistoryはTrendという形で間引きされるが、これをZabbix APIで
とる方法がなかったのでHatohol側で長期間のグラフを描画するのは難しかった。
が、Zabbix 3.0ではZabbix APIにTrendのgetが実装されたようだ:

https://www.zabbix.com/documentation/3.0/manual/api/reference/trend/get

Zabbix 3.0は昨日リリースが出ていたようだ:

http://www.zabbix.com/jp/pr145.php

**Comment by Mnakagawa** [comment]
別Issueを建てたのでこっちはクローズ
