### ISSUE TITLE
[16.01][EventView] 文言の統一

### ISSUE THREAD

**Issue by Mnakagawa** [project-hatohol/hatohol#1927]
![a](https://cloud.githubusercontent.com/assets/7106792/12285740/a0260d08-ba00-11e5-9ba1-263bff4a992c.png)
フィルタ設定画面

![b](https://cloud.githubusercontent.com/assets/7106792/12285741/a15108ae-ba00-11e5-9a07-444ef4aa95f8.png)
イベントコンソール

フィルタの設定画面では「対応」，イベントコンソール画面では「対処」となっている。

**Comment by ashie** [comment]
エラーメッセージにも前の用語が残っている。
ついでに関数名等も全部直す。

**Comment by Mnakagawa** [comment]
#1932 で修正。masterにmerge後close
