### ISSUE TITLE
[HAP2][server] Should rabbitmq required libraries in 16.01 release?

### ISSUE THREAD

**Issue by cosmo0920** [project-hatohol/hatohol#1933]
Currently, `rabbitmq` is marked as optional dependency. 
Thus, a environment rack of rabbitmq libraries and its server does not support HAP2.
Should we change it to mark required?

**Comment by Mnakagawa** [comment]
`rabbitmq` is `rabbitmq-server` ?

**Comment by cosmo0920** [comment]
No, `librabbitmq-dev` or `librabbitmq-devel`.

**Comment by Mnakagawa** [comment]
Hmm.
How do you think it @kz0817 ?

**Comment by kz0817** [comment]
In general, *-dev/-devel is unnecessary for run-time environment.

**Comment by cosmo0920** [comment]
This issue means that "Should we always treat librabbitmq as required when building hatohol server?".
Because current Hatohol server does not build HAPI2 when librabitmq-dev is absent.

**Comment by cosmo0920** [comment]
Issue #2219 で扱うこととし、こちらはクローズ。

**Comment by ashie** [comment]
おっと、すでにあったのか。
普通、新しい方をクローズするような

**Comment by cosmo0920** [comment]
話が変な方向に進んでいたので説明が簡潔な方を残した方が良いかな、と言うことでこちらをクローズしました。

**Comment by cosmo0920** [comment]
あと、このIssueは16.01の状況が対象なので新しく立てた方を残した方が良いと思いました。

**Comment by ashie** [comment]
了解です。
