### ISSUE TITLE
Provide rabbitmq setting up documents

### ISSUE THREAD

**Issue by cosmo0920** [project-hatohol/hatohol#1935]
Currently, it is undocumented!

**Comment by cosmo0920** [comment]
CentOS7に限らずこんな感じ https://github.com/project-hatohol/hatohol/blob/b1f688b71e70d9dc79e31a01989bb465552dc3b5/doc/server/hap2/HowToUse.md のドキュメントを用意してやれば良さそう。

**Comment by cosmo0920** [comment]
#1938 で取り扱う。HAP2を動かすのに関するドキュメントを追加する。

**Comment by Mnakagawa** [comment]
releng/masterにはmerge済み。masterにマージ次第，close.
