### ISSUE TITLE
[client] ビルド時にDjangoを要求される

### ISSUE THREAD

**Issue by ashie** [project-hatohol/hatohol#1939]
サーバとクライアントを別のホストで動かす構成も考えられなくは無いが、現状ではビルド時に
必ずDjangoを要求される。
やっていることは mo ファイルのコンパイルだけであり、中でやっているのは msgfmt を呼び出
すだけなので、本来は Django がなくてもビルドできる。

上記のためだけに server/README.md に Django のインストール手順を記述するのは煩雑
なので、Djangoがなくてもビルドできるようにする。

**Comment by cosmo0920** [comment]
#1940 で修正。masterにマージされたら閉じる。
