### ISSUE TITLE
16.01 beta：　過去のイベントを全て取得してしまう

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#1947]
built-inのZabbixでは、登録時、過去のイベントを取得しないが、HAP2版だと取得しているように見える。両者で振る舞いが異なるは不自然だし、当時、議論して、取得しないという動作を標準にしているので、HAP2版もそうなるべき。

**Comment by Mnakagawa** [comment]
Zabbixに限らず，他のプラグインでも同様の同様の動作を想定したほうが良いですよね。
その認識で良いなら，haplib.pyの以下の関数を編集するだけで実装できそうです。

```
    def get_cached_event_last_info(self):
        if self.__event_last_info is None:
            self.__event_last_info = self.get_last_info("event")
        return self.__event_last_info
```
get_last_info("event")で取得した後もなおself.__event_last_infoがFalseであるならば，
現在時刻をreturnすれば仕様は満たせるかと。
いかがでしょう

**Comment by kz0817** [comment]
そうですね。

ただ、Noneとかでなく、Falseが帰るんでしたっけ？

**Comment by Mnakagawa** [comment]
記載不足でした…上記、正しくは
(ifで評価して)Falseなら、です。
ちなみに帰ってくるのは空文字です。

**Comment by kz0817** [comment]
帰る -> 返る
二人とも間違ってた。

**Comment by Mnakagawa** [comment]
Fix済み。masterにmergeされてからクローズする。
