### ISSUE TITLE
How to use Livestatusを書く

### ISSUE THREAD

**Issue by Mnakagawa** [project-hatohol/hatohol#1948]
掲題通り。
Nagiosモジュールのインストール方法から，設定までを書く。

https://github.com/project-hatohol/hatohol/blob/master/doc/misc/nagios-setup-cent6.md

にNDOUtilsのセットアップ方法はあるので，同ディレクトリに作りたい。

**Comment by cosmo0920** [comment]
これ、@Mnakagawa さんにアサインしておきます。

**Comment by Mnakagawa** [comment]
優先度はそこまで高くない（本格的な使用は16.04を視野に入れているため）ので，
16.01のリリース作業に余裕ができれば16.01に入れようと思います。

**Comment by Mnakagawa** [comment]
作成済み。masterにマージされたらクローズする。
