### ISSUE TITLE
[16.01] DBのアップグレード方法

### ISSUE THREAD

**Issue by Mnakagawa** [project-hatohol/hatohol#1951]
掲題について質問です。
15.06から16.01へのアップグレードを行おうと思ったのですが，
最新のアップデート方法が14.09 to 14.12でとかなり古かったので，
やり方も変わっているかと思い質問しました。

まず現在のmasterでは15.06からのアップデートはそもそも対応しているのでしょうか。

**Comment by Mnakagawa** [comment]
```
# hatohol-db-initiator -f
```

を実行すると
```
DB already exists: hatohol
[INFO] <DBTables.cc:203> DBTables 16 is outdated, try to update it ...
	old-version: 00.16 [00]
	new-version: 00.18 [00]
Failed to create DBHatohol object
```

上記の出力が得られる。

**Comment by Mnakagawa** [comment]
try to updateとはいうが，そもそもどうアップデートするのかわからない。

**Comment by ashie** [comment]
> try to updateとはいうが，そもそもどうアップデートするのかわからない。

MLPL_LOGGER_LEVEL=DBG でもう少し詳しい情報得られないでしょうか?

**Comment by ashie** [comment]
> やり方も変わっているかと思い質問しました。

変わっていないです。

> まず現在のmasterでは15.06からのアップデートはそもそも対応しているのでしょうか。

アップデートできるようにコードは書いていますが、十分な検証はできていないというのが
正直なところです。

**Comment by kz0817** [comment]
> try to updateとはいうが，そもそもどうアップデートするのかわからない。

このメッセージのtry to updateは、(This program is going to) try to update it ...という意味なので、手動で人が何かをしてくださいということではないです。

失敗の原因については、@ashieさんが助言しているようにログをもう少し詳しくみたいですね。

**Comment by Mnakagawa** [comment]
```
[root@localhost ~]# MLPL_LOGGER_LEVEL=DBG hatohol-db-initiator -f
DB already exists: hatohol
[INFO] <DBTables.cc:203> DBTables 16 is outdated, try to update it ...
        old-version: 00.16 [00]
        new-version: 00.18 [00]
[DBG] <HatoholException.cc:59> HatoholException: <DBAgentMySQL.cc:667> Failed to query: CREATE TABLE severity_ranks (id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,status INT(11) NOT NULL,color VARCHAR(255) NOT NULL,label VARCHAR(255) NOT NULL,as_important INT(11) NOT NULL DEFAULT 1): (1050) Table 'severity_ranks' already exists

Failed to create DBHatohol object
```

15.06にはseverity_ranksテーブルはなかった気がするので，
複数回，同コマンドを実行したために起こっているでているメッセージの気がします。
初回実行時にはどこで躓いているのか，環境を作りなおして検証してみます。

**Comment by ashie** [comment]
> 複数回，同コマンドを実行したために出ているメッセージの気がします。

クリーンな環境で試しても発生するので、アップデート処理の問題のようです。

**Comment by ashie** [comment]
> 15.06にはseverity_ranksテーブルはなかった気がするので，

なかったのに（開発者向けの）アップデート処理が実装されていて、そこで引っかかっている
ということのようです。

開発者に対しては多少不親切でも構わないので、アップデート処理を丸々削ります。

**Comment by ashie** [comment]
> 開発者に対しては多少不親切でも構わないので、アップデート処理を丸々削ります。

もしちゃんとケアするなら、バージョン指定をもっと厳密にやらないといけない。

**Comment by Mnakagawa** [comment]
#1955 をマージ後にも同様のコマンドを実行，同様のエラーメッセージが発生した。
hatohol-db-initiator, またDBTablesConfigは問題なく 16.01のものが使用されているはず。

**Comment by ashie** [comment]
> 同様のエラーメッセージが発生した。

具体的なエラーメッセージを張り付けてもらうことは可能ですか?
私の手元では、少なくとも15.06の初期状態であれば、アップデートできています。

逆に言うと初期状態からのアップデートでしか検証していなくて、実際に使われている
あらゆる環境からのアップデートが保証できいなら「アップデートできる」と言うべきでは
無いという話はあるかもしれませんが、まだ時間はあるので簡単には諦めたく無いところ
でもあります。

**Comment by kz0817** [comment]
＠Mnakagawaに所用があるため、@kz0817が引き継ぐ。

**Comment by kz0817** [comment]
私の環境 CentOS 7 (on Ubuntu15.10)でも、以下の操作、成功しました。

- 15.06のRPM(Server, Web)をインストール
- 起動して、組み込みのZabbixServer１つをWebUIから登録
- Hatohol Server停止
- 16.01のRPM(Server, Web)をインストール (16.01_releng/master: 2cd8819)
- Hatohol Server起動
- HPPTDリスタート

ただし、WebUIでEvent画面に移ると次のエラーが発生しています。
![_2016-01-20_15-57-05](https://cloud.githubusercontent.com/assets/2610513/12441835/7a90eb60-bf8e-11e5-85e6-43903b57a900.png)

**Comment by kz0817** [comment]
上記の時、/var/log/syslogには、Hatohol Serverのログ(INFO以上)は出ず。
/var/log/httpd/error_logにも何も情報なし。

**Comment by kz0817** [comment]
あー、hatohol-db-initiatorを実行してないかも。

**Comment by ashie** [comment]
event-filtersはクライアント側なので、`./manage.py syncdb`で解決しないでしょうか。

**Comment by kz0817** [comment]
はい、hatohol-db-initiatorと./manage.pyをした結果、正常に動作しました。
よって、私の環境でも不再現なので、@Mnakagawaさんに差し戻します。
ちょっと、続きが来週移行になるけど、やむを得ないですね。

**Comment by Mnakagawa** [comment]
私の方でも確認できました。
なぜ前回は失敗したのか…
クローズします。
