### ISSUE TITLE
[client] 監視サーバ設定のTLSの項目が日本語環境でも英語になっている

### ISSUE THREAD

**Issue by ashie** [project-hatohol/hatohol#1956]
以前は翻訳してあったが、今はなぜかpoファイルでコメントアウトされている

**Comment by ashie** [comment]
HAP1用のコードで翻訳用のjsファイルを作っていたが、それがなくなったため。
#1957 を復活させればこっちも復活する。

当面はこれで良いが、HAPI-JSONを削除するときが来たら何らかの対応が必要。

**Comment by ashie** [comment]
と思ったけど他にも何か足りない?

**Comment by Mnakagawa** [comment]
あとは[Static queue address]も対象？

**Comment by Mnakagawa** [comment]
[Passive Mode]もだろうか。このあたり手を付けていないのでそれっぽいの書いているだけです。
@BlueSkyDetector さんあたりに聞いたほうが良い？

**Comment by ashie** [comment]
> と思ったけど他にも何か足りない?

いや、やはり #1957 を修正した状態でpoを更新すれば日本語が出た。
ただし "Passive mode" は HAPI-JSON に無いので別途対応が必要。

**Comment by ashie** [comment]
> 当面はこれで良いが、HAPI-JSONを削除するときが来たら何らかの対応が必要。

> ただし "Passive mode" は HAPI-JSON に無いので別途対応が必要。

単純にWebUIプラグインに必要なラベルを持たせておけば良いか。

**Comment by ashie** [comment]
> 単純にWebUIプラグインに必要なラベルを持たせておけば良いか。

もっと言うと、パラメータのリストはHatoholサーバから送るのではなくてWebUIプラグインに
持たせた方が融通が効くし重複が避けられる。

融通が効くというのは、例えばサードバーティのプラグインで多言語対応をgettextで行うのは
難しいが、プラグイン自体にカタログを持たせれば対応できる。

16.01では無理だが、16.04ではそのように修正したい。

**Comment by ashie** [comment]
> もっと言うと、パラメータのリストはHatoholサーバから送るのではなくてWebUIプラグインに
> 持たせた方が融通が効くし重複が避けられる。

いや、プラグインにも情報を送らないといけないので、やはりHatoholサーバ側でも持つ必要が
あり、重複は避けられないか。

**Comment by ashie** [comment]
> いや、プラグインにも情報を送らないといけないので、やはりHatoholサーバ側でも持つ必要が
> あり、重複は避けられないか。

ラベルはHatoholサーバ側では必要なさそうなので、WebUIプラグインだけに持たせるという
仕組みにすれば一応重複は避けられる。とにかく16.04でもう一度見なおしたいところ。

16.01では

> 単純にWebUIプラグインに必要なラベルを持たせておけば良いか。

これだけにとどめておく。

**Comment by ashie** [comment]
>    単純にWebUIプラグインに必要なラベルを持たせておけば良いか。

いや、16.01時点ではラベルリストの所在が2箇所に別れるのは避けたいので、
hatohol-server-type-utilに暫定対処を入れる。

**Comment by cosmo0920** [comment]
https://github.com/project-hatohol/hatohol/pull/1962 で修正、masterにマージされたら閉じる。
