### ISSUE TITLE
[client][server] HAPI-JSONの設定が削除されている

### ISSUE THREAD

**Issue by ashie** [project-hatohol/hatohol#1957]
16.01_releng/masterでHAPI-JSONの設定が削除されている。
HAPI-JSONはユーザーがいるので私は16.01では削除するつもりはなかった。
意図した変更なのか確認が必要。

**Comment by ashie** [comment]
意図した変更じゃ無さそうなので復活させる

**Comment by Mnakagawa** [comment]
#1873 で削除したHAPI関連のソースがなくても，HAPI-JSONは動作するものなのですか？
（ex. HatoholArmPluginGate.cc）
それとも今はHAPI2.0を流用している？
理解度があまり足りていないので的はずれなコメントかもしれません。

**Comment by cosmo0920** [comment]
HAPI1-JSONはHatoholArmPluginGateJSON.ccを使って動作しているので #1873 で誤って削除してしまっているのはWebUI側に関係するコードです！

**Comment by cosmo0920** [comment]
このコードは既にlibrabbitmqを使用していて、ひたすらRabbitMQのブローカーからメッセージをConsumeする動作をしています。

**Comment by Mnakagawa** [comment]
なるほど！
理解しました。ありがとうございます。

**Comment by cosmo0920** [comment]
#1959 で修正。masterにマージされたら閉じる。
