### ISSUE TITLE
[client] 「イベントページの設定」内の表示項目設定の「すべて選択」が動作しない

### ISSUE THREAD

**Issue by ashie** [project-hatohol/hatohol#1958]
たぶんデザインだけ更新して実装し忘れ。

**Comment by Mnakagawa** [comment]
気づいてたのにIssueにあげるの忘れてた…
ありがとうございます！

**Comment by kz0817** [comment]
本件Closeできますよね？そうなら、お願いします。

**Comment by cosmo0920** [comment]
> 本件Closeできますよね？そうなら、お願いします。

いえ、16.01_releng/masterにマージされただけなのでまだクローズ出来ません。

#1965 で修正。masterにマージされたら閉じる。

**Comment by kz0817** [comment]
> #1965 で修正。masterにマージされたら閉じる。

了解
