### ISSUE TITLE
[hap2] zabbixapi.get_event_end_id()は文字列を返すほうがよいか？

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#1966]
get_event_end_id()は、取得した文字列を数値に変化して返す。
この関数の唯一のユーザーであるupdate_events_poll()は、その数値を再度文字列に変換しており、このシーケンスだけに着目すると無駄なことをしている。一見、数値でなく文字列を返したほうがよいようにも思うが、最終的な判断基準は、end idがなんなのか（それは数値なのか文字列なのか）を突き詰めて考えてそれにすればよいと思う。

**Comment by Mnakagawa** [comment]
end idをlastInfoとして捉えるのであれば、文字列で返すべきです。
文字列に変換している理由は、代入先がlastInfoだからです。
しかし、その先の処理ではend idが数値としてwhileから抜けるための条件に利用されています。
一つの関数内で、２つの意味で使用されているため、どちらがいいとは一概には言えないと思います。
ただ、処理が増えているのは間違いないので、処理を減らすためzabbixapi.get_event_end_idは
文字列をそのまま返したほうがいいかもしれません。

**Comment by Mnakagawa** [comment]
修正済み。masterにmergeされたらcloseする。

**Comment by kz0817** [comment]
これ、masterにマージされたのならクローズお願いします。
