### ISSUE TITLE
インシデント管理機能実装の方針とマイルストーン

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#1967]
現在、インシデント管理機能に次の２つがある
- Redmine
- 16.01から追加されたbuilt-in

#1949をはじめとして、最近、インシデント管理機能を
拡充する議論がなされている。

built-in型は、HatoholのWebUIと密結合でき、我々の
都合のよいように拡張できるという利点があるが、
開発と保守には相応の時間を要する。

Redmineなどの外部ソフトウェアは、すでに高い完成度で
あり、操作に慣れているユーザーも多い。一方、
Hatoholとのシームレスな融合という点では、built-inには
及ばないと考えられる。

これらの住み分け（使い分け）を、今後どうするのかをいま一度
整理したい。

**Comment by tksmatsunaga** [comment]
いろいろ考えてみましたが、以下の案はいかがでしょう？
・まずはRedmine前提で実装。
　UIだけはHatoholのWebUIもしくはAjax+マッシュアップなどでRedmineのWebUIの一部と連携できるか
　を検討。
　制限事項としては「Redmineを導入すればこの機能が使える」こととし、リリースノートにその旨を記載。
　Redmineのサポートは連携部分のみ行うこととする。Redmine自体のサポートは行わない。

・これで市場の反応を見て、Built-inの要望が多ければ次のバージョン以降で改めて実装を検討する。

・Redmine自体のアプライアンスの組み込みはもっと将来的な視点で検討。

**Comment by kz0817** [comment]
概ね賛成です。

> ・Redmine自体のアプライアンスの組み込みはもっと将来的な視点で検討。

ここは、オープンソースの開発コミュニティなので、所属企業固有のトピックはお控えください。

**Comment by tksmatsunaga** [comment]
すいませんでした。
コメントからは該当部分を削除しました。

**Comment by kz0817** [comment]
16.04では、とりあえずビルトインで、対処変更者と
メモを記録できるようにします。その実装や使い勝手を
みて再度、方針を決めましょう。本Issueを一旦閉じます。
