### ISSUE TITLE
[hap2] RabbitMQのQueue名の重複回避

### ISSUE THREAD

**Issue by Mnakagawa** [project-hatohol/hatohol#1975]
新しくサーバーを追加する際に，静的キューアドレスを既存の監視サーバーで使用しているキューに
重複する形で入力すると，両者のプラグインの動作に支障をきたす。

例えば現在，監視サーバー登録時に静的キューアドレスを空にした場合は「hap2.X(監視サーバー番号)」という
キューを作成し使用している。
ユーザーがコレを知っていれば意図的に重複させることも可能である。

これをユーザーの自己責任とすべきか，それともHatohol側で対処すべきか。
対処すべきならどのように，と言ったことを議論し，16.04に盛り込みたい。

**Comment by kz0817** [comment]
HAPI2.0の

**Comment by Mnakagawa** [comment]
間違ってクローズした感じでしょうか？Openします

**Comment by kz0817** [comment]
失礼しました。あやまってクローズしました。

**Comment by Mnakagawa** [comment]
hap側から判別するのは現状不可能だと思われる。
WebUIから登録するときだけエラーを吐くしかない？

**Comment by Mnakagawa** [comment]
また，現状Hatoholサーバーはstatic queueの名前しか記憶していない（arm_pluginsテーブル内にて）
staticではないqueueの名前（default）も保存しなければ，このIssue解決はできない。

**Comment by Mnakagawa** [comment]
defaultも保存するとWwbUI上で静的キューアドレスのところに表示されてしまう。
かといってDBに保存しないと他のプラグインのキュー名との比較もできないし，どうしたもんかなぁ

**Comment by Mnakagawa** [comment]
WebUI上の「静的キューアドレス」という表記が良くないのかも。
単に「キューアドレス」としてしまえば不都合もない？

**Comment by kz0817** [comment]
> 単に「キューアドレス」としてしまえば不都合もない？

その方がわかりやすそうですね。
指定がなければ、内部的に自動生成するってだけの仕様ですし。

**Comment by Mnakagawa** [comment]
サーバー情報編集時にデフォルトのキューアドレスが出てきても問題ないでしょうか。

**Comment by kz0817** [comment]
> サーバー情報編集時にデフォルトのキューアドレスが出てきても問題ないでしょうか。

内部生成される文字列ですよね？それは見せないほうがいいですよね。

**Comment by Mnakagawa** [comment]
表示，非表示の判断基準を文字列にすると，ユーザーが「hap2.X」といったキュー名を使用できなくなるし，
そのキュー名がどういった手段で生成されたものなのか，というメタ情報も作らないといけない？
修正の規模大きくなる。。。

**Comment by Mnakagawa** [comment]
「hap2.X」という名前は内部で予約されているものとして，ユーザーは入力できないようにするのがいいのかも。
現状の仕様だと，ユーザーから内部的なキュー名は見れため，偶然hap2.Xという名前を付けた時に
他のプラグインとキュー名が被る可能性もあるわけだし。

**Comment by Mnakagawa** [comment]
まとめ：
- 従来通り，ユーザーが定義したキュー名だけ保存する
- hap2.xは予約されているとしてエラーを返す
- ユーザー定義のキュー名を設定した際，保存しているキュー名(DB内のarm_pluginsテーブル内で検索)と被っていればエラーを吐く

とすれば穴もないし，比較的例に実装できそう。
