### ISSUE TITLE
Fluentdプラグインを使用すると、Hatoholサーバがエラーを出力する。

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#1977]
16.01のbeta2 RPMをCentOS7上でFluentdプラグイン使用すると、Hatohol Serverが以下のメッセージを出力する。

    Jan 27 00:14:11 localhost hatohol[32182]: [ERR] <ActionManager.cc:1577> Not found: svID: 3, trigID: __DO_NOT_ASSOCIATE_TRIGGER

ここで、svID: 3は、fluentdプラグインのサーバID。

**Comment by kz0817** [comment]
fluentdプラグインから送信されるイベントには、triggerIDが含まれないので、src/HatoholArmPluginGateHAPI2.cc:parseEventsParams()でtriggerIDにDO_NOT_ASSOCIATE_TRIGGER_IDがセットされて、DBに保存される。

ActionManager::fillTriggerInfoInEventInfo()では、getTriggerInfo()を実行して、
tiggger情報を得るが、この場合、登録されていないので、上記のエラーメッセージが
出力される。

多分、triggerIDがDO_NOT_ASSOCIATE_TRIGGERの場合、エラーメッセージを
抑止する必要がありそう。

**Comment by kz0817** [comment]
この問題のいやらしいところは、syslogをfluentdプラグイン経由で監視すると、このエラーメッセージを契機にまたfluentdプラグインがイベントを送信し、再度このエラーメッセージがでることがループされること。無限ループになるような気もするが、実際には、数万回でループが止まっている。別の問題があるのか。

**Comment by kz0817** [comment]
syslog爆弾になるので、severityはやや高いが、fluentdの設定ファイルで、この行にmatchする場合、無視するような動作にすれば、回避できそう。fluentdの柔軟性すばらしい！

**Comment by kz0817** [comment]
例えば、こんな感じのFluentd用のconfファイルを作ればOK

<source>
  type tail
  format syslog
  path /var/log/messages
  pos_file messages.pos
  tag hatohol.syslog.messages
</source>

<filter hatohol.**>
  type grep
  exclude1 message Not found: svID: [0-9]+, trigID: __DO_NOT_ASSOCIATE_TRIGGER
</filter>

<filter hatohol.**>
  type record_transformer
  <record>
    status "NG"
    severity "ERROR"
    type "BAD"
  </record>
</filter>

<match hatohol.**>
  type stdout
</match>

**Comment by cosmo0920** [comment]
ところで、Fluentd 0.12系を使っているなら `type` は `@type` と書くのが正式な書き方なようですよ。
参考: http://qiita.com/repeatedly/items/e882fdb46dfe85d9556f#プレフィックスパラメータ

**Comment by kz0817** [comment]
> ところで、Fluentd 0.12系を使っているなら type は @type と書くのが正式な書き方なようですよ。

なる。

**Comment by kz0817** [comment]
【参考】大量の重要イベント
![many-events](https://cloud.githubusercontent.com/assets/2610513/12604591/43750a40-c500-11e5-8806-c6a843abbc03.png)

**Comment by cosmo0920** [comment]
HouseKeeperだと古いイベントを古い順に個数を指定して削除する機能はありますが、バックアップ機能までは無いですね。。

**Comment by cosmo0920** [comment]
HAP2 Fluentdを動かしてみようとすると、

```log
% which td-agent
/usr/sbin/td-agent
```

```xml
<source>
  type tail
  format syslog
  path /var/log/messages
  pos_file messages.pos
  tag hatohol.syslog.messages
</source>
<filter hatohol.**>
  type grep
  exclude1 message Not found: svID: [0-9]+, trigID: __DO_NOT_ASSOCIATE_TRIGGER
</filter>
<filter hatohol.**>
  type record_transformer
  <record>
    status NG
    severity ERROR
    type BAD
  </record>
</filter>
<match hatohol.**>
  type copy
  <store>
    type hatohol2
    flush_interval 1
    url amqp://user:password@localhost/hatohol
    queue_name gate.1
  </store>
  <store>
    type stdout
  </store>
</match>
<system>
  rpc_endpoint 127.0.0.1:9000
</system>
```

の環境で

```log
INFO:15096:got monitoring server info.
[DBG] <HatoholArmPluginInterfaceHAPI2.cc:221> message: <application/json>/<{"jsonrpc": "2.0", "result": {"procedures": ["exchangeProfile", "updateMonitoringServerInfo"], "name": "Hap2FluentdMain"}, "id": 3864659967}>
INFO:15108:Started fluentd manger process.
WARNING:15108:Got SIGCHLD
[INFO] <HatoholArmPluginGateHAPI2.cc:323> HAP Process connecting done. Connected HAP process name: "Hap2FluentdMain"
INFO:15108:Started fluentd manger process.
WARNING:15108:Got SIGCHLD
```

のようなログが頻繁に出てtd-agentが全く立ち上がらないのですが、何か動かすために必要な事項の見落としがあるのでしょうか？

**Comment by kz0817** [comment]
/var/log/messagesを読むためには、root権限が通常必要ですが、hap2_fluentd.pyをroot権限で起動していますか？

**Comment by kz0817** [comment]
また、上記のfluentdのconfファイルを指定してtd-agentを起動すると、正常に動作しますか？

**Comment by cosmo0920** [comment]
> /var/log/messagesを読むためには、root権限が通常必要ですが、hap2_fluentd.pyをroot権限で起動していますか？

はい、hatoholサーバーをrootで起動して実行してパッシブモードではない状態で起動しています。

> また、上記のfluentdのconfファイルを指定してtd-agentを起動すると、正常に動作しますか？

上記のconfファイルで正常に起動します。

> url amqp://user:password@localhost/hatohol

このurlは実際の環境に合わせて変えてはありますが。。。

**Comment by kz0817** [comment]
うーむ、なぜでしょうかね。
"got monitoring server info."が表示されてるので、AMQP brokerを通じたHatohol Serverとの通信には成功していると思われます。
Got SIGCHLDは、何を契機に表示されているのか？第一に想定されるのは、td-agentが終了しているということですが、例えば、psやpstreeをしてtd-agentが起動しているのか、それともそうでないのか確かめてもらえますか？

**Comment by cosmo0920** [comment]
```log
% ps -aux |grep td-agent
hhatake  25246  0.0  0.0  16908   940 pts/17   S+   11:23   0:00 grep --color=auto td-agent
```

居ない、ですね…。

**Comment by kz0817** [comment]
hap2_fluentd.pyを起動するコマンドラインをオプション含めて教えてください。

**Comment by cosmo0920** [comment]
ノンパッシブモードなのでhap2_fluentd.pyの`--fluentd-launch`そのままです。

**Comment by kz0817** [comment]
> ノンパッシブモードなのでhap2_fluentd.pyの--fluentd-launchそのままです。

念のため、こんな感じの完全なコマンドラインを教えていただけますか？
<pre>
$ sudo HAPI_AMQP_PASSWORD=hatohol /usr/libexec/hatohol/hap2/hatohol/hap2_fluentd.py --amqp-broker localhost --amqp-vhost hatohol --amqp-queue aq --amqp-user hatohol --fluentd-launch "td-agent -c a.conf -q"
</pre>

**Comment by cosmo0920** [comment]
```log
root     28033  0.4  0.0 150880 16088 ?        Sl   11:44   0:00  python /usr/local/libexec/hatohol/hap2/hatohol/hap2_fluentd.py --amqp-broker=localhost --amqp-port=5675 --amqp-user=hatohol --amqp-queue=hap2.2 --amqp-vhost=hatohol --log-conf=/usr/local/etc/hatohol/hap2-logging.conf
```

ですね。

**Comment by kz0817** [comment]
じゃあ、上で示しているconfig fileは、/etc/td-agent/td-agent.confってこと？

**Comment by cosmo0920** [comment]
そうですね！

**Comment by kz0817** [comment]
まさに#2010の機能がほしいなぁ。

**Comment by cosmo0920** [comment]
今のhap2_fluentd.pyのままだとtd-agent(fluentd)のログファイルが保存されないのでエラーの調査がかなりやりづらいです。 `--log /var/log/hatohol/td-agent.log` のような箇所にログを保存したほうがいいと思いました。

**Comment by kz0817** [comment]
I think so too.

**Comment by cosmo0920** [comment]
他にも td-agent はbundlerのエコシステムにも乗っけることができるので #2023 も立てておきました。

**Comment by cosmo0920** [comment]
(やっと、fluentdのHAP2プラグインが動き出した…！)
質問なのですが、td-agentが今は決め打ちで`td-agent`と指定されていて、こちらのUbuntu 14.04 LTS環境では`/usr/sbin/td-agent` に変更しないと動かなかったです。
これを将来的に変更できるようにする予定はありますか？
また、起動オプションもWebUIから変更可能になっていると、 #2023 で上がっているbundler用のファイルのオプションもユーザーが自分で指定できるので嬉しいなぁと思いました。

**Comment by kz0817** [comment]
hap2_fluentd.pyの--fluentd-launchオプションで対応できませんか？
それとも、WebUIから指定できる様な振る舞いを指していますか？

**Comment by cosmo0920** [comment]
WebUIから指定できる仕組みを指しています。

**Comment by kz0817** [comment]
> WebUIから指定できる仕組みを指しています。

そうね。その場合、confファイルもWebUIで指定できないと、ほとんど自由度が増えないよね。

**Comment by cosmo0920** [comment]
なるほど。confファイルだけでもあると規定の動作を変更出来て尚かつ変に壊す可能性も減るので便利ですね。hap2 fluentdは既にconfファイルを扱えるんでしたっけ？

**Comment by kz0817** [comment]
> hap2 fluentdは既にconfファイルを扱えるんでしたっけ？

--fluentd-launch "td-agent -c hoge.conf -q"とかすると、任意のconfを与えられます。
こういう回答を期待してました？

**Comment by cosmo0920** [comment]
いえ、Fluentd自体のconfではなくhap2のconfです。と思ったらそれはこのIssue https://github.com/project-hatohol/hatohol/issues/1985 でしたね…

**Comment by Mnakagawa** [comment]
ですね。
私がいま担当しているissueを完了させればhap2のconfファイルからtd-agentの名前を指定できるようになるはず

**Comment by cosmo0920** [comment]
…では、本題としてtrigIDがDO_NOT_ASSOCIATE_TRIGGER_IDの時にはエラーメッセージを抑止する方向で対処します。

**Comment by cosmo0920** [comment]
#2123 がマージされたため、クローズ。また何か問題があった場合は再オープンしてください。
