### ISSUE TITLE
通知のアイコンが侵入禁止なのに違和感

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#1981]
もっと適切なのがありあそう。
![taisyo-break](https://cloud.githubusercontent.com/assets/2610513/12633200/c8f834be-c5b2-11e5-9c06-2cb13cb62553.png)

**Comment by cosmo0920** [comment]
glyphicon glyphicon-info-sign で→ :information_source: のようなアイコンであれば違和感がなさそうでしょうか

**Comment by kz0817** [comment]
そうですね。

**Comment by ucksts** [comment]
Bootstrap Default(v2.2.2)で使用できるアイコンの中で検討してみました。

単純に"通知"アイコンのみを探したところ、
意味的にもBellが近い気がしました。
![_new_bell](https://cloud.githubusercontent.com/assets/16419592/13065008/53b4ad02-d49b-11e5-84c9-d05575eda327.png)

※Informationマークだと、"正常"や"障害"を上回って目立ってしまう懸念。
![_info_sign](https://cloud.githubusercontent.com/assets/16419592/13065067/fb223ca8-d49b-11e5-8a90-af2d1d4b0eb3.png)

ただし、正常、障害、通知の３種類が並んだ時に、
形状がバラバラで美しくなかったので、以下のように揃えたら見やすいのではと考えました。
ネガティブな情報かどうかは"色情報"で十分担保できると考えます。

**▼改善A案**
![_new_a](https://cloud.githubusercontent.com/assets/16419592/13065034/a43b73be-d49b-11e5-84f2-34597b8f415e.png)

**▼改善B案**
→通知のみBellというのも見やすくおすすめです
![_new_b](https://cloud.githubusercontent.com/assets/16419592/13065083/20e9fc14-d49c-11e5-83ec-b208dd15f254.png)

**Comment by kz0817** [comment]
対応ありがとうございます。どちらもデザイン的には自然でよいと思います。
どちらかというとA案がいいと思います。全体的にアイコンの統一感がありますので。

今週金曜日2/19までに、他の意見がなければ、A案でプルリクエストしてください。

**Comment by ucksts** [comment]
承知しました！

**Comment by ucksts** [comment]
期限の2/19を越えましたので、こちらはA案で実装を進めて参ります。

**Comment by mmikan22** [comment]
Pull Request出しました！

**Comment by ashie** [comment]
修正がマージされたのでクローズします。
