### ISSUE TITLE
組み込みのデータ取得方法(Zabbix , Nagios NDOUtils)を削除する

### ISSUE THREAD

**Issue by Mnakagawa** [project-hatohol/hatohol#1983]
データ取得の方法をHAP2.0プラグインでの取得に統一する

**Comment by cosmo0920** [comment]
ついでにBuilt-inなどの条件分岐をがんばっているところも削除してしまいましょう :sparkles:

**Comment by kz0817** [comment]
別Issueで議論すべきかもしれませんが。。。
いくつかの内部APIは、ArmPlugiInfoの指定が任意であった。
というのも組み込み型のArmに対しては不要だったから。でも、
この改修によって、ArmPluginInfoの指定が必須になる。

いっそのこと、MonitoringServerInfoとArmPluginInfoの
テーブルをひとつにして、対応するデータ構造もマージしたほうが、
扱いやすくなるかもしれない。

**Comment by Mnakagawa** [comment]
- HAPI-JSONも削除するかどうか
 - 現在はhap2のIDは7で統一されているが組み込みの取得法が削除されるのであれば，各プラグインのuuidをidとしても良さそう？

**Comment by kz0817** [comment]
> HAPI-JSONも削除するかどうか

最近、ユーザーさんがいるから削除せずに残そうって話がありましが、
代わりの手段を用意して削除した方がよいと思います。

> 現在はhap2のIDは7で統一されているが組み込みの取得法が削除されるのであれば，各プラグインのuuidをidとしても良さそう？

賛成。かなりすっきりしそう。

**Comment by Mnakagawa** [comment]
> 現在はhap2のIDは7で統一されているが組み込みの取得法が削除されるのであれば，各プラグインのuuidをidとしても良さそう？

と思ったけど，uuidだからintであるserverIDをstringであるuuidにすると規模がとんでもないことになりそう。

**Comment by ashie** [comment]
> と思ったけど，uuidだからintであるserverIDをstringであるuuidにすると規模がとんでもないことになりそう。

サーバIDとサーバtypeを混同していませんか?
serversテーブルのIDはノータッチ（これまで通り）でいいはずです。

サーバtypeの判別は、単にtypeを廃止してuuidだけで判別(文字列のままでOK)すれば良いだけだと思います。

**Comment by Mnakagawa** [comment]
そういえばそうでした。ご指摘ありがとうございます。

**Comment by kz0817** [comment]
casperjsを使ったテストの修正、心が折れそう。。。

**Comment by kz0817** [comment]
監視サーバーを手動ですべて削除してから、下記のテストをすると登録されてないエラーが出る
<pre>
$ casperjs --verbose  test  test/feature/register_server_test.js
</pre>
<pre>
FAIL Registered server's nickName "test" exists in the monitoring servers table.
#    type: assertTextExists
#    file: test/feature/register_server_test.js:137
#    code: "\" exists in the monitoring servers table.");
#    subject: false
#    text: "test"
</pre>
でも、DBには登録されている
<pre>
> select * from servers;
+----+------+-------------+------------+-------------+------+----------------------+--------------------+-----------+--------------+---------+-----------------------------------------+---------------+
| id | type | hostname    | ip_address | nickname    | port | polling_interval_sec | retry_interval_sec | user_name | password     | db_name | base_url                                | extended_info |
+----+------+-------------+------------+-------------+------+----------------------+--------------------+-----------+--------------+---------+-----------------------------------------+---------------+
| 47 |    7 | test        |            | test        |    0 |                   30 |                 10 | admin     | zabbix-admin |         | http://127.0.0.1/zabbix/api_jsonrpc.php |               |
| 48 |    7 | edited-test |            | edited-test |    0 |                   30 |                 10 | admin     | zabbix-admin |         | http://127.0.0.1/zabbix/api_jsonrpc.php |               |
+----+------+-------------+------------+-------------+------+----------------------+--------------------+-----------+--------------+---------+-----------------------------------------+---------------+
</pre>
この状態で、再度実行すると成功する。レスポンスが返るまで待ててないのか?

**Comment by kz0817** [comment]
console.logを入れて調べていると、仮説のとおり、Hatohol serverからレスポンスが返る前にチェックしているように見える。

**Comment by kz0817** [comment]
<pre>
  casper.waitFor(function() {
    return this.evaluate(function() {
      return $(document).on("DOMNodeInserted",
                            "table tr",
                             function() {return true;});
    });
</pre>
これって、$.on()がすぐに返ってる？$.on()の返り値ってなんだ？

**Comment by kz0817** [comment]
> これって、$.on()がすぐに返ってる？$.on()の返り値ってなんだ？

jQueryが返る？つまり$(document)。そうするとtrueと評価されるから、実際には待たないってこと？
http://api.jquery.com/on/

**Comment by kz0817** [comment]
本件、削除は割りと簡単だったが、従来のArmZabbixAPIを使用している
テストが多くあった。今後、デファクトは、HAPI2のzabbix_apiなので、
それに改変しているが、その規模がかなり大きい。

Pull Requestとしては、次の４つに分けて行うことを計画している。
・serverテスト
・WebUIのブラウザテスト
・WebUIのfeatureテスト
・削除パッチ

**Comment by kz0817** [comment]
https://travis-ci.org/project-hatohol/hatohol/jobs/109500633で、すべてのテストが通った模様。15821.4の失敗は、システムの問題と思われる。

**Comment by cosmo0920** [comment]
:clap:

**Comment by kz0817** [comment]
>・serverテスト
>・削除パッチ

これは分離しにくい。というのは、serverInfoだけでなく、ArmPluginInfoがが必須になるようにAPIを変更したため。

**Comment by kz0817** [comment]
We've done it !

**Comment by cosmo0920** [comment]
:tada:
