### ISSUE TITLE
[hap2] haplibを整理する

### ISSUE THREAD

**Issue by Mnakagawa** [project-hatohol/hatohol#1994]
現在肥大化しているhaplibを整理する。
Utilsクラスを切り出して別ファイルにする。

**Comment by Mnakagawa** [comment]
haplib内のUtilsクラスを丸ごとhap2_utils.pyとして切り出してみたが，
一部の関数はhaplibに残しておいたほうがいいのだろうか。

'ParsedMessage'
'__check_error_dict'
'__convert_json_to_dict'
'conv_to_hapi_time'
'generate_request_id'
'get_biggest_num_of_dict_array'
'get_current_hatohol_time'
'get_maximum_eventid'
'get_top_file_name'
'is_allowed_procedure'
'optimize_server_procedures'
'parse_received_message'
'translate_hatohol_time_to_unix_time'
'translate_int_to_decimal'
'translate_unix_time_to_hatohol_time'
'validate_arguments'

以上がhaplibのUtils内に存在している関数。
このなかで例えばconv_to_hapi_timeは比較的汎用性が高いため，hap2_utilsで良いはず。
逆にparse_received_messageなどは明らかにhaplib内でしか使用していない固有の関数である。

残すのは良いと思うのだが，それらをUtilsクラスに属する関数として残すことに抵抗がある。
hap2_utilsというモジュールを別に作るためである。
hap2_utils内には先ほどあげたようにconv_to_hapi_timeなどの汎用性の高い関数を
特にクラスなどを作成せずベタ書きする。
対して，haplibに残す関数はどのように書くのが良いだろうか。。。

**Comment by Mnakagawa** [comment]
普通にベタ書きでいい気がする

**Comment by cosmo0920** [comment]
ところで切り出すことには :+1: ですが、Utilsと言う名前には :-1: の票を入れておきます。

**Comment by Mnakagawa** [comment]
common，とかでしょうか

**Comment by cosmo0920** [comment]
そんな感じですね！

**Comment by Mnakagawa** [comment]
OK

**Comment by Mnakagawa** [comment]
各クラス（Pollerとか）で使用する定数がベタ書きなのだから，
各クラスで使用する関数が定数と同位置に存在するのは自然なはず。そうします（自己完結）

**Comment by Mnakagawa** [comment]
マージ済み。クローズ
