### ISSUE TITLE
[Server] Synchronization of added and deleted triggers and hosts

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#20]
Currently, Hathol server doesn't have a feature to synchronization of deleted triggers and hosts on the monitoring system.

**Comment by miyashita-k** [comment]
this issue,
Is object to synchronize only "trigger"?　OR "item" and "trigger"?

**Comment by o-wakabayashi** [comment]
すみません、Triggerについては対処しましたが、ご指摘のとおり他にも対応が
必要だと思います。
対応方法
概要アイテム：現状態という意味では存在しないサーバの情報は「表示されない」
最新データ：現状態という意味では存在しないサーバの情報は「表示されない」
イベント：蓄積データなので存在しないサーバの情報も「表示される」



2015-01-21 9:26 GMT+09:00 katsuji miyashita <notifications@github.com>:

**Comment by Mnakagawa** [comment]
Related: #2029 #2195 
I close issue.
