### ISSUE TITLE
[WebUI] 期間フィルタのクリアボタンが壊れている

### ISSUE THREAD

**Issue by ashie** [project-hatohol/hatohol#2001]
期間フィルタで日時を選択するとクリアボタンが表示される機能を実装していたのだが、
16.01ではこの機能が壊れている。

* クリアボタンが「絞り込みオプション」の右上辺りに表示されてしまう
* クリアボタンを押すことができない

新デザインを適用したときに壊れたようだ。

**Comment by ashie** [comment]
form-control-feedbackが悪さしているようだ。
これを外すと正しい位置に表示されて動作も問題ない。
Bootstarpの更新でおかしくなった?

**Comment by ashie** [comment]
hoge

**Comment by cosmo0920** [comment]
test comment
