### ISSUE TITLE
フィルタの絞り込みエリアがもう少し小さくてもよいのではないか？

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#2005]
以下のキャプチャは、1280x800のディスプレイでフルスクリーン表示したときのものである。16.01から導入された新しいフィルタの絞り込みは、インタラクティブ性が高く、かなり操作性が高いと感じています。一方、この解像度ではフィルタされたイベントが数件しか表示できません。ヘッダ部や絞り込みエリアに空白が多く、それらを調節することで、もう少しイベントをたくさん表示できないでしょうか。

<img width="1280" alt="2016-02-05 9 19 05" src="https://cloud.githubusercontent.com/assets/2610513/12834283/b04a6ae4-cbe9-11e5-98cd-dad6a7ccabe0.png">

**Comment by kz0817** [comment]
なお、フルスクリーンでなくWindowの最大サイズだとさらに表示されるイベント数がすくなく、せっかくの操作性が活用しきれない印象です。

<img width="1280" alt="2016-02-05 9 25 29" src="https://cloud.githubusercontent.com/assets/2610513/12834430/983bc19a-cbea-11e5-8137-72da30af917b.png">

**Comment by ucksts** [comment]
「絞り込みオプション」展開時は、イベントリストの表示行数を抑えてでも
フィルタ操作を迷わず完結にできるように、という意図がありました。

各プルダウンの行間を、例えば0.8-0.5に抑えることで、あと1行程度の確保は可能かもしれません。

**Comment by ucksts** [comment]
お待たせしました。絞り込みオプションの省スペース化を検討しました。
各プルダウンの行間を22px→12pxへと圧縮することにより、Windows表示時でも
テーブル１行分の確保が可能になりそうです。

**▼現在（22px）**
![event_option_ui_size1](https://cloud.githubusercontent.com/assets/16419592/13064067/9e1f73f8-d492-11e5-874b-07c550634c85.png)

**▼改定案（12px）**
![event_option_ui_size2](https://cloud.githubusercontent.com/assets/16419592/13064075/b7aef2f8-d492-11e5-9bca-2aabf6a488b0.png)

**▼デザインサンプル**
![event_option_ui_sample](https://cloud.githubusercontent.com/assets/16419592/13064084/d0049ba0-d492-11e5-9361-5c318763b1ad.png)

**Comment by kz0817** [comment]
おおー、フィルタの見やすさを維持したまま、スペースが少し広がった感じですね。
「イベント」横の広大な空白はやっぱり気になりますが、他に有力な案がなｋれば、
この修正をPull Requestしていただけますか。

**Comment by mmikan22** [comment]
失礼します、フロントエンドです。
このissueの修正をcommitまではしたのですが、pull requestはどのようにして出せばよいでしょうか？

不慣れで申し訳ないです、ご教授いただけたら幸いです。

何卒よろしくおねがいいたします。

**Comment by ashie** [comment]
> このissueの修正をcommitまではしたのですが、pull requestはどのようにして出せばよいでしょうか？

コミットされた修正はpushされていますか?
されていない場合は、まずはpushをお願いします。

Hatoholのリポジトリで作業する場合は

1. `git clone git@github.com:project-hatohol/hatohol.git`
2. 作業ブランチを作成: `git cehckout -b your-branch master`
3. 修正をコミット: `git commit -a`
4. `git push -u origin your-branch`
5. https://github.com/project-hatohol/hatohol でyour-branchを選んで`New pull request`ボタン
6. 説明文を加えて`Create pull request`

もしいきなりHatoholのリポジトリで作業するのが怖い場合は、最初に「Fork」ボタンで自分のアカウントに
コピーしてから、そこで同様の作業をして下さい(1.と5.を自分のアカウントに読み替えて下さい)。

**Comment by mmikan22** [comment]
＞ashieさん
ありがとうございます！
PR出せたようです、涙が出るほどうれしいです！

**Comment by ashie** [comment]
英語での表示時に、改行される項目の縦方向の位置がおかしい感じがする。

![filter-vertical-align](https://cloud.githubusercontent.com/assets/135104/13867955/a452d2b4-ed07-11e5-9f17-56a1563029b8.png)

改行されるのはいいけど、中央で揃えた方が綺麗だと思う。

**Comment by ucksts** [comment]
ashieさん有難うございます。
合わせて、テキストの行間（現在26px）を18pxの指定にすると
綺麗に収まりそうです。

![default](https://cloud.githubusercontent.com/assets/16419592/13868976/2f5c5ec0-ed12-11e5-9d31-3910d4becb3a.jpg)

**Comment by mmikan22** [comment]
こちら、配慮が足らず申し訳ない！
（そりゃ、複数行になりますよね）

3行以上になることも考慮し、.filter-elementをdisplay:inline-tableに、.filter-element > p（項目名部分）をdisplay:table-cellとし、vertical-align:middle、line-height:100%を適用。

【イベントのフィルター要素】
![cap01](https://cloud.githubusercontent.com/assets/17230101/13898484/acac9e36-ee15-11e5-88e2-f5b72f9f148c.png)
【トリガーのフィルター要素】
![cap02](https://cloud.githubusercontent.com/assets/17230101/13898485/af83916e-ee15-11e5-8b97-d8fb8a21a142.png)

**Comment by ashie** [comment]
元コメントの問題は #2180 で修正されているようだ。
改行されたラベルの問題も #2190 で修正されている。
対応ありがとうございます！
