### ISSUE TITLE
イベント画面のサマリエリアを狭くできないか？

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#2006]
サマリエリアの文言が少し長く、また下部の空白が大きい。
用語を吟味したり、アイコンを使うことなどでもっと幅を小さくできないか。
#1991とも関連しそう。

#2005に添付のスクリーンキャプチャも参照
https://github.com/project-hatohol/hatohol/issues/2005

**Comment by kz0817** [comment]
基本的にアイコンにしておいてホバーで「未対処の重要イベント」というヒントをだすというのはどうでしょうか？

**Comment by ucksts** [comment]
サマリエリアの幅を圧縮するデザインを検討してみました。
▼改善案資料
[hatohol Event Page 改善案.pdf](https://github.com/project-hatohol/hatohol/files/142969/hatohol.Event.Page.pdf)

左カラム（サマリエリア）のデザイン見直しにより、
右カラム（テーブル）の表示スペースをより確保することを目的としています。
あとは、"サマリー"というだけあり、視覚的に簡素化された情報が
大きく置いてある方が、UI操作上も好ましいと考えました。

▼A案
![hatohol1604_event_summary_a1](https://cloud.githubusercontent.com/assets/16419592/13258314/088c3ea2-da96-11e5-8eab-c8874ca7d26f.jpg)

▼B案
![hatohol1604_event_summary_b1](https://cloud.githubusercontent.com/assets/16419592/13258326/10984ea6-da96-11e5-9d23-f09c5ad9f969.jpg)

**Comment by Mnakagawa** [comment]
A案に1票。
ユーザーが「この項目はこの色」と一度覚えてしまえば以降は文字を読む必要が無くなるのではないかと思った。

**Comment by kz0817** [comment]
私もA案がシンプルな感じがして好きです。
ただ、上部のメニューもそうなんですが、橙と白の組み合わせで、文字が視認しにくいように感じます。
イメージカラーの橙の色味を微調整してコントラストを上げることってできないでしょうか。

**Comment by ucksts** [comment]
A案サマリエリアの、オレンジ地色を濃く変更し視認性を上げました。
（現Headerで使われている、current色です）
![hatohol1604_event_summary_a1](https://cloud.githubusercontent.com/assets/16419592/13308457/bae79cce-dbb6-11e5-9d3c-492a34ae8dc2.jpg)


また、[資料内](https://github.com/project-hatohol/hatohol/files/142969/hatohol.Event.Page.pdf)に
貼りましたが改めて、左のサマリエリアは、ボタンの役割も持っていますので、
それぞれ押下したときの状態が以下になります。

▼重要イベント選択時
![hatohol1604_event_summary_a2](https://cloud.githubusercontent.com/assets/16419592/13308448/ae5a09c4-dbb6-11e5-9f3a-fbbb19f17276.jpg)

▼未対応の重要イベント選択時
![hatohol1604_event_summary_a3](https://cloud.githubusercontent.com/assets/16419592/13308451/b3c4ecbc-dbb6-11e5-85de-1de72da9fd54.jpg)

**Comment by kz0817** [comment]
迅速な対応ありがとうございます。
かなり、シンプルでいいですね。

ただ、今更ながらなんですが、ここまで不要なものをそぎ落としてすっきりすると、サイドでなく上部「エベント」右横の空白領域に配置できそうですよね。そうすると、イベントの各行にもっと幅をアサイン出来そうですし。どう思われますか？

**Comment by ucksts** [comment]
コメント有難うございます。
おっしゃる通り、ページのタイトル行（イベント右横）の空白は広大なので、
以降の改善の余地はあると思います。

前回verにてメーラーと同様のUIとして、左：サマリ→右：詳細スペース
という、左右分割を導入しました。
目的としては、スペース効率を多少犠牲にしても、「理解のしやすさ」と「情報を把握するスピード」を優先していました。
とはいえ、テーブル部分を中心にモニタリングしたいニーズに対しては、
サマリエリアはアコーディオンUIで格納できる仕様で解決できているのではと考えております。

**Comment by Mnakagawa** [comment]
そもそもの話なんですけど，「イベント」というタイトルは必要でしょうか。
上部メニューバーも暗くなり現在がどのページなのか理解できますし，必要性を感じません。

「設定」や「最終更新時間」も左のサマリエリアに移動することができれば，上の空間丸ごと使えて良いのではないかと思いました。

**Comment by ucksts** [comment]
コメントありがとうございます。

あくまで私の考え方ではありますが、
基本的に、hatoholではどのページにおいても
画面の大半のエリアを表組が占めることになります。
上部メニューを操作した際に、一瞬で確信が得られる応答として
ページごとのタイトルは是非ともマストで欲しいな、とデザイナー視点で考えております。
ご検討いただけたらと存じます。

ただし、今後は、イベントと並列するページの"トリガー"や"ダッシュボード"でも、
左カラムの存在ありとして統一できれば、ご指摘通りタイトル行の廃止は考えられます。
（左カラムにタイトルを収める、という手法で）

**Comment by Mnakagawa** [comment]
なるほど。ありがとうございます。

ではタイトルを残す方針にするとして，kzさんの提案はいかがでしょうか。
左のサマリ部を縦ではなく，横にしてタイトル横の広大な空間に配置する。
タイトルを残すのであれば空間が出来るのは必然ですし，それを有効活用するのは合理的かと思いました。

**Comment by ucksts** [comment]
承知しました。一回、サンプルご提示差し上げます！

**Comment by ucksts** [comment]
間が空いてしまい申し訳ありません。
サマリエリアを、タイトル行に統合するデザインサンプルを作成してみました。
こちらも候補として検討できればと思います。

表組のスペースを最大限稼ぐことを目的に、[更新]ボタンの置き位置も変更しております。

![hatohol1604_event_summary_c0301](https://cloud.githubusercontent.com/assets/16419592/13414301/eae35602-df94-11e5-9c70-f0813fd95c23.jpg)

結果的に、表組で１行・概要のテキストを20字相当、増やすことができそうです。
サマリエリアに置かれていた「イベント発生ホスト数」は情報量が多すぎるため、
割愛いたしました。（もし監視オペレーションで絶対的に必要であればおしらせください）

**Comment by kz0817** [comment]
サンプルの作成ありがとうございます。
いい感じに配置されていると感じます。「すべてのイベント」や「未対処の重要イベント」などのボタンの高さがもう少し大きくてもいいかなという気もしますが、そこは好みの問題かもしれないですね。

他にコメントなければ、これをベースにすすめましょう。

**Comment by ashie** [comment]
ぱっと見、サマリーのフィルターがイベントリストにも適用されてしまいそうに見えましたが、
そう感じるのは私だけ?

**Comment by kz0817** [comment]
> ぱっと見、サマリーのフィルターがイベントリストにも適用されてしまいそうに見えましたが、そう感じるのは私だけ?

たしかに、そうですね。
上部のボタンとフィルタのリストボックスがセットで、下のイベントリストと
独立していることが直感的にわかるように工夫したいですね。

**Comment by ucksts** [comment]
仕様の理解が追いついておらず申し訳ありません。
下記図のように、フィルターを操作することで、点線のエリア（イベントリスト含む）に作用すると理解していたのですが、これは間違いでしたでしょうか。

![hatohol1604_event_summary_c0301_smpl](https://cloud.githubusercontent.com/assets/16419592/13417579/af56b900-dfb0-11e5-9b55-c3e741d1281d.jpg)

もしよろしければ、フィルター操作で起こることを
教えていただけるとデザインを再検討できますので大変たすかります！

**Comment by cosmo0920** [comment]
イベント画面の場合、サマリーのフィルタとテーブルへのフィルタは別になっています。
なので、上記の画像での赤丸のフィルタがテーブルの対するフィルタでの絞り込みならば下部のテーブルのみに作用し、サマリーに対するフィルタならばヘッダー部のサマリーのみに適用されます。

**Comment by ashie** [comment]
> イベント画面の場合、サマリーのフィルタとテーブルへのフィルタは別になっています。

サマリーへのフィルタは常に表示されていますが、テーブルへのフィルタについては
同じものが「絞り込みオプション」の中に隠されています。

**Comment by ashie** [comment]
> イベント画面の場合、サマリーのフィルタとテーブルへのフィルタは別になっています。

そもそもフィルタを別にすべきなのかどうかは、私個人としては判断できていません。
分かりづらいなとは思っているものの、良い改善案が思いついていない状態です。

**Comment by ucksts** [comment]
皆様、教えていただきありがとうございます。

サマリーとテーブルのフィルタを別々に運用するイメージが
個人的には沸かなかったもので申し訳ありません。
サマリに対してのフィルタ操作ということで、以下の位置にpulldownを置くと
微妙な位置変更ですが、直感的になるのではと思っております。

![hatohol1604_event_summary_c0302](https://cloud.githubusercontent.com/assets/16419592/13459876/37673662-e0ba-11e5-9a4c-757c2aaacb33.jpg)

※補助的な扱いに見えるように、pulldown内のテキストサイズも小さくしています。

**Comment by ucksts** [comment]
あと、kz0817さんからもコメントいただいておりますが
積極的に操作してもらうボタンなので高さを他ボタンよりも大ぶりに変更しています。


もし、フィルタの一本化が叶うならば（絞り込みオプション内から削除しつつ）
この位置に置くのが好ましいと考えております。
※こちらは後日検討、ということでひとまずのサンプル画となります。

![hatohol1604_event_summary_c0302_all](https://cloud.githubusercontent.com/assets/16419592/13459989/072a43f8-e0bb-11e5-926a-4d4fd5fce124.jpg)

**Comment by ucksts** [comment]
**タイトル行  デザイン別案**

タイトル行に"イベント"という言葉が連呼されており、
もう少し省略できそうでしたので、ラベルを見直した別案を検討してみました。

前案と比べていかがでしょうか。

![hatohol1604_event_summary_c0303_navi](https://cloud.githubusercontent.com/assets/16419592/13481373/849d98cc-e128-11e5-901e-0d1192f744ed.jpg)

**Comment by kz0817** [comment]
> 前案と比べていかがでしょうか。

提案ありがとうございます。かなりすっきりしてて、前のより好きです。

**Comment by ucksts** [comment]
ありがとうございます。それではこちらをベースに進めてまいります。

**Comment by kz0817** [comment]
> もし、フィルタの一本化が叶うならば（絞り込みオプション内から削除しつつ）

それをやると、コンセプトがだいぶ変わってしまうと思います。

サマリ部分は、今システムに障害があるかどうかを、迅速に知るために
使用することを想定しています。ですので、サマリ部のフィルタ（上記のキャプチャで
「全て（３６５日間）」は、それほど頻繁には変更されないと想定しています。
この想定からすると、フィルタ目立たなくするとかいっそ、隠してもいいかもしれません。

一方、下のテーブルは、絞り込み条件を変えながら、インタラクティブに
イベントの発生状況を理解することを目的に設置しています。ですので、
こちら側のフィルタは、予め想定される条件を設定しておき、より効率的な
絞り込みを行うために使用します。

**Comment by ucksts** [comment]
テーブル部のフィルタが、より頻繁に利用されるわけですね。失礼いたしました。
上記デザイン案のサマリ部のプルダウンは視覚的にかなり控えめになっていると思いますので、
一応は"残す"かたちで、後日、不要であれば、隠すということでいかがでしょうか。

**Comment by ashie** [comment]
サマリ部のフィルターはもともとの仕様案には存在しなかったのですが、私の独断で追加しました。
（無いと何の値を示しているのかよく分からなかったため）
なので相談の上削除の方向性もありだと思います。

**Comment by kz0817** [comment]
> 一応は"残す"かたちで、後日、不要であれば、隠すということでいかがでしょうか。

じゃあ、その方向でいきましょう。

**Comment by kz0817** [comment]
修正がマージされたのでクローズ
