### ISSUE TITLE
登録済みのインシデント設定の編集時，「ステータス」の設定が反映されない

### ISSUE THREAD

**Issue by Mnakagawa** [project-hatohol/hatohol#2007]
![a](https://cloud.githubusercontent.com/assets/7106792/12836445/55d13382-cbfc-11e5-9642-01d7ad4cb1de.png)

登録済みのインシデント設定を編集する際，他の項目では現在の設定内容が反映されているが，
「ステータス」項目だけ現在の値が何であれ初期値が「障害」となる。
（Ex. 監視サーバーの設定は「ANY」のため，「条件」ウィンドウの「サーバー」は「ANY」が初期値。
「ステータス」以外の項目は全て同様に現在のステータスが初期値となっている）

他の項目同様，「ステータス」項目も現在の値を初期値としたい。

**Comment by Mnakagawa** [comment]
全てANYの状態からサーバーの値だけ変えたかったのに，
いつの間にかステータスの値が障害になっていた，という想定しない設定になる可能性があるため，

**Comment by ashie** [comment]
デフォルトだけを障害になるようにしていたつもりが、常に障害になってしまっていた...

**Comment by ashie** [comment]
今はDB初期化時にANYで設定するようにしているので、GUIの方もデフォルトANYに変更する。
(インシデント設定での特別扱いをやめて普通のアクションと同じにする)

**Comment by ashie** [comment]
別のバグを見つけたかも?
masterで試したらこの画面でインシデント管理サーバが空になっている。

**Comment by ashie** [comment]
ちがう、必要なコードまで消しちまってた...

**Comment by Mnakagawa** [comment]
Fixされたのでクローズ
