### ISSUE TITLE
[WebUI] トリガー画面のテストが環境によっては通らないことがある

### ISSUE THREAD

**Issue by ashie** [project-hatohol/hatohol#2009]
以下のどれかで発生するようになったようだ。

https://github.com/project-hatohol/hatohol/pull/1995/files
https://github.com/project-hatohol/hatohol/pull/1993/files
https://github.com/project-hatohol/hatohol/pull/1992/files

原因は動的に変更している属性を含むHTMLを静的なHTMLでマッチさせようとしているため。

**Comment by kz0817** [comment]
#1983の作業の中でも気になったので、私が担当します。
対応方針は、正規表現でのマッチにして、スペースが有無などの違いを許容します。

**Comment by cosmo0920** [comment]
#2030 をマージしたのでクローズ。何かまだ問題があるなら再オープンしてください。

**Comment by ashie** [comment]
手元では属性の順番が変わってしまって正規表現では吸収しきれていないのでReopenします
