### ISSUE TITLE
create-db.sqlはhatohol-serverには必要かどうか

### ISSUE THREAD

**Issue by Mnakagawa** [project-hatohol/hatohol#2014]
現在，hatohol.spec.inではhatohol-serverパッケージにcreate-db.sqlファイルを追加している。
しかしこのcreate-db.sqlは私の確認した範囲ではtravisでのテストにしか使用されていない。
specファイルからは削除しても良い？

**Comment by Mnakagawa** [comment]
travis周りといえば @cosmo0920 さんなイメージがあるのですが，どう思いますか？

**Comment by cosmo0920** [comment]
お、このSQLファイルでhatoholのデータベースとテスト用のユーザーを作っているんですね。
僕が作業する分には構いませんが、他にできる人が居た方が良いと思うので余裕があれば @Mnakagawa さんもTravis周りを見られるようになってみませんか？

**Comment by Mnakagawa** [comment]
ですね。見れるようになりたいです。
今回の件で言えばおっしゃるようにテスト用なので，Makefileに記載があることには納得なのですが，
PMからインストールし，Hatoholを使用する際には不要なのではないか？という確認がしたかったのです。

**Comment by Mnakagawa** [comment]
作業については，ちょうど今db-initiator周りの修正をしていて，sqlファイルあたりをいじっているので
私の認識が正しければそこでspecからは削除しようかなと思っています。

**Comment by ashie** [comment]
Fixed in #2022
