### ISSUE TITLE
オートリロード時のイベントページのフィルタ適用抑制が完全ではない

### ISSUE THREAD

**Issue by cosmo0920** [project-hatohol/hatohol#2016]
下記の丸をつけたセレクトボックスが有効になっている場合、

![screenshot from 2016-02-09 09 51 42](https://cloud.githubusercontent.com/assets/700876/12904432/ed06dedc-cf12-11e5-9cf9-b38b8f90e9a8.png)

オートリロード時に以下のクエリを発行してしまう：

![screenshot from 2016-02-09 09 52 59](https://cloud.githubusercontent.com/assets/700876/12904476/1de7cc32-cf13-11e5-95cb-299f5fc78222.png)

**Comment by cosmo0920** [comment]
トリガー画面のフィルタのオートリロード時の適用抑制 #2013 の作業をしていた時に見つけたので PR #2013 でも同様の問題がある。

**Comment by cosmo0920** [comment]
再現頻度が低くなってしまった…orz

**Comment by ashie** [comment]
再現できないし、コード的にも発生するように見えない。
いったんcloseし、再現したらreopenする。
