### ISSUE TITLE
WebUIのBrowserテストで、画面の下に要素が残っていて美しくない

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#2027]
<img width="480" alt="2016-02-12 12 10 34" src="https://cloud.githubusercontent.com/assets/2610513/12997978/bfd2eb1a-d181-11e5-85e6-6af9f6db1876.png">

**Comment by ashie** [comment]
基本的にはテストが終わったら削除するようにしている。
犯人はSeverityRanksViewのテストっぽい。
個別に実行してみたらこのテストで上記スクリーンショットの要素が残った。
