### ISSUE TITLE
[hap2_zabbix_api] 無効化したホスト，トリガーが表示される

### ISSUE THREAD

**Issue by Mnakagawa** [project-hatohol/hatohol#2029]
私の認識では，現在のAPI，またHatoholサーバーの実装では無効化(削除)された
ホストやトリガーはHatoholのUI上からも見えなくなるはずなのだが，残るという話を耳にした。
本格的に調査するという意味でIssueとして立てる。

**Comment by Mnakagawa** [comment]
現在の実装だとホストにしろトリガーにしろ，残ってしまうことが判明した。
hap2.zabbixapiは問題なく，無効化されたホストやトリガーは取得していないのだが，
どうもHatoholサーバー側が，無効化されたホスト，トリガーを削除していない。

**Comment by Mnakagawa** [comment]
例えばトリガーだが，監視サーバー一覧のページに「監視サーバートリガー再読み込み」という項目がある。
これを実行した場合，私の想定ではDB内のトリガーを一度削除し，取得したものを再度登録するため，
無効化したトリガーは非表示になると思っていた。
だが実際のところ，同じIDを持つトリガーをアップデートしているだけなので，無効化したトリガーが残ってしまう。

**Comment by Mnakagawa** [comment]
ホストに関しても，zabbixAPI上は問題なかったが，ホスト一覧を貰ったHatoholサーバーは
貰ったホストの情報をアップデートしているだけであった。

**Comment by Mnakagawa** [comment]
なので，ホストの場合は受け取るたびに既存のホスト一覧の削除，
トリガーの場合も同様に削除してから登録し直す必要がある。

**Comment by Mnakagawa** [comment]
という仕様でHatoholサーバーの変更をしても大丈夫でしょうか。
なにかに影響が出る？

**Comment by ashie** [comment]
> なので，ホストの場合は受け取るたびに既存のホスト一覧の削除，
> トリガーの場合も同様に削除してから登録し直す必要がある。

全部削除して全登録を想定していますか?
であれば、差分だけを登録or削除すべきだと思います。

Hatoholサーバ的には一応下記のようにトリガーの更新と同期を分けて頑張ろうとはしています。
(addTriggers()はupsertの筈なので追加だけでなく既存トリガーの更新も行う)

Hatohol
```
	if (checkInvalidTriggers) {
                dataStore->syncTriggers(triggerInfoList, serverInfo.id,
                                        lastInfoUpserter);
        } else {
                dataStore->addTriggers(triggerInfoList, lastInfoUpserter);
        }
```

期待通り動いていないのであればバグなので修正する必要があります。

**Comment by ashie** [comment]
> ホストに関しても，zabbixAPI上は問題なかったが，ホスト一覧を貰ったHatoholサーバーは
> 貰ったホストの情報をアップデートしているだけであった。

> なので，ホストの場合は受け取るたびに既存のホスト一覧の削除，
> トリガーの場合も同様に削除してから登録し直す必要がある。

HAPI2の仕様的にはupdateTypeで見分けるようなので、それの受け渡しが実際の動作では
どうなっているかというところもチェックしないと、どこの問題なのか特定できていないと
思います。

**Comment by Mnakagawa** [comment]
> 期待通り動いていないのであればバグなので修正する必要があります。

恐らくバグではないでしょうか。余裕があればそちらでも確認していただければと思います。
上であげた例の場合，hap2からはALLオプションで送信するようになっているはずです。

また，hostsに関しては決め打ちで”ALL”で送っています。

**Comment by Mnakagawa** [comment]
と思ったけど，「監視サーバートリガー再読み込み」で，hap2からHatoholサーバーにトリガーが送られてないっぽい…？

**Comment by Mnakagawa** [comment]
> 期待通り動いていないのであればバグなので修正する必要があります。

期待通り動いていました！すみません！！！！

ホストの方はもう少し調査します。

**Comment by Mnakagawa** [comment]
ホストの方はsyncHosts関数に入ってますし，送られてきたホストも減っているのに
更新されていない模様。

**Comment by Mnakagawa** [comment]
> 更新されていない模様。

またまた勘違い。。。
server_host_defみたら,無効化したホストのstatusはきちんと1（REMOVED）になってました。
ということは問題は，WebUIからのリクエストを受けて，DBからデータを参照するselect文かな

**Comment by Mnakagawa** [comment]
色々と調査してて思ったけど，監視対象からのデータの一連の流れ全てをチェックするとなると
確認範囲がかなり広い。

**Comment by ashie** [comment]
> ということは問題は，WebUIからのリクエストを受けて，DBからデータを参照するselect文かな

確かにHOST_STAT_ALLがデフォルトで

https://github.com/project-hatohol/hatohol/blob/master/server/src/DBTablesHost.cc#L404

とくに絞り込んでいないようだ。

https://github.com/project-hatohol/hatohol/blob/master/server/src/RestResourceMonitoring.cc#L337

ダッシュボードの方は絞りんこでいる。

https://github.com/project-hatohol/hatohol/blob/master/server/src/RestResourceMonitoring.cc#L180

**Comment by ashie** [comment]
意図的なのか単に忘れただけなのかがよくわからない。

**Comment by Mnakagawa** [comment]
ぱっとみなんですけど，setStatusで一つのステータスしかセットできないから，
NORMALとSELF_MONITORの2つが必要なフィルター部分ではこのままでは使用できなさそう

**Comment by ashie** [comment]
たしかにそんな気がする。

**Comment by Mnakagawa** [comment]
74dfdfe3be8ae
こんな感じで何とか。。。

**Comment by ashie** [comment]
ちとやっつけ感が...
クエリオプション追加する方が良いです。

原因は分かりましたし、修正は私のほうで引き取りましょうか?

**Comment by Mnakagawa** [comment]
いえ，そこまでタスクもないのでやります。
このあたりほとんど触ってなかったので勉強がてら

**Comment by ashie** [comment]
了解です。

**Comment by Mnakagawa** [comment]
自分でやるといっておいてなんなのですが，あまり自信がないので相談させてください。
現在impl->statusにHostStatusを保持していますが，これをHostStatusのvectorにして，
取得したい複数のHostStatusを保持しておくという手法で大丈夫でしょうか。

**Comment by ashie** [comment]
はい、それで良いと思います。

もうひとつ考えられるのは、デフォルトで削除されたホストは除外する条件を差しこむようにしておいて、
caller敢えて取ろうとしたときだけその条件を外すという方法もあると思います。

**Comment by cosmo0920** [comment]
`std::set<T>` で保持するようにしてみるのはいかがでしょう。Statusの値を重複して保持しても良い事はないはずなので。

**Comment by Mnakagawa** [comment]
> もうひとつ考えられるのは、デフォルトで削除されたホストは除外する条件を差しこむようにしておいて、
caller敢えて取ろうとしたときだけその条件を外すという方法もあると思います。

他の部分への影響度の少なさ的にもこの方法は良さそうに見えます。
コレでやってみようと思います。

**Comment by Mnakagawa** [comment]
> std::set<T> で保持するようにしてみるのはいかがでしょう。Statusの値を重複して保持しても良い事はないはずなので。

確かに重複しても意味無いですもんね。
今回は配列を用いた方法は使用しませんけど，知らないことだったのでありがとうございます！

**Comment by kz0817** [comment]
ちょっと気になったんのでコメント。
ソースのコメントにあるように元々は、イベント画面で、
過去のイベント参照の際、ホスト名がきちんと
表示される様にするために、HOST_STAT_ALLを意図的に
していました。いま、イベントテーブルにホスト名って
入るんでしたっけ？そうなら、上のパッチのHOST_STAT_NORMAL
に変更するのは妥当ですね。
<pre>
  	// This is a workaround to show host name that was deleted in the
  	// Event page. We should save host name in Event table.
 -	option.setStatus(HOST_STAT_ALL);
 +	option.setStatus(HOST_STAT_NORMAL);
</pre>

**Comment by ashie** [comment]
今は仕様上も実装上も曖昧な状態かもしれませんが、基本的にはイベントのhostNameは極力埋めよう
という方針で動いていたものと認識しています。

* HAPI2.0の仕様では`putEvents`の`hostName`はOptional: https://github.com/project-hatohol/HAPI-2.0-Specification#puteventsmethod
    * とはいえプラグインが`putHosts`でホスト情報を送ってくる保証もない
    * 現実的にはサーバやWebUI側は以下のような実装にすべきか
        * putEventsにhostNameがセットされていればそれを使用する
        * 上記が無い場合、putHostsでホスト情報が送られてきていればそれを使用する
        * どちらも無い場合はホスト名がセットされていない旨を表示する
* Hatoholに同梱されているプラグインは全てhostNameを付けて`putEvents`している
* HatoholArmPluginGateHAPI2では、`putEvents`の`hostName`はmandatoryとしてパースしている（バグ）。
    * 結果的に`hostName`がついていることは実装では保証されている。
* HatoholArmPluginGateJSONではイベントの`hostName`は必須
* WebUIではイベントの`hostName`は見ないでputHostsで送られた`hostName`のみを見ている。
    * これは上記方針で直した方が良さそう。

WebUIのイベントやトリガーのホスト名表示の実装さえ直せば

> いま、イベントテーブルにホスト名って
> 入るんでしたっけ？そうなら、上のパッチのHOST_STAT_NORMAL
> に変更するのは妥当ですね。

削除されたホストは除外するという方針で良さそうに見えます。

**Comment by Mnakagawa** [comment]
Fixed it so close.
