### ISSUE TITLE
イベント画面にてバグ？

### ISSUE THREAD

**Issue by Mnakagawa** [project-hatohol/hatohol#2037]
![a](https://cloud.githubusercontent.com/assets/7106792/13065980/2cb76f78-d4a5-11e5-8ddb-17a9088f7048.png)

現行のmasterにて，画像のようなバグが出てイベントが表示されなくなった。
何か心当たりある人いますか？

**Comment by ashie** [comment]
このイベントのstatusの値ってわかります?

C++側にはTRIGGER_STATUS_UNKNOWNというのが定義されているけど、JavaScript側には
無いので、それのラベルをセットできなくて止まってるのではないかと思う。

**Comment by ashie** [comment]
あとイベント画面の設定で「現在のトリガーステータス」を表示するようにしてますか?
これを表示するようにしていて、かつTRIGGER_STATUS_UNKNOWNなイベントがあったら
この問題が発生するんじゃないかと思います。

**Comment by Mnakagawa** [comment]
ステータスは2のものがありました。
また，おっしゃるように現在のトリガーステータスも表示するようにしました。

**Comment by ashie** [comment]
#2039 で修正パッチ投げました。

**Comment by cosmo0920** [comment]
マージされたのでクローズ。問題がまだあるようなら再オープンしてください。
