### ISSUE TITLE
フィルタのセレクトボックスのデザインの方向性の相談

### ISSUE THREAD

**Issue by cosmo0920** [project-hatohol/hatohol#2040]
現時点でのHatoholのWebUIのセレクトボックスはHTMLの標準のものを使っています。
例えば、[bootstrap-select](https://silviomoreto.github.io/bootstrap-select/examples/)を使えば複数選択可能なセレクトボックスにしたり、入力フォーム付きのセレクトボックスにすることが可能です。

例えば、入力フォームにキーワードを入れるとセレクトボックスの選択肢が絞り込まれていくようにすることも可能なので、余力があれば行いたいです。

**Comment by kz0817** [comment]
いいんじゃない。

**Comment by cosmo0920** [comment]
了解です。他のjQueryUIのモーダルをBootstrapのモーダルに置き換えられればコレも使えるようになるので、Bootstrapに置き換えるとこんなに良いことがあるよ！という目標になりそうだったので提案してみました。

**Comment by cosmo0920** [comment]
#2058 ではトリガーのフィルタについてboostrap-selectでライブサーチを実装してみたが、実はイベント画面のフィルタにも移植してみるべきかもしれない。

**Comment by cosmo0920** [comment]
現時点ではトリガーのページのフィルタには以下のようなデザインが当たっている。

![screenshot from 2016-03-04 17 12 45](https://cloud.githubusercontent.com/assets/700876/13521508/773b4206-e22c-11e5-9b7c-715d465fd2b5.png)

![screenshot from 2016-03-04 17 12 51](https://cloud.githubusercontent.com/assets/700876/13521519/897705a4-e22c-11e5-99a5-2e1c2ce1b7c8.png)

**Comment by cosmo0920** [comment]
こちらトリガーのページに関しては既にmasterに変更が入っています。

@ucksts さん、トリガーのページとイベントのページのフィルタのUIに関してデザインのレビューをお願いできますか？

**Comment by ucksts** [comment]
並行となりますが、現在イベントのページについて、
テーブル部分の表示領域をより確保するための調整を行っています。

まずは、トリガーの「絞り込みオプション」部分のみ、
デザイン的な調整をお願いできればと思います。
（タイトル部分や更新ボタン位置やデザインについては後日またご連絡させてくださいませ。）

１）天地方向のスペース調整
　イベント側に合わせて、以下の２箇所の天地スペースを詰めていただけますか
![tigger_option_01](https://cloud.githubusercontent.com/assets/16419592/13545587/5b0ccf48-e2d4-11e5-9417-8ffaf705e793.jpg)

２）左右方向のスペース調整
　こちら２箇所も、20px相当のスペースを確保してください
![tigger_option_02](https://cloud.githubusercontent.com/assets/16419592/13545592/714fa53c-e2d4-11e5-8cd8-7fbe4bf4cc7e.jpg)

３）あと、監視サーバ　＞　グループ　＞　ホストは
従属関係にあると思うので、触れないセレクトボックスは
グレー背景にして操作を抑制すると直感的かと思いますが、設定可能でしょうか
![tigger_option_03](https://cloud.githubusercontent.com/assets/16419592/13545606/e0faafa8-e2d4-11e5-8e61-c9172d77b125.jpg)


どうぞ宜しくお願いいたいます。

**Comment by Mnakagawa** [comment]
@cosmo0920 さん
このIssue，完了していますか？

**Comment by cosmo0920** [comment]
完了しています。と言うことで、クローズします。
