### ISSUE TITLE
[WebUI] ブラウザクローズの誤操作防止

### ISSUE THREAD

**Issue by ucksts** [project-hatohol/hatohol#2052]
Hatoholログイン中に、ブラウザウインドウを"クローズ"をしようとすると、
アラートのダイアログを表示することで誤操作を防止したい。

■ブラウザデフォルトのダイアログをJavascriptで表示する
参考サイト：https://employment.en-japan.com/signup/

表示する文言はこちらでいかがでしょうか。
"Hatoholがシステム監視中です。
このページから移動してもよろしいですか？"
[ このページにとどまる ] [ このページから離れる ]

サンプルデザインはこちら
![browser_close_alert](https://cloud.githubusercontent.com/assets/16419592/13133902/9a1279ec-d643-11e5-8905-8eb30d826032.png)

**Comment by kz0817** [comment]
こちらもほぼ想定どおりです。
コードができたら、プルリクエストお願いします。

**Comment by ucksts** [comment]
ご確認ありがとうございました。完了後、pull requestいたします。

**Comment by mmikan22** [comment]
https://github.com/project-hatohol/hatohol/pull/2132
branch issue#2052-close-defender にて主機能の開発はしたものの、起動条件の精査が必要になったため、保留となった。

**Comment by mmikan22** [comment]
こちら、アラートを出す方針、決定しましたでしょうか？

**Comment by ucksts** [comment]
@mmikan22 さん
一度、課題やPR時にいただいたフィードバックを棚卸し、
UIとしての方針をすり合わせしましょう。

**Comment by ucksts** [comment]
@kz0817 さん
@tksmatsunaga さん

誤ってブラウザを閉じてしまう操作を防止する機能の
起動条件について、改めて、ご相談させてください。
（静観してしまい、申し訳ございません）

以前にkzさんより、PR時にフィードバックいただいた[２点のご指摘](https://github.com/project-hatohol/hatohol/pull/2132#issuecomment-193526811)について、
完全な問題解決を行おうとした場合は、専用アプリやプラグイン開発の範疇となり、
フロントエンド側のみでの対応が難しいというのが、正直なご返答となります。

誤操作を徹底して100%防ぐところまで至れないのは残念ではありますが、
例えば、大半を防止することができれば「概ねOK」と捉えていただくことはできないでしょうか。
CPU負荷やページングなどで遅延が発生した場合には、
当然"漏れ"も生じうることが予想されますが、
あくまでフォローアップのための機能なので、いくらかでも防止につながればという考え方です。


また、同窓遷移時にアラートを出さない２つの具体的な方法をサジェストいただきました。

> 意図された遷移を許可するのであれば、そのリンクの実行時などに明示的に許可フラグをセットするほうが確実

> メニューのところに許可フラグを設定する仕組みをいれるか、このパッチ自身をそこらへんと統合してもいいかかも

技術的にはご対応可能なのですが、Hatohol全体を把握しているわけではないので、
こちらで『どの要素』の『どのイベント』に紐付けるかが不明であることが、不安要素になります。
例えば、
「ヘッダーメニュー内のAタグすべてのclickイベント」に、
許可フラグを適用する方法ではいかがでしょうか。

どうぞよろしくお願いいたします。

**Comment by kz0817** [comment]
> 例えば、大半を防止することができれば「概ねOK」と捉えていただくことはできないでしょうか。

この考えには同意です。100%抑止できなくても、このような機能を搭載する意味はあると考えています。

ただ、これまでの本プロジェクトの開発では、時間など様々な制約がある中でも最大限、最善と思われる方法で新機能開発や拡張を行ってきました。時間を要するかもしれないけれども、よりよいと考えられる方法がある場合、基本的にはそちらを選択してきました。そのようなやり方ですので、必ずしも当初計画したスケジュールで進められないこともあります。その場合は、次のリリースに持ち越したり、一部の機能のみを実装しています。

最初のPRにおいては、そういう思いや文化に対して、実装が非常にアドホックに感じました。また、上記の「Hatohol全体を把握しているわけではないので」という意見に対しても、「じゃあ、把握すればいいじゃん」って思いました。だって、そっちのほうがよい実装をできる可能性が高まると思うんですよね。そもそも、Hatoholはオープンソースですので、すべてのソースコードは入手できますし、UIのメニュー部分のソースコードも数百行〜数千行程度とそれほど大規模というわけではありません。分からないところがあれば、Issueなどで聞いていただければ、私を含めたコミュニティのメンバーもできるかぎり対応します。
「不安要素」があるというのは、ソフトウェアエンジニアとして、非常によくわかります。だからこそ、PRで開発コミュニティのメンバがチェックする体制がとられています。コードの問題を指摘することは当然ありますが、PRしていただけることにはみな感謝しています。
ですので、ベストな提案をお待ちしています。スケジュール等の制約が懸念される場合、別途話し合いましょう。

**Comment by ucksts** [comment]
> この考えには同意です。100%抑止できなくても、このような機能を搭載する意味はあると考えています。

ご賛同ありがとうございます。
また、思いや思想の斟酌が足りず申し訳ありません。
（ご迷惑をおかけしないがための発言としてご容赦ください。）
本実装の遅延もあって、なる早での完了をと焦る気持ちも正直ございますが、
先にご提案した内容をベースに、よい改善の方法がないか模索してみます。

**Comment by ucksts** [comment]
旧案の[setTimeoutを使った手法](https://github.com/project-hatohol/hatohol/pull/2132)ですが、マークアップ・フロントエンドエンジニア界隈において
オールドブラウザ時代から20年以上の実績があり、
今後hatoholの仕様が変わったとしても、永く耐えうるスタンダードな手法として、
mmikan22氏よりご提案させていただいておりました。

ただ、setTimeout等による不安定さのご指摘もありましたので、「誤操作でない条件」を明示的に設定する新案を検討しました。
上部メニューのソース精査の結果ですが、Aタグのクリック（またはクリック相当のキー操作）時に
「これは画面遷移であり、ブラウザのクローズ誤操作ではない」という判定を与えることが、
有効であると思いますので、新案ではこの考え方をベースに、できるだけ漏れのない仕様を検討しました。
（細かい条件の策定内容は後述いたします）

**Comment by ucksts** [comment]
まず、ブラウザのｘボタンやキーボードショートカットでのクローズは絶対アラートをあげることが主目的です。
ただし、Hatohol上での操作によるページ遷移などでアラートが上がることは避けたいため、『誤操作でない条件』を以下のように設定し、条件を満たしたときにこのアラート機能の動作をOFFにするようにします。

＝＝＝＝条件＝＝＝＝
すべてのAタグのクリック、またはクリック相当のキー操作時に、

以下の条件のうち１つ以上を満たし、
・Shift・Alt・Ctrlを押していない（任意の別窓遷移）
・Aタグのhrefが存在しない（遷移しない）
・Aタグのhrefに#が含まれている（ページ内遷移）

さらに以下の条件を１つ以上満たす
・Aタグのtargetが不在、値なし（target=""）、_top、_self、window名と同じの場合
（同窓遷移であることを示す）
＝＝＝＝条件ここまで＝＝＝＝

これで基本的に、hatohol内での同窓遷移、別窓遷移、ダイアログでの設定変更、で
誤ってアラートが出てしまうことは概ね防止できます。

念のため、以下のシビアコンディションでは漏れが生じる可能性が残りますが、
ケースとしてはごくわずかであり、必要十分な機能として、ほぼ満たせていると考えております。
・Aタグクリック後、次のページの読み込みが始まるまでの誤操作
・Aタグクリック後、読み込み中止をした後、再読み込みするまでの誤操作
・通信状況やサーバのファイル構築遅延によりブラウザがJSの読み込みができていないタイミングでの誤操作


こちらの内容でよろしければ、一旦プルリクエストに進めたいのですがいかがでしょうか。
どうぞ宜しくお願いいたします。

**Comment by kz0817** [comment]
提案ありがとうございます。
よく見てみますが、第一印象はheuristicで複雑な感じですね。

**Comment by kz0817** [comment]
Aタグを使った方法ですが、棄却します。

理由は、複雑だからです。
ポイントは、ご指摘のように「誤操作でないこと」の検出です。
以前、私がコメントしたように、HatoholのUIのおける意図されたページ遷移は、決められた操作（メニューの選択など）のみで発生します。その操作をもって、誤ったページ遷移でないとするのもが最もシンプルで確実と考えられます。

**Comment by ucksts** [comment]
@kz0817 
承知しました。一旦検討し直してみます。

**Comment by ucksts** [comment]
@kz0817 さん

引き続き、実装の方針についてご相談になります。

（A）上部メニューを操作した際に、同ドメイン下での
/
/ajax_events
/ajax_triggers
/ajax_latest
などへ遷移するケースのみをシンプルに指定して、除外したらよいのでは？という
kzさんからのご指摘かと存じます。

（B）ただ、一見シンプルなのですが、それでは対策が十分ではなく、
以下のケースにおいても、誤ってアラートダイアログが表示されてしまい、
ユーザーからするとたいへん煩わしいUIに感じられると思います。
- #table内のリンク（同窓/別窓）
- ログアウト時
- パスワード変更ボタン
- ユーザー情報edit時のボタン
- その他のJS内に散見するリンク（同窓/別窓）

そのため、上記の(A)と(B)の箇所を両方とも防ぐ目的で、
ややシンプルではないのかもしれませんが、
■ setTimeoutを使用した初案
■ Aタグを使用した第２案
を今後、hatoholの機能の増強が生じても、比較的カバーのしやすい
ベスト、ベターな手法としてご提案差し上げておりました。
（当初の説明が言葉足らずで申し訳ありませんでした）

一周ぐるっと元に戻ってしまうのですが、AタグのNGを受けまして
実績もあり、より漏れの少ない「 setTimeoutを使用した案」で進めさせていただく
ことはできないでしょうか。

以下に、hatoholで使われている同窓/別窓遷移のリンクをひとおり精査した調査結果を添付させていただきます。
[Hatoholリンク調査_201603280107.txt](https://github.com/project-hatohol/hatohol/files/191269/Hatohol._201603280107.txt)

どうぞよろしくお願い致します。

**Comment by kz0817** [comment]
> ■ setTimeoutを使用した初案

これって、「何でもいいからクリックがあった直後の遷移は意図したものだ」っていう考えに基づくアルゴリズムですよね。
- 「何でもいい」ってところは、やはり引っかかります
（ほんとに意図したものだけ抽出するの？っていうのと、コメントしたように将来イベントバブリングが止められることがないなかという点に懸念があります）
- 「直後」っていうのを非リアルタムOS（加えてブラウザ内）で検出するのは難しいですよね。結局、setTimeoutを使うにしてもそのパラメータって1なの10なの100なの、どれがいいのかという疑問が残ります。それに、タイマハンドラが呼び出されるタイミングって、かなりブラウザ依存じゃないですか。

**Comment by ucksts** [comment]
ご質問への回答をコメントいたします。

----------------
Q.意図したものだけ抽出されるのか？

現在は、当方で想定されるあらゆる事象の中で、対応可能なものをできるだけ対策する、という実装方針となります。
きっちり意図したものだけの抽出は可能です（ただし別途、効果範囲の定義が必要となります）

----------------
Q.将来イベントハブリングが止められることがないか？

作成したJS内に意図的にバブリング停止処理を入れることまで視野にいれるならば、
可能性は0ではありません。

----------------
Q.「直後」の検出は非リアルタイムOS（加えてブラウザ内）では難しいか？

フロントエンドの実装であるため、必ずブラウザに依存することになりますので、
正直なところを申し上げれば、難しいと思います。

タイマーがある程度不安定なことは否めませんが、ブラウザの仕様上『何もしないを検知するイベント』は存在しないので、イベントごとのsetTimeoutでの制御が好ましいと考えております。
あるいはsetIntervalやonmousemoveなどで常時フラグを制御する方法もございますが、
そちらの方が負荷が高くなるため採用しづらいです。

----------------
Q.パラメーターの1,10,100の想定（最適値は？）

負荷への影響は検証が必要ですが、低ければ低いほど確実性は担保できます。
なお、1という設定は厳密な1msではなく、ブラウザの処理上できるだけ早く、となります。

----------------
Q.タイマハンドラが呼び出されるタイミングはブラウザ依存？

はい。ブラウザに依存となります。
その他、閲覧ページの状態（アラートが開きっぱなしになっているなど）、
OS、端末のコンディション、その他ユーザーの行動などにも影響されます。

----------------


正直なところ、危惧されているブラウザ依存については、今のところフロントエンドだけでの対策は難しく、
アドオン開発など、違う形での実現を目指した方が良いのかもしれません。。

最初のご提案時に比較的ライトに実装できそうな気がしていたのですが、
副作用の精査不足でございました。申し訳ございません。

**Comment by ashie** [comment]
あまり議論を追えていなかったけど、

> 「Hatohol全体を把握しているわけではないので」という意見

この懸念というのは、要はサイト内リンクを全部抽出できるかどうかが分からないということですかね?
ざっと見てみました。

* hatohol_navi.jsで生成しているリンク
* 「トリガー」ページ内の「名前」でイベントページに飛ばしているリンク
* 「最新データ」内のグラフページへのリンク
* 「設定」->「グラフ」でのグラフ設定作成や編集時の遷移

たぶん、以上だと思います。
（もし漏れがあったら気がついた時に修正すれば良いと思います。）

他はサイト外リンクで、基本的には別タブで開いているようです。
「ヘルプ」->「オンラインドキュメント」が別タブではなくて遷移してしまうけど、これは他のサイト外リンク
と合わせてtarget属性を追加して別タブで開くように修正すべきです。

**Comment by ashie** [comment]
あと、まだ存在していないですが、イベントのサマリー部分のリンクもサイト内リンクで実装する予定。
（以下のブランチ）

https://github.com/project-hatohol/hatohol/tree/issue-%232184-events-view-summary-link

**Comment by kz0817** [comment]
transitionManagerみたいなオブジェクトを作っておいて、
最初のPRのif (beforeUnloadFlag && !$('#hatohol_login_dialog').is(':visible'))を
if (transitionManager.isUnloadAllowed())みたいな感じにするのはどうか。

login dialogうんぬんも、このオブジェクトの中で処理したほうが、
細かいところを隠蔽できる。

**Comment by ucksts** [comment]
@kz0817 さん
@ashie さん

手法について議論中のところ申し訳ございません。
「hatoholがどのような状態であるか」についてバックエンドからの
返り値を取得できるようなJS関数をご用意いただければ、
setTimeoutや、Aタグを用いた方法でなくとも、誤操作だけを検出できそうです。

エンジニアと会話しまして、JS関数からの返り値に関する要望をまとめましたので、
開発の現実味がありそうかどうかのご相談をさせていただけますでしょうか。

（恥ずかしながらバックエンドへの理解が不足しており、
できること/できないことのイメージがついておらず、申し訳ございません）


**■期待する返り値
**
期待する戻り値としては、至極単純なもので
『誤操作の是非』という情報をブラウザが閉じる寸前で正確に取得できれば良いと
考えております（場合分けも不要かもしれません）。

A）最善手
『閉じるボタンやキーボードショートカットでブラウザが閉じられようとしている』
というステータスを返り値として取得することは、バックエンドで実現可能でしょうか？

B）次善手
『Hatohol内での操作か、否か』というステータスを返り値として取得は可能でしょうか。
また、例えば、下記のリストのように『どんな操作があったか？』のような情報でも、
内容決めうちであれば、判定への活用は可能です。

- 上部メニューを操作して遷移した
- #table内のリンクを押下した
- なんらかのボタンを押下した
- ログアウトしている状態
- ユーザー情報をedit中の状態

**■返り値の文字列**
単純な「真偽値」ですとたいへん助かりますが、
仕様詳細についておうかがいできるなら、文字列でもオブジェクトでも対応可能となります。


開発でお忙しいところ恐れ入りますが、
新たなJS関数について、ご検討いただくことは可能でしょうか。

@mmikan22 　上記、不足があれば指摘ください。

**Comment by kz0817** [comment]
> 『閉じるボタンやキーボードショートカットでブラウザが閉じられようとしている』
> というステータスを返り値として取得することは、バックエンドで実現可能でしょうか？

ちょっと調べてみますが、難しいんじゃないでしょうか。
そのようなイベントに対して、指定したコールバック関数を呼び出す
イメージでしょうか？
受動的に返すとしたら、たまたま、そのタイミングで読み出さないと
閉じられちゃいますよね。読みだすタイミグをクローズなどのイベントで
ファイヤさせるとすれば、そもそも、このような関数不要ですよね。

> 『Hatohol内での操作か、否か』というステータスを返り値として取得は可能でしょうか。
それは、できます。
上に書いたようにinternalStatusを管理するオブジェクトを作って、内部の特徴的な動作
（メニューを操作するなど）ごとに、ハンドラを登録できるようにすると汎用的でいいかな。

**Comment by kz0817** [comment]
> HatoholのUI独自のイベント（メニューを操作するなど）に対して、ハンドラを

Eventという名前を使うと、監視のイベントと混乱するから、
オブジェクトの名前は、HatoholTracerがいいか。

**Comment by ucksts** [comment]
ご返答ありがとうございます！
エンジニアとともにコメントを確認させていただきました。

> ちょっと調べてみますが、難しいんじゃないでしょうか。

ブラウザが閉じられようとしているタイミングでの返り値は難しそうである旨、
承知いたしました。

> むしろ、能動的に取得するより、内部状態を管理するオブジェクト（HatoholTracer）

はい。この方針はとてもスマートな実装で、
結合しやすいと小林からも返答ありました。

こちらの方針にて、JS関数の開発を進めていただくことは可能でしょうか。
あとは実装後に、すみやかに結合作業を実施させていただきたく存じます。

どうぞ宜しくお願いいたします。

**Comment by kz0817** [comment]
#2224でトレーサーのPRを出しました。これがマージされたら、
hatoholTracer.addListener(HatoholTracePoint.PRE_HREF_CHANGE, func)
で意図されたページ遷移イベントがリスンできます。
ハンドラで遷移許可フラグをアサートすれば、当初に想定された動作をするはずです。

**Comment by kz0817** [comment]
超暫定のリスン用の確認コードです。そのうち、ブランチごと消します。
ご参考に。

https://github.com/project-hatohol/hatohol/commit/7454ed3949bdfa3cd086eb0a6990d3cc8c055ada

**Comment by ucksts** [comment]
ありがとうございます！！
内容確認させていただきます！！

**Comment by ashie** [comment]
まだ「最新データ」と「グラフ」ページに処置されていない内部がリンクがあるような気がしますが、
ひとまずここまではマージしました。

**Comment by kz0817** [comment]
> まだ「最新データ」と「グラフ」ページに処置されていない内部がリンクがあるような気がしますが、

「最新データ」って、グラフへのリンクですよね？
名前列のリンクは、別窓なので不要と考えています。

トレーサーとしては、別窓を開く動作にフックできるといいかもしれませんが、急ぎの需要はないのでいまは静観したいです。

**Comment by ashie** [comment]
> 「最新データ」って、グラフへのリンクですよね？
> 名前列のリンクは、別窓なので不要と考えています。

「名前」列はZabbixのグラフへのリンクなので別タブを開くようになっていますが、「グラフ」列はHatohol
自身で描くグラフなので別タブを開かずに遷移するようになっています。

**Comment by mmikan22** [comment]
#2227 
資料を参考に、hatohol_tracer参照型のclose_defenderを作成いたしました。
参照した値で制御できています。

ユーザーがShift、Ctrl または Alt を押した状態でクリックした後、フラグが true のままになり誤操作防止機能が停止しますが、それはどのように回避すればいいでしょうか？

**Comment by mmikan22** [comment]
#2228
資料を参考に、hatohol_tracer参照型のclose_defenderを作成いたしました。
参照した値で制御できています。

ユーザーがShift、Ctrl または Alt を押した状態でクリックした後、フラグが true のままになり誤操作防止機能が停止しますが、それはどのように回避すればいいでしょうか？

**Comment by kz0817** [comment]
> ユーザーがShift、Ctrl または Alt を押した状態でクリックした後、フラグが true のままになり誤操作防止機能が停止しますが、それはどのように回避すればいいでしょうか？

なるほど。ご指摘ありがとうございます。考えてみますが、いいアイデアがあれば、提案ください。

**Comment by kz0817** [comment]
遷移試行の事後eventイベントを送る方法を検討してみる。そのeventが来たということはページ遷移が実現しなかったということで、フラグを再度falseにすればよいと目論む。

**Comment by kz0817** [comment]
単純にこんな感じにしても、実際のページ遷移は、ブラウザに制御が
もどった時に行われるから、フラグをfalseにするだけの模様でうまく
いかない。

<pre>
   hatoholTracer.pass(HatoholTracePoint.PRE_HREF_CHANGE);
   document.location.href = uri;
+  hatoholTracer.pass(HatoholTracePoint.POST_HREF_CHANGE);
</pre>

**Comment by kz0817** [comment]
いままであまり意識しなかったが、メニューをクリックする際にCtrlやShiftで別Windowやtabを開くことができるのはアプリとして、画面遷移が自由すぎないかという気がしている。
ただ、今の画面を保持したたま別のデータを見たいという場合はあるので、全く需要がないわけでもない。altとかは意味ないからむしろデフォルト動作を抑制したほうがいいだろう。

GMailでもサイドの「受信トレイ」や「スター付き」をShiftやCtrlと一緒にクリックしても、別窓やタブは開かない。メニューバーについてはこういう動作でいいんじゃないか。どうしても、別窓で開きたいときは、右クリックのコンテキストメニューで行うというオプションを残しておくのがよいと思う。

**Comment by kz0817** [comment]
domesticLink()経由の遷移は、CtrlやShiftをケアしてないので、そもそもflagがアサートしっぱなしになる問題は置きない。aタグでの遷移もonClickでdomesticLink()をコールすればよそうさう。

そうすると、issue#2052-close-defender3をマージして、上記の修正を別Issueとして改修すれば、本件はクローズできそう。

**Comment by mmikan22** [comment]
上記リンクボタンの挙動を確認しました。
Shift・Ctrlによる別窓遷移はせず、理想的な動きに感じます。

**Comment by kz0817** [comment]
#2229 でShift/Ctrlによる別窓遷移を抑止するパッチをPRした。

**Comment by mmikan22** [comment]
https://github.com/project-hatohol/hatohol/pull/2230
文言修正を加えたものを、こちらにPRいたしました。
プレビュー環境を破損してしまったため、別branchでのPRとなっています、すみません。

**Comment by kz0817** [comment]
実装できたのでクローズします。
