### ISSUE TITLE
[WebUI]ブラウザpush通知の強化

### ISSUE THREAD

**Issue by ucksts** [project-hatohol/hatohol#2053]
例えば、監視していない時（別窓でRedmine操作、メール操作）でも
深刻度の高いインシデントが発生した際に、push通知でモーダルウィンドウを割り込ませたい。

■モーダルに表示する項目
・発生時間
・未対処の重要イベント数
・深刻度
・期間
・監視サーバ＆ホスト名
・概要は2行程度（長大な場合は...で省略）

※イベントページを見ていない場合に限ります
こちら、デザイン初案です。

![browser_push](https://cloud.githubusercontent.com/assets/16419592/13133988/828da674-d644-11e5-86cd-68c91341b8f9.png)

**Comment by kz0817** [comment]
了解です。その方向で作業すすめてください。

**Comment by ucksts** [comment]
ありがとうございます。こちらの機能単体でwebUI作業が終わりましたら
pull requestいたします。

**Comment by ucksts** [comment]
本件の調査を進めたところ、hatohol専用にデザインされたダイアログの表示が難しいことがわかり、
ブラウザ由来の通知窓での実装へ変更いたしました。
（私の調査不足でした。申し訳ありません・・・）

このようなシンプルな通知窓です
![push_hatohol_mini](https://cloud.githubusercontent.com/assets/16419592/13552921/9781fd60-e3b8-11e5-984d-edde2a4b7697.jpg)

▼実装サンプル
http://mikanmoe.jp/notify/notify.html

▼以下、基本的な仕様になります。
　-通知ウインドウの位置とデザインは固定。
　-アイコン画像の設定が可能。
　-テキスト量によって、縦にある程度は伸びる（限界でスクロール化）
　-連続通知・複数通知ができます。
　-30秒ほどで自動で画面から非表示に。

なお『hatoholの画面が非表示の状態』はJSが感知できないため、
『一定時間操作がない（例：30分以上ページ上でマウスを動かさなかった、キー操作もなかった）』という状況を判定して、深刻度を"重要"にしているイベントが発生した際に
このpush通知を出すような仕様ではいかがでしょうか。

**Comment by tksmatsunaga** [comment]
確認させていただきたいのですが、例えば30分間に10個の重要イベントが発生していたら、Push通知も10個分出るということになりますか？

**Comment by mmikan22** [comment]
おつかれさまです。
実装の考え方としては、２通りに大別されると思います。

１つ目は『エラーの数だけPush通知を出す』
この場合、10個の重要イベントがあれば、最終的に10種類の通知がでます。
OSやブラウザの仕様にも依ると思いますが、Windows8・最新Chromeでは、同時に３つまで通知、その後１つの通知表示終了時間が来るたびに次の通知が出ます。
（サンプルのボタンを連続クリックすると出ます）

２つ目は『エラーがいくつでも１つ出す』
http://mikanmoe.jp/notify/notify.html
長文を仕込んでみましたが、スクロールバーすら出ないため、Push通知単体での情報取得はかなり難があります。
とにかく監視画面に戻らなければ詳細情報取得も操作もできないので、監視者を監視画面に戻す機能と割り切って活用する感じです。


どちらのプランにせよ、監視画面に戻らない限りは一定間隔で通知を出し続けなければ機能しないと思われます。
（通知が30秒ほどで消えてしまうため）

**Comment by tksmatsunaga** [comment]
お疲れ様です。
たとえ障害が一つだとしても、それに関係するイベントが多数発生する可能性があることを考えると、一つ目の案は無いと思います。

となると二つ目の案が残りますが、「新規の重要イベントがあること」を知らせれば良いだけですから、全てを表示させる必要はなく、最新の1件分だけを表示させれば良いのではないかと思います。
もしくは、「新しく、○○件の重要イベントが発生しています！」くらいでも良さそうに思います。

皆さん、いかがでしょうか？

**Comment by ucksts** [comment]
複数表示時の想定が不足し、申し訳ありません。

@mmikan22 さん
詳細のテキストが短い場合は、下記のデザインのように
通知ウインドウの縦幅は、自動的に縮まりますか？

▼改行なしで収まるように文言を調整した案です。
![push_hatohol_2](https://cloud.githubusercontent.com/assets/16419592/13837547/b2d1670a-ec4f-11e5-8090-e1d6d9941a4a.jpg)

「新しく、n件の...」とした場合は、例えば"hatoholをブラウザ表示していた最後の時間"など
いつを起点とするか、検討の必要になります。
障害発生を伝え、監視画面に戻す機能と捉えると、以下のような「未対処の重要イベント」を機械的に表示するという方法もありかと思います。
![push_hatohol_2b](https://cloud.githubusercontent.com/assets/16419592/13837496/46db62a8-ec4f-11e5-9ca9-00904c48f397.jpg)

もし、通知ウィンドウの天地が縮まないのであれば、何か埋め草的なテキストが
必要になりますが、情報過多でスマートではないかもしれません。。
以下、サンプルまで。
![push_hatohol_2a](https://cloud.githubusercontent.com/assets/16419592/13837641/9a11fda0-ec50-11e5-9eb6-dc4ef913d68d.jpg)

**Comment by mmikan22** [comment]
想定される挙動のサンプルを作成しました。
http://mikanmoe.jp/notify/notify.html

通知開始時間やイベント増加数をカスタマイズできます。
『監視している』を『ブラウザ上で何か操作があった』と定義し、mousemove mousedown click keydown focusイベントによって時間とイベント数がリセットされます。

許容未監視時間オーバー＆イベントが１つ以上ある状態で、20秒毎に通知が行われます。
countをAJAX処理で加算する感じです。
（手法やタイミングはお任せします！）

**Comment by ucksts** [comment]
@tksmatsunaga さん
@kz0817 さん

間が空いてしまい申し訳ありません。
表示させるpush通知の文言ですが、以下で進めさせていただきたいのですが
よろしいでしょうか？
![push_hatohol_2a](https://cloud.githubusercontent.com/assets/16419592/14037786/396718a0-f28b-11e5-9ac9-8fcaba7cba75.jpg)
実現可能なら、以下の短縮版で進めたく存じます。
![push_hatohol_2b](https://cloud.githubusercontent.com/assets/16419592/14037799/5b33869e-f28b-11e5-8f70-18298a27453a.jpg)

また、push通知の挙動（仕様）ですが、
●イベントがいくつでも、push通知は常時１つのみ表示する
●通知は30秒ほどで消える
●35秒間隔でpush通知する
●hatohol上でブラウザ操作（mousemove mousedown click keydown focus）がない場合

で考えております。

**Comment by tksmatsunaga** [comment]
>表示させるpush通知の文言ですが、以下で進めさせていただきたいのですが
>よろしいでしょうか？

はい、それで進めてください。
＃可能であれば短縮版の方でお願いします。

また、挙動（仕様）についても了解しました。

**Comment by ucksts** [comment]
ありがとうございます。進めてまいります。
短縮版が実現できるかは、追って進捗をお知らせいたします。

**Comment by ucksts** [comment]
進捗ご報告となりますが、短縮版で実現できそうです。
ひき続き宜しくお願いいたします。
<img width="378" alt="2016-03-25 23 52 01" src="https://cloud.githubusercontent.com/assets/16419592/14046522/67c127f4-f2e5-11e5-8738-82148309e9bc.png">

**Comment by mmikan22** [comment]
PRだしました。
https://github.com/project-hatohol/hatohol/pull/2206

**Comment by mmikan22** [comment]
プレビュー環境を破損してしまったため、 #2232 に指摘事項修正を盛り込んだものを再PRいたしました。

**Comment by kz0817** [comment]
Linux上のChrome 49では通知確認しました。Linux上のFirefox 45では通知が出現しませんでしたが、これについて情報をご存知の方いますか？

**Comment by ashie** [comment]
この版では確認してませんが、 #2206 の段階では出てましたよ。

**Comment by kz0817** [comment]
> この版では確認してませんが、 #2206 の段階では出てましたよ。

じゃあ、FFの設定かな。一応許可してるつもりなんだけど。
![notify-ff](https://cloud.githubusercontent.com/assets/2610513/14271355/2df9b6d4-fb33-11e5-9d7f-28088c49924d.png)

**Comment by kz0817** [comment]
> この版では確認してませんが、 #2206 の段階では出てましたよ。

Chromeみたいに独自のWindowですか、それともデスクトップ環境のnotificationを利用してる感じですか？確認されたデスクトップ環境はUnity? Gnome?
私のはXFce 15 (on Ubuntu 15.10)です。

**Comment by ashie** [comment]
Unity on Ubuntu 15.10です。

> Chromeみたいに独自のWindowですか、それともデスクトップ環境のnotificationを利用してる感じですか？

これは意識していなかったのでわからないです。

**Comment by kz0817** [comment]
情報ありがとうございます。

**Comment by Mnakagawa** [comment]
Unity on Ubuntu 14.04 LTSのChrome 48で他のページに居るときに通知が来なかった。
（ページを離れますか？の通知は出た）
何か条件があるのだろうか。

**Comment by mmikan22** [comment]
timeLimit 秒以降、未対処の重要イベントの数（#numOfUnAssignedEvents 内の数字）が1以上の場合に通知が出るので、もしかしたら未対処の重要イベントが0ではなかったでしょうか？

役に立つかどうかわかりませんが、Push通知機能自体あるいは setInterval の問題である可能性を探るための簡易サンプルを作ってみました。
http://mikanmoe.jp/notify/push_test.html

**Comment by ashie** [comment]
> 役に立つかどうかわかりませんが、Push通知機能自体あるいは setInterval の問題である可能性を探るための簡易サンプルを作ってみました。
> http://mikanmoe.jp/notify/push_test.html

前回とは環境が異なりますが、手元で上記を試してみました。

* GNOME3 on Ubuntu 14.04: 出ない
* Windows 10: 出る

**Comment by mmikan22** [comment]
＞ahieさん
Push通知のサポートと許可は、どんな表示になっていましたか？

**Comment by ashie** [comment]
どちらも

> このブラウザはPush通知をサポートしています。
> 
> このブラウザはPush通知を許可しています。 

です。

**Comment by ashie** [comment]
ついでに

* Mac: 出る

**Comment by ashie** [comment]
もういっちょ

* Unity on Ubuntu 14.04: 出る

**Comment by ashie** [comment]
以上、全てFirefox 45

**Comment by mmikan22** [comment]
＞GNOME3 on Ubuntu 14.04: 出ない
OSレベルでのセキュリティ設定……とかでしょうか。。。

**Comment by Mnakagawa** [comment]
テストページでは問題なく通知が出ました。
ただ，やはりHatohol上で出ないです。。。
もちろん未対処の重要イベントは1件以上で，別タブに居るときに未対処のイベントが増えるような環境でテストしています。

**Comment by ashie** [comment]
あ、ちなみに私はテストページのみで、Hatoholではまだテストできていません。

**Comment by kz0817** [comment]
私は、Hatohol (UIはmanage.pyで提供)でchromeを使って出るのを確認しました。

**Comment by Mnakagawa** [comment]
Firefoxで確認できました。と思ったらChromeでも確認できた。。。
助言有難うございました。

**Comment by Mnakagawa** [comment]
実装に問題がないのでクローズ
