### ISSUE TITLE
[hap2][server] putEventsにて任意の項目を省いた時の挙動，ログ

### ISSUE THREAD

**Issue by Mnakagawa** [project-hatohol/hatohol#2059]
https://github.com/project-hatohol/HAPI-2.0-Specification#user-content-puteventsmethod

このページにあるように，トリガーID,ステータス，セベリティは任意は項目である。
しかし，param内の上記3項目を追加せずにイベントを送信した際，下記の様なエラーが出る。

```
[WARN] <HatoholArmPluginGateHAPI2.cc:1732> Unknown trigger severity: 
[WARN] <HatoholArmPluginGateHAPI2.cc:1700> Unknown trigger status: 
[ERR] <ActionManager.cc:1577> Not found: svID: 1, trigID: __DO_NOT_ASSOCIATE_TRIGGER
```

また，それに伴いWebUIのほうで，Error:200のダイアログが発生し，アイテム，トリガー，イベント関連のページ全てにアクセスできなくなる。

**Comment by kz0817** [comment]
たしかに、任意項目を指定しないことで、警告やエラーができるのはおかしいですね。
Labelをbugにしました。

**Comment by kz0817** [comment]
Mnakagawaさん、Assignしても大丈夫ですか？
ただし、__DO_NOT_ASSOCIATE_TRIGGERのエラー対策は、#1977でも取り扱われていますので、このissueとしては対処不要かもしれません。

**Comment by Mnakagawa** [comment]
アサイン了承です。
私が貼ったログの内、上2行が今回のIssueで下1行が#1977 という認識です。

**Comment by Mnakagawa** [comment]
> また，それに伴いWebUIのほうで，Error:200のダイアログが発生し，アイテム，トリガー，イベント関連のページ全てにアクセスできなくなる。

（これは私が作ったプログラムの問題でした）

**Comment by Mnakagawa** [comment]
```
[WARN] <HatoholArmPluginGateHAPI2.cc:1700> Unknown trigger status: 
[WARN] <HatoholArmPluginGateHAPI2.cc:1732> Unknown trigger severity: 
[ERR] <HatoholArmPluginGateHAPI2.cc:1918> Failed to parse 'hostId' member.
[ERR] <HatoholArmPluginGateHAPI2.cc:1919> Failed to parse 'hostName' member.
[ERR] <HatoholArmPluginGateHAPI2.cc:1921> Failed to parse 'extendedInfo' member.
```

もしかして，と思って試した見たら他の任意項目も全部アウト。
その他のput系のプロシージャに関しては，任意の項目がlast_infoしか無いため問題なさそう。

**Comment by Mnakagawa** [comment]
Fixed.
