### ISSUE TITLE
Nagios's triggers are not updated

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#207]
With Hatohol 14.03, I met the bug that doesn't update the trigger status.
For example, Dashboard, Latest data, and Nagios's Web UI show 7 OK and 1 Warning.
But trigger pages shows Errors for all items.

[Dashboard]
![dashboard](https://cloud.githubusercontent.com/assets/2610513/2940985/dcc57576-d994-11e3-8f6b-8afe8242afbf.png)

[Latest data]
![latest-data](https://cloud.githubusercontent.com/assets/2610513/2940986/e280380c-d994-11e3-87a9-b478a2482eda.png)

[Triggers]
![triggers](https://cloud.githubusercontent.com/assets/2610513/2940987/e629f9d4-d994-11e3-92f4-4354af00d925.png)

[Nagios's web UI]
![nagios](https://cloud.githubusercontent.com/assets/2610513/2940993/2be87d92-d995-11e3-8393-d5b7e26a2f00.png)

**Comment by t-miyazawa** [comment]
以下のような再現試験を5回行いましたがトリガーが更新されない現象は発生しませんでした。
1) Nagiosで監視している全てのホストが正常な状態であり、Hatoholも正常に表示されていることを確認
2) Nagiosで監視している1台をshutdownする
3) Nagiosでshutdownしたホストのサービスが全て障害に見えることを確認
4) Hatoholのダッシュボードとトリガー画面でNagiosの障害が見えることを確認
5) 2でshutdownしたホストを起動
6) Nagiosで起動したホストのサービスが全て正常に見えることを確認
7) Hatoholのダッシュボードとトリガー画面でNagiosの障害が消えていることを確認
8) 2～7を繰り返す

**Comment by kz0817** [comment]
上記を試したHaotoholのバージョンもしくは、Revisionはいくつですか？

**Comment by t-miyazawa** [comment]
確認したHaotoholのバージョンは15.03_dev(昨日(2/25) git clone したソースをビルドしたもの)です。

**Comment by kz0817** [comment]
報告からかなり時間が経過しているので、
振る舞いが変わったのかもしれません。
クローズします。
