### ISSUE TITLE
hatohol-db-initiatorでactions.sqlの実行が失敗する

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#2105]
actions.sqlは、incident_trackersテーブルの内容を使用するので、事前にincident-trackers.sqlが実行されていることが前提となっている。とろころが、hatohol-db-initiatorでは、指定されたディレクトリの中のsqlファイルをos.listdir()が返す順に実行する。そのため、先にactions.sqlが実行される場合があり、その場合、SQL文の実行に失敗する。

<pre>
INSERT actions VALUES
  (0, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
   2,
   (select id from incident_trackers where type=1 order by id limit 1),
   '', 0, 0);
</pre>

**Comment by kz0817** [comment]
例えば、標準のSQLファイルの名前の先頭には数値をつけて、os.listdir()が返したファイルリストの名前の昇順に実行するとかにして、順序を制御する？

**Comment by cosmo0920** [comment]
> 標準のSQLファイルの名前の先頭には数値をつけて、os.listdir()が返したファイルリストの名前の昇順に実行するとかにして、順序を制御

ファイル名ベースの制御ならばこの方法がベターだと思います。

**Comment by ashie** [comment]
#2117 で自動クローズするようにしていたつもりが、 間違って #2106 を指していたorz

**Comment by cosmo0920** [comment]
なんと… :dizzy:
