### ISSUE TITLE
サーバーまたぎのトリガーのフィルタの相談

### ISSUE THREAD

**Issue by cosmo0920** [project-hatohol/hatohol#2118]
サーバーまたぎのフィルタ条件とWebUIの挙動をどうするかの相談です。

#2114 ではトリガーのホスト名に関してのサーバーまたぎのフィルタを追加しました。
このプルリクエストの時点ではホスト名はいつでも選べ、ホストIDに対してANDで絞り込まれます。

1. WebUI側でホストIDとホスト名の選択を排他にする。サーバー側は何もしない
2. ホストIDとホスト名をANDではなくORで絞り込むようにする。WebUI側は何もしない

の二通りの実装パターンを考えています。

どちらの実装の方がより思い描いていたものに近いでしょうか？

**Comment by kz0817** [comment]
うーん。難しいね。現状#2114のままでも良い気もする。
それよりも、トリガー名（の部分一致？）でのマタギができるとかなり便利なように思う。

**Comment by cosmo0920** [comment]
おぉ。確かにそうですね。

bootstrap-selectのリアルタイムの要素検索とトリガー名の部分一致検索は役割が微妙に違うように思えますね。。
ちなみに #2144 のままでもトリガー名の完全一致のサーバーまたぎ検索はトリガー名をサーバーに送るようになっているので出来るようになっているはずです。

**Comment by cosmo0920** [comment]
現状：

```sql
WHERE hostname IN ('host1','host2','host3')
```

やるとしたらこんな感じのwhere句が出せれば良さそうです。

```sql
WHERE hostname REGEXP '\'host1\'|\'host2\'|\'host3\'
```

ただ、このREGEXPはどうやらマルチバイト文字を扱うのに向いていないらしい[1]です。ううむ…。

[1] http://dev.mysql.com/doc/refman/5.7/en/regexp.html

**Comment by cosmo0920** [comment]
トリガー名のサーバー跨ぎのフィルタはトリガー名の完全一致+bootstrap-selectのリアルタイム検索の併用で実装してみます。

**Comment by cosmo0920** [comment]
#2126 とトリガーの概要を取ってくるWebUI側の諸々を実装してみたところ、次のような問題があることがわかりました。

* トリガーはlimit句で制限しているので一度に取ってこれない
* しかし概要のサーバー跨ぎのフィルタは重複を除いて一度に表示されてほしい

という問題があることから、/triggersだけでサーバー跨ぎのフィルタを完結させるのが難しいです。

そのため、

* DB側のAPIにトリガーのbrief(概要)のみを重複を除いてSELECTするAPIを追加する
* /trigger-briefs(URLは要検討)にアクセスし、トリガーの概要を一度に取得する。

という方向性で概要のサーバー跨ぎのフィルタを実装しようと考えています。

@kz0817 さん、上記の方針で何か気になることや、このようにしたほうが良いという指摘事項はありますか？

**Comment by cosmo0920** [comment]
上記の問題に気づいていなかった時に実装を進めていたブランチを置いておきます：
https://github.com/project-hatohol/hatohol/tree/try-to-implement-beyond-server-filter-for-trigger-brief-rest-triggers-only

サーバーをまたいでトリガーの概要を絞り込むことができるものの、使い勝手は良くないです。

**Comment by cosmo0920** [comment]
#2126 はトリガーの概要のパラメータを受け取るのに必須のオプションを追加しているのでこれはこれでOKのはずです。

**Comment by cosmo0920** [comment]
> それよりも、トリガー名（の部分一致？）でのマタギができるとかなり便利なように思う。

こちらとホストグループ名のサーバーまたぎのフィルタの実装の優先度はどちらが上になるのでしょうか？

**Comment by kz0817** [comment]
うーん、使い方によると思うけど、ホストグループ名かな。

トリガーマタギは、完全一致だと、柔軟性が低くて使いにくい気がするし、
部分一致だと、仕様と実装に結構な時間が必要な気がします。

**Comment by cosmo0920** [comment]
> 完全一致だと、柔軟性が低くて使いにくい

bootstrap-selectのライブサーチ機能と組み合わせれば実はそこまで不便ではない気がします。

**Comment by kz0817** [comment]
> bootstrap-selectのライブサーチ機能と組み合わせれば実はそこまで不便ではない気がします。

これって、ブラウザ側の処理のことですよね。
サーバから取得するときにある程度絞らないと、行けないデータ量が多すぎる気もするので

**Comment by cosmo0920** [comment]
> サーバから取得するときにある程度絞らないと、行けないデータ量が多すぎる気もするので

そうですね。トリガーのサーバーまたぎはトリガー名に絞って取得するREST APIがあれば良いと思っています。
ところで、このIssueは相談が完了した（？）という事でクローズで良いのでしょうか？それとも単にミス？

**Comment by kz0817** [comment]
ミス。破棄したつもりが記録されていた。

**Comment by cosmo0920** [comment]
グループ名でのサーバー跨ぎフィルターは #2149 でWebUIから使えるようになった。

**Comment by cosmo0920** [comment]
ひとまず #2149 までで、
トリガー画面でのサーバー跨ぎフィルタはホスト名とホストグループ名について完了する見込みです。
残す作業として、トリガー概要のサーバー跨ぎフィルタとトリガー画面のフィルタの保存が残されています。こちらどちらの作業の優先度を上げて作業したほうが良いでしょうか？

**Comment by cosmo0920** [comment]
https://github.com/project-hatohol/hatohol/pull/2173 でトリガー画面のフィルタでトリガー概要のサーバー跨ぎの検索も出来るようになった。

**Comment by cosmo0920** [comment]
https://github.com/project-hatohol/hatohol/pull/2173 ではbootstrap-selectでWebUI側ではライブサーチを効かせつつ、サーバー側では完全一致の検索に留めています。

**Comment by cosmo0920** [comment]
諸々実装が完了したのでこのIssueはクローズします。サーバー跨ぎのフィルタのブラッシュアップは気づいた時点で個別のIssueで取り扱う事としましょう。
