### ISSUE TITLE
イベント：コメント機能

### ISSUE THREAD

**Issue by ucksts** [project-hatohol/hatohol#2119]
イベントページにおける、コメント機能についてご提案です。
障害時発生のエスカレーションや申し送りなど、Next actionを補助する機能の
要望が多くあるということで、デザインのプロトタイプとして検討してみました。

●障害発生時のタスク化と行動を、より促すため「対処」状況をバッジアイコン化する
●テーブル行の右端に「編集（鉛筆）マーク」を追加。押下することでコメント欄がひらく

![event_memo_0](https://cloud.githubusercontent.com/assets/16419592/13457899/cbce9550-e0ad-11e5-9818-637c19f9f57b.jpg)

この後、連続して投稿いたします。

**Comment by ucksts** [comment]
**[1] 障害発生をうけてコメントを書く場合**

コメントを記入したい行の右端「鉛筆」アイコンを押下します。
するとアコーディオンUIで、コメント欄とアカウントが展開表示されます。

![event_memo_1](https://cloud.githubusercontent.com/assets/16419592/13458055/ae2d6430-e0ae-11e5-9aa7-6ffd4d0d3967.jpg)

コメントは大規模なやりとりを想定していないメモ的な機能のため文字上限は（仮に）250字。

※（案）nameとdate,time,記入したコメントはRedminと連携する。

**Comment by ucksts** [comment]
**[2]投稿完了**

投稿後は自分のコメントであれば、[編集]と[削除]が行える。　
（確定されたコメントは背景が”白”に。直近の投稿はNEWがつく）
また、[コメント追加]ボタンにより、連続投稿も可能。

![event_memo_2](https://cloud.githubusercontent.com/assets/16419592/13458141/2cdc8d88-e0af-11e5-9d67-61b9f74883a1.jpg)

**Comment by ucksts** [comment]
**[3]コメントを確認する**

誰かがコメントを行った場合は、行の右端にコメント件数が表示されている。（仮：表示上限は99まで）
![2016-03-02 19 45 56](https://cloud.githubusercontent.com/assets/16419592/13458189/6fe71af8-e0af-11e5-991b-b713f5652d36.png)

この件数部分を押下することで、コメントの確認ができる。
※コメントは時系列に表示される
また、即入力できるコメント欄が設けられているため、すばやい返答が可能。

![event_memo_3](https://cloud.githubusercontent.com/assets/16419592/13458230/928900f8-e0af-11e5-8605-342c2f69ba0f.jpg)

**Comment by ucksts** [comment]
**[4]コメント返答した場合**

コメント投稿後は、同様に[編集]と[削除]が行える。　
（確定されたコメントは背景が”白”に。直近の投稿はNEWがつく）
また、[コメント追加]ボタンにより、連続投稿も可能。

![event_memo_4](https://cloud.githubusercontent.com/assets/16419592/13458321/e8a858b2-e0af-11e5-8178-2a6f0705cdf2.jpg)

**Comment by ucksts** [comment]
**[5]深刻度設定のない行へのコメント**

背景カラーがついていない場合の見え方はこちら
![event_memo_5](https://cloud.githubusercontent.com/assets/16419592/13458362/2f7bb5fe-e0b0-11e5-81f2-9e62c1f24790.jpg)


このコメント欄と一連の操作で、
[未対処]→[処理中]のようにステータスの変更ができればなお良いと思います。

**Comment by ucksts** [comment]
細かい仕様を煮詰め切れているわけではなく、
あくまでデザイン先行でのご提案となります。

**Comment by ucksts** [comment]
※参考までに、おおよそ上記をまとめたスライド資料です
（サマリエリアが旧デザインですがご了承ください）
[hatohol コメント履歴機能UI案.pdf](https://github.com/project-hatohol/hatohol/files/154571/hatohol.UI.pdf)

**Comment by kz0817** [comment]
デザイン提案ありがとう御座います。

ashieさん、これベースにREST APIの提示できますか？
3/18がFeature freezeの目標なので、今週中ぐらい？
それでも2weekで、UI、APIともに実装ギリギリ？

**Comment by ashie** [comment]
明日までに提示します。

**Comment by cosmo0920** [comment]
> コメントは大規模なやりとりを想定していないメモ的な機能のため文字上限は（仮に）250字。

コメントやインシデントの状態を記録するためのDBのテーブルのコメントのカラムは2048文字まで確保していますが、この想定で問題ありません。

**Comment by ashie** [comment]
RedmineのAPIを参考にしてincidentに対してステータスやコメント付きでPOST/PUTできるように
しようと思っていたが、

> コメント投稿後は、同様に[編集]と[削除]が行える。　

これのことは考慮に入れていなかった。

http://www.redmine.org/projects/redmine/wiki/Rest_api にもこのことは書かれていなかったが、
挙動やソースを確認すると /journals でCRUDできるようだ。

**Comment by cosmo0920** [comment]
今のインシデント履歴のテーブル構造だとコメントと変更者、イベントに紐づくIDが一緒のテーブルに格納される事になっているのですが、コメントは一つの変更履歴にいくつも付けられる方が良いんでしょうかねぇ。今のテーブル構造だとDELETEの場合はコメントだけ消すという謎REST APIが生えそうでもんにょりします。

**Comment by ashie** [comment]
コメントのテーブルは分けた方が良いかも? というのは私も考えていたところではあります。
が、現状でも機能は実装できるので、まずはAPIの実装を優先して、後で必要であれば変更すれば
良いかと思っています(後でとは言っても、リリース前には方式確定)。

**Comment by cosmo0920** [comment]
コメントのテーブルを確実に分けた方が良いと言う場合は32767文字まで入力可とする場合とかですかねぇ。この仕様だとテーブルを分けないと制限に引っかかりやすくなる気がします。

**Comment by ashie** [comment]
# API案

Redmineと似たような形で、ステータスの変更とコメントを一体で扱うようなAPIを想定しています。
既存コメントの扱いが微妙なので後で変更するかもしれませんが、変更する場合はJavaScriptのコードも
含めてこちらで修正します。

問題等あればコメントお願いします。

## インシデントの変更履歴とコメントのリスト取得

### リソース

* GET: `/incident/<unifiedEventId>/history`

### 応答例

```js
  {
    "apiVersion":4,
    "errorCode":0, // 詳細はhatohol_defs.jsのerrorMessages参照
    "incidentHistory":[
      // イベントが発生してインシデントが作成された
      {
        "id":"230",
       	"unifiedEventId":"13517", // インシデントが紐ついているイベントのID
        "userId":"0",  // 0はシステムによる自動作成
        "status":"NONE",  // 取りうる値はPUTの項を参照
        "time":"1456221146" // UNIX時間
      },

      // 「対処」が「処理中」に変更された
      {
       	"id":"233",
        "unifiedEventId":"13517",
        "userId":"4",
        "status":"IN PROGRESS",
        "time":"1456231146"
      },
      // コメントが追加された
      {
        "id":"235",
        "unifiedEventId":"13517",
        "userId":"3",
        "status":"IN PROGRESS",
        "comment":"ashieにアサインする!",
        "time":"1456241146"
      },

      ...

       // 「対処」が「対処済」に変更され、
       // コメントも同時に追加された
      {
       	"id":"330",
        "unifiedEventId":"13517",
        "userId":"3",
        "status":"DONE",
        "comment":"解決した!",
        "time":"1456251146"
      }
  }
```

### 備考

* Redmineとは異なり、各要素に変更前のstatusは入れていません。
* ただし、そうなるとコメントのみを追加した後にコメントを削除した場合の扱いが微妙

## インシデントの変更・インシデントへのコメント追加

### リソース

* PUT: `/incident/<unifiedEventId>`

### クエリパラメータ:
* status
   * 「対処」の変更。
   * コメントの追加のみの場合は省略可。
   * 値は（16.04では）以下のいずれか
       * NONE
       * HOLD
       * IN PROGRESS
       * DONE
       * USER1
       * USER2
       * USER3
       * USER4
       * USER5
       * USER6
* comment
    * コメント本文。
    * 「対処の変更」のみの場合は省略可。

### 例

```
/incident/123?status=HOLD&comment=hoge
```

### 備考

* 現時点で既に実装されています。
* JavaScriptでの実際の処理は他のPUTのコードを参考して頂ければ良いかと思います。

## コメントの削除

### リソース

* DELETE: `/incident-comment/<id>`

### 備考

* 投稿した本人のみ削除可
* incident-historyとしたいところだが、コメント以外は凍結しているのでincident-commentとした
* しかしDELETEと言ってもヒストリが消えるわけでは無い（特にstatusの変更を伴う場合は消すわけにはいかない）のが微妙

## コメントの編集

### リソース

* PUT: `/incident-comment/<id>`

### クエリパラメータ:
* comment
    * コメント本文。
    * 「対処の変更」のみの場合は省略可。

### 例

```
/incident-cmment/330?comment=hage
```

### 備考

* 投稿した本人のみ編集可

**Comment by ashie** [comment]
ひとりごと

個人的には一度投稿したコメントを削除できたり編集できたりするシステムは後から参照すると
話が繋がらなくなったりしてあまり好きではない。でも、実際には結構使ってしまう。

例えばBugzillaではコメントの編集や削除はできないけど、後から間違いに気づいて訂正コメント
追加すると、それはそれで読む側のコストが上がってしまうというのはよく経験することなので、
編集できるシステムではつい編集してしまう。

**Comment by mmikan22** [comment]
みなさま
はじめまして、フロントエンドエンジニア小林まさきちです。

こちらのほう、HTML上でのデザイン適用を開始いたします。
つきまして、以下のような仕様になりますが、よろしいでしょうか？

＝＝＝＝＝仕様＝＝＝＝＝
１）コメント閲覧・投稿開始時にサーバの監視は停止される
閲覧中にデータ更新された場合、テーブルがリフレッシュされてしまう。
投稿中にリフレッシュ⇒投稿内容がクリアされる、という悲しい事態を回避するため。

２）実装は動くデザインサンプルです
スクリプト上で『投稿内容が反映されたように見える』ところまで実装いたしますが、なんちゃって投稿となります。
＝＝＝＝＝仕様ここまで＝＝＝＝＝

以上２点、ご確認よろしくおねがいします。

**Comment by kz0817** [comment]
提案ありがとうございます。

> １）コメント閲覧・投稿開始時にサーバの監視は停止される

完全に監視を停止するのではなく、次のようにすることはできますか？
- 上部またはサイドに配置予定の「未対処の重要イベント」の数などは、
　定期的に更新される
- 閲覧・投稿が終了したのち、ポーリング時間以上経過している場合、
　更新する

> ２）実装は動くデザインサンプルです
> スクリプト上で『投稿内容が反映されたように見える』ところまで実装いたしますが、なんちゃって投稿となります。

@ashieさんが２つ前のコメントで提示したAPIを利用する実装を
していただければ、結合後、動作するはずでので「反映されたよう
に見える」コードは不要かと思われます。
もちろん、双方（API, UI実装者）で結合試験をする必要はあります。
そのために、こまめにmasterにマージしてしていただけますか。

**Comment by mmikan22** [comment]
速やかなご回答、ありがとうございます！

>完全に監視を停止するのではなく、次のようにすることはできますか？
>-上部またはサイドに配置予定の「未対処の重要イベント」の数などは、 　定期的に更新される
-閲覧・投稿が終了したのち、ポーリング時間以上経過している場合、 　更新する

可能です。
当初予定では開発用の別JSをご用意するつもりでしたが、その実装ですと『/static/js/events_view.js』を直接、かなり修正することになりますが、よろしいでしょうか？
また、閲覧・投稿の終了の定義は『コメント欄を閉じる』でよろしいでしょうか？


>@ashieさんが２つ前のコメントで提示したAPIを利用する実装を
していただければ、結合後、動作するはずでので「反映されたよう
に見える」コードは不要かと思われます。
もちろん、双方（API, UI実装者）で結合試験をする必要はあります。

API結合を念頭に置いた開発は前提ですが、API実装までデザインチェックを伸ばすわけにも行きませんので、モックアップ機能は結合までは残すことになります。


>そのために、こまめにmasterにマージしてしていただけますか。

こちら、開発ステップ毎にcommitするような感じでよろしいでしょうか？

よろしくおねがいします。

**Comment by ashie** [comment]
API案で一つ見落としていた。

```js
      // コメントが追加された
      {
        "id":"235",
        "unifiedEventId":"13517",
        "userId":"3",
        "status":"IN PROGRESS",
        "comment":"ashieにアサインする!",
        "time":"1456241146"
      },
```

ユーザー名はuserIdから引っ張ってもらえば良いと考えていたが、今のHatoholでは「ユーザー情報を
取得する権限」が無いと、ユーザー一覧を取得しようとしても空のリストしか取得できないと思う。
これでは不便なので、上記に加えて`userName`を追加して、Hatoholサーバ側でユーザー名をつけた
状態で渡してやるようにする。

```diff
      // コメントが追加された
      {
        "id":"235",
        "unifiedEventId":"13517",
        "userId":"3",
+        "userName":"ashie",
        "status":"IN PROGRESS",
        "comment":"ashieにアサインする!",
        "time":"1456241146"
      },
```

**Comment by ashie** [comment]
あと、余裕があればユーザー情報にフルネームを追加できるようにした方が良いか?

**Comment by kz0817** [comment]
> 当初予定では開発用の別JSをご用意するつもりでしたが、その実装ですと? >『/static/js/events_view.js』を直接、かなり修正することになりますが、よろしいでしょうか？

はい。
小手先でやるよりは、ソフトウェア構成としての総合的な
妥当性やメンテナンス性などを高めることを大切にしている
メンバがこのプロジェクトでは多いので、そのほうがよいと
思います。

あと、修正した後、既存テストが全て通ることを、本プロジェクト
では、Pull Request時の必須事項にしています。改変に起因
してテストが失敗する場合（テスト対象関数の仕様が変わった
とか、そもそもその関数がなくなった場合）、テストコードの
修正も合わせてお願いします。
テストは、GitHubにPushした時に自動で走ります。結果は、以下で
確認できます。https://travis-ci.org/project-hatohol/hatohol/builds

様々なコンポーネントのテストを実行しているので終了までに
小一時間要します。また、他のプロジェクトメンバーのPushし
た変更に対するテストがシーケンシャルに実行されるので、最近
ではpushした後、実際に実行されるのが半日後ということもしば
しばです。また、False Positiveな結果になることもかなり多いです。
その場合、個別にテストシステムが悪かったとか、そういう原因を
見ています。わからなければ、都度聞いてください。

このような事情があるので、テストそのものを改変する場合、
ローカルマシンで実行させるほうが効率がよいです。
方法は、以下に記載されています。
https://github.com/project-hatohol/hatohol/blob/master/client/HowToTest.md


> また、閲覧・投稿の終了の定義は『コメント欄を閉じる』でよろしいでしょうか？

そうですね。次版向けには、そうやってみしょう。

> API結合を念頭に置いた開発は前提ですが、API実装までデザインチェックを伸ばすわけにも行きませんので、モックアップ機能は結合までは残すことになります。

なるほど。
これまで、UIデザインに強い者が開発者におらず、開発段階での
モックについて、深く考える機会がありませんでしたので、よい
刺激を受ける意見です。

DIというか、API層を簡単に切り替えられる仕組みがあればいいんですが、
時間も有限ですし。。。何かいいアイデアがあれば、ぜひ提案ください。

>> そのために、こまめにmasterにマージしてしていただけますか。
> こちら、開発ステップ毎にcommitするような感じでよろしいでしょうか？

開発ステップというのが、プロジェクトや個人によって、かなり変わってくる
と思うのですが、本プロジェクトでは、だいたい以下のような感じでコミット
しています。また、次のwikiもご参照ください。
https://github.com/project-hatohol/hatohol/wiki/masterブランチへの変更適用ガイドライン

・バグなどの修正では、1件1commit
（改変が多ければ、それ以上のcommitに分割することあるが、
 2件以上のバグ修正を1commitに含めることはない）
・typoなど：原則1件1コミット。ただし、あまりにも数が多いとか、
同じ綴りの間違いが多数あるなどの場合は、臨機応変にまとめることもあり。
これら自明なものについては、1commitごとにPull Request
していただいたほうがよいと思います。

・新規開発では、比較的小さい変更ごとにコミットすることが
望ましいと考えられています。
例：最終的に100の関数から構成される新機能でも、コミットは単機能
（関数1つ〜結合度の高い数個)ごとのようなイメージ。

※実際には、（特に新規開発では）試行錯誤的に関数を作ったり、
消したり、まとめたりを繰り返すと思うので、なかなか難しい
作業ではあると思います。ただ、努力目標とういか、なるべく
そうしようと念頭に置いてやっているプロジェクトメンバーが多いです。

Pull Requestに時には、レビューしやすいコミット単位でお願いします。
といいつつ、これを定義するのは難しいのですが、機能の意味を理解
できる範囲でなるべく短いというイメージでしょうか。
一概に行数ではないですが、差分が100行を超えるあたりから、
なんとなく、レビューが大変になり1000行を超えると相当
時間と精神力を使う印象があります。

**Comment by mmikan22** [comment]
＞kz0817さん
資料拝読いたしました。
プロジェクト背景、だいたい把握です。

こまめなPR、心がけていきます！

**Comment by ashie** [comment]
上記のWebAPI案は #2129 で実装したので、マージされれば動くようになるかと思います。
（当初思っていたほど時間かからなかった）
改善案は引き続き検討していきます。

**Comment by ashie** [comment]
一点、APIの検討項目が抜けていた:

https://github.com/project-hatohol/hatohol/commit/c3163054202f2d876a9be6047e8aee4b5547b78e#commitcomment-16662455

インベントテーブルに表示しているコメント数をどこから取ってくるかという問題がある。
incidentHistoryはコメント欄を開くときにxmlHttpRequestで取ってくる想定なので、最初の時点では
コメント数を取ってくる術が無い。
全てのeventに対してはじめからincidentHistoryをつけたりコメント数をカウントするのでは、ただでさえ
重くなりがちなイベントのクエリをさらに重くすることになるので避けたい。

`event.incident.commentCount`というプロパティを追加し、ユーザーがコメントを追加したり削除した
際に更新するようにする。

**Comment by ashie** [comment]
最低限のコメント表示機能と投稿機能を実装した版をプルリクした: #2188
ただし、まだいくつか課題が残っている。詳しくは #2167

**Comment by kz0817** [comment]
この版をマージしたら、概要列に編集アイコンが現れますか？
3/28の朝のmaster (1afa218c)をビルドしても、表示されなかったので。
設定とか、DBの再作成とか必要ですか？hatohol-db-initiatorは実行しんですが。。

**Comment by ashie** [comment]
あ、設定が必要ですね。デフォルトで有効にしておくのを忘れてました。

現状で有効にした場合は設定画面で表示項目に「Comment」を追加して下さい。

**Comment by ashie** [comment]
デフォルト設定はプルリク出します。

**Comment by kz0817** [comment]
回答ありがとうございます。表示できました。

**Comment by ashie** [comment]
> デフォルト設定はプルリク出します。

インシデント機能が無効化されている場合の処置が抜けていたため、単純に追加しただけでは
テストが通らない。その点も含めて修正が必要。

**Comment by Mnakagawa** [comment]
ひとまず新機能の実装という点では，クローズしても良い？

**Comment by kz0817** [comment]
いいと思います。クローズしましょう。
