### ISSUE TITLE
「デフォルトフィルター」の設定画面のサムネイルを変更した方が良い

### ISSUE THREAD

**Issue by tksmatsunaga** [project-hatohol/hatohol#2181]
イベント画面のレイアウトが変わったので、「デフォルトフィルター」の設定画面のサムネイルを変更した方が良いと思います。

![default](https://cloud.githubusercontent.com/assets/7628896/13806638/13678afa-eba0-11e5-851d-97adc8c4831d.png)

**Comment by ashie** [comment]
うげ、確かにそうですね...
