### ISSUE TITLE
イベント一覧の表示項目（カラム）を追加することはできるが削除ができない

### ISSUE THREAD

**Issue by tksmatsunaga** [project-hatohol/hatohol#2182]
「イベントページの設定」で、表示する項目を追加することはできますが、表示されている項目を削除することができませんでした。

例えば、イベント一覧の中で「担当者」とか「進捗率」などのカラムを削除（非表示）にしたいと思っても、「イベントページの設定」で行うことができませんでした。

![default](https://cloud.githubusercontent.com/assets/7628896/13808126/de2eb126-eba7-11e5-8303-b05adaf59661.png)

**Comment by ashie** [comment]
> 例えば、イベント一覧の中で「担当者」とか「進捗率」などのカラムを削除（非表示）にしたいと思っても、「イベントページの設定」で行うことができませんでした。

これは具体的にはどういう挙動になっていますか?
非表示にしたい項目を選択して左矢印ボタンを押しても、何も反応が無いということでしょうか?
それとも、項目は左に移動するが、イベント画面にその設定が反映されないということでしょうか?

手元の環境では正しく動作しているようです。

**Comment by tksmatsunaga** [comment]
> 非表示にしたい項目を選択して左矢印ボタンを押しても、何も反応が無いということでしょうか?

はい、そうです。
以下の環境で起きています。
http://hatohol-github.cloudapp.net/ajax_events#

**Comment by ashie** [comment]
> 以下の環境で起きています。
> http://hatohol-github.cloudapp.net/ajax_events#

アカウント知らないです...
(知ってたかもしれないけど発掘できない...)

**Comment by ashie** [comment]
> テスト環境で起きています。

ここで試してみましたが、再現しませんでした。
もしまだ発生するようであればブラウザの問題かもしれませんので、お使いのブラウザとバージョンを
教えて下さい。

**Comment by cosmo0920** [comment]
今のmaster(db5595509156942beb6c36bf45c5647b45e6565c)でUbuntu 14.04.4 LTS でHatoholサーバーを起動し、WebUIを開発サーバーで起動している場合、+ IE 11でイベント画面のテーブルのカラムの追加と削除は動作しました。

**Comment by ashie** [comment]
再現できないためいったんクローズします。
まだ発生するようであればリオープンして下さい。
