### ISSUE TITLE
[WebUI] イベント画面のサマリーのリンクの実装

### ISSUE THREAD

**Issue by ashie** [project-hatohol/hatohol#2184]
イベント画面のサマリー（画面の上にある「すべてのイベント」「未対処の重要イベント」「重要イベント」）の
リンクでイベントリストを絞り込めるように実装する。

オフラインミーティングでは欠席裁判で @Mnakagawa さんが担当することになったと私の議事メモには
書いてあるが、状況を見るに本人に伝わっていない気がする（議事メモ共有しとくべきだった...）。

ちょっとタイムオーバーになると思うがこっちで引き取る。

**Comment by Mnakagawa** [comment]
I hear it first time....
I'm sorry

**Comment by ashie** [comment]
`ajax_events?important=true&unhandled=true` という感じのクエリがつく単純なリンクにして、
開始時によろしくフィルタするようにすれば良いだろうか。

**Comment by ashie** [comment]
```
ajax_events?important=true&unhandled=true という感じのクエリ
```

とするよりは、それに相当するincidentStatusesとseveritiesのクエリがつくようにしたほうが良いか?

**Comment by ashie** [comment]
> とするよりは、それに相当するincidentStatusesとseveritiesのクエリがつくようにしたほうが良いか?

これである程度動いているが、一つ問題がある。

「末対処」はインシデントが「NONE」か「HOLD」、あるいは`NULL`という条件でselectする必要が
あるが、今のREST APIでは最後の条件を与える方法が無い。
空文字を与えた場合は空文字だけではなく`IS NULL`を加えれば良いと思ったが、そもそも
`StringUtils::split()`が空文字を除外してしまう影響で、空文字を与えることができない。
普通、この手のAPI、例えば`g_strsplit()`とかだと空文字も配列に加えてくれるので、同様に空文字を
受け入れてもらえるように修正すべきか?

**Comment by ashie** [comment]
あと、実際に動くものを見てみると、リンク部分はラジオボタンあるいはタブっぽくなっていると
良いなと思った。いまどの条件で絞り込んでいるのかが(URLを見ないと)分からない。

**Comment by ashie** [comment]
> 普通、この手のAPI、例えばg_strsplit()とかだと空文字も配列に加えてくれるので、同様に空文字を
> 受け入れてもらえるように修正すべきか?

問題は、これの影響範囲がよく分からない。
（全ての利用側コードできちんと空のケースのテストが書かれているとは到底思えない）

**Comment by ashie** [comment]
> （全ての利用側コードできちんと空のケースのテストが書かれているとは到底思えない）

構わずやっちゃう気だけどね:stuck_out_tongue_winking_eye:

**Comment by ashie** [comment]
> 普通、この手のAPI、例えばg_strsplit()とかだと空文字も配列に加えてくれるので、同様に空文字を
> 受け入れてもらえるように修正すべきか?

と思ってコードを見てみたら、`doMerge`という引数を`false`にすれば空文字も受け入れてもらえそうなことがわかった。

**Comment by ashie** [comment]
というわけで

> 空文字を与えた場合は空文字だけではなくIS NULLを加えれば良いと思ったが、

この方針で期待通り動作するようになった。

**Comment by ashie** [comment]
ラジオボタン化（あるいはタブ化）は別途考えるとして、ここまでのをPR出しておく。

**Comment by ashie** [comment]
Thanks!
