### ISSUE TITLE
[WebUI] 監視サーバのプロパティが現状にそぐわない

### ISSUE THREAD

**Issue by ashie** [project-hatohol/hatohol#2205]
監視サーバのプロパティで「ホスト名」や「IPアドレス」は現在は使われていないが、
監視サーバのリストではこれらの列がまだ存在している。

![monitroing-server-properties](https://cloud.githubusercontent.com/assets/135104/14042258/abe0155a-f2bb-11e5-9e75-9b39ffa55a20.png)

**Comment by ashie** [comment]
現状では他に共通のプロパティというのは無いが、代わりにURLくらいは入れておいても良いか。

**Comment by kz0817** [comment]
一概に削除というよりJSプラグインで、プラグイン別に処理させてはどうでしょうか？
ただ、ホスト名とIPアドレスというカラムは、プラグインによってはふさわしくないので、「説明」「ホスト情報」ぐらいのゆるい感じの列を一つ提供するのがいいのかな。

**Comment by ashie** [comment]
「IPアドレス」と「ホスト名」は仕様として存在していないので、これらを削除して、仕様として存在している
「URL」を代わりに入れるのは特に問題ないと思っています。

https://github.com/project-hatohol/HAPI-2.0-Specification#getmonitoringserverinfomethod

それ以外の付加的情報を表示する手段としてプラグインで処理させるという案は良いなと思いました。
ただ、安直なAPIは生やしたくないので、どのような仕様にするのかは慎重に決めたいです。
16.04向けには現行案にとどめておきたいです。
