### ISSUE TITLE
16.01においてダッシュボード上のアイテム数にZabbix側の最新値が反映（減）されない

### ISSUE THREAD

**Issue by netbuffalo** [project-hatohol/hatohol#2210]
Hatohol 16.01（hatohol-server/web-16.01-1.el7.centos.x86_64）へ監視対象ホストが登録されているZabbix 3.0.1を登録すると、最新の「アイテム数」がHatoholダッシュボード上に表示されました。
その後、Zabbix側で監視対象ホストに紐付くアイテムを減らしたのですが、Hatoholダッシュボード側の「アイテム数」にはZabbix側の最新値（減少した総アイテム数）が反映されませんでした。

ちなみに、Zabbix側で監視対象ホスト自体を削除するとHatoholサーバーのZabbixAPIポーリング後にHatohol側の「ホスト数」も変化しました。

また、「トリガ数」は「設定」>「監視サーバー」から「監視サーバートリガ再読込」でZabbix側と同期できることも理解しました。

ただ、アイテム数だけはZabbixAPIポーリング、「監視サーバートリガ再読込」の何れにも連動せずアイテム自体がitemsテーブルに保存されているようで、ダッシュボード以外にも「概要：アイテム」、「最新データ」ページで既にZabbix側で存在しなくなっている個々のアイテム情報が表示され続けました。

これは意図的にそう設計されているものでしょうか？
（アイテムは意図的に同期しないのかな・・・とは想像したのですが、運用ではアイテム設定が増減することも多く監視者が混乱しそうで気になっています）

**Comment by netbuffalo** [comment]
過去のissueを見返した所、以下の議論に似ている点があるので調べてみました。

https://github.com/project-hatohol/hatohol/issues/2029#issuecomment-194716192

Hatoholのダッシュボード上でZabbixと同期する項目、例えば「トリガー数」であればhatohol/triggersテーブルにはvalidityフィールドがあり、Zabbixで削除される前は1、削除された後は0になっていることが分かりました。
ただ、やはりitemsテーブルにはvalidity相当のフラグが無くこれが原因かな、と理解しました。

＃hatoholを中心に運用を行うと監視者がアイテム表示＝監視中と誤解する可能性あるかと危惧しています。

**Comment by kz0817** [comment]
ご質問ありがとうございます。

はい、ご指摘のとおり同期していません。
ただ、強い信念（考え）があって、そうしているわけではないです。
基本的には、要望が多いものから機能強化しているので後回しになっているのと、監視情報が少しでも多いほうがいいかな(Zabbix上で削除されてもしばらくはHatoholのDBに保持しておいてもいいかな)という程度の理由で現在の実装になっています。

itemの同期について次次版(16.07 or 08?)以降で検討してみます。

**Comment by netbuffalo** [comment]
早速の回答ありがとうございます。

ご指摘の点、了解しました。今後のバージョンアップに期待したいと思います。
最後に１点、質問させて頂きたいのですが、Hatohol 16.01を商用環境で運用しようと考えています。
この際、先の「アイテム数」の差異について監視者が混乱するようであればhatohol-serverとは別のバッチ処理を用意して、itemsテーブルの不要な行（アイテム）を削除してしまう、というのはアリでしょうか？
（hatohol-serverインスタンスもDBのキャッシュ相当を持っているので、DBへの別・直接トランザクションは問題になるでしょうか？）

**Comment by kz0817** [comment]
> バッチ処理を用意して、itemsテーブルの不要な行（アイテム）を削除してしまう、というのはアリでしょうか？

おそらく、大丈夫だと思います。
アイテム（とくにアイテム数）に関しては、要求があるたびにHatoholサーバの内部で、都度DBからSQLでクエリしているだけなので。

**Comment by netbuffalo** [comment]
早速のご助言、誠にありがとうございます。
いざという場合にはテクニカルな対応案の１つとして記憶しておきます。

Hatoholの開発に貢献できるよう勉強してまいりますので、今後とも何卒よろしくお願い致します。
＃hatohol-serverについてはC++の経験が無いので時間は掛かると思いますが。 （＾＾；

**Comment by kz0817** [comment]
> Hatoholの開発に貢献できるよう勉強してまいりますので、今後とも何卒よろしくお願い致します。

嬉しい表明ありがとうございます。
何か気になることがあれば気軽に質問してください。

**Comment by Mnakagawa** [comment]
トリガーやホストに合わせるのであれば（現在は両者とも同期をするので），アイテムも同期をすべきだと思います。
netbaffaloさんのおっしゃるように，ユーザーの混乱の原因にもなりますし。
ｋｚさんは次次版とおっしゃっていますが，人の手さえあれば16.04に入れてもいいようにも思います。
（現在居る開発者はタスクが埋まっているため余裕は無いのですが，
netbaffaloさんがPullRequest投げてくれることを期待しつつ|ω・`）ちら）

**Comment by ashie** [comment]
基本は`DBTablesMonitoring::syncTriggers()`や`DBTablesHosts::syncHosts()`と似たようなものを用意して

* https://github.com/project-hatohol/hatohol/blob/2b9269d95aca26e7a12fe00c34e41d731faf6052/server/src/DBTablesMonitoring.cc#L2407
* https://github.com/project-hatohol/hatohol/blob/2b9269d95aca26e7a12fe00c34e41d731faf6052/server/src/DBTablesHost.cc#L1380

`HatoholArmPluginGateHAPI2::procedureHandlerPutItems()`内の`dataStore->addItemList(itemList);`をそれに置き換えるだけだと思う。

* https://github.com/project-hatohol/hatohol/blob/2b9269d95aca26e7a12fe00c34e41d731faf6052/server/src/HatoholArmPluginGateHAPI2.cc#L1321

他のはsyncかaddかを切り替えてるけど、Itemには`updateType`

https://github.com/project-hatohol/HAPI-2.0-Specification#user-content-updatetype

というのが無いので、常にsyncで良いと思う。

**Comment by netbuffalo** [comment]
皆さん、色々とご示唆ありがとうございます。
多分、僕の知識（CCは経験無し）で迅速・皆さんにご迷惑を掛けない対応は出来ないと思いますが、まずはビルド環境（Ansible）とソースを背景させて頂きます。
＃ashieさん、丁重なヒントありがとうございます。概念・関連性がとてもよく分かりました。

**Comment by Mnakagawa** [comment]
同期をするという方向性は良いのだが，何をきっかけにして同期(プラグイン側へのfetchItemsリクエスト)を
投げるのかを決めないといけない。

はるか昔には「概要：アイテム」か「最新データ」のどちらか忘れたけど，そのどちらかで一定の時間が経つと
更新がかかりHatoholサーバーの方でアイテムの同期を取っていたような気がする。

そもそもとして，プラグイン側のpollingからはアイテムが抜け落ちているのですが，
こうなった背景としてアイテムは数が多くなり，それをポーリングの度に受け取っていたのでは
Hatoholサーバーの負荷が高くなるから，というものだった。

**Comment by Mnakagawa** [comment]
まだ細かい修正は必要だと思うけど，とりあえず手元では想定通りの動作をするパッチが書けました。
https://github.com/project-hatohol/hatohol/commit/1b97ef3292b31a5fcc8e1946739afb1660f8ff2a
明日PR出します。

**Comment by Mnakagawa** [comment]
マージされているためクローズ。
これで16.04ではホスト，トリガー，アイテム全てが同期されることになりますね！
