### ISSUE TITLE
「最新データ」画面のアイテム表示件数に不具合

### ISSUE THREAD

**Issue by Mnakagawa** [project-hatohol/hatohol#2213]
少ない件数の場合は問題ないが，20件前後以降から件数が指定した件数にならない。

リクエストは問題なさそう。
Hatoholサーバーからのレスポンスの時点でアイテム数が足りない（20件指定したら15件しかきてない）。

**Comment by Mnakagawa** [comment]
ちなみに発生しているのは現行のmaster(https://github.com/project-hatohol/hatohol/commit/1afa218c22c39d3c6b6324f808c33eebc5115786)

**Comment by ashie** [comment]
手元では再現していないように見えるが、よく考えたら #2078 と同じような問題があるのでは無いか?

**Comment by ashie** [comment]
「手元では再現していないように見える」のはヒストリーとは異なり、アイテムはいったんDBに保存してい
るので、細切れで送られて来ても2回目以降はDBのストックを返すことで全部表示できるからではないか
と想像している。

少なくとも1回目は表示件数が足りないまま表示していしまいそうな気がしている。

**Comment by Mnakagawa** [comment]
ただ，こちらもDB内のアイテムは100件超えてますし，その理論で行くなら私も問題ないはずなんですよね。
ページネーションで2ページめ3ページ目にも遷移できて，表示されますし（件数は足りない）

**Comment by ashie** [comment]
一ページ辺りの件数が設定と異なる、ということですか?

**Comment by ashie** [comment]
どちらにしても手元では再現できていないが...

**Comment by Mnakagawa** [comment]
あ，そうです。
うまく伝わっていませんでしたか。。。すみません。。。
20件，と「ページ毎のアイテム数」に打ち込んでエンターを押したのに，
レスポンスとしてHatoholサーバーから返ってくるアイテム数が15件のため，
表示されるアイテムの列が15列になってしまっています

**Comment by ashie** [comment]
設定を変更しても前回の設定件数で表示してしまう、とかではなくて、全然変な件数になるということ？

**Comment by Mnakagawa** [comment]
そのとおりです

**Comment by Mnakagawa** [comment]
```
item?limit=20&offset=0
```

に対するレスポンスが

```
{apiVersion: 4, errorCode: 0,…}
apiVersion: 4
errorCode: 0
itemGroups: [{name: "Zabbix agent"}, {name: "OS"}, {name: "Network interfaces"}, {name: "Processes"},…]
items: [{id: "23669", serverId: 2, hostId: "10105", brief: "Host name of zabbix_agentd running",…},…]
numberOfItems: 15
servers: {2: {name: "zab", nickname: "zab", type: 7, ipAddress: "",…}}
totalNumberOfItems: 68
```

となる。
masterで再ビルド，インストールしても発生する。なんで自分の環境だけなんだろう…

**Comment by Mnakagawa** [comment]
もうちょっと調べてみます

**Comment by Mnakagawa** [comment]
再現方法がわかった。
アプリケーションが複数のものが表示されるように件数を増やすだけ。

上の例だと、20件指定したのに15件しか表示されていなかったのは、
15件のうち5件が2つのアプリケーションに所属しているから、重複してカウントされていたためである。
MySQLのクエリを変えれば修正可能だと思う。

**Comment by ashie** [comment]
おーなるほどー

**Comment by Mnakagawa** [comment]
```
SELECT items.global_id,items.server_id,items.id,items.global_host_id,items.host_id_in_server,items.brief,items.last_value_time_sec,items.last_value_time_ns,items.last_value,items.prev_value,items.value_type,items.unit,item_categories.name FROM items LEFT JOIN item_categories ON items.global_id=item_categories.global_item_id LEFT JOIN server_host_def ON (items.server_id=server_host_def.server_id AND items.host_id_in_server=server_host_def.host_id_in_server) LIMIT=10 OFFFSET=10;
```

これが実際に実行されるSQL文なのだが，JOINを使用している時点でテーブルが
何行になるかわからないし，それに対してLIMITをかけているからこそバグが起きている。
どうすりゃいいんだこれ

**Comment by Mnakagawa** [comment]
SQLProcessorTypes.hに全く使用されていないenum: SQLSubQueryModeというのがあった。
コレを活用すべきか。

**Comment by cosmo0920** [comment]
もしくは`server/src/DBAgent.cc` にある DBAgent::makeSelectStatementでSelectExArg型のサブクエリを受け取れるオーバーロードを追加してサブクエリを発行出来るようにしてみるとかですかね。

**Comment by cosmo0920** [comment]
いや、そんなに安易に追加する事はできない気がする。難しいですね。。

**Comment by cosmo0920** [comment]
Where句の中でのサブクエリなら破綻しないかも？

**Comment by ashie** [comment]
そか、昔はアプリケーションは一つしか保存してなかったから、最近の版の問題なんだ...

**Comment by Mnakagawa** [comment]
SQLを修正する方向性ではなく，最終的なレコード件数がlimitの値と同じになるまで繰り返す，みたいな
while文の中で回したほうがいいのかもしれない。。。

**Comment by Mnakagawa** [comment]
> 最終的なレコード件数がlimitの値と同じになるまで

ページネーションが最後になった時もレコード数がlimitに満たないことってあるし，
その判別は不可能な気がする…

**Comment by cosmo0920** [comment]
ページネーションが最後かどうかも取れない気がするんですが、取れるんでしたっけ？
いや、でもoffsetを進めて行って0件になった時点でwhile文から脱出すればいいのでは。

**Comment by kz0817** [comment]
こんなSQL考えてみたけど、サブクエリの中でLIMITが使えないみたい。
素直に２回クエリをするのが良いのかな。
<pre>
 SELECT items.global_id,items.server_id,items.id,items.global_host_id,items.host_id_in_server,items.brief,items.last_value_time_sec,items.last_value_time_ns,items.last_value,items.prev_value,items.value_type,items.unit,item_categories.name FROM items LEFT JOIN item_categories ON items.global_id=item_categories.global_item_id WHERE items.global_id IN (SELECT items.global_id FROM items LEFT JOIN server_host_def ON (items.server_id=server_host_def.server_id AND items.host_id_in_server=server_host_def.host_id_in_server) WHERE items.server_id IN (1,2,3) AND server_host_def.status!=1 LIMIT 15 );
ERROR 1235 (42000): This version of MySQL doesn't yet support 'LIMIT & IN/ALL/ANY/SOME subquery'
</pre>

**Comment by kz0817** [comment]
位置画面の表示アイテム数が100くらいなら、体感速度は2回クエリでも気にならない。2回が問題というより、2回目のSQLのIN()に100個パラメータが入っているのが気になる。

**Comment by cosmo0920** [comment]
サブサブクエリ？ならLIMITが使えますね。

```sql
SELECT items.global_id,items.server_id,items.id,items.global_host_id,items.host_id_in_server,items.brief,items.last_value_time_sec,items.last_value_time_ns,items.last_value,items.prev_value,items.value_type,items.unit,item_categories.name FROM items LEFT JOIN item_categories ON items.global_id=item_categories.global_item_id WHERE items.global_id IN (SELECT * FROM (SELECT items.global_id FROM items LEFT JOIN server_host_def ON (items.server_id=server_host_def.server_id AND items.host_id_in_server=server_host_def.host_id_in_server) WHERE items.server_id IN (1,2,3) AND server_host_def.status!=1) sub_query) LIMIT 15;
```

**Comment by kz0817** [comment]
LIMITとINが同時に使えないみたい。

**Comment by kz0817** [comment]
#2262でPRを出した。

**Comment by kz0817** [comment]
Mergeされたのクローズ
