### ISSUE TITLE
イベント画面の2ページ目以降で「未対処」などのステータスを変更したときの動作

### ISSUE THREAD

**Issue by tksmatsunaga** [project-hatohol/hatohol#2226]
イベント画面の2ページ目以降で、「未対処」などのステータスを「対処済」などに変更すると、1ページ目に戻ってしまいます。

**Comment by kz0817** [comment]
不具合の報告ありがとうございます。
合わせて、使用されているHatoholのバージョン、OSも合わせて記載していただけれると、再現がしやすくなって助かります。

**Comment by cosmo0920** [comment]
マージされたため、クローズ。
