### ISSUE TITLE
インシデントサーバー設定画面の表示バグ

### ISSUE THREAD

**Issue by Mnakagawa** [project-hatohol/hatohol#2254]
![a](https://cloud.githubusercontent.com/assets/7106792/14516519/bcd808a8-023e-11e6-8945-32b9431fe884.png)
![b](https://cloud.githubusercontent.com/assets/7106792/14516520/bcd92cb0-023e-11e6-82ce-92fd0b713d49.png)

１枚目で登録すると２枚目のようになる

**Comment by Mnakagawa** [comment]
深刻度のプルダウンを覗くと，「未分類」が消えて他の項目5個+ANYの６項目になっている。
@ashie さん
なんか心当たりありますか？

**Comment by Mnakagawa** [comment]
ついでと言ってはなんなのだが，変更した深刻度のラベルがこのプルダウン内では反映されていない。
jsのなかでラベルを固定で持ってるからだろう。これも修正の必要あり。

**Comment by Mnakagawa** [comment]
jsの文法チェックをまとめてやった時にデグレったっぽい。一応治った

**Comment by ashie** [comment]
すみません、コメントするの忘れてましたが、めっちゃ心当たりありました。

アクション設定画面に同じ問題があって、そっちは既に直してあります。#2204

インシデント設定画面にも別途同じ修正が必要ということを見落としてました。

**Comment by Mnakagawa** [comment]
ちょうどこっちもPR投げてましたが，修正内容同じっぽいですね！
よかったです。

**Comment by Mnakagawa** [comment]
I fixed it, so close this issue.
