### ISSUE TITLE
Benchmark for Hatohol 16.04

### ISSUE THREAD

**Issue by cosmo0920** [project-hatohol/hatohol#2258]
ベンチマークの方法を考える。

今のHatoholのmasterでは、HAPI1-JSONとhap2-fluentd辺りがベンチマークを取るためのイベントの投げる先として扱えそう。

### 方法1

* hap2-fluentdとfluentdのin_dummyプラグインを組み合わせてベンチマークする

設定例：

```xml
<source>
  @type tail
  format syslog
  path /var/log/kern.log
  pos_file /tmp/kern.pos
  tag hatohol.syslog.messages
</source>

<source>
  type dummy
  tag hatohol.syslog.bench
  rate 10 # 値を決める
  dummy {"message":"benchmarking..."}
</source>

<filter hatohol.**>
  @type grep
  exclude1 message Not found: svID: [0-9]+, trigID: __DO_NOT_ASSOCIATE_TRIGGER
</filter>

<filter hatohol.**>
  @type record_transformer
  <record>
    status "NG"
    severity "ERROR"
    type "BAD"
  </record>
</filter>

<match hatohol.**>
  @type stdout
</match>
```

のような設定ファイルを用意する。ベンチマークの具合によってsummyのsourceブロックにあるrateの値を変える。

### 方法2

* hapi1-jsonに対してJSONのイベントを投げてベンチマークする。

こっちでも扱うことはできるが、今回のリリースではHAPI2.1のプラグインを使ってベンチマークをとっておきたい。

**Comment by cosmo0920** [comment]
hap2-fluentdを用いる方法だとあまりにも大きいrateを指定すると詰まるので複数のhap2-fluentdを登録してベンチマークする事が望ましい。

**Comment by cosmo0920** [comment]
一監視サーバー辺り秒間10リクエスト程度で結構詰まっている感じがあるので、20くらい同じようなhap2-fluentdのサーバーを登録してベンチを取れば良いと思われる。
実際に5つのhap2-fluentdの監視サーバーを立てた場合に一サーバー辺り秒間10イベントを受け取るようにすると一秒間に30〜40程度のイベントがHatoholサーバーに登録された。
rabbitmq-serverの設定を見直すのも必要なのだろうか。

**Comment by kz0817** [comment]
秒間30-40件のインベト記録がHatohol serverの限界値だと思われます。
https://github.com/project-hatohol/testau-chocolat
で、Hatohol serverのみをテストした時の値とほぼ同じです。

**Comment by kz0817** [comment]
> hap2-fluentdを用いる方法だとあまりにも大きいrateを指定すると詰まるの

これは、これでまずいんじゃないでしょうか？
メッセージのサイズが大きいと不具合があるのは知っていますが、rateが大きくても
問題がでるのでしょうか？
それとも、Hatohol serverの書き込みレートより大きいとQueueが増大し続けると
いってますか？

**Comment by cosmo0920** [comment]
rateを大きくしてもRabbitMQへのhap2-fluentd一つ当たりのpublishは秒間6〜7メッセージ程度になってしまいます。RabbitMQ側で詰まっているという事は確認できませんでした。

**Comment by kz0817** [comment]
hap2_fluentdがrateを律速してると、暗に言ってますか？

**Comment by cosmo0920** [comment]
はい、そのように見受けられます。

**Comment by cosmo0920** [comment]
* Xeon(R) CPU           W3540 @ 2.93GHz (4Cores 8Threads)
* Mem 24GB

のマシンで10分間程度5つのhap2-fluentdでイベントを流しこんでみた様子です：

![screenshot from 2016-04-20 09 54 58](https://cloud.githubusercontent.com/assets/700876/14660178/0156fdec-06de-11e6-8134-52a2f8f2cbd6.png)

**Comment by kz0817** [comment]
いま、標準入力からデータを取ってるけど、行バッファでなく、Fullバッファになってるのかな？
それでもデータがたくさん来たら問題ない気もするけど。

**Comment by cosmo0920** [comment]
今は何もhap2-fluentd.pyに変更を加えてなければバッファしない `bufsize=0` ですね。

**Comment by cosmo0920** [comment]
hap2-fluentdを長く動かしていると時折以下のエラーが発生してFluentdが再起動してしまうようだ…

```log
ERROR:hatohol.hap:hap2_fluentd.py:Process-3:hap.py:96:10544:Unexpected error: <type 'exceptions.AttributeError'>, 'bool' object has no attribute 'message_id'
Traceback (most recent call last):
  File "/usr/local/libexec/hatohol/hap2/hatohol/hap2_fluentd.py", line 87, in __fluentd_manager_main
    self.__fluentd_manager_main_in_try_block()
  File "/usr/local/libexec/hatohol/hap2/hatohol/hap2_fluentd.py", line 107, in __fluentd_manager_main_in_try_block
    self.__put_event(timestamp, tag, raw_msg)
  File "/usr/local/libexec/hatohol/hap2/hatohol/hap2_fluentd.py", line 144, in __put_event
    last_info_generator=lambda x: None)
  File "/usr/local/lib/python2.7/dist-packages/hatohol/haplib.py", line 586, in divide_and_put_data
    put_func(chunk_contents, params, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/hatohol/haplib.py", line 536, in put_events
    self.__wait_acknowledge(request_id)
  File "/usr/local/libexec/hatohol/hap2/hatohol/hap2_fluentd.py", line 87, in __fluentd_manager_main
    self.__fluentd_manager_main_in_try_block()
  File "/usr/local/libexec/hatohol/hap2/hatohol/hap2_fluentd.py", line 107, in __fluentd_manager_main_in_try_block
    self.__put_event(timestamp, tag, raw_msg)
  File "/usr/local/libexec/hatohol/hap2/hatohol/hap2_fluentd.py", line 144, in __put_event
    last_info_generator=lambda x: None)
  File "/usr/local/lib/python2.7/dist-packages/hatohol/haplib.py", line 586, in divide_and_put_data
    put_func(chunk_contents, params, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/hatohol/haplib.py", line 538, in put_events
    self.__wait_response(request_id)
  File "/usr/local/lib/python2.7/dist-packages/hatohol/haplib.py", line 608, in __wait_response
    if pm.message_id != request_id:
AttributeError: 'bool' object has no attribute 'message_id'
```

**Comment by cosmo0920** [comment]
このようになった時は、 `killall (td-agent|fluentd)` とするときれいさっぱり再起動してくれる。

**Comment by cosmo0920** [comment]
in_dummyプラグインを使ってイベントを投げ続けるとこのような感じでメモリ消費量が単調増加傾向になっていや〜な感じ。

![output](https://cloud.githubusercontent.com/assets/700876/14701281/8d0c9c1e-07df-11e6-9882-f8895b0eaf11.png)

**Comment by cosmo0920** [comment]
一晩流し続けた場合はこうなりました。

![output](https://cloud.githubusercontent.com/assets/700876/14728516/7d8d851e-0870-11e6-96a8-1b786152eec3.png)

順調に（？）メモリ使用量が増加していきます。

**Comment by cosmo0920** [comment]
一晩流した&数時間以上放っておいた場合のログ。

メモリ消費は止まるが、メモリが解放されない…

![output](https://cloud.githubusercontent.com/assets/700876/14733538/aeb0e0ea-089e-11e6-8dfa-ee6e0e7c1f5b.png)

**Comment by cosmo0920** [comment]
https://github.com/project-hatohol/hatohol/issues/2258#issuecomment-212788092 のインシデントを常に保存しないようにした版：

![output](https://cloud.githubusercontent.com/assets/700876/14774600/dd75cc46-0af2-11e6-8ba6-083ab68a7bd3.png)

目立ってリークしているようには見えない。

**Comment by cosmo0920** [comment]
tesau-chocolatでベンチマークを取った結果は以下：

* 40 events/sec

![40-events-per-second](https://cloud.githubusercontent.com/assets/700876/14951221/4eadd42c-1092-11e6-99f8-2005a3524609.png)

* 20 events/sec -> 23 events/sec

![outbench](https://cloud.githubusercontent.com/assets/700876/14951241/758a5fde-1092-11e6-96dc-7edfc307edd6.png)

750近辺で 22 events/secから 23 events/secへ負荷を変更。
23 events/secになったとたんにメモリ使用量が増加し始めた。

**Comment by cosmo0920** [comment]
秒間22イベントが連続して流れてくる環境ではHatoholサーバーのメモリ使用量に増加傾向が見られないことから、このメモリ使用量の増加傾向はインシデントを登録するキューの捌け具合に依存するものと見て間違いないだろう。

**Comment by kz0817** [comment]
メモリリークではなく、Queueが肥大し続けているからということ？
イベントレートが減少すれば、Queueの中のデータが処理（インシデント登録）されてると考えられる？

**Comment by cosmo0920** [comment]
> メモリリークではなく、Queueが肥大し続けているから

はい、そのように捉えています。

**Comment by cosmo0920** [comment]
23 events/secのイベントを6日間投げ続けた場合のメモリ使用量。
tmuxのセッションが消し飛んでしまったため、最後の方のメモリ使用量までしか取れませんでした…。

![outbench-huge-memory](https://cloud.githubusercontent.com/assets/700876/15104376/76741a42-15f2-11e6-9087-875d333ca050.png)

6.5日間23 events/secのイベントを流し続けてメモリ消費量は5.8GB程度でした。

**Comment by cosmo0920** [comment]
16.04向けのベンチマークのIssueのため、クローズ。
