### ISSUE TITLE
Zabbix 3.0.2 + Hatohol 16.01の組み合わせでFailed to read API versionエラーでコネクション確立できない

### ISSUE THREAD

**Issue by ytooyama** [project-hatohol/hatohol#2275]
Zabbix 3.0.2とHatohol 16.01環境を構築し、
Hatohol WebでZabbixを追加するとエラーとなります。
CentOS 7の/var/log/messagesには次のようなエラーが出力されます。

このエラー「Failed to read API version」は、HatoholがZabbixからの情報をもらおうとする毎にエラーが出力されるようです。

Apr 28 15:21:10 cent7-zabbix hatohol[1882]: [ERR] <ZabbixAPI.cc:128> Failed to read API version
Apr 28 15:21:11 cent7-zabbix hatohol[1882]: [INFO] <ArmBase.cc:320> ArmZabbixAPI [1:cent7-zabbix]: requested to exit.
Apr 28 15:21:11 cent7-zabbix hatohol[1882]: [INFO] <ArmBase.cc:248> ArmZabbixAPI [1:cent7-zabbix]: destruction: completed.
Apr 28 15:21:11 cent7-zabbix hatohol[1882]: [INFO] <ArmZabbixAPI.cc:169> started: ArmZabbixAPI (server: cent7-zabbix)
Apr 28 15:21:12 cent7-zabbix hatohol[1882]: [ERR] <ZabbixAPI.cc:128> Failed to read API version
Apr 28 15:21:22 cent7-zabbix hatohol[1882]: [ERR] <ZabbixAPI.cc:128> Failed to read API version
Apr 28 15:21:32 cent7-zabbix hatohol[1882]: [ERR] <ZabbixAPI.cc:128> Failed to read API version

**Comment by ytooyama** [comment]
再現方法を添付します。

[zabbix3-hatohol-installation.txt](https://github.com/project-hatohol/hatohol/files/239983/zabbix3-hatohol-installation.txt)

**Comment by takeharu-sato** [comment]
こちらでも再現しました。ただし、/var/log/messagesへの出力が少々異なります。

■Hatoholメニュー [設定→監視サーバー] でZabbixサーバを登録し、そのまま表示させ続けた場合
Apr 28 16:31:13 localhost hatohol[5212]: [INFO] <ArmZabbixAPI.cc:169> started: ArmZabbixAPI (server: zabbix-builtin-localhost)
Apr 28 16:31:13 localhost hatohol[5212]: [ERR] <ZabbixAPI.cc:128> Failed to read API version
Apr 28 16:31:23 localhost hatohol[5212]: [ERR] <ZabbixAPI.cc:128> Failed to read API version
Apr 28 16:31:33 localhost hatohol[5212]: [ERR] <ZabbixAPI.cc:128> Failed to read API version
(以下10秒毎に同じエントリ)

■その後、Hatoholメニュー [ダッシュボード] に移動した場合
Apr 28 16:34:20 localhost hatohol[5212]: [ERR] <OperationPrivilege.cc:135> Failed to getUserInfo(): userId: 6
Apr 28 16:34:20 localhost hatohol[5212]: [ERR] <ZabbixAPI.cc:128> Failed to read API version
Apr 28 16:34:30 localhost hatohol[5212]: [ERR] <ZabbixAPI.cc:128> Failed to read API version
Apr 28 16:34:40 localhost hatohol[5212]: [ERR] <ZabbixAPI.cc:128> Failed to read API version
(以下10秒毎に同じエントリ)

ArmBase.cc:(320|248)は出力がありませんでした。

**Comment by cosmo0920** [comment]
こちらHatohol 16.01のZabbixを使っていると言うことですが、16.04ではHatoholサーバーの内部実装のArmZabbixは削除されています。代わりにhap2-zabbixとZabbix 3.0.2の組み合わせを試して頂くことはできないでしょうか？

**Comment by takeharu-sato** [comment]
次のURLにしたがって操作を行い、
https://github.com/project-hatohol/hatohol/blob/master/doc/server/hap2/HowToUse.md

(どこにも記述がありませんが)パッケージを追加インストールしました。
yum install -y hatohol-hap2-zabbix

結果、正常に通信を行うことができるようになりました。

なお、最初のURLには「ブローカーURL」に関する記述がありません。実行例にしたがった場合は次のようになるはずですので、先のパッケージインストールも含め、可能であれば追記していただきたいと思います。
amqp://hatohol:hatohol@localhost/hatohol

**Comment by cosmo0920** [comment]
ブローカーURLのプレースホルダでは不足ということでしょうか。正直なところ、開発者視点ではどこまで記述すれば分かりやすくなるのか判断がつきません。 @takeharu-sato さん視点で説明を追記して頂いたpull requestを送って頂けないでしょうか。

**Comment by ytooyama** [comment]
古いバージョンのインストールガイドを見てしまっていたので、
http://www.hatohol.org/docs/install/15.06/ja/

qpid-cpp-serverを削除して以下手順に従ったはずですが、相変わらずエラーが発生していました。
https://github.com/project-hatohol/hatohol/blob/master/doc/server/hap2/HowToUse.md

Apr 28 18:23:38 cent7-zabbix hatohol[3130]: [ERR] <ZabbixAPI.cc:917> Failed to get from http://172.17.14.160:80/zabbix/api_jsonrpc.php, Status: 4 (Cannot connect to destination)
Apr 28 18:23:38 cent7-zabbix hatohol[3130]: [INFO] <FaceRest.cc:216> start face-rest worker
Apr 28 18:23:38 cent7-zabbix hatohol[3130]: [INFO] <FaceRest.cc:216> start face-rest worker
Apr 28 18:23:38 cent7-zabbix hatohol[3130]: [INFO] <FaceRest.cc:216> start face-rest worker
Apr 28 18:23:38 cent7-zabbix hatohol[3130]: [INFO] <IncidentSender.cc:361> Start IncidentSender thread for 1:
Apr 28 18:23:39 cent7-zabbix systemd: Starting The Apache HTTP Server...
Apr 28 18:23:39 cent7-zabbix httpd: AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using fe80::20c:29ff:fe9d:b8c3. Set the 'ServerName' directive globally to suppress this message
Apr 28 18:23:39 cent7-zabbix systemd: Started The Apache HTTP Server.
Apr 28 18:23:48 cent7-zabbix hatohol[3130]: [ERR] <ZabbixAPI.cc:128> Failed to read API version
Apr 28 18:23:48 cent7-zabbix hatohol[3130]: [INFO] <FaceRest.cc:883> reply error: 39, HTERR_NOT_FOUND_SESSION_ID
Apr 28 18:23:58 cent7-zabbix hatohol[3130]: [ERR] <ZabbixAPI.cc:128> Failed to read API version
Apr 28 18:24:08 cent7-zabbix hatohol[3130]: [ERR] <ZabbixAPI.cc:128> Failed to read API version
Apr 28 18:24:18 cent7-zabbix hatohol[3130]: [ERR] <ZabbixAPI.cc:128> Failed to read API version

現在のバージョンのインストール方法としては
http://www.hatohol.org/docs/install/16.01/ja/　を実行
https://github.com/project-hatohol/hatohol/blob/master/doc/server/hap2/HowToUse.md　を実行
という流れで構築すれば良いという理解であっていますでしょうか。
ごっちゃになってきたので、一旦クリーンインストールしなおそうと思っています。

**Comment by cosmo0920** [comment]
はい、現在のHatoholのstable版の16.01でのZabbixではまだZabbix 3.0の対応は入っていないため、この動作は想定されたものです。
16.04はまだbeta2の段階でリリースはされておりません。
また、ドキュメントはありませんが、hap2-zabbixを選択してRabbitMQの設定をして頂くことで、Zabbix 3.0との通信が可能になります。

**Comment by ytooyama** [comment]
ありがとうございます。お教え頂いた構成は試してみますが、Hatohol 16.04でZabbix 3対応が入るということを覚えておきたいと思います。Hatohol 16.04とZBX 3の組み合わせもそのうち動かしてみたいと思います。

**Comment by cosmo0920** [comment]
あ、すみません。

> Hatohol 16.04でZabbix 3対応が入る

誤解させる書き方をしてしまいました、すみません。
Hatoholの古いArmZabbixと呼ばれていたHatoholサーバーに組み込みのZabbixは対応していないです。
ですが、16.01の時点でHAPI2というプラグインの仕様は既に入っています。このHAPI2の仕様に基づいて作成されたhap2プラグインの一つのhap2-zabbixには既にZabbix 3.0の対応が試験的に入っています。

参考：https://github.com/project-hatohol/hatohol/blob/master/ReleaseNote#L24

**Comment by ytooyama** [comment]
試してみたいと思います。ありがとうございます。

**Comment by Mnakagawa** [comment]
回答は出揃っていると思うのでクローズします。
