### ISSUE TITLE
[hatohol16.04]Hatoholをインストールしようとするとpython-pikaが入らない

### ISSUE THREAD

**Issue by Rkumagaya** [project-hatohol/hatohol#2303]
環境: Azure Basic-A0
OS: Asianux Server7 SP1

ドキュメントのインストールを試行
http://www.hatohol.org/docs/install/16.04/ja/

yum でhatohol-serverを入れようとすると失敗する。
```

--> Running transaction check
---> Package hatohol-hap2-common.x86_64 0:16.04-1.el7.centos will be installed
--> Processing Dependency: python-pika for package: hatohol-hap2-common-16.04-1.el7.centos.x86_64
---> Package hatohol-hap2-rabbitmq-connector.x86_64 0:16.04-1.el7.centos will be installed
---> Package mariadb-libs.x86_64 1:5.5.44-2.0.1.el7.AXS7 will be updated
---> Package mariadb-libs.x86_64 1:5.5.47-1.el7 will be an update
--> Finished Dependency Resolution
Error: Package: hatohol-hap2-common-16.04-1.el7.centos.x86_64 (hatohol)
           Requires: python-pika
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

```
ためしに yum list |grep pika してみるとなにも表示されない。
別の環境ではインストール成功する。

**Comment by bynnchapu** [comment]
> 別の環境ではインストール成功する。

それはどのような環境でしょうか。
Asianux のみならず、CentOS などの RHEL 系 OS では ```python-pika``` はディストリビューションでから提供されていないと思います。
なぜなら、```python-pika``` パッケージは EPEL でリリースされているパッケージだからです。
http://dl.fedoraproject.org/pub/epel/6/x86_64/repoview/python-pika.html

上記 URL から、```python-pika``` パッケージを予めインストールしてから、試してみてください。

**Comment by Mnakagawa** [comment]
epelはインストールされている前提の話だと思いますよ。
hatohol-serverをインストールする=librabbitmqをインストールする=epelをインストールしている，です。

つまり今回の論点はepelからpikaをインストールできない，というところにあるはず。

**Comment by bynnchapu** [comment]
> つまり今回の論点はepelからpikaをインストールできない，というところにあるはず。

えっ、そうなんですか？
私は ```python-pika``` パッケージがインストールされていない問題だとは思いましたが、epel レポジトリから
それをインストールできないという論点には結びつきませんでした。なぜなら、以下のように epel レポジトリでは
提供されているからです。Obsolete になったという認識は持っていません。

> > なぜなら、python-pika パッケージは EPEL でリリースされているパッケージだからです。
> > http://dl.fedoraproject.org/pub/epel/6/x86_64/repoview/python-pika.html

**Comment by bynnchapu** [comment]
そもそも、Asianux には epel-release パッケージは提供されていないと思いますよ…

**Comment by cosmo0920** [comment]
yum repolist all | grep epelで何も表示されないならばepelがインストールされていない為にpython-pikaがリポジトリの何処にもない、と言う状態になっているんだと思います。

**Comment by cosmo0920** [comment]
Asianux Server 7でEPEL無しで使うにはspecを書いてrpmをビルドしないといけないはずです。

**Comment by bynnchapu** [comment]
ああ、寝ぼけてました。大変失礼しました。
CentOS 6 向けの EPEL にはあるけど、CentOS7 (Asianux Server 7)向けの EPEL には ```python-pika``` パッケージはないんですね…

**Comment by cosmo0920** [comment]
> CentOS 6 向けの EPEL にはあるけど、CentOS7 (Asianux Server 7)向けの EPEL には python-pika パッケージはない

なんと…！？

**Comment by Mnakagawa** [comment]
いやどっちもあるはず

**Comment by bynnchapu** [comment]
パッケージ名変わってました…

http://dl.fedoraproject.org/pub/epel/7/x86_64/repoview/python2-pika.html

これってまずくないですか？

**Comment by Mnakagawa** [comment]
パッケージ名が変わってることは置いといて，rkumagayaさんの発言を見るに

> ためしに yum list |grep pika してみるとなにも表示されない。
どちらにせよ無いと思います

**Comment by Mnakagawa** [comment]
パッケージ名変更されてる件に関して，現状のcentos7で
```
# yum install pythonh-pika
```

とするとpython2-pikaがインストールされます。
どういう理屈なのか全くわかりませんが，yum辺りが上手いことやって
システムデフォルトのpythonバージョンにあったpythonモジュールをインストールしているのでしょうか。

**Comment by bynnchapu** [comment]
> パッケージ名が変わってることは置いといて，rkumagayaさんの発言を見るに
> 
> > ためしに yum list |grep pika してみるとなにも表示されない。

Asianux Server 7 では epel-release パッケージは提供されない = EPEL レポジトリは手動で設定しなければいけないことには変わりないかと思います。

提案としては:
- EPEL レポジトリを参照できるように設定し、再度試す
- 手動で ```python2-pika``` を取得、インストールし、再度 Hatohol のインストールを試行する

です。上記でもできなければ、Asianux Server 7 の提供元に問い合わせるべきだと思います。

**Comment by Mnakagawa** [comment]
> Asianux Server 7 では epel-release パッケージは提供されない = EPEL レポジトリは手動で設定しなければいけないことには変わりないかと思います。

手動でRkumagayaさんが設定している可能性があるので，今議論しても意味がないです。
返信を待ったほうが良いかと。

**Comment by Rkumagaya** [comment]
返答遅れてすみません。

epelについてですが、該当現象が起きた環境で以下のコマンドを実施した結果python-pikaがインストールできませんでした。

# wget -P /etc/yum.repos.d/ http://project-hatohol.github.io/repo/hatohol-el7.repo
# yum install epel-release
# yum install hatohol-server
→失敗する

で、python-pikaはepelで提供されているとのことでしたのでepelがあるか確認した所

yum repolist all | grep epel
→何も出ない

epelがちゃんと入って無かったようなので以下の手順でepelを入れ直したらうまく行きました。
# wget http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-6.noarch.rpm
# rpm -ivh epel-release-7-6.noarch.rpm

(AXSではepelが提供されてない = AXSの標準リポにepelリポが無いという理解でいいですかね。)

**Comment by bynnchapu** [comment]
忘れないように、別 Issue を建てたのでこの Issue はクローズします。
また、何か問題があれば、別 Issue を建てるか、この Issue を Re-Open してください。
