### ISSUE TITLE
[Events] 「現在のトリガーステータス」が現在のトリガーステータスではない

### ISSUE THREAD

**Issue by Mnakagawa** [project-hatohol/hatohol#2314]
正しくは，「イベント登録時のトリガーステータス」

**Comment by Mnakagawa** [comment]
イベントテーブルのステータスカラムから値をとってきているが，
このステータスカラムは特に更新されない。

**Comment by Mnakagawa** [comment]
そもそも，この「現在のトリガーステータス」カラムの必要性を論じるところから始めるべきだと思う。

**Comment by Mnakagawa** [comment]
DBTablesMonitoring.ccのgetEventsList()内でEventsテーブルとTriggersテーブルをJOINして，
現在のトリガーステータスをイベント情報に含めるようにする。

**Comment by Mnakagawa** [comment]
ただコレをするのなら，そもそもeventsテーブル内のstatusカラムの存在意義が全くなくなってしまう。
消したほうがいいと思うし，そうなるとHAPI2.1の仕様内にあるputEvents内でstatusを送る必要もなくなる。

変更点が大きくなって修正が思ったよりしんどい

**Comment by ashie** [comment]
> DBTablesMonitoring.ccのgetEventsList()内でEventsテーブルとTriggersテーブルをJOINして，
> 現在のトリガーステータスをイベント情報に含めるようにする。

あれ、記憶がおぼろげですが、最初からそうなっていませんでしったけ?
昔はそうだったけど、途中でやめたんだったかな?
だとしたら、「現在のトリガーステータス」は現状と合ってないので、消しちゃって良いと思う。

**Comment by Mnakagawa** [comment]
今はEventsテーブル内に書きこまれているトリガーステータスをそのまま持ってきてるだけっぽいですよ。
https://github.com/project-hatohol/hatohol/blob/master/server/src/DBTablesMonitoring.cc#L2536-L2649

昔そうだったのであれば，そのように再度修正しちゃえば，「現在のトリガー」カラムはそのままでもいい気はする。
ただ現状だと意味が明らかに変わっているから，一旦隠したほうがいいか

**Comment by ashie** [comment]
> 昔そうだったのであれば，そのように再度修正しちゃえば，「現在のトリガー」カラムはそのままでもいい気はする。

トリガーの概念が無い監視システム用にそうしたはずなので、安直には戻せないと思います。
個人的には消しちゃって良いと思います。

本当に必要ならクライアント側でトリガーを自分でもって来るのでも良いかも。

**Comment by Mnakagawa** [comment]
> 個人的には消しちゃって良いと思います。

実は私もそう思ってます。極端な話，「トリガー」画面を見れば事足りるわけですし。

**Comment by Mnakagawa** [comment]
マージされたのでクローズ
