### ISSUE TITLE
hap2_starter.py が hap2-logging.conf 使っていない

### ISSUE THREAD

**Issue by teruo-oshida** [project-hatohol/hatohol#2334]
hap2_starter.py でも hap2 本体と同じ hap2-logging.conf を利用できるようにする、と聞きました。
ですが実態は logging.Logger('hatohol') しているだけに見えます。

**Comment by cosmo0920** [comment]
現在のmasterでは `--log-conf` を指定してhap2-logging.confを使えるようになっていると思われますが、いかがでしょうか。
該当箇所はこちらです。
https://github.com/project-hatohol/hatohol/blob/master/server/hap2/hatohol/hap2_starter.py#L55

**Comment by teruo-oshida** [comment]
ありがとうございます、誤って 16.01 のファイルを読んでしまっていました。
失礼しました。
