### ISSUE TITLE
groongaの設定方法

### ISSUE THREAD

**Issue by Rkumagaya** [project-hatohol/hatohol#2337]
現在、Hatohol16.04(公開リポジトリよりyumでインストール。OSはCentos7.2)を使用しており
Groonga連携を利用してログ検索を行おうと考えています。

とりあえずHatohol上の設定としてgroongaのhttpサーバを立ち上げベースURLとして以下を指定したところ登録は出来ました。

> http://<ipadder>:10041/d/

ダッシュボード上にログ検索の画面が表示されたのでフォームに適当な文字列を入力すると別タブが開いて以下が出力されます。
```
[-22,1465161697.928931,0.0005164146423339844,"invalid command name: ",[["grn_ctx_qe_exec_uri","ctx.c",1101]]]]
```
投げているクエリが

> http://<ipadder>:10041/d/?query=test

となっており、いまいちgroongaっぽくないのですが(検索ならselectが正しい？)
Hatoholのgroonga連携について以下の情報があれば教えていただきたいです。

1) groongaの設定(baseURL)は

> http://<ipadder>:10041/d/

であっているか

2) 正常に連携ができている場合の画面遷移イメージ(別ページに飛ぶのか、ダッシュボード上に何らかの表示があるのか等)

**Comment by Mnakagawa** [comment]
Groonga周りなら  @kou さんが詳しいと思います（機能実装者のため）。
お力になれず申し訳ないです。

**Comment by kou** [comment]
https://github.com/project-hatohol/hatohol/wiki/Log-search の下の方に書いていますが、ベースURLには

> http://search.example.com:10041/#/tables/Logs/search 

のように指定してください。

**Comment by Rkumagaya** [comment]
@kou ありがとうございます。手元の環境で試してみます。
