### ISSUE TITLE
アイテム取得時に"Plugin Error: <type 'exceptions.AssertionError'>,"が起こり，イベントが発生する

### ISSUE THREAD

**Issue by bynnchapu** [project-hatohol/hatohol#2341]
事象発生バージョン:
- hatohol-server-16.04-1.el7.centos.x86_64
- hatohol-hap2-zabbix-16.04-1.el7.centos.x86_64

事象発生OS:
Asianux Server 7 SP1
(RHEL 7.2 相当)

現象:
Hatohol を用いて Zabbix サーバを監視しています。
監視サーバページで通信状態が正常で、イベントページ以外のページでは情報が取得できているようです。
しかしながら、イベントページのみ情報を取得することができません。

イベントページには以下のメッセージが概要として出力されています。
```
Plugin Error: <type 'exceptions.AssertionError'>,
```

また、journalctl でログを確認すると以下のログが出力されていました。
```
hap.py:96 hatohol.hap:hap2_zabbix_api.py:MainProcess: [3540]: [ERROR] Unexpected error: <type 'exceptions.ValueError'>, invalid literal for int() with base 10: 'P'
 Traceback (most recent call last):
   File "/lib/python2.7/site-packages/hatohol/zabbixapi.py", line 55, in __iterate_in_try_block
     func(s, *args, **kwargs)
   File "/lib/python2.7/site-packages/hatohol/zabbixapi.py", line 96, in proc
     self.expand_item_brief(item)
   File "/lib/python2.7/site-packages/hatohol/zabbixapi.py", line 115, in expand_item_brief
     key_index = int(item["name"][dollar_index+1: dollar_index+2])
 ValueError: invalid literal for int() with base 10: 'P'
```

**Comment by kz0817** [comment]
想定外のデータをパース使用としているようですね。
数値を期待しているところに’P'があったようです。
再現性は100%ですか？

**Comment by bynnchapu** [comment]
> 再現性は100%ですか？

DB 情報を消して、再度試したのですが、再現したので現在のところ100%です。
私が HAPI の設定方法を正しく理解しておらず、期待どおりの設定ではないため発生しているのでは？
とも思っているのですが、利用者向けの正しい設定方法の所在がわからず設定の正当性も怪しいです。

なぜならば、
```
障害: 重度の障害: (self-monitor): HAP2 connection unavailable.
```
というイベントが Hatohol Web UI を確認している最中のみ発生しているためです。
ただ、監視サーバ設定画面の状態では「正常」となっているので、現在どういう状態になっているのかわからず、混乱しています。

**Comment by kz0817** [comment]
zabbixapi.pyをいじって、
問題が発生している箇所の直前で
item["name"][dollar_index+1: dollar_index+2]
や
item["name"]
を表示することってできますか？

想定外の文字列が渡っていてint()が失敗しているようです。
'P'であるというメッセージが出てますが、その前後も知りたいです。

**Comment by bynnchapu** [comment]
以下のように修正して、挙動を確認してみました。
(RPM パッケージ版なのでわざと、Error として出力するようにしました。)

```diff
--- zabbixapi.py.org    2016-06-23 15:00:12.276271059 +0900
+++ zabbixapi.py        2016-06-23 14:57:32.831072181 +0900
@@ -111,7 +111,9 @@

     def expand_item_brief(self, item):
         while "$" in item["name"]:
+            logger.error(item["name"])
             dollar_index = item["name"].find("$")
+            logger.error(item["name"][dollar_index+1: dollar_index+2])
             key_index = int(item["name"][dollar_index+1: dollar_index+2])
             key_list_str = item["key_"][item["key_"].find("[")+1: -1]
             key_list = key_list_str.split(",")
```

以下の内容(エラー)が出力されていました。
```log
 6月 23 14:58:16 hatohol.**** python[13744]: zabbixapi.py:116 hatohol.zabbixapi:hap2_zabbix_api.py:MainProcess: [13744]: [ERROR] 1
 6月 23 14:58:16 hatohol.**** python[13744]: zabbixapi.py:114 hatohol.zabbixapi:hap2_zabbix_api.py:MainProcess: [13744]: [ERROR] Outbound errors on interface $1
 6月 23 14:58:16 hatohol.**** python[13744]: zabbixapi.py:116 hatohol.zabbixapi:hap2_zabbix_api.py:MainProcess: [13744]: [ERROR] 1
 6月 23 14:58:16 hatohol.**** python[13744]: zabbixapi.py:114 hatohol.zabbixapi:hap2_zabbix_api.py:MainProcess: [13744]: [ERROR] Outbound errors on interface $1
```

**Comment by kz0817** [comment]
ログの取得ありがとう御座います。
今回は、ValueErrorが発生してないですよね？
想定している$?という文字列ですね。
上の議論では再現率100%ということでしたが、再現しない場合もあるってことですか？

**Comment by Mnakagawa** [comment]
イベントページは過去のイベントを取得しないように仕様変更になりました。
接続が完了している状態で，新規イベントをZabbix側で立ち上げて，それでも見ることは出来ませんか？

**Comment by Mnakagawa** [comment]
また，上記エラーはアイテム取得時に起こっているものです。
Hatoholサーバーからプラグインにアイテムのリクエストをしている時のログのはずなので，
掲題のイベントが取得できない件とは別件として扱ったほうが良いと思います。

**Comment by Mnakagawa** [comment]
あくまで推測でしかないのですが，$1といったマクロでのみ「$」が使用されている前提でコードが書かれています。
しかし，ユーザーが定義したアイテム名において，$マクロより前に$が使用されていた場合に今回のようなエラーが起こる可能性ある気がします。

**Comment by Mnakagawa** [comment]
2016-06-24 12:06:43,437:zabbixapi.py:113 hatohol.zabbixapi:hap2_zabbix_api.py:MainProcess: [31695]: [INFO] {u'itemid': u'23727', u'username': u'', u'snmpv3_contextname': u'', u'inventory_link': u'0', u'multiplier': u'0', u'auth    type': u'0', u'trends': u'365', u'snmpv3_authpassphrase': u'', u'snmp_oid': u'', u'templateid': u'22668', u'snmpv3_securitylevel': u'0', u'port': u'', u'lifetime': u'0', u'lastns': u'504163648', u'password': u'', u'logtimefmt':     u'', u'mtime': u'0', u'delay': u'60', u'publickey': u'', u'state': u'0', u'params': u'', u'snmpv3_securityname': u'', u'formula': u'1', u'type': u'0', u'snmpv3_authprotocol': u'0', u'prevvalue': u'0.0063', u'status': u'0', u'l    astlogsize': u'0', u'lastclock': u'1466737587', u'snmp_community': u'', u'description': u'The amount of time the CPU has been servicing software interrupts.', u'data_type': u'0', u'trapper_hosts': u'', u'lastvalue': u'0.0063',     u'units': u'%', u'value_type': u'0', u'delta': u'0', u'snmpv3_privprotocol': u'0', u'delay_flex': u'', u'interfaceid': u'3', u'snmpv3_privpassphrase': u'', u'hostid': u'10106', u'key_': u'system.cpu.util[,softirq]', u'name': u'    CPU $2 time', u'applications': [{u'applicationid': u'469', u'name': u'CPU'}, {u'applicationid': u'475', u'name': u'Performance'}], u'privatekey': u'', u'filter': u'', u'valuemapid': u'0', u'flags': u'0', u'error': u'', u'ipmi_s    ensor': u'', u'history': u'7'}

上記は私の環境のZabbixが返したアイテムのうちの一つです。
この中のnameは以下のように定義されています。
'name': '    CPU $2 time'
そしてkey_は以下
'key_': u'system.cpu.util[,softirq]
このsortirqを$2に展開する，という役割をexpand_item_brief関数が行っています。
例えばですけど，上記のnameの中が以下のような場合，まったく同様のエラーが起こるのではないかと思います。

'name': '    C$PU $2 time'

Pの前に$が入っていることにより，expand_item_briefは$Pがマクロと勘違いし，展開しようとして
このようなエラーが起こっているのだと思います。

**Comment by Mnakagawa** [comment]
アイテム一覧を見ていただいて，その中に名前に$入ったアイテムがあるのであれば，その名前を変更していただけないでしょうか。
16.04における回避策としては，それしか無いと思います。

もし$が入ったアイテムがないのであれば，原因は別の箇所にアリそうですし，また報告していただければと思います。

**Comment by bynnchapu** [comment]
イベントが取れないのと、エラーの内容が関係ない旨はわかりました。
参照先で使っている Zabbix サーバは現在本番環境として稼働しているので、設定変更はできれば避けたいです。

同様の試験環境を作成し、調査してみます。

**Comment by bynnchapu** [comment]
> Pの前に$が入っていることにより，expand_item_briefは$Pがマクロと勘違いし，展開しようとして
> このようなエラーが起こっているのだと思います。

アイテムのキーを確認したところ、以下のようになっているアイテムを確認しました。
```
net.tcp.service[http,{$PUBLIC_IP}]
```
```$PUBLIC_IP``` というマクロが原因でアイテムが展開できなかったのではないかと思います。

**Comment by teruo-oshida** [comment]
すみません、本件、アイテムにマクロが使われていると発生する、という認識で良いですか？　手元で再現させる必要があるので、情報が知りたいです。
トリガー作ってないとダメ、とか、イベントが発生しないとダメ、とか、詳細情報教えてください。
よろしくお願いします。

**Comment by teruo-oshida** [comment]
追伸です。手元で icmppingsec[{$LOOPBACK}] というアイテムを作っていますが、再現しないようです。

**Comment by bynnchapu** [comment]
> すみません、本件、アイテムにマクロが使われていると発生する、という認識で良いですか？　手元で再現させる必要があるので、情報が知りたいです。

今のところわかっているのはマクロに数値(```$0```など)ではなく、文字列(```$PUBLIC_IP```など)を指定している時に発生しているようだということはわかっています。

> トリガー作ってないとダメ、とか、イベントが発生しないとダメ、とか、詳細情報教えてください。
> よろしくお願いします。

今の所それ以外の条件は私の調査では不明です。
アイテムの取得って全て取得するんでしたっけ？それともイベント発生アイテムだけですか？
それによって発生するしないという条件が変わるような気がしました。(憶測なので信ぴょう性は無いです。)

**Comment by bynnchapu** [comment]
>> トリガー作ってないとダメ、とか、イベントが発生しないとダメ、とか、詳細情報教えてください。
>> よろしくお願いします。

> 今の所それ以外の条件は私の調査では不明です。

追伸です。
アイテムのキーや名前にもマクロとして文字列が指定 (```$PUBLIC_IP```など)が指定されている時に発生します。
監視サーバを登録後イベントページに遷移した時には発生していました。

**Comment by kz0817** [comment]
>  監視サーバを登録後イベントページに遷移した時には発生していました。

「最新データ」ページでなく、「イベント」ページですか？

**Comment by teruo-oshida** [comment]
> 「最新データ」ページでなく、「イベント」ページですか？

横から失礼します。
厳密に表現するなら、監視サーバ登録後、裏側で行われる通信の際に現象が発生、イベントが記録され、直後にイベントページに遷移すると、その記録されたイベントが目視確認できる、そういう意味だと思います。

というか、昨日口頭で会話して、そのように理解しました。
