### ISSUE TITLE
16.04-2をリリースする

### ISSUE THREAD

**Issue by masa0612** [project-hatohol/hatohol#2350]
手元で色々とバグを見つけて，その修正パッチなどを書いているので，
それらがマージされたら16.07としてリリースしたいです。
アクティブなメンバーが現状，私だけなので私が修正した内容だけで進めようと思っています。

ご意見あればください。

**Comment by Mnakagawa** [comment]
16.04.02としてリリースしてもいいかもしれません。

**Comment by cosmo0920** [comment]
メジャーリリースほどの大きな変更でなければ 16.04.1 や 16.04.2 のようなパッチレベルリリースにするのはどうでしょうか？

**Comment by Mnakagawa** [comment]
そうしましょう

**Comment by kz0817** [comment]
これ閉じていいですよね？
賛成多数か、数日リアクションがなければクローズします。
