### ISSUE TITLE
Why should #2316 be reverted ?

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#2375]
#2370 の修正項目の中に Revert #2316 というのがありますが、その理由を教えてください。

**Comment by ashie** [comment]
https://github.com/project-hatohol/hatohol/pull/2316#issuecomment-243985205 に理由が記載されていますね。

**Comment by kz0817** [comment]
Thank youです。

しかし、#2316には、翻訳ファイル（それも単にコメント行内の行番号）の差分が
多くふまれる。revertコマンドでなく、手動でそんなに多くないロジック部分だけを差し戻して、
あとで翻訳ファイルは整理したほうがよいか。

**Comment by kz0817** [comment]
revertコマンドを使っても、解決の難しいconflictはなかった。翻訳ファイル内の一部の行番号と日付が異なるだけだった。なので、revertコマンドベースでPRを作る。
