### ISSUE TITLE
What is for hap2_starter_alive.py

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#2383]
掲題のファイルが #2370 で提案されていますが、
この目的を教えてください。

また、hap2_starter.pyとの違いを教えてください。

**Comment by Mnakagawa** [comment]
hap2_starter_aliveはhatoholサーバーが内部的に起動している（not passive）
プラグインの個数をカウントするスクリプトです。カウントのみです。
用途は現状，はっきりとは無いです。

hap2_starterは各プラグインのラッパーです。

**Comment by kz0817** [comment]
回答ありがとう。

名前は似ているけど、全然別の機能ってことですね。

> 用途は現状，はっきりとは無いです。

とは言え、なにかモチベーションはあたっんですよね。
HAPの状態監視用途とかではないんですか？

**Comment by Mnakagawa** [comment]
そうですね。
現状のHatoholだとnot passiveなプラグインが落ちた時にリカバリーする手段が無いので，
（一応監視サーバーをアップデートすればプラグインは立ち上がるのですが）

例えばこのスクリプトを外部アプリで恒常的にまわしておいて，
exit 1が帰ってきたらHatoholサーバー自体を再起動する，といった用途を想定しています。

**Comment by kz0817** [comment]
これに関する機能(#2396)がマージされたのでクローズ
