### ISSUE TITLE
Why is setAutoReload replaced with enableAutoRefresh?

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#2385]
#2370の中でいくつかのsetAutoReload()がenableAutoRefresh()に置き換えられています。この理由を教えてください。

**Comment by Mnakagawa** [comment]
enableAutoRefresh = setAutoReload + naviバーにある現在の監視ステータスを緑にする
だからです。
この変更を入れなければ，一度監視を止めて再度有効にした際に
内部的には監視が再開しているがナビバーの監視ステータスは赤という挙動になります。
今後，新ページを追加するとしても基本的にはsetAutoReloadではなく，
それをラップしているenableAutoRefreshを使うべきです。

**Comment by kz0817** [comment]
回答ありがとう。

とすると、setAutoReloadをenableAutoRefreshに変更している数行だけで、バグフィックスとして
コミットを作るとわかりやすくなりそうですね。

**Comment by kz0817** [comment]
質問です。

> この変更を入れなければ，一度監視を止めて再度有効にした際に

監視を止めるというのは、バー右上の「監視中」のボタンを押して「停止中に」することですよね。
パッチで行われている修正なくても、この状態「停止中」ボタンを押すと、「監視中」に戻ります。
「再度有効」という操作は、上記のことでよいですか？

**Comment by a24-yamaguchi** [comment]
ちょっと話は戻りますが、修正の概要としては次のような
画面上のトグルボタンと実際の動きが異なる現象の解消になります。

１．トリガー画面で右上緑の「監視中」をクリックして「停止中」にする。
２．すぐ下の「手動更新」ボタンを押下して画面を更新する。
３．右上は「停止中」のままだが、次のような現象が出ている。
Hatoholサーバのhttpログ（/var/log/httpd/access_log）を見ていると、60秒ごとに継続してアクセスがある。
Hatohol画面上の最終更新タイムスタンプも更新されている。

「再度有効」は手動更新ボタンで画面を更新した時の事を指しています。

手動更新ボタンを押した時に自動更新をONにするのか？　という所も
今後検討したほうが良いかもしれません。
現状はイベント画面の動きに合わせています。

**Comment by Mnakagawa** [comment]
> 「再度有効」という操作は、上記のことでよいですか？

違います。説明不足でした。
kzさんがおっしゃる「再度有効」のパスも確かにあるのですが，
私が言った「再度有効」のパスはyamaguchiさんがおっしゃるように
「手動更新」のボタンを押した際のことを言っています。

**Comment by kz0817** [comment]
回答ありがとう。現象再現できました。

**Comment by ashie** [comment]
09bf8434 での考慮漏れっぽい
