### ISSUE TITLE
Why is 'current trigger status

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#2387]
#2370 でRemove [Current trigger status] from Event page columnという項目が
ありますが、この理由をご存知なら教えてください。

現在のトリガー状態ではないからですか？
（実際は、DBに登録されたときのトリガー状態）

**Comment by kz0817** [comment]
あと、削除でなく、コメントアウトしているのには何か理由がありますか？

+//    "status": {
+//      header: gettext("Current trigger status"),
+//      body: renderTableDataTriggerStatus,
+//    },

**Comment by ashie** [comment]
#2354 で話してました。
materでは既に修正されていますね。
（なのでBig patchでは単純に無駄なコードを追加するpatchになってます。）

**Comment by ashie** [comment]
クローズします。

**Comment by kz0817** [comment]
情報ありがとうございます。
