### ISSUE TITLE
What is the purpose of fixing hap2_nagios_ndoutils.py ?

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#2388]
#2370 でhap2_nagios_ndoutils.pyが修正されている理由を教えてください。
単に考慮漏れですか？

また、__get_latest_statehistory_id()は0を返さないですよね？
MySQLがそうだから。

でも、None or integerを返す関数で、Noneの場合を調べる一般的な方法は、
    if not raw_last_info:
よりも
    if raw_last_info is None:
でしょうね。(0が返った時の振る舞いが異なる）

**Comment by Mnakagawa** [comment]
現状のmasterだと全部のstatehistoryとってきますよね？
hap2_zabbixapiでは登録時点からのイベントしかとっていないため，
動作を揃える必要がある，また登録時の負荷を下げる意味での修正です。

**Comment by kz0817** [comment]
もうひとつ質問です。
-        if event_id <= 0:
+        if event_id < 0:

って、改変がありますが、event_id = 0の場合に不都合あるから、この
修正があるんですよね。event_idが0になるケースが思い浮かばなかった
のですが、実際に問題があるケースがあれば、教えてください。
もしくは、単にそうあるべきとして修正してますか？

**Comment by kz0817** [comment]
+                    self.set_event_last_info("0")

この修正で0に場合が発生するようになったからってことでOK?

**Comment by kz0817** [comment]
度々の質問、失礼します。最後、returnしていますが、
なぜ、処理を途中でやめるのですか？
この実装だと、ndoutilsからの情報の取得が次回のpolling時に
なるように思えますが、その理解でよいですか？

+            if not raw_last_info:
+                latest_id = self.__get_latest_statehistory_id()
+                if latest_id:
+                    self.set_event_last_info(latest_id)
+                else:
+                    self.set_event_last_info("0")
+                return

**Comment by Mnakagawa** [comment]
> この修正で0に場合が発生するようになったからってことでOK?

OK

> この実装だと、ndoutilsからの情報の取得が次回のpolling時に
> なるように思えますが、その理解でよいですか？

その理解で良いです。
このreturn文が使用されるのは，Hatoholサーバーにもプラグインのキャッシュにも
last_infoが存在しないケースだからです。

**Comment by kz0817** [comment]
回答ありがとう。

>> この実装だと、ndoutilsからの情報の取得が次回のpolling時に
>> なるように思えますが、その理解でよいですか？
>
> その理解で良いです。

理想的な動作は、次回に先送りしないで、そのpolling時に
ndoutilsのDBからデータ取得して、Hatoholサーバに
送ると思うのですが、それは同意？

ただ、そうであっても、実装の容易さなどから、現案を採用して、
エンハンスメントを必要に応じて将来、行うことでいいと
思います。

**Comment by Mnakagawa** [comment]
> 送ると思うのですが、それは同意？

同意です。
return文を取り除くだけで実装できる気もしますし，
そうしていただいても問題ありません

**Comment by kz0817** [comment]
returnしてしまうと、testが失敗するんですよね。
returnを除いたほうが良い気がしてきた。
<pre>
======================================================================
ERROR: test_collect_events_and_put (TestHap2NagiosNdoutils.TestCommon)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kyamato/hatohol.x/server/hap2/hatohol/test/TestHap2NagiosNdoutils.py", line 171, in test_collect_events_and_put
    self.assertEquals(type(comm.stores["events"]), type([]))
KeyError: 'events'
</pre>

**Comment by kz0817** [comment]
関連するPRがマージされたのでクローズ
