### ISSUE TITLE
Feature test is broken

### ISSUE THREAD

**Issue by ashie** [project-hatohol/hatohol#2389]
Recently feature test is always failed on TravisCI with the same pattern:

e.g.) https://travis-ci.org/project-hatohol/hatohol/jobs/179166854

But I can't reproduce it on my local environment.

**Comment by cosmo0920** [comment]
Recently, casperjs is frequently released.
Could you confirm installed casperjs version and re-run feature tests with updated version?

**Comment by kz0817** [comment]
Many of the error messages are like time-out as
<pre>
uncaughtError: "input#inputUserName" still did not exist in 5000ms
</pre>

Can we change the timeout value other than 5000ms ?

**Comment by kz0817** [comment]
manage.pyを起動せずに
 
     $ LANG=ja_JP.utf8 LC_ALL=ja_JP.UTF-8 ./client/test/feature/run-test.sh

を実行したら、TravisCIと似た結果を得た。

<pre>
Details for the 10 failed tests:

In /home/kyamato/hatohol.kz0817/client/test/feature/dashboard_test.js
  Dashboard test
    uncaughtError: "input#inputUserName" still did not exist in 5000ms
In /home/kyamato/hatohol.kz0817/client/test/feature/login_logout_test.js:19
  Login/Logout test
    assertExists: Find an element matching: input#inputUserName
In /home/kyamato/hatohol.kz0817/client/test/feature/register_action_test.js
  Register/Unregister action test
    uncaughtError: "input#inputUserName" still did not exist in 5000ms
In /home/kyamato/hatohol.kz0817/client/test/feature/register_incident_setting_test.js
  Register/Unregister incident settings test
    assertExists: Find an element matching: input#inputPassword
In /home/kyamato/hatohol.kz0817/client/test/feature/register_log_search_system_test.js
  Register/Unregister log search system test
    uncaughtError: "input#inputUserName" still did not exist in 5000ms
In /home/kyamato/hatohol.kz0817/client/test/feature/register_redmine_test.js
  Register/Unregister incident tracker(Redmine) test
    assertExists: Find an element matching: input#inputPassword
In /home/kyamato/hatohol.kz0817/client/test/feature/register_server_test.js
  Register/Unregister server test
    uncaughtError: "input#inputUserName" still did not exist in 5000ms
In /home/kyamato/hatohol.kz0817/client/test/feature/register_user_access_info_test.js
  Register/Unregister access info list test
    assertExists: Find an element matching: input#inputPassword
In /home/kyamato/hatohol.kz0817/client/test/feature/register_user_roles_test.js
  Register/Unregister user role test
    uncaughtError: "input#inputUserName" still did not exist in 5000ms
In /home/kyamato/hatohol.kz0817/client/test/feature/register_users_test.js
  Register/Unregister user test
    assertExists: Find an element matching: input#inputPassword
</pre>

**Comment by kz0817** [comment]
manage.pyとhatohol serverを起動したローカルマシンでも、再現した。
casperjsのバージョンは、1.1.3

**Comment by kz0817** [comment]
register_action_testに関しては、util.moveToServersPage(test)で、
this.click(x("//a[normalize-space(text())='監視サーバー']"))を実行するも
ページ遷移が発生していない模様。
anchorタグ自体は見つけているが、クリックがうまくemulateできていないと
思われる。

**Comment by kz0817** [comment]
「監視サーバー」をクリックする前に、「設定」をクリックすると、期待どおり動作した。

**Comment by kz0817** [comment]
#2492 で修正をPRした。

**Comment by ashie** [comment]
マージされたのでクローズ
