### ISSUE TITLE
Why is `raise' removed ?

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#2395]
big-patchで__wait_response()に次の改変があるのですが、
これの目的を教えてください。

ここで例外を起こさずに単にreturnすると、例えば、put_events()から
呼ばれていた場合、後続のself.__wait_response(request_id)は、失敗する
と思われます。

たまたま、Hatohol serverには一見、正常に登録されている状況はあると
思いますが、処理の途中で想定外の状況が発生しているにもかかわらず、
無理やり続行しているように見えます。

<pre>
+++ b/server/hap2/hatohol/haplib.py
@@ -602,10 +602,9 @@ class HapiProcessor:
             if self.__reply_queue.get(True, self.__timeout_sec) == True:
                 pass
             else:
-                raise
+                logger.error("Request(ID: %d) is not accepted." % request_id)
         except Queue.Empty:
             logger.error("Request(ID: %d) is not accepted." % request_id)
-            raise
</pre>

**Comment by Mnakagawa** [comment]
ほんとだ。デグレですねコレ。すみません。
raise追加しておいてください。

**Comment by Mnakagawa** [comment]
#2394 で書いたコメントの

> ただこの付近で
> TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType
> とログには出ていた記憶はあるから要調査かもしれない。

これはこの削除してしまったraiseから出たログっぽい。
except文の外でraiseだけ記載すると上記のエラーが出てしまうっぽい。

**Comment by kz0817** [comment]
このあたりは、結果としてこんな風に、ほぼもとのままです。
<pre>
diff --git a/server/hap2/hatohol/haplib.py b/server/hap2/hatohol/haplib.py
index 289275b..52b477c 100644
--- a/server/hap2/hatohol/haplib.py
+++ b/server/hap2/hatohol/haplib.py
@@ -603,8 +603,10 @@ class HapiProcessor:
                 pass
             else:
                 logger.error("Request(ID: %d) is not accepted." % request_id)
+                raise
         except Queue.Empty:
             logger.error("Request(ID: %d) is not accepted." % request_id)
+            raise
 
     def __wait_response(self, request_id):
         try:
@@ -618,12 +620,13 @@ class HapiProcessor:
                 logger.error(msg)
                 raise Exception(msg)
             return pm.message_dict["result"]
-        except ValueError:
+
+        except ValueError as exception:
             logger.error("Got invalid response.")
-            raise Exception
+            raise
         except Queue.Empty:
             logger.error("Request failed.")
-            raise Exception
+            raise
 
 class ChildProcess:
</pre>
