### ISSUE TITLE
Why is unifiedId gotten from the parent element?

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#2399]
big-patchの中で、以下のようにunifiedIdの取得方法を変えていますが、
元々、どういう問題があったか教えてください。

<pre>
-      unifiedId = parseInt(incidents[i].getAttribute("data-unified-id"));
+      unifiedId = parseInt(incidents[i].parentElement.getAttribute("data-unified-id"));
</pre>

**Comment by a24-yamaguchi** [comment]
イベント画面の「対処」列はデフォルトでは左端にありますが、ユーザが配置を入れ替えて
左から2番目などにした時に鉛筆マークを押下してもコメントフォームが開かなくなる不具合が
あったため変更しています。

**Comment by Mnakagawa** [comment]
```
-      var unifiedEventId = $tr.children('td').first().attr("data-unified-id");
+      var unifiedEventId = $tr.attr("data-unified-id");
```

first()を使っていたため，左端にインシデントカラムが無いとコメントフォームが開けませんでした。
tdに埋め込むと順序を入れ替えた時に指定ができなくなるので，trに埋め込んだ形です。

**Comment by Mnakagawa** [comment]
当時は頭から抜けてたから試してないけど，
```
$tr.children('td').find("data-unified-id");
```

だけの修正でも直るのかな。
jqueryのセレクタは難しい。

**Comment by kz0817** [comment]
回答ありがとうございます。#2411 がマージされたのでクローズします。
