### ISSUE TITLE
Isn't the mistake for adjusting index.

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#2402]
big-patchの中で次のようにインデントを調整しているところが
あるのですが、元々の位置が正しいと思います。どうでしょうか？
<pre>
--- a/client/static/js/hatohol_history_loader.js
+++ b/client/static/js/hatohol_history_loader.js
@@ -127,7 +127,7 @@ HatoholHistoryLoader.prototype.load = function() {
       if (self.options.onLoadHistory)
         self.options.onLoadHistory(self, self.history);

-      deferred.resolve();
+        deferred.resolve();
     });
</pre>

**Comment by Mnakagawa** [comment]
確かに元のほうが正しいです。
autoindentで入っちゃって気づかなかったかな…

**Comment by kz0817** [comment]
了解。won't fixで。
