### ISSUE TITLE
Is the change really correct ?

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#2420]
big-patchの中でのこの改変、default_value=="True"は、直前でdefault_valueをFalseにしているので、決して実行されないですが、意図した変更ですか？
<pre>
-        if kwargs.get("action")=="store_true" and default_value=="":
-            default_value = True
+        if kwargs.get("action")=="store_true":
+            default_value = False
+            if default_value=="True":
+                default_value = True
</pre>

**Comment by Mnakagawa** [comment]
```diff
-        if kwargs.get("action")=="store_true" and default_value=="":
-            default_value = True
+        if kwargs.get("action")=="store_true" and default_value=="True":
+           default_value = True
```

正しくはこうですね。ご指摘ありがとうございます。

**Comment by Mnakagawa** [comment]
修正の後，以下の2パターンをテストしていただけますか？

1．コマンドライン引数に-pを与えず，configファイルのdisable_pollerをTrueにする
→hap2のPollerが無効になっていること
2．コマンドライン引数に-pを与えず，configファイルのdisable_pollerをFalseにする
→hap2のPollerが有効になっていること
３．コマンドライン引数に-pを与え，configファイルのdisable_pollerをTrueにする
→hap2のPollerが有効になっていること
４．コマンドライン引数に-pを与え，configファイルのdisable_pollerをFalseにする
→hap2のPollerが有効になっていること

よろしくおねがいします。

**Comment by masa0612** [comment]
> 正しくはこうですね。ご指摘ありがとうございます。

全然正しくありませんでしたすみません。
以下diffは手元で確認したので，本当に大丈夫だと思います。

```diff
         if kwargs.has_key("type") and default_value:
             default_value = kwargs["type"](default_value)
-        if kwargs.get("action")=="store_true" and default_value=="":
-            default_value = True
+        if kwargs.get("action")=="store_true":
+            if default_value=="True":
+                default_value = True
+            else:
+                default_value = False
         if kwargs.has_key("nargs") and default_value:
             default_value = default_value.split()
         if not default_value:
```

**Comment by kz0817** [comment]
これも等価かな。
<pre>
default_value = (default_value == "True")
</pre>

**Comment by masa0612** [comment]
そのコードいいですね。好きです
