### ISSUE TITLE
Is this just a refactoring ?

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#2421]
big-patchの中でのこの変更は、単にシンプルにして可読性を上げるためのだけ？
ロジックの変更はないですよね？

<pre>
-static bool shouldHaveTriggerInfo(EventInfo &eventInfo) {
-   return DO_NOT_ASSOCIATE_TRIGGER_ID != eventInfo.triggerId &&
-            STATELESS_MONITOR != eventInfo.triggerId;
-}
-
 void ActionManager::fillTriggerInfoInEventInfo(EventInfo &eventInfo)
 {
        ThreadLocalDBCache cache;
@@ -1577,7 +1619,8 @@ void ActionManager::fillTriggerInfoInEventInfo(EventInfo &eventInfo)
                eventInfo.hostName = triggerInfo.hostName;
                eventInfo.brief    = triggerInfo.brief;
        } else {
-           if (shouldHaveTriggerInfo(eventInfo)) {
+         if (DO_NOT_ASSOCIATE_TRIGGER_ID != eventInfo.triggerId &&
+                 STATELESS_MONITOR != eventInfo.triggerId) {
                        MLPL_ERR("Not found: svID: %" FMT_SERVER_ID ", "
                                 "trigID: %" FMT_TRIGGER_ID "\n",
                                 eventInfo.serverId, eventInfo.triggerId.c_str());
</pre>

**Comment by Mnakagawa** [comment]
これは間違いです。ロジック的には同じで，本来は関数（shouldHaveTriggerinfo）があるべきですね。
shouldHaveTriggerinfoがあるべきです。この部分の変更は不要です。
