### ISSUE TITLE
testFaceRestMonitoring::test_overview has been broken

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#2423]
big-patchのマージ作業で以下のテストが壊れた
testFaceRestMonitoring::test_overview

https://travis-ci.org/project-hatohol/hatohol/jobs/183773867

**Comment by masa0612** [comment]
```
test/../server/test/testFaceRestMonitoring.cc:516: void testFaceRestMonitoring::_assertOverviewInParser(JSONParser*, RequestArg&): _assertValueInParser(parser,"numberOfItems",getNumberOfTestItems(svInfo.id))
```

ということは
https://github.com/project-hatohol/hatohol/pull/2418
に起因している用に見えますね

**Comment by kz0817** [comment]
このコミットがテストを壊したと思われる。
commit 10dd478b8e8fc89569e2f25a78fe57fc459803c3
    [Server] Don't send numberOfItems and nvps for dashboard.

**Comment by kz0817** [comment]
#2425 で修正をPR
