### ISSUE TITLE
Why is setLoading() used with false ?

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#2433]
big-patchの多くで、以下の修正が見られます。
この目的を教えてください。
<pre>
-    setLoading(true);
+    setLoading(false);
</pre>

**Comment by masa0612** [comment]
その部分に関しては修正しなくても良いです。patchから抜き忘れました。
以下の手順を踏むことで，発生するバグがあるのですが，このバグの応急措置として
入れたpatchです。

■再現手順
１．Hatoholログイン
２．イベント画面を表示させる
３．右上、緑の「監視中」を押下して「停止中」にする
４．セッションが切れるまで放置（10分程度？）
５．手動リロードボタンを押下（このタイミングでは押下可能）
６．ログインダイアログが出る→ログインする
７．最終更新時刻が更新される
８．手動リロードボタンが押せない（マウスカーソルがban）状態となる

本来であればこちらのバグを直すべきなので，setLoading部の修正はする必要が無いです。

**Comment by kz0817** [comment]
了解しました。setLoading()についてそのままにしておきます。
