### ISSUE TITLE
Is minUpdateInterval no longer used ?

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#2442]
big-patchの中の次のコードは、最低限、更新を抑制する機能を廃止するように
見えます。それを意図した変更でしょうか？

また、その場合、そのモチベーションを教えてください。

<pre>
--- a/server/src/ItemFetchWorker.cc
+++ b/server/src/ItemFetchWorker.cc
@@ -164,7 +164,6 @@ void ItemFetchWorker::updatedCallback(Closure0 *closure)
        if (sem_post(&m_impl->updatedSemaphore) == -1)
                MLPL_ERR("Failed to call sem_post: %d\n", errno);
        m_impl->nextAllowedUpdateTime.setCurrTime();
-   m_impl->nextAllowedUpdateTime += m_impl->minUpdateInterval;
</pre>

**Comment by masa0612** [comment]
それを意図した変更です。

モチベーション，というより必要に迫られたからそうしています。
今までは「最新データ」画面を開いた際にHatoholサーバーへリクエスト
（全サーバーのアイテムを取得するリクエスト）を出していましたが，
監視サーバー群がそれぞれ数千ホストを監視している際，
全てのサーバーに対してアイテムリクエストを投げると負荷が高くなってしまうと判断したため
WebUI側にも変更を加え「監視サーバーを一つ選択した際，その監視サーバーのアイテムのみ取得する」
ことにしました。

結果として，従来のサーバー側のコードだと例えば
「監視サーバーAを選択し，10秒以内に監視サーバーBを選択」すると監視サーバーBへの
リクエストが発行されず，何も表示されないという結果になります。
もちろんユーザーが大量のリクエストを発行してしまう可能性もありますが，
ヘタをすると1万単位の監視サーバーが保持する全てのアイテムを処理する負荷に比べると
こちらのほうが良いと判断してのpatchです。

**Comment by kz0817** [comment]
分割PRでは、更新無効時間を0にすることで同じ振る舞いをするようにした。
