### ISSUE TITLE
Why is the behavior of syncItems() changed ?

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#2443]
big-patchで、以下の箇所って、syncItemsの仕様を変更してますよね？
従来は、引数のitemInfoListが空なら、DB内のitemを全部削除する。
このパッチでは、空のときに何もしない。
この変更のモチベーションを教えてください。

<pre>
@@ -2887,6 +2921,11 @@ static LocalHostIdType getTargetHostId(const ItemInfoList itemInfoList)
 HatoholError DBTablesMonitoring::syncItems(const ItemInfoList &itemInfoList,
                                            const ServerIdType &serverId)
 {
+ HatoholError err = HTERR_OK;
+ if (itemInfoList.size() == 0) {
+         return err;
+ }
</pre>

**Comment by masa0612** [comment]
SEGVが起きるパスがあるからです

**Comment by kz0817** [comment]
回答ありがとう。
そういえば、以前、口頭でききましたね。

**Comment by kz0817** [comment]
たしかに、syncItem()自体、最初のアイテムのホストを対象とする。
すわなち、ホストはひとつであるという縛りがあるので、リストから
空の場合、対象のホストがわからず、削除しないという動作は道理にあってる気がする。

**Comment by kz0817** [comment]
> たしかに、syncItem()自体、最初のアイテムのホストを対象とする。

ただ、この仕様はシンプルじゃないが。すぐにはどうしようもないか。
