### ISSUE TITLE
Change module Name

### ISSUE THREAD

**Issue by bynnchapu** [project-hatohol/hatohol#245]
Currently, Hatohol has 2 module:
- Server
  - Collects monitoring data from the monitoring servers, Posts event data to the incident management servers, Runs actions.
- Client
  - Provides web UI.

But, these names are difficult to understand.
So, I think it is good to change the module names.

I have an idea:
- Server -> Core
- Client -> Frontend

**Comment by Mnakagawa** [comment]
Done in 14.12.
