### ISSUE TITLE
Reason to add a validation

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#2453]
big-patchで次のfetchItemsAsync()にvalidationが加えられている理由を
教えてください。どうせ見つからないので、効率のため？それともcrashなどを回避するため？

<pre>
+++ b/server/src/UnifiedDataStore.cc
@@ -462,6 +462,10 @@ bool UnifiedDataStore::fetchItemsAsync(Closure0 *closure,
        if (!m_impl->itemFetchWorker.updateIsNeeded())
                return false;
 
+ const ServerIdType targetServerId = option.getTargetServerId();
+ if (targetServerId == INVALID_SERVER_ID)
+         return false;
+
</pre>

**Comment by masa0612** [comment]
コレ確かINVALID_SERVER_IDがデフォルトで，
INVALID_SERVER_IDの時は全部のサーバーに対してリクエスト投げる，
みたいな処理じゃありませんでしたっけ？

それを弾くための処理だったと思います。
WebUIの処理上，optionの値がデフォルトのままになることはなくなったはずですが，
念の為サーバー側でもvalidationを入れたという経緯だったはず。

**Comment by ashie** [comment]
だとすると、見るべき値は`INVALID_SERVER_ID`ではなくて`ALL_SERVERS`な気がする。

**Comment by masa0612** [comment]
確かに。経緯が違うかもしれない。
ちょっと想い出すので時間ください

**Comment by masa0612** [comment]
「最新データ」を開いた時はemptyFlagがデフォルトのクエリになっているのですが，
例えばサーバーAを選択して，その後に「監視サーバー」部のフィルターを「---------」に戻した場合，
従来であればサーバーIDを-1としてクエリを返して全ての監視サーバーのアイテムを取得していたのですが，
全ての監視サーバーのアイテムを表示することを辞めたので「--------」の扱いを-2に変えたんですよね。
この-2というのが，Hatoholサーバー側でいうところのINVALID_SERVER_IDなので，
そのリクエストがきた時はfalseを返す，というvalidationを入れたのでした。

```diff
hatohol_monitoirng_view.js in big-patch

-  query.serverId = serverId ? serverId : "-1";
+  if (isOverview) {
+    query.serverId = serverId ? serverId : "-2";
+  } else {
+    query.serverId = serverId ? serverId : "-1";
+  }
```

**Comment by kz0817** [comment]
というこは、監視サーバの選択を「--------」に戻した時にも、
emptyFlagをむしろ指定すべきということ？

**Comment by kz0817** [comment]
ただ、想定外の動作を抑止するためにもこういうバリデーションはあってもいいとは思う。

**Comment by masa0612** [comment]
> というこは、監視サーバの選択を「--------」に戻した時にも、
> emptyFlagをむしろ指定すべきということ？

そういうことです。

**Comment by kz0817** [comment]
#2459 でIssueを作成したの、本件はクローズ。

**Comment by kz0817** [comment]
とはいえ、UnifiedDataStoreのfetchTriggerAsync()だけに
validationを入れるのは不自然な感じがする。。。

**Comment by masa0612** [comment]
確かに。validation入れるならHatoholArmPluginGateHAPI2.ccとか？
RestResourceMonitoring.ccも候補か
