### ISSUE TITLE
What is the purpose of changing RestResourceSummary.cc in big-patch

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#2470]
big-patchで、RestResourceSummary.ccが変更されていますが、
これにはどういう目的があるかおしえてください。

**Comment by kz0817** [comment]
具体的には2つ疑問があって、1点目は、次の修正の目的が何かしりたいです。
-   customIncidentStatusMap.erase(IncidentSenderHatohol::STATUS_HOLD);

2点目は、getImportantEventStatistics()の第2引数からconstが外されていますが、
この必要性を教えてください。

**Comment by masa0612** [comment]
「サマリーバーの未対処の重要イベント」＝＝「”未対処”＋”保留”」が分かりづらいと考えたからです。
言葉の通り，未対処の重要イベントは「未対処」のみであるべきです。ユーザーライクじゃない。

2点めについては，userFilterを引数に与えてる関数が，
どれか覚えてないけどconstを許容しないから外したはずです。
よくよく考えるとkzさんが随所でやってるようにconstで受け入れて，
const無しの新しい変数を作って移し替えたほうがいいか。

**Comment by kz0817** [comment]
> よくよく考えるとkzさんが随所でやってるようにconstで受け入れて，
> const無しの新しい変数を作って移し替えたほうがいいか。

もともとの実装は、そんな感じでしたが、それだと意図しているように
動作しないのですか？

**Comment by kz0817** [comment]
もともとのコードでも不思議なところがあって、getImportantEventStatistics()で
<pre>
EventsQueryOption importantEventOption(userFilter);
</pre>
というのを作っているけど、それを与える以下の3つの関数はいずれも、constを取るので
そもそもimportantEventOptionを使わずに、userFilterを直接渡せばいいはず。
dataStore->getNumberOfEvents()
dataStore->getNumberOfHostsWithSpecifiedEvents()
dataStore->getEventSeverityStatistic()

**Comment by kz0817** [comment]
実際、これでもビルドはできる。
結果も同じになるはず。もしかしたら、importEventOptionは
userFilterから条件を変えることがありえるために、この関数で
宣言されているのかも。

<pre>
--- a/server/src/RestResourceSummary.cc
+++ b/server/src/RestResourceSummary.cc
@@ -139,15 +139,14 @@ HatoholError getImportantEventStatistics(ImportantEventStatistics &statistics,
                                         const EventsQueryOption &userFilter)
 {
        UnifiedDataStore *dataStore = UnifiedDataStore::getInstance();
-       EventsQueryOption importantEventOption(userFilter);
        statistics.numOfImportantEvents =
-         dataStore->getNumberOfEvents(importantEventOption);
+         dataStore->getNumberOfEvents(userFilter);
        statistics.numOfImportantEventOccurredHosts =
-         dataStore->getNumberOfHostsWithSpecifiedEvents(importantEventOption);
+         dataStore->getNumberOfHostsWithSpecifiedEvents(userFilter);
        HatoholError err =
          dataStore->getEventSeverityStatistics(
            statistics.severityStatisticsVect,
-           importantEventOption);
+           userFilter);
        if (err != HTERR_OK)
                return err;
</pre>

**Comment by kz0817** [comment]
いずれにせよ、変更は下記の1行だけでいいように思います。
コメントお願いします。
<pre>
-   customIncidentStatusMap.erase(IncidentSenderHatohol::STATUS_HOLD);
</pre>

**Comment by masa0612** [comment]
その変更だけだとバグが埋まっているので駄目でした。

> EventsQueryOption importantEventOption(userFilter);
```
EventsQueryOption::EventsQueryOption(const EventsQueryOption &src)
: HostResourceQueryOption(src),
  m_impl(new Impl())
{
    *m_impl = *src.m_impl;
}
```

この処理だけではuserFilterを完全にコピーすることが出来ておらず，
setSeverityCondition関数でセットしたパラメータがリセットされるというバグがあります。
（HostResourceQueryOptionのimplしかコピーされていない）
なのでuserFilterを元に新たなEventsQueryOptionを作ることはしてはいけないのです。

assignedEventOptionも使用できなくなるので，そこもuserFilterに変更，
そうなるとassignedEventOptionが使用されている関数，setAssignedIncidentStatusCondition()では
引数にとっているEventQueryOptionに対して変更を加えているので，constではコンパイルエラーが
発生するので，getImportantEventStatistics()の引数userFilterもconstを外さざるを得なくなって外した，という経緯がありました。

**Comment by kz0817** [comment]
ちょっと、コード詳しく見てみるけど、コメントを元にすると、EventsQueryOptionの
コンストラクタを修正したほうがよさそう。
<pre>
EventsQueryOption importantEventOption(userFilter);
</pre>

**Comment by masa0612** [comment]
> EventsQueryOptionのコンストラクタを修正したほうがよさそう。

そのとおりだと思います。
当時は時間がなくて仕方なく，このコードで進めていただけなので。。。

**Comment by masa0612** [comment]
> setSeverityCondition関数でセットしたパラメータがリセットされるというバグがあります。
> （HostResourceQueryOptionのimplしかコピーされていない）

これ間違いでした。
正しくは
「EventQueryOptionのm_implがコピーされるだけであって，HostqueryOptionのm_implはコピーされない」ですね。
サマリーのAPI叩くときには，ホストの情報などが全てリセットされてしまうというバグでした。
（Ex. ホストAのみ表示するというフィルターを設定していたとしても，サマリバーにはそれが反映されず，全てのホストを元にした数字が表示される）

**Comment by kz0817** [comment]
HostResourceQueryOption::Impl()で代入演算子を定義しているのが原因なんだろうが、
なぜ、明確に定義する必要があったのか？

<pre>
dd1366d3 (Kouhei Sutou      2014-08-08 17:08:54 +0900  91)      Impl &operator=(const Impl &rhs)
5a4cfe69 (Kazuhiro Yamato   2014-03-13 15:02:16 +0900  92)      {
d947c31f (Takuro Ashie      2015-08-18 16:55:11 +0900  93)              targetServerId        = rhs.targetServerId;
d947c31f (Takuro Ashie      2015-08-18 16:55:11 +0900  94)              targetHostId          = rhs.targetHostId;
d947c31f (Takuro Ashie      2015-08-18 16:55:11 +0900  95)              targetHostgroupId     = rhs.targetHostgroupId;
d947c31f (Takuro Ashie      2015-08-18 16:55:11 +0900  96)              excludeDefunctServers = rhs.excludeDefunctServers;
5a4cfe69 (Kazuhiro Yamato   2014-03-13 15:02:16 +0900  97)              return *this;
5a4cfe69 (Kazuhiro Yamato   2014-03-13 15:02:16 +0900  98)      }
</pre>

**Comment by kz0817** [comment]
dd1366d3は、PrivateContextからImplへのクラス名の変更。
d947c31fは、以下の2つのメンバの名前の変更に併せて、
インデントを全体的に変更しているだけ。
<pre>
-       bool            filterDataOfDefunctServers;
+       bool            excludeDefunctServers;
</pre>

5a4cfe69には、次のコメントがある。おそらく、この後に追加されたメンバを
代入演算子でコピーするのを忘れていたのだろう。しかし、メンバ追加時に代入演算子の
オーバーロード関数も修正することは忘れやすい。
現状でかでかとコメントを書くぐらいしかできないのか。
<pre>
    [server][HostResourceQueryOption] Define the substitution operator.
    
    I'll add a reference member in PrivateContext. In that case,
    the default substitution operator cannot be used.
</pre>

ともかく、代入演算子のオーバーロード関数に他のメンバのコピーも追加すればよさそう。

**Comment by kz0817** [comment]
#2486 の修正で、HostResourceQueryOptionのメンバーがコピーされない問題は
修正される。なので、次の1行パッチをPRする。
<pre>
-   customIncidentStatusMap.erase(IncidentSenderHatohol::STATUS_HOLD);
</pre>
