### ISSUE TITLE
Cloud you tell me the change reason of hap2-control-functions.sh.in ?

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#2478]
2つ質問があります。

(1) 以下でtailの引数が+2が+1に変えられたのはなぜですか？formatが変わった？
(2) ALIVEをもとめるコマンドでgrep -v grepが削除された理由を教えてください。
<pre>
-        PID=`tail -n +2 ${PID_FILE}`
-        ALIVE=`ps $PID | grep $PLUGIN_PATH | grep -v grep | wc -l`
+        PID=`tail -n +1 ${PID_FILE}`
+        ALIVE=`ps $PID | grep $PLUGIN_PATH | wc -l`
</pre>

**Comment by masa0612** [comment]
> formatが変わった？

◯

> grep -v grepが削除された理由

そもそも必要なかったからですね。
ps aux | grep HOGEHOGE
ならこのgrepコマンド自体がpsの出力に出るから，grep -v grepが必要ですけど，
ps $PID | grep HOGE
ならそもそもこのgrepコマンドがpsの出力に出ないです

**Comment by kz0817** [comment]
了解しました。回答ありがとう。
