### ISSUE TITLE
Hatohol DB backup tool

### ISSUE THREAD

**Issue by bynnchapu** [project-hatohol/hatohol#253]
In investigating issue #252, I want a tool to backup Hatohol DBs.

**Comment by Mnakagawa** [comment]
I think, we can backup to use mysqldump command on command line.
Why do you think to create backup tools?

**Comment by bynnchapu** [comment]
Sorry, I forget that why I want to DB backup tool.
(This issue is opened in July 2014...)

I agree with your opinion...
If you don't have more opinion, we can close this issue.

**Comment by bynnchapu** [comment]
> If you don't have more opinion, we can close this issue.

As wontfix.

**Comment by Mnakagawa** [comment]
OK.
Close this issue.

**Comment by bynnchapu** [comment]
I've added ```wontfix``` label because we will not implement this function.
