### ISSUE TITLE
[Client] Can't select host in add action dialog

### ISSUE THREAD

**Issue by bynnchapu** [project-hatohol/hatohol#397]
Procedure for reproducing:
1. Show Action page
2. Click Add Action
3. Select a Server to someone
4. Select a Hostgroup to someone
5. Select a Hostgroup to "ANY"

Result: Can't select Host

We can select host before select Hostgroup.
So, this is a bug.

**Comment by cosmo0920** [comment]
#892 is merged. So, I close this issue.
If there is a remaining problem, please reopen this issue.
