### ISSUE TITLE
[DBTables] DBTables::Impl::setTablesVersion() returns no error

### ISSUE THREAD

**Issue by ashie** [project-hatohol/hatohol#508]
Even if DBTables::Impl::setTablesVersion() fails to update a tables version, it doesn't return any
error codes or exception.
It's hard to investigate the detail of the error.

**Comment by t-miyazawa** [comment]
ソース上は以下により例外を発生させている様に見えます。
　・THROW_HATOHOL_EXCEPTION_WITH_ERROR_CODE(...)
　・THROW_HATOHOL_EXCEPTION(...)
　・HATOHOL_ASSERT (中でTHROW_HATOHOL_EXCEPTION起動)
具体的な例として以下の箇所が該当します。
　DBAgentMySQL::queryWithRetry() の mysql_query() 
　　リトライしてエラーの場合は、エラー理由により以下のどちらかを呼んでいます。
　　THROW_HATOHOL_EXCEPTION_WITH_ERROR_CODE(...)
　　THROW_HATOHOL_EXCEPTION(...)
本問題の指摘はより詳細（適切）なエラー情報が必要という事でしょうか？

**Comment by kz0817** [comment]
OK. Let's close.
Now upgrade of the databases is done at the startup.
If an exception is thrown, Hatohol server stops safely.

**Comment by kz0817** [comment]
More specifically, DBHatohol instance is first created at main.c::checkDBConnection().
And the check for the upgrade is done in the method.
