### ISSUE TITLE
How dealing with "0(zero)" in the monitoring interval(polling/retry) of the server.

### ISSUE THREAD

**Issue by o-wakabayashi** [project-hatohol/hatohol#595]
Currently, be able to set 0 in "Polling interval" and "Retry interval" of the server monitoring parameters.
However, in term of CPU resources and log output, interval 0 is undesirable. 
I think the measure should be taken, For example, by failing to allow a 0 in DB or GUI.

**Comment by ashie** [comment]
@ t-miyazawa fixes this issue in #1007.
