### ISSUE TITLE
When you monitor the Ceilometer by Hapi, trigger "Internal error happend" is unknown.

### ISSUE THREAD

**Issue by o-wakabayashi** [project-hatohol/hatohol#654]
In a state in which Ceilometer is not running, I will start monitoring in HAPI. 
In that case, the monitoring status of the Ceilometer(HAPI) is the following.
  Failed in connecting to Broker. -> OK
  Failed in connecting to ArmPlugin. -> OK
  Internal error happend. -> Unknown
If Ceilometer is started, state of "Internal error happend" becomes normal.

Restrictions in the first release(14.09).

**Comment by Mnakagawa** [comment]
We need to confirm in latest release because the current implementation has been changed.

**Comment by Mnakagawa** [comment]
Hapi1 is legacy imprementation.
And I do not confirm this Issue in hap2_ceilometer.
I close this issue.
