### ISSUE TITLE
[server] Need a mechanism to upgrade server_types table

### ISSUE THREAD

**Issue by ashie** [project-hatohol/hatohol#672]
Initial data of server_types table is registered by server-type.sql via hatohol-db-initiator.
But there is no way to update modified records.
Since 'parameters' column of 'JSON (HAPI)' has been modified after 14.09, we must prepare the way to update it until 14.12.

**Comment by ashie** [comment]
server_types関連では他に以下のような要求がある。
このissueで一緒に扱う。

* 監視サーバ種別毎に個別にインストールできるようにしたい
* RPM等でプラグインを別パッケージにしたときもよろしくインストールできるようにしたい
* インストールされていても無効化/有効化を切り替えできるようにしたい?

**Comment by cosmo0920** [comment]
現時点での考えている仕様は次のとおりです。

> 監視サーバ種別毎に個別にインストールできるようにしたい
> RPM等でプラグインを別パッケージにしたときもよろしくインストールできるようにしたい

* サーバー種別毎にSQLを分割する
  - 合わせてhatohol-db-initiatorを分割されたSQLに対応させる

> インストールされていても無効化/有効化を切り替えできるようにしたい?

* 有効無効を表すカラムを追加してやる（現時点ではすべてtrue：有効）とする。
  - 追加したカラムのマイグレーションを書く

**Comment by cosmo0920** [comment]
> サーバー種別毎にSQLを分割する 

* サーバー種別毎のSQLにバージョン情報を持たせたい。
  - バージョンを保存できるカラムの追加を行う

**Comment by cosmo0920** [comment]
追加の仕様のメモです。
サードパーティのプラグインと既存のプラグインとがぶつからないようにしたい。

* プラグインのIDをintではなくUUIDとして扱いたい

**Comment by cosmo0920** [comment]
> * プラグインのIDをintではなくUUIDとして扱いたい

こちら一旦pendingにします。

**Comment by ashie** [comment]
> プラグインのIDをintではなくUUIDとして扱いたい

HAPI2.0(Hatohol 15.06で実装予定)でUUIDに変更される予定

**Comment by ashie** [comment]
> HAPI2.0(Hatohol 15.06で実装予定)でUUIDに変更される予定

本Issueのスコープ外として、本Issueはクローズします。
