### ISSUE TITLE
[Server] Use DNS name to access to the monitoring server

### ISSUE THREAD

**Issue by bynnchapu** [project-hatohol/hatohol#675]
Currently, Hatohol accesses to the monitoring server using ip address.
But, I think it is good that hatohol permits host name to access to the monitoring server.

**Comment by Mnakagawa** [comment]
It will be solved by HAPI-2.0.

**Comment by kz0817** [comment]
As the above comment. HAPI-2.0 plugins support DNS name.
And we don't fix the issue for built-in plugins.
So I close this issue.
