### ISSUE TITLE
[Server] Doesn't reflect disable Trigger information.

### ISSUE THREAD

**Issue by bynnchapu** [project-hatohol/hatohol#676]
How to reproduce:
1. (in monitoring server) Enable all Triggers of all hosts
2. Run Hatohol and get Trigger information
3. (in monitoring server) Disable a Trigger of a host
4. Wait a few minute to get Trigger information

Expect result:
Hatohol doesn't show disable Trigger of the host.

Result:
Hatohol shows disable Trigger of the host.

**Comment by Mnakagawa** [comment]
Hatoholは無効なトリガーと削除されたトリガーを同様に扱う仕様とします。
定期的にすべてのトリガーを取得するように変更し、存在しないトリガーと無効になっているトリガーを削除します。

**Comment by Mnakagawa** [comment]
Fixed it in #2195
