### ISSUE TITLE
Test failed due to double free or corruption.

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#693]
https://travis-ci.org/project-hatohol/hatohol/jobs/37391461
<pre>
 testConfigManager::test_parseDisableCopyOnDemand:	.: (0.000069)
  testConfigManager::test_parseEnableCopyOnDemand:	.: (0.000064)
  testConfigManager::test_parseFaceRestPort:		.: (0.000067)
  testConfigManager::test_parseConfigServerWithPort:	.: (0.000102)
  testConfigManager::test_getActionCommandDirectory:	.: (0.000043)
  testConfigManager::test_setResidentYardDirectory:	.: (0.000038)
  testConfigManager::test_parseConfigServerDefault:	.: (0.000062)
  testConfigManager::test_setFaceRestPort:		.: (0.000033)
  testConfigManager::test_parsePidFilePath:		.: (0.000071)
  testConfigManager::test_parseFaceRestPortDefault:	.: (0.000034)
*** glibc detected *** /usr/bin/cutter: double free or corruption (!prev): 0x000000000266fa20 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x7e626)[0x7f69febce626]
/usr/lib/libcutter.so.0(+0x421fa)[0x7f69ff1721fa]
/usr/lib/libcutter.so.0(cut_test_suite_run_with_filter+0x71)[0x7f69ff1727a1]
/usr/lib/libcutter.so.0(+0x41c00)[0x7f69ff171c00]
/usr/lib/libcutter.so.0(cut_runner_run+0x37)[0x7f69ff160567]
/usr/lib/libcutter.so.0(cut_run_context_start+0x41)[0x7f69ff15fc11]
/usr/lib/libcutter.so.0(cut_start_run_context+0x19f)[0x7f69ff156a3f]
/usr/lib/libcutter.so.0(cut_run+0x58)[0x7f69ff156aa8]
/usr/bin/cutter(main+0x1f)[0x4006df]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xed)[0x7f69feb7176d]
/usr/bin/cutter[0x40071d]
======= Memory map: ========
00400000-00401000 r-xp 00000000 00:15 3572598136                         /usr/bin/cutter
00600000-00601000 r--p 00000000 00:15 3572598136                         /usr/bin/cutter
00601000-00602000 rw-p 00001000 00:15 3572598136                         /usr/bin/cutter
025ea000-109dc000 rw-p 00000000 00:00 0                                  [heap]
7f690a7e4000-7f690a7e5000 ---p 00000000 00:00 0 
7f690a7e5000-7f690b1e5000 rw-p 00000000 00:00 0 
7f690b1e5000-7f690b1e6000 ---p 00000000 00:00 0 
7f690b1e6000-7f690bbe6000 rw-p 00000000 00:00 0 
7f690bbe6000-7f690bbe7000 ---p 00000000 00:00 0 
7f690bbe7000-7f690c5e7000 rw-p 00000000 00:00 0 
7f690c5e7000-7f690c5e8000 ---p 00000000 00:00 0 
7f690c5e8000-7f690cfe8000 rw-p 00000000 00:00 0 
7f690cfe8000-7f690cfe9000 ---p 00000000 00:00 0 
7f690cfe9000-7f690d9e9000 rw-p 00000000 00:00 0 
7f690d9e9000-7f690d9ea000 ---p 00000000 00:00 0 
7f690d9ea000-7f690e3ea000 rw-p 00000000 00:00 0 
7f690e3ea000-7f690e3eb000 ---p 00000000 00:00 0 
7f690e3eb000-7f690edeb000 rw-p 00000000 00:00 0 
7f690edeb000-7f690edec000 ---p 00000000 00:00 0 
7f690edec000-7f690f7ec000 rw-p 00000000 00:00 0 
7f690f7ec000-7f690f7ed000 ---p 00000000 00:00 0 
7f690f7ed000-7f69101ed000 rw-p 00000000 00:00 0 
7f69101ed000-7f69101ee000 ---p 00000000 00:00 0 
7f69101ee000-7f6910bee000 rw-p 00000000 00:00 0 
7f6910bee000-7f6910bef000 ---p 00000000 00:00 0 
7f6910bef000-7f69115ef000 rw-p 00000000 00:00 0 
7f69115ef000-7f69115f0000 ---p 00000000 00:00 0 
7f69115f0000-7f6911ff0000 rw-p 00000000 00:00 0 
7f6911ff0000-7f6911ff1000 ---p 00000000 00:00 0 
7f6911ff1000-7f69129f1000 rw-p 00000000 00:00 0 
7f69129f1000-7f69129f2000 ---p 00000000 00:00 0 
7f69129f2000-7f69133f2000 rw-p 00000000 00:00 0 
7f69133f2000-7f69133f3000 ---p 00000000 00:00 0 
7f69133f3000-7f6913df3000 rw-p 00000000 00:00 0 
7f6913df3000-7f6913df4000 ---p 00000000 00:00 0 
7f6913df4000-7f69147f4000 rw-p 00000000 00:00 0 
7f69147f4000-7f69147f5000 ---p 00000000 00:00 0 
7f69147f5000-7f69151f5000 rw-p 00000000 00:00 0 
7f69151f5000-7f69151f6000 ---p 00000000 00:00 0 
7f69151f6000-7f6915bf6000 rw-p 00000000 00:00 0 
7f6915bf6000-7f6915bf7000 ---p 00000000 00:00 0 
7f6915bf7000-7f69165f7000 rw-p 00000000 00:00 0 
7f69165f7000-7f69165f8000 ---p 00000000 00:00 0 
7f69165f8000-7f6916ff8000 rw-p 00000000 00:00 0 
7f6916ff8000-7f6916ff9000 ---p 00000000 00:00 0 
7f6916ff9000-7f69179f9000 rw-p 00000000 00:00 0 
7f69179f9000-7f69179fa000 ---p 00000000 00:00 0 
7f69179fa000-7f69183fa000 rw-p 00000000 00:00 0 
7f69183fa000-7f69183fb000 ---p 00000000 00:00 0 
7f69183fb000-7f6918dfb000 rw-p 00000000 00:00 0 
7f6918dfb000-7f6918dfc000 ---p 00000000 00:00 0 
7f6918dfc000-7f69197fc000 rw-p 00000000 00:00 0 
7f69197fc000-7f69197fd000 ---p 00000000 00:00 0 
7f69197fd000-7f691a1fd000 rw-p 00000000 00:00 0 
7f691a1fd000-7f691a1fe000 ---p 00000000 00:00 0 
7f691a1fe000-7f691abfe000 rw-p 00000000 00:00 0 
7f691abfe000-7f691abff000 ---p 00000000 00:00 0 
7f691abff000-7f691b5ff000 rw-p 00000000 00:00 0 
7f691b5ff000-7f691b600000 ---p 00000000 00:00 0 
7f691b600000-7f691c000000 rw-p 00000000 00:00 0 
7f691c000000-7f691c021000 rw-p 00000000 00:00 0 
7f691c021000-7f6920000000 ---p 00000000 00:00 0 
7f69203ba000-7f69203bb000 ---p 00000000 00:00 0 
7f69203bb000-7f6920dbb000 rw-p 00000000 00:00 0 
7f6920dbb000-7f6920dbc000 ---p 00000000 00:00 0 
7f6920dbc000-7f69217bc000 rw-p 00000000 00:00 0 
7f69217bc000-7f69217bd000 ---p 00000000 00:00 0 
7f69217bd000-7f69221bd000 rw-p 00000000 00:00 0 
7f69221bd000-7f69221be000 ---p 00000000 00:00 0 
7f69221be000-7f6922bbe000 rw-p 00000000 00:00 0 
7f6922bbe000-7f6922bbf000 ---p 00000000 00:00 0 
7f6922bbf000-7f69235bf000 rw-p 00000000 00:00 0 
7f69235bf000-7f69235c0000 ---p 00000000 00:00 0 
7f69235c0000-7f6923fc0000 rw-p 00000000 00:00 0 
7f6923fc0000-7f6923fc1000 ---p 00000000 00:00 0 
7f6923fc1000-7f69249c1000 rw-p 00000000 00:00 0 
7f69249c1000-7f69249c2000 ---p 00000000 00:00 0 
7f69249c2000-7f69253c2000 rw-p 00000000 00:00 0 
7f69253c2000-7f69253c3000 ---p 00000000 00:00 0 
7f69253c3000-7f6925dc3000 rw-p 00000000 00:00 0 
7f6925dc3000-7f6925dc4000 ---p 00000000 00:00 0 
7f6925dc4000-7f69267c4000 rw-p 00000000 00:00 0 
7f69267c4000-7f69267c5000 ---p 00000000 00:00 0 
7f69267c5000-7f69271c5000 rw-p 00000000 00:00 0 
7f69271c5000-7f69271c6000 ---p 00000000 00:00 0 
7f69271c6000-7f6927bc6000 rw-p 00000000 00:00 0 
7f6927bc6000-7f6927bc7000 ---p 00000000 00:00 0 
7f6927bc7000-7f69285c7000 rw-p 00000000 00:00 0 
7f69285c7000-7f69285c8000 ---p 00000000 00:00 0 
7f69285c8000-7f6928fc8000 rw-p 00000000 00:00 0 
7f6928fc8000-7f6928fc9000 ---p 00000000 00:00 0 
7f6928fc9000-7f69299c9000 rw-p 00000000 00:00 0 
7f69299c9000-7f69299ca000 ---p 00000000 00:00 0 
7f69299ca000-7f692a3ca000 rw-p 00000000 00:00 0 
7f692a3ca000-7f692a3cb000 ---p 00000000 00:00 0 
7f692a3cb000-7f692adcb000 rw-p 00000000 00:00 0 
7f692adcb000-7f692adcc000 ---p 00000000 00:00 0 
7f692adcc000-7f692b7cc000 rw-p 00000000 00:00 0 
7f692b7cc000-7f692b7cd000 ---p 00000000 00:00 0 
7f692b7cd000-7f692c1cd000 rw-p 00000000 00:00 0 
7f692c1cd000-7f692c1ce000 ---p 00000000 00:00 0 
7f692c1ce000-7f692cbce000 rw-p 00000000 00:00 0 
7f692cbce000-7f692cbcf000 ---p 00000000 00:00 0 
7f692cbcf000-7f692d5cf000 rw-p 00000000 00:00 0 
7f692d5cf000-7f692d5d0000 ---p 00000000 00:00 0 
7f692d5d0000-7f692dfd0000 rw-p 00000000 00:00 0 
7f692dfd0000-7f692dfd1000 ---p 00000000 00:00 0 
7f692dfd1000-7f692e9d1000 rw-p 00000000 00:00 0 
7f692e9d1000-7f692e9d2000 ---p 00000000 00:00 0 
7f692e9d2000-7f692f3d2000 rw-p 00000000 00:00 0 
7f692f3d2000-7f692f3d3000 ---p 00000000 00:00 0 
7f692f3d3000-7f692fdd3000 rw-p 00000000 00:00 0 
7f692fdd3000-7f692fdd4000 ---p 00000000 00:00 0 
7f692fdd4000-7f69307d4000 rw-p 00000000 00:00 0 
7f69307d4000-7f69307d5000 ---p 00000000 00:00 0 
7f69307d5000-7f69311d5000 rw-p 00000000 00:00 0 
7f69311d5000-7f69311d6000 ---p 00000000 00:00 0 
7f69311d6000-7f6931bd6000 rw-p 00000000 00:00 0 
7f6931bd6000-7f6931bd7000 ---p 00000000 00:00 0 
7f6931bd7000-7f69325d7000 rw-p 00000000 00:00 0 
7f69325d7000-7f69325d8000 ---p 00000000 00:00 0 
7f69325d8000-7f6932fd8000 rw-p 00000000 00:00 0 
7f6932fd8000-7f6932fd9000 ---p 00000000 00:00 0 
7f6932fd9000-7f69339d9000 rw-p 00000000 00:00 0 
7f69339d9000-7f69339da000 ---p 00000000 00:00 0 
7f69339da000-7f69343da000 rw-p 00000000 00:00 0 
7f69343da000-7f69343db000 ---p 00000000 00:00 0 
7f69343db000-7f6934ddb000 rw-p 00000000 00:00 0 
7f6934ddb000-7f6934ddc000 ---p 00000000 00:00 0 
7f6934ddc000-7f69357dc000 rw-p 00000000 00:00 0 
7f69357dc000-7f69357dd000 ---p 00000000 00:00 0 Aborted
The command "echo $RUN_TEST; eval "$RUN_TEST"" exited with 134.
</pre>

**Comment by Mnakagawa** [comment]
We recently don't see this failure at least since 15.03.
