### ISSUE TITLE
Reconsider Hatohol license model

### ISSUE THREAD

**Issue by robertclonez** [project-hatohol/hatohol#773]
In this moment, as we know that Hatohol uses GPLv2 license.

There is one thing that we have to consider. 

Some user want develop their own plug-in module so that it can link with their specific application.
Actually, user has to link plugin library to build module. If they don't want to open the source code
how to to?

Let's consider if GPLv3 or LGPL or others can protect such users.

**Comment by kz0817** [comment]
This issue was fixed, so I close the issue.
