### ISSUE TITLE
Create configurable about Web UI

### ISSUE THREAD

**Issue by bynnchapu** [project-hatohol/hatohol#778]
Currently, DB settings for Web UI is fixed.
However, I think user want to change configure about DB.

Not only that, I think user want to set a Hatohol server and the port and above it at one file.

**Comment by kz0817** [comment]
何が問題かよくわかりませんでした。
日本語でいいので、解説お願いします。

**Comment by bynnchapu** [comment]
返信遅くなってすいません。
現在のHatohol web UI用の設定類は ```client/hatohol/settings.py``` ファイルに以下のように決め打ちされています。

``` python
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'hatohol_client',
        'USER': 'hatohol',          
        'PASSWORD': 'hatohol',
        'HOST': '',                      # Set to empty string for localhost.
        'PORT': '',                      # Set to empty string for default.
    }
}
```

ただ、上記の設定を変更すると、パッケージアップデート時などに設定が消失する可能性があります。
そのため、上記の設定項目の一部を (NAME, USER など) 他のファイルに書き出した方が良いのではないかと思いました。

関連 Issue: #909

**Comment by bynnchapu** [comment]
```settings.py``` ファイルを見返していたのですが、このファイル自体を設定ファイル扱い(specファイルに ```%config(noreplace)``` をつける)にすれば良いのではないかと思いました。

**Comment by Mnakagawa** [comment]
@kz0817 created webui.conf in #2175
