### ISSUE TITLE
Doesn't rename the host name in hatohol

### ISSUE THREAD

**Issue by Mnakagawa** [project-hatohol/hatohol#815]
Host name is not renamed in hatohol when we change the host name on zabbix.
But I didn't confirm other middleware. (ex. Nagios)

**Comment by kz0817** [comment]
I assigned this issue to @Mnakagawa. But please get engaged in it after the new host management system is merged into master.

**Comment by Mnakagawa** [comment]
This problem was fixed in 15.03
