### ISSUE TITLE
Use the same style of pagination buttons among and Triggers page and Events page

### ISSUE THREAD

**Issue by bynnchapu** [project-hatohol/hatohol#818]
Currently, pagination button in Trigger and Event page is different.
I think it is good to integrate pagination button in Triggers page into Events page.

Because, user can't back to previous page in Events page, however user can back to previous page.

F.Y.I.
Pagination button in Events page:
![event](https://cloud.githubusercontent.com/assets/1008151/5278153/a302bd54-7b19-11e4-9c91-4ad44c4fa591.png)

Pagination button in Triggers page:
![trigger](https://cloud.githubusercontent.com/assets/1008151/5278161/b79fca4a-7b19-11e4-8ae4-f433ad9e5958.png)

**Comment by ashie** [comment]
Done: #1003
