### ISSUE TITLE
Can't update information of action

### ISSUE THREAD

**Issue by bynnchapu** [project-hatohol/hatohol#828]
Currently, Hatohol has following items of privileges about Action function:
1. Create a action
2. Update own actions
3. Update all actions
4. Delete own actions
5. Delete all actions
6. Get all actions

1, 4, 5, and 6 are already implemented yet.
But, I think 2 and 3 are not implemented yet because Hatohol doesn't show "Edit" button in Actions page. aren't it ?
If then, we need to implement to add "Edit" button and function.

**Comment by ashie** [comment]
Now both actions & incident settings are updatable.
