### ISSUE TITLE
[server] A value in "BIGUINT" column becomes zero unexpectedly

### ISSUE THREAD

**Issue by ashie** [project-hatohol/hatohol#850]
https://github.com/project-hatohol/hatohol/blob/master/server/src/DBAgent.cc#L535

Because a wrong format specifier "PRId64" is used against uint64_t, a value in "BIGUINT" column 
becomes zero on updating it with a big number (> 0x7fffffffffffffff).

@cosmo0920 found it while he was attending to fix #828.
(https://github.com/project-hatohol/hatohol/commit/8753aee5bc293b3306705ddb15ec08cb0bceb27d)

**Comment by kz0817** [comment]
The fix has been merged. So I close this issue.
