### ISSUE TITLE
When Qpid daemon is absent, the screen(Web UI) isn't updated.

### ISSUE THREAD

**Issue by o-wakabayashi** [project-hatohol/hatohol#872]
1. Stop qpid process during monitoring of using HAPI.
2. When you get ITEM via HAPI from the dashboard, is not go back response on screen(Web UI).(*1
3. When you update 4 times the dashboard in a 2 state, the screen(Web UI) of the state becomes 
   the "PREPARE".And the screen is unresponsive.(*2

*1: While locked to "readlock", and stops at the "send(qpid/messaging/Sender.h)" API 
    in HatoholArmPluginGate::startOnDemandFetchItem.
*2: Stop until the "readlock" lock of is released.

**Comment by o-wakabayashi** [comment]
原因は、
HatoholArmPluginInterface.cc の
HatoholArmPluginInterface::send の中で、
send（qpid/messaging/Message.h）を実行したときに、
qpiddが停止している状態だと
--
(gdb) l
296             m_impl->sender.send(request);
297     }
298
299     bool HatoholArmPluginInterface::getMessagingContext(MessagingContext &msgCtx)
300     {
301             HATOHOL_ASSERT(m_impl->currMessage,
302                            "This object doesn't have a current message.\n");
303             msgCtx.replyAddress = m_impl->currMessage->getReplyTo();
304             if (!msgCtx.replyAddress) {
305                     MLPL_ERR("No return address.\n");
(gdb) n
[Thread 0x7fbc0bfff700 (LWP 13795) exited]
--
例外が発生して、スレッドが停止する。
qpiddが停止した状況でも処理を継続するため、例外をcatchする処理が必要。

**Comment by cosmo0920** [comment]
こちら @o-wakabayashi さんのプルリクエスト #973 がmasterにマージされているので、問題が解消しているように思えますが、いかがでしょうか？
