### ISSUE TITLE
User role is changed into "unknown" when update privilege

### ISSUE THREAD

**Issue by miyashita-k** [project-hatohol/hatohol#890]
I update only privilege.
Then user role is changed into "unknown" even though I do not change role.

Is this behavior design?

##### screen shot:
![_002-2](https://cloud.githubusercontent.com/assets/8952002/5624440/84fc96fa-95a8-11e4-9a7a-c08f803ec137.png)

##### used user information:

 * user name:  user1
 * role name:  role1
    - on check only "Create a user"  

##### Steps to Reproduce:

1. click [Settings]-[Users].
2. click "user1" link.
3. click "EDIT" button.
4. click "Show/Edit" button right "role1".
5. on check "Update users" and "APPLY" button.
6. click "CLOSE" button.
7. click "CANCEL" button.
8. show [Settings]-[Users] page.

**Comment by ashie** [comment]
#905でユーザーロール更新時にユーザーのflagsも更新されるようになりましたが、
まだ課題があるのでopenしたままにしておきます。

* flagsの更新処理はRestResourceUserではなくDBTablesUserで行った方がよい
  * トランザクションで処理したい
  * ユーザー側の変更はクエリ一回で済ませたい

**Comment by cosmo0920** [comment]
気になったところを口頭でやりとりしたのでメモしておきます。

> * ユーザー側の変更はクエリ一回で済ませたい

こちらはMySQLに関してはbulk updateをサポートしてそれを使いたい。
SQLiteについてはbulk updateを使わず、一個つづupdateするように切り替える。

**Comment by ashie** [comment]
> こちらはMySQLに関してはbulk updateをサポートしてそれを使いたい。
> SQLiteについてはbulk updateを使わず、一個つづupdateするように切り替える。

すんません、よく理解しないまま生返事しましたが、各行バラバラの値をセットするなら
ともかく、この話に関しては全て同じflags値から別の同じflags値に変更するだけなので、
どちらも以下のようなSQLでいけませんか?

```sql
update users set flags=2 where flags = 1;
```

**Comment by cosmo0920** [comment]
いけそうです。
まずこちらを試してみて、うまくいかないようならばbulk updateを試してみようと思います。

**Comment by ashie** [comment]
> まだ課題があるのでopenしたままにしておきます。

もう一つ

* ユーザーの編集画面から対象ユーザーが属しているユーザーロールを編集すると、ユーザー編集画面でのユーザーロールの選択が「ゲスト」になってしまう

**Comment by cosmo0920** [comment]
> flagsの更新処理はRestResourceUserではなくDBTablesUserで行った方がよい

#920 で下記の2つの課題が解決されました。残り1つです。

- [x] トランザクションで処理したい
- [x] ユーザー側の変更はクエリ一回で済ませたい
- [ ] ユーザーの編集画面から対象ユーザーが属しているユーザーロールを編集すると、ユーザー編集画面でのユーザーロールの選択が「ゲスト」になってしまう

**Comment by cosmo0920** [comment]
このIssueは解決しましたので、閉じさせて頂きます。
なにかまだ問題があるようでしたらこのIssueをReopenしてください。
