### ISSUE TITLE
Not found "Get allowed monitoring servers" in privilege settings page

### ISSUE THREAD

**Issue by miyashita-k** [project-hatohol/hatohol#901]
I want to create user for only reading.

requirements:

 * can read event of only allowed zabbix server
 * can not create/update/delete all zabbix server

Please tell me, How to set such a user.

**Comment by miyashita-k** [comment]
内容について補足します。

特定のzabbixサーバのみのイベントを参照できるユーザを作成したいです。

求める要件：

 * 特定のzabbixサーバのみのイベントを参照できる
 * すべてのzabbixサーバの作成、更新、削除ができない

privilegeページにあるほかの権限では”all”と”allowed”が存在しています。
そのため、”Get allowed monitoring servers"にて設定するものと想定しました。
しかし、”Get allowed monitoring servers"が見当たらないです。

お手数をお掛けしますが、このような権限の設定方法をおしえていただけないでしょうか？

**Comment by Mnakagawa** [comment]
現在の仕様では監視サーバー毎に閲覧権限を設定できるため、おっしゃるような権限の設定は必要ありません
