### ISSUE TITLE
When I update only user name, does password change?

### ISSUE THREAD

**Issue by miyashita-k** [project-hatohol/hatohol#902]
Please tell me,
When I update only user name, does password change?

**Comment by miyashita-k** [comment]
補足します。

ユーザの名前だけを更新したいです。
以下がその画面なのですが、パスワード欄が空白になっています。
![_003](https://cloud.githubusercontent.com/assets/8952002/5716037/d2be6164-9b27-11e4-8c90-f2d70ab22d7f.png)



このまま、”APPLY”をクリックするとパスワードは空白に変更されるのでしょうか？

**Comment by ashie** [comment]
パスワードが空白の状態で更新した場合は、現在のパスワードのまま更新されます。

**Comment by miyashita-k** [comment]
ご回答くださり、ありがとうございます。
更新時の挙動、理解しました。
更新時はパスワード欄が「*******」となるとユーザにとってより親切になりますね。

**Comment by t-miyazawa** [comment]
入力前はパスワード欄に説明文（入力しないと前と同じパスワードである旨）の表示がうっすらと見えた状態で、クリックすると説明文が消えるようにする予定

**Comment by t-miyazawa** [comment]
更新時はパスワード欄が「********」となるようにしてみました。（文を書くより判り易い感じがするので）

![user_edit](https://cloud.githubusercontent.com/assets/10411652/8322648/b4138ffc-1a73-11e5-8cb3-a592d82ac4c3.png)

**Comment by cosmo0920** [comment]
This issue is fixed at #1290.
