### ISSUE TITLE
can't connect to SSL support zabbix

### ISSUE THREAD

**Issue by htomoya** [project-hatohol/hatohol#907]
hatohol 14.12 を試してみようとセットアップを行いましたが、当方で使用しているzabbixには接続できません。httpsで接続するようにzabbixをセットアップしておりますが、hatohol側はhttpのみで接続するようでした。

機会がありましたらSSL接続もサポート頂けるとうれしいです。

https://github.com/project-hatohol/hatohol/blob/master/server/common/ZabbixAPI.cc#L69

```c
	void setMonitoringServerInfo(const MonitoringServerInfo &serverInfo)
	{
		const bool forURI = true;
		uri = "http://";
		uri += serverInfo.getHostAddress(forURI);
		uri += StringUtils::sprintf(":%d", serverInfo.port);
		uri += "/zabbix/api_jsonrpc.php";

		username = serverInfo.userName.c_str();
		password = serverInfo.password.c_str();
	}
```

**Comment by yoshfuji** [comment]
I agree.  And, I think we should specify by (base) URL, not by ip-address and port for Zabbix.

**Comment by Mnakagawa** [comment]
ビルトインのArmZabbixでは非対応です。
15.06で開発予定のHAPI-2.0のZabbixプラグインでは対応予定です。

**Comment by Mnakagawa** [comment]
HAPI2.0プラグイン（python）では、実行環境のマシンでsslモジュールを
インポート可能な状況であれば、ssl通信でデータを送受信することができるようになりました。
urllib2というモジュールを用いて通信を行うのですが、URLを指定した際、httpsであれば、
urllib2が上記sslモジュールを用いて通信を行う。

**Comment by Mnakagawa** [comment]
クローズします。

**Comment by Mnakagawa** [comment]
証明書を用いて認証には、現在作成しているプラグインでは対応できません。
それを行う場合、httplibというモジュールを用いて証明書を用いた通信を確立し、
urllib2内のHTTPSHandlerを作成し、そして最後にこのハンドラーを用い、
通信相手と通信を行う必要があります。
