### ISSUE TITLE
When upgrade to ver14.12, hatohol.conf was changed

### ISSUE THREAD

**Issue by miyashita-k** [project-hatohol/hatohol#909]
Upgraded package. (14.09 --> 14.12)

ver14.09, I customized hatohol.conf and used it.
I hoped hatohol.conf was kept.
But hatohol.conf was changed.

show document:
https://github.com/project-hatohol/website/blob/master/contents/docs/upgrade/14.12/en/index.md

**Comment by miyashita-k** [comment]
たんに使ってみた感想になってしまうこと、ご容赦いただければと思います。

手順どおりにアップグレードしましたが、サービスが起動しませんでした。
調べてみると、これまで使っていた設定ファイル（hatohol.conf）の中身が書き換えられていることが原因でした。

14.09では設定ファイルをカスタマイズしていました。
あくまでアップグレードなので設定ファイルは維持されるだろうと、勝手に思い込んでいました。

アップグレードのドキュメントに、設定ファイルは維持されない記述が注意としてあるといいかなと思いました。

**Comment by kou** [comment]
RPMでは.specの書き方で設定ファイルを上書きしないようにできる気がするのでそれを設定するのがよいかもしれません。（具体的な書き方を示せなくてすみません。。。）

**Comment by bynnchapu** [comment]
> RPMでは.specの書き方で設定ファイルを上書きしないようにできる気がするのでそれを設定するのがよいかもしれません。

上書きされないようにするためには、```%files```セクション内の対象のファイルに```%config(noreplace)```をつければ良いそうです。
http://dev.tapweb.co.jp/2010/12/273

**Comment by Mnakagawa** [comment]
これ，現状（16.01）でも上書きのまんまなのですが，どうしますか？

**Comment by kz0817** [comment]
%configついてるように思います。これでいいんじゃないでしょうか？

https://github.com/project-hatohol/hatohol/blob/master/hatohol.spec.in#L247

**Comment by Mnakagawa** [comment]
%configに加えて(noreplace)がないと上書きされるという認識だったのですが，勘違い？

**Comment by kz0817** [comment]
> %configに加えて(noreplace)がないと上書きされるという認識だったのですが，勘違い？

ああ、そういうことね。上書きされるのが問題ってIssueか。

**Comment by Mnakagawa** [comment]
確かに現状のspecだと古い設定も残るし，新しい方もインストールされるしそれでいいのか。
上書きしないことも，それはそれで古いconfigが起動を妨げる原因も可能性もあるし。

**Comment by Mnakagawa** [comment]
理想は，古い方のconfigの一部の設定を新しい方のconfigに移し替えることだけど，
それ言い出したらきりがない気がしますし，現状でいいかなと思えました。

**Comment by Mnakagawa** [comment]
> アップグレードのドキュメントに、設定ファイルは維持されない記述が注意としてあるといいかなと思いました。

上のコメントにもありますが，これをドキュメントに追加すれば良さそうですね。
