### ISSUE TITLE
Reset Sorting data when pages are automatically update

### ISSUE THREAD

**Issue by miyashita-k** [project-hatohol/hatohol#912]
Reset Sorting data when pages are automatically update.
Is this behavior design?

**Comment by miyashita-k** [comment]
並べ替えして画面を見ていましたが、ページが自動更新されるとデータの並びが変わってしまいます。

この挙動は仕様かどうか、おしえていただけないでしょうか？

**Comment by ashie** [comment]
We should fix it with issue #497.

**Comment by ashie** [comment]
> Is this behavior design?

I think it's not expected behaviour, so we should treat it as a bug.

**Comment by t-miyazawa** [comment]
修正方針
* ソートは時刻フィールドのみ可能とするよう変更（他のフィールドはフィルタで絞る事で代用可能と考える）
* URLのsortOrderパラメータに指定する値をユーザ毎に保存できるようにする

**Comment by kz0817** [comment]
時刻以外のカラムヘッダは、クリックできないようにしたほうがよいです。
それができることで、いろいろと混乱を招くので。
全てのカラムでソートができるのは、意図したものではなく、使用しているライブラリのデフォルトがそうであったためです。

**Comment by ashie** [comment]
#1311 で修正された。
2015/12/15時点のmasterではイベント画面の「時間」以外はソートできなくなっている。
stupidtableは完全削除してしまってよさそう。
