### ISSUE TITLE
Polling interval column is not displayed in monitoring servers page

### ISSUE THREAD

**Issue by miyashita-k** [project-hatohol/hatohol#917]
In monitoring servers page,
Polling interval column is not displayed.

**Comment by miyashita-k** [comment]
たんなる使用した感想になること、ご容赦いただければと思います。
ポーリングインターバルの数値を見たいだけでもモニタリングサーバの編集画面に移らなければならず、少し不便に感じました。
編集画面に移ることは誤って変更するリスクがあるので、厳格な運用が求められる環境では嫌われる可能性もあるのでは、と思いました。

**Comment by ashie** [comment]
確かに。

監視サーバ設定以外にも編集と表示を兼ねているところがありますが、本当は表示専用のページが
あるべきだと思っています。

**Comment by kz0817** [comment]
サーバー一覧の表示画面で、マウスホーバーで直下の監視サーバのパラメータが吹き出し（ヒント）表示されてもいいかもしれませんね。

**Comment by t-miyazawa** [comment]
マップ欄をホバーした時に監視サーバのパラメータが吹き出しが出るようにする予定

**Comment by kz0817** [comment]
マップと、設定パラメータの関係が低いので、次のようにしてはどうでしょうか？
[info]なアイコンを列のどこかに用事して、それのクリックか、ホバーで表示。
マップも、どうようにするべきという議論が以前ありました。

**Comment by t-miyazawa** [comment]
以下の様にしました。ご意見をお願いします。
* マップの右に[info]アイコンを付け、その付近をホバーした時に表示する
* [info]アイコンの位置がウィンドウの右端に近いため、ポップオーバーは左側に出す
* タイトルは通信状態のポップオーバーと同一
* パスワードも"******"として表示
* チェックボックスの状態は "True" / "False" で表示
* 値が設定されていない要素の場合、ヒントがあればそれを表示（設定後の値なので"(empty: Default)"のみのはず）

![popover](https://cloud.githubusercontent.com/assets/10411652/8545405/562e2e9e-24e9-11e5-86b9-8120a3c88813.png)

**Comment by Mnakagawa** [comment]
わかりやすく，利便性も高い良い変更だと思います。
ありがとうございます。

**Comment by kz0817** [comment]
パスワードを表示しないなら、項目自体なくてよいと思いました。

**Comment by t-miyazawa** [comment]
了解です。無駄なのでパスワード欄は削除します。

**Comment by ashie** [comment]
#1471 でマージされましたのでクローズします。
