### ISSUE TITLE
Hostname for self monitoring is incomplete when hostname of monitoring server is long

### ISSUE THREAD

**Issue by miyashita-k** [project-hatohol/hatohol#918]
Hostname for self monitoring is incomplete when hostname of monitoring server is long.

I thought,
"SELF" string was always added to hostname for self monitoring.

Is it not so?

in "Triggers" page:
![_005-1](https://cloud.githubusercontent.com/assets/8952002/5794649/bf613dca-9fba-11e4-95af-b387209b2b8d.png)

**Comment by ashie** [comment]
> I thought,
> "SELF" string was always added to hostname for self monitoring.

Yes, it should always be added.

**Comment by Mnakagawa** [comment]
Delete ”_SELF”

**Comment by Mnakagawa** [comment]
Host name was unified to "(self-monitor)"
So, this problem does not occur.
