### ISSUE TITLE
Only ArmZabbixAPI accepts "--load-old-events" option

### ISSUE THREAD

**Issue by ashie** [project-hatohol/hatohol#921]
The behaviour of loading old events is changed in #915.
But this modification is only for ArmZabbixAPI, it's not applied to other arms or HAPI plugins such as 
ArmNagiosNDUtils or HAP-Zabbix.

**Comment by Mnakagawa** [comment]
ArmNagiosNDUtilsで対応が必要

**Comment by Mnakagawa** [comment]
#2240 load-old-option is removed
