### ISSUE TITLE
What does host of self monitoring in filter on "LatestData" page use it for?

### ISSUE THREAD

**Issue by miyashita-k** [project-hatohol/hatohol#922]
On "LatestData" page,
Host of self monitoring in filter.

What is it for?

![_007-3](https://cloud.githubusercontent.com/assets/8952002/5810217/04b1bd20-a086-11e4-87bb-8e4a339af99d.png)

**Comment by miyashita-k** [comment]
"LatestData"ページでは、ホストxxx_SELFでフィルタが可能になっています。
しかし実際に操作してみると何も表示されません。
"LatestData"ページでSELFホストのフィルタはどういった用途で使用するものでしょうか？

バグ等ではなく使い方の質問になってしまうこと、ご容赦ください。

**Comment by ashie** [comment]
現状ではxxx_SELFに対応したアイテムというのは無いので、特に用途は無いと思います。
トリガー画面などと処理が共通化されてしまうので表示されてしまいますが、表示しない方が適当かも
しれませんね。「Overview: Items」も同様ですね。

**Comment by miyashita-k** [comment]
@ashie san
コメントありがとうございます。
私のセットアップ方法が間違っていて表示されるはずのものが表示されてないのか、それとも現状ではそれが仕様なのかが不明でしたのでご質問をしました。
現状では用途がない旨、理解しました。

**Comment by ashie** [comment]
#1300 で修正された
