### ISSUE TITLE
Host group is changed into "unknown" when update incident tracking settings

### ISSUE THREAD

**Issue by miyashita-k** [project-hatohol/hatohol#928]
I update incident tracking settings.
Then host group is changed into "unknown".
![_008-5](https://cloud.githubusercontent.com/assets/8952002/5828916/a498a12e-a14d-11e4-8bb8-d6d2ae6c9ccc.png)

#### Steps to Reproduce:  
  

1. click [Settings]-[Incident tracking settings].
2. click "ADD" button.
3. select condition.
![_008-1](https://cloud.githubusercontent.com/assets/8952002/5828853/f4c5a92c-a14c-11e4-9d23-5d914a235656.png)

4. click "APPLY" button.
5. click "EDIT" button.
![_008-2](https://cloud.githubusercontent.com/assets/8952002/5828862/086d7a9a-a14d-11e4-8494-42fe58329f44.png)

6. change condition.
![_008-3](https://cloud.githubusercontent.com/assets/8952002/5828863/15352084-a14d-11e4-85ee-e0fd73f2671f.png)

7. click "APPLY" button.

**Comment by miyashita-k** [comment]
"unknown"になってしまうのは、何か操作が間違っているのでしょうか？

また、これは関連があるかわかりませんが、モニタリングサーバを指定したうえで、incident tracking設定を追加しても、編集画面を開くとモニタリングサーバの指定が消えてanyになってしまいます。

**Comment by ashie** [comment]
私の環境でも再現しました。
たしかに、おかしな挙動ですね。
同じコードを使用しているアクション設定の方は正しく動作しているようです。
対応を検討します。

**Comment by cosmo0920** [comment]
原因はincident tracking設定で使用しているモニタリングサーバのCSSセレクタの指定が間違っていたためでした。

**Comment by cosmo0920** [comment]
モーダルダイアログのBootstrap化を試していて、インシデント管理設定の更新に以下のバグを見つけました。

* インシデント管理の編集のモーダルダイアログを出した時にインシデント管理サーバーのプルダウンが追従しない

**Comment by cosmo0920** [comment]
まだ問題が直っていないようなのでReopenしました :cold_sweat:
