### ISSUE TITLE
When delete "host" on zabbix, deleted item continues remaining in "Overview:Items" page

### ISSUE THREAD

**Issue by miyashita-k** [project-hatohol/hatohol#929]
When delete "host" on zabbix, deleted item continues remaining in "Overview:Items" page.

**Comment by miyashita-k** [comment]
I saw pull request #900.

pull request #900,
Is object to exclude only "trigger"?　OR "item" and "trigger"?

**Comment by ashie** [comment]
Fixed in #942 

Related issue: #20
