### ISSUE TITLE
Number of event is not displayed in "Dashboard" page

### ISSUE THREAD

**Issue by miyashita-k** [project-hatohol/hatohol#930]
In "Dashboard" page, 
Number of host is displayed.
Number of trigger is displayed.
Number of item is displayed.

But,
Number of event is not displayed.
Number of user is not displayed.

**Comment by miyashita-k** [comment]
たんなる使用した感想になること、ご容赦いただければと思います。
”Dashboard”ページの役割は、”Triggers”や”LatestData”など各ページのサマリや統計であるとの印象をうけました。
ほんとうにそのような役割で、”Dashboard”ページを作成なさっているのでしたら、イベント数やユーザ数も見れたほうが自然で、ユーザにとって有益な画面になるのでは、と感じました。
ただ何を表示するかは、少し検討があったほうがいいのかもしれません。

**Comment by bynnchapu** [comment]
> イベント数やユーザ数も見れたほうが自然で、ユーザにとって有益な画面になるのでは、と感じました。

私もイベント数がダッシュボード(イベントページでも？)閲覧できるようにした方が良いと思います。
(もっと言うならば、当日の発生件数、前日との差分なども表示できるようになるとより良いと思いました。)

ただ、私はユーザ数を見られる必要性を感じませんでした。

**Comment by ashie** [comment]
> 私もイベント数がダッシュボード(イベントページでも？)閲覧できるようにした方が良いと思います。
> (もっと言うならば、当日の発生件数、前日との差分なども表示できるようになるとより良いと思いました。)

当日など時間範囲を区切ったイベント数は意味があると思いますが、一行目はDB内の全イベント数を
意味していますか? もしそうだとしたら、通常の監視のコンテキストではあまり意味が無さそうに感じて
います（DBメンテナンス等のコンテキストでは意味があると思います）。

全イベント数の取得は、主に性能上の問題で、やらなくていいなら避けたいです。

単にeventsテーブルの全行の行数をとるだけならテーブル情報から引っ張ればいいだけなので性能面
の問題はありませんが、そのユーザーが見られるイベントに限定するなどの条件が入ると全行を舐める
ことになるので、性能面の問題が発生します。

**Comment by bynnchapu** [comment]
> 一行目はDB内の全イベント数を意味していますか?

そのつもりで投稿しましたが、深くは考えていなかったです。
ただ、1日あたりの発生件数については「あれば便利かな」と思い投稿しました。

> 全イベント数の取得は、主に性能上の問題で、やらなくていいなら避けたいです。
> 
> 単にeventsテーブルの全行の行数をとるだけならテーブル情報から引っ張ればいいだけなので性能面
> の問題はありませんが、そのユーザーが見られるイベントに限定するなどの条件が入ると全行を舐める
> ことになるので、性能面の問題が発生します。

確かに仰る通りです。そういうところをあまり考慮していませんでした。

Zabbixの画面を見ると、Zabbixのダッシュボードでもイベント数は表示されていないですね。
確認不足でした。

**Comment by Mnakagawa** [comment]
UI-2.0で検討

**Comment by Mnakagawa** [comment]
wont fix
