### ISSUE TITLE
Label of monitoring server port is not translated in pop-up window

### ISSUE THREAD

**Issue by miyashita-k** [project-hatohol/hatohol#931]
Label of monitoring server port is not translated in pop-up window.

in pop-up window,
Is label not translated?

in setting page,
label is translated.
![_004-6](https://cloud.githubusercontent.com/assets/8952002/5828995/da07813a-a14e-11e4-82b3-fbb71dfe0b08.png)

But,
in pop-up window,
label is not translated.
![_004-5](https://cloud.githubusercontent.com/assets/8952002/5828999/ea27bf1c-a14e-11e4-8323-0011433752e5.png)

**Comment by miyashita-k** [comment]
エラー画面内のport文字列は翻訳されないのでしょうか？
これが正常な画面なのか、そうではないのか、私ではわからないためご教示いただければと思います。

**Comment by ashie** [comment]
現状では、翻訳されない仕様です。

**Comment by Mnakagawa** [comment]
wont fix
