### ISSUE TITLE
[ZabbixAPI] Using different function to be used for setting boolean value of JSON

### ISSUE THREAD

**Issue by bynnchapu** [project-hatohol/hatohol#934]
When I checked the Pull Request #932 and #933, I noticied.

We use ```addTrue(member)``` (or ```addFalse(member)```) and ``` add(member, "True")``` (or ```add(member, "False")```) functions to be used for setting boolean value of JSON.

**Comment by kz0817** [comment]
add(member, "True") sets a string, doesn't it ?

**Comment by bynnchapu** [comment]
Yes, I think so too.

But, when I checked the ```common/ZabbixAPI.cc``` file now, using above style is used one point only.
Probably, I mistook... 

I'll fix following line:
https://github.com/project-hatohol/hatohol/blob/master/server/common/ZabbixAPI.cc#L716

**Comment by Mnakagawa** [comment]
Define new enum for boolean

**Comment by cosmo0920** [comment]
Pull Request #1195 では言い切れていない箇所もあると思うのでこちらには日本語でメモしておきます。

確かにenumでJSON用のBooleanの値を作ってやるか、型が曖昧にならないようにaddのオーバーロードを定義してやることで `JSONBuilder::add` のオーバーロードでBooleanも扱えるようになりました。

ただ、これには弊害もあって、`add(std::string&, bool)` が期待されている箇所に `add("expected boolean", 2)` を入れてしまった場合、 `add(std::string&, gint64)` のオーバーロードがマッチしてしまい、意図とはことなる挙動になってしまいます。

APIを綺麗にする観点としてはこの方針では間違っていないのですが、JSON上ではintとbooleanは明確に型が分かれています。
なので、JSONへ落とすときにBoolean型を強制する、というのと、意図せずBooleanを入れるべき所に入れなかったという事故を防ぐためにも`addTrue/addFalse` のように関数名に明示してある方が良いと感じました。

**Comment by cosmo0920** [comment]
という結論になりましたので、JSONBuilderの `addTrue`, `addFalse` メンバはこのまま据え置きです。

**Comment by cosmo0920** [comment]
もしも `addBoolean(std::string&, bool)` のような関数を定義して、bool値を扱う実装とするならば、boolを受け取れるようにするのではなく `enum JSONBoolean = { JSONTrue, JSONFalse};` とし、このenumを使うようにすれば意図せずbool値を期待する箇所にbool値に暗黙の内に型変換されるgint64型やint型などを入れないようにできると思います。（が、これはC++の観点からすると少々やりすぎです。直和型が気軽に定義できるような型の軽い言語のアプローチなので。）
