### ISSUE TITLE
Filter condition is cleared when change a page

### ISSUE THREAD

**Issue by miyashita-k** [project-hatohol/hatohol#935]
Filter condition is cleared when change a page.

When problem happened,
I change "Events","Triggers","Dashboard" page frequently.
I feel inconvenience because condition of filter is cleared.

**Comment by miyashita-k** [comment]
たとえばホストAで問題が起きたとすると、ホストAに注目して調査したいので、各ページにてホストAでフィルタします。
各ページを移動するたびに、フィルタがクリアされると、毎回フィルタをやり直さなければならず、少し困ってしまいました。

Hatoholはこのように、”Events”、”Triggers”、”Dashboard”ページを頻繁に移動する使い方はあまり推奨されておらず、フィルタがクリアされないようページは固定して自動更新するだけの使い方が主流なのでしょうか？

もし一般的にもありそうな使い方だとご判断されるようでしたら、フィルタ条件を保持したり、もしくは保存されたフィルタ条件を簡単に呼び出せるなど、の機能を検討してみてもよいのでは、と思いました。

**Comment by ashie** [comment]
issue登録されていなかったようですが、フィルタの保存既存は検討しています。

**Comment by t-miyazawa** [comment]
各ページのフィルター条件をuserconfigに保存するようにしてみました。何となく動いている 感じ。
https://github.com/project-hatohol/hatohol/commit/4417e7ba4c6f0a214e245ad17efb02eeda3f0a4e

**Comment by Mnakagawa** [comment]
新UIに変わってから，フィルターの保存が可能になった。
本Issueはその機能を利用することにより解決できる。
