### ISSUE TITLE
Some hosts are "unknown" in "Events" page when enable "load-old-events" option

### ISSUE THREAD

**Issue by miyashita-k** [project-hatohol/hatohol#937]
Some hosts are "unknown" in "Events" page when enable "load-old-events" option.

in "Events" page,
Some hosts are "unknown".

What is the reason of this behavior?

hatohol "Events" page:
![_009-1](https://cloud.githubusercontent.com/assets/8952002/5847983/bc31ed12-a216-11e4-887a-d126bc941cd1.png)

zabbix "Events" page:
![_009-2](https://cloud.githubusercontent.com/assets/8952002/5847989/c6ff18f0-a216-11e4-9563-d55aa85832ef.png)

zabbix "Host" settings:
![_009-3](https://cloud.githubusercontent.com/assets/8952002/5847992/caebd6ec-a216-11e4-9f5d-139652812d72.png)

**Comment by miyashita-k** [comment]
イベント”Disk I/O overloaded”が、Hatoholの画面では”unknown”になってしまいます。
”unknown”になる理由をご教示いただけないでしょうか？

**Comment by ashie** [comment]
対応するトリガーのHatohol上での表示はどうなっていますか?
(Hatohol上には表示されていないだろうと予測しています)

Hatoholでは、Host情報等は対応するトリガーから取ってきます。
トリガーを取得できていないと、ご指摘のような問題が起こる可能性があります。

トリガーを取得できない既知のケースとしては、Zabbix側で新規に追加されたトリガー
の場合、トリガーの状態が変わるまでHatohol側に同期されないというものがあります。

ただ、イベントが取得できていて、トリガーが取得できていないというケースが発生し得る
のかどうかは今のところ把握できていません。

**Comment by miyashita-k** [comment]
トリガー画面は以下のようになっています。

![_009-4](https://cloud.githubusercontent.com/assets/8952002/5851362/6830b42c-a249-11e4-9e8f-1266ae78997e.png)

予測なさっていたようにhost5のトリガーが一切無いようです。
ここで仕様についてご教示いただきたいことがあります。

* トリガーはzabbix上でホストが無効でも取得されるのでしょうか？
* イベントはzabbix上でホストが無効でも取得されるのでしょうか？

**Comment by ashie** [comment]
> * トリガーはzabbix上でホストが無効でも取得されるのでしょうか？
> * イベントはzabbix上でホストが無効でも取得されるのでしょうか？

有効化されているトリガーのみが取得されます。

**Comment by Mnakagawa** [comment]
無効になっているトリガー、ホストを取得するようにZabbixAPIのオプションを変更する。
無効となっているホストのステータスも返ってくるのか調査の必要あり。

**Comment by Mnakagawa** [comment]
{"output": "extend", "selectGroups": "refer", "monitored_hosts": True}
{"output": "extend", "selectHosts": ["name"], "active": True}
これが現在ホストを取得しているAPI. 
それぞれmonitoring_hosts: True， active: Trueを消せばよいか。

**Comment by Mnakagawa** [comment]
> 無効になっているトリガー、ホストを取得するようにZabbixAPIのオプションを変更する。
> 無効となっているホストのステータスも返ってくるのか調査の必要あり。

決めたのはかなり前で記憶が相当あやふやなのだが，今から修正を加えるとしてもこの内容でよい？
自分の発言ですけど「ホストのステータス」が何を指しているのか全くわからない。。。

**Comment by Mnakagawa** [comment]
> active	flag	Return only enabled triggers that belong to monitored hosts.

とあって，無効になっているホストに属するトリガーをまず取得できない。
無効となっているホストは取得できた。

よって
```
それぞれmonitoring_hosts: True， active: Trueを消せばよいか。
```
を実施した際には

- 無効ホストに属するトリガーはenableｄもdisabledも取得できない。
- 有効ホストに属するdisabledトリガーは取得できる。

となる。

つまりこのIssueの問題は解決できない。

**Comment by Mnakagawa** [comment]
意見がなければwan't fixということでクローズしようと思いますがいかがでしょうか。

**Comment by ashie** [comment]
そもそもこの問題って今のHAP2 Zabbixで再現するのでしょうか?

ちょっと前に試した時、削除されたホスト(無効ではなく、削除されたホストだったと思いますが
自信なし)に対するイベントは取得されていなかったように見えました。
(ログにバックトレースが表示されて、そのイベントはスキップされていた)
削除ではなく無効の場合にどういう挙動になるのかはよくわかっていません。

**Comment by Mnakagawa** [comment]
そもそも過去イベントは取得しない方針になりましたからね。
削除された or 無効になっているホストからはイベントがそもそも発生しませんし。
 このIssueも"load-old-events"を使用した場合発生しているものなので，hap2ではそもそも起きないはず。

**Comment by Mnakagawa** [comment]
クローズします
