### ISSUE TITLE
When a session did time-out, the operation of the deletion of Action settings is completed, but it is not deleted

### ISSUE THREAD

**Issue by miyashita-k** [project-hatohol/hatohol#938]
When a session did time-out, the operation of the deletion of Action settings is completed, but it is not deleted.

Steps to Reproduce:

1. wait session time-out (10 minutes?).
2. in check Action, and clink "DELETE ACTIONS" button.
![_010-1](https://cloud.githubusercontent.com/assets/8952002/5848022/30229dde-a217-11e4-803f-a39524ec2b02.png)

3. input user and password.
![_010-2](https://cloud.githubusercontent.com/assets/8952002/5848025/38145302-a217-11e4-8e47-24bcceb57dbe.png)

4. after login.
![_010-3](https://cloud.githubusercontent.com/assets/8952002/5848028/3c460768-a217-11e4-8973-b7dd2a34bf3f.png)

5. show "Actions" page.  
##### Action is not deleted.
![_010-4](https://cloud.githubusercontent.com/assets/8952002/5848033/46ec6f90-a217-11e4-8278-884e88e6e09d.png)

**Comment by miyashita-k** [comment]
セッションがタイムアウトしたとき、アクションを削除すると、complete画面が返されるにもかかわらず、削除されていません。

私ですと途中で電話が入り、終了後、タイムアウトと知らずに、操作したら今回の事象になるので、気になりました。

* 削除できなかったときは、削除不可の画面が返ったり
* タイムアウトしたらポップアップで通知したり
* そもそも削除のオペレーションができないようにタイムアウトしたら自動的にログイン画面に切り替わったり

など、もう少し工夫の余地もあるのでは、と感じました。

**Comment by ashie** [comment]
現象確認しました。

1. 「選択項目を削除してもよろしですか」->「はい」を選択
2. この段階で一度DELETEメソッドと、一覧取得のためのGETメソッドが走っている
3. ログイン処理が走る
4. 再度選択アイテムに対する処理が走るが、DELETEメソッドにすべきところがなぜかGETメソッドになっている
5. GETメソッドの成功をDELETEメソッドの成功と勘違いして成功ダイアログを出してしまう

**Comment by ashie** [comment]
手っ取り早い再現方法

1. ブラウザでActionページのタブと、適当なHatoholページのタブを用意する
2. Actionページで削除確認ダイアログまで進む
3. もう一つのタブでログアウト
4. Actionページで削除実行

**Comment by ashie** [comment]
> * 削除できなかったときは、削除不可の画面が返ったり

そもそも削除できないことがバグであり、これは#940で直しました。
これで削除できない場合はエラーが返るので、本issueは閉じます。

ただ、

> * タイムアウトしたらポップアップで通知したり
> * そもそも削除のオペレーションができないようにタイムアウトしたら自動的にログイン画面に切り替わったり

上記のいずれかの対応は確かに欲しいなと思っています。
