### ISSUE TITLE
"/en/" string is not added to URL in "Name" column on "Triggers" page when add "/en/"  string to a URL and access Hatohol

### ISSUE THREAD

**Issue by miyashita-k** [project-hatohol/hatohol#944]
"/en/" string is not added to URL in "Name" column on "Triggers" page when add "/en/"  string to a URL and access Hatohol.

**Comment by miyashita-k** [comment]
問題というわけではないのですが、少し気になったので記載します。

トリガー画面に、http://localhost/en/ajax_triggersでアクセスしています。
しかし、”名前”列のリンク先のURLは以下になっていて”/en/”が付いていません。
http://localhost/ajax_events?serverId=3&triggerId=28826

URLをこのようになさっている理由をご教示いただけないでしょうか？
（”/en/”を付けてしまうとxxxxxの動作で不具合があるなど）

**Comment by bynnchapu** [comment]
> URLをこのようになさっている理由をご教示いただけないでしょうか？
> （”/en/”を付けてしまうとxxxxxの動作で不具合があるなど）

仕様のようです。```サーバーアドレス:ポート番号/en/``` または ```サーバーアドレス:ポート番号/ja/``` でアクセスした時、Hatohol内のリンク先のアドレスは ```/en/``` または ```/ja/``` をつけるよう考慮されていません。
``` javascript
      html += "<td>"
	+ "<a href='/ajax_events?serverId=" + escapeHTML(serverId)
	+ "&triggerId=" + escapeHTML(trigger["id"]) + "'>"
	+ escapeHTML(trigger["brief"])
	+ "</a></td>";
```

**Comment by ashie** [comment]
> 仕様のようです。サーバーアドレス:ポート番号/en/ または サーバーアドレス:ポート番号/ja/ でアクセスした時、

いや、単なるミスですね。
最新データ -> グラフの方は相対パスになってますし、ナビバーも全部相対パスになってます。
その辺書いたのは両方とも私です。犯人は私です。

**Comment by ashie** [comment]
修正しました。
