### ISSUE TITLE
Same value is displayed by "Previous value" column and "Last value" column in "LatestData" page when used item for log

### ISSUE THREAD

**Issue by miyashita-k** [project-hatohol/hatohol#945]
Same value is displayed by "Previous value" column and "Last value" column in "LatestData" page when used item for log.

On zabbix,
I used item for error of the log.

I thought,
"Previous value" column exists to display the previous value.

What is the reason of this behavior?

Hatohol page:
![_011-1](https://cloud.githubusercontent.com/assets/8952002/5867455/db6c6e2c-a2df-11e4-80a7-686b55ca1bd4.png)

zabbix page:
![_011-2](https://cloud.githubusercontent.com/assets/8952002/5867457/dea40320-a2df-11e4-9b3f-8cdacf5432e9.png)

**Comment by miyashita-k** [comment]
zabbixでログ用のアイテムを使っています。

”Previous value”列と"Last value"列に同じ内容が表示されてしまいます。
このような表示になさっている理由をご教示いただけないでしょうか？

zabbixでは異なる内容がきちんと表示されています。（上記のスクリーンショット）
”Previous value”列にはその名前のとおり、前回の値が表示されると予想していましたが、そうなっていないので、その理由がわかればと思います。

**Comment by kz0817** [comment]
Hatoholのバグのようにも思われますね。ただ、他の監視サーバのことも考慮に入れるとPrevious valueが本当に必要か検討する必要があると思います。そもそも、previous valueが何かというのは、監視システムによって異なるはずですし、必ずしも取得できると限らないので。

**Comment by Mnakagawa** [comment]
UIとレストAPIの修正が必要

**Comment by t-miyazawa** [comment]
* 問題の原因は utils.js: formatItemPrevValue() で、 数値以外の場合に "Last value" を表示してるため
* PreviousValueを削除する方針： DBテーブルからprev_valueを削除する

**Comment by ashie** [comment]
あー、バグ自体は #1264 で直りますね。
#1264 をやっているときに、issueが立ってたはずと思いつつも、ここを見つけることができていませんでした。

**Comment by ashie** [comment]
#1298 で Previous value は削除された
