### ISSUE TITLE
The elements of a server list is redundant.

### ISSUE THREAD

**Issue by bynnchapu** [project-hatohol/hatohol#95]

**Comment by t-miyazawa** [comment]
内部IDを付けるとこんな感じになります。
![n](https://cloud.githubusercontent.com/assets/10411652/6369696/ff774146-bd2b-11e4-9cc1-5b8e646d2a6e.png)

**Comment by t-miyazawa** [comment]
以下の理由から表示を区別しなくても良いのではないでしょうか
* ユーザには表示の違いから自分が参照したいホストを判断することが出来ないこと
* ニックネームはユーザ責任として重複を許すこと

**Comment by kz0817** [comment]
UIに関する事項なので、次回のFace2Face Meetingで議論しましょう。

**Comment by Mnakagawa** [comment]
> ニックネームはユーザ責任として重複を許すこと

結論コレでクローズしていいと思いますがいかがでしょう

**Comment by ashie** [comment]
私はそれでいいと思います。

**Comment by Mnakagawa** [comment]
OK
