### ISSUE TITLE
Upper case character and lower case character are separated when sorted by "Name" column in "Triggers" page

### ISSUE THREAD

**Issue by miyashita-k** [project-hatohol/hatohol#952]
Upper case character and lower case character are separated when sorted by "Name" column in "Triggers" page.

hatohol sort:
![_013-1](https://cloud.githubusercontent.com/assets/8952002/5893975/2fb32efa-a53b-11e4-8cbe-16ee7c955c43.png)

zabbix sort:
![_013-2](https://cloud.githubusercontent.com/assets/8952002/5893978/33d1679a-a53b-11e4-86c4-ac897a45130e.png)

**Comment by miyashita-k** [comment]
Hatoholのソートは大文字と小文字を区別して、zabbixとは異なるようです。

まったく同じである必要はないと思いますが、
将来、用途に合わせて大文字、小文字を区別する、しないの両方でソートできるとユーザにとって便利なのでは、と感じました。

**Comment by Mnakagawa** [comment]
won't fix
