### ISSUE TITLE
Order of sorted event was reversed in "Events" page when filter event by monitoring server

### ISSUE THREAD

**Issue by miyashita-k** [project-hatohol/hatohol#953]
Order of sorted event was reversed in "Events" page when filter event by monitoring server.

Steps to Reproduce:

1. sort by "Brief" column.
![_012-1](https://cloud.githubusercontent.com/assets/8952002/5893985/7a853b6c-a53b-11e4-8b9e-c4f4f13c9fda.png)

2. filter by monitoring server.
3. sort by "Brief" column. event reversed.
![_012-2](https://cloud.githubusercontent.com/assets/8952002/5893987/9ba5788e-a53b-11e4-91b7-d204ba945ce6.png)

**Comment by miyashita-k** [comment]
上記の手順のでソートすると矢印の向きは同じにもかかわらず、内容が反対になってしまいます。
私の環境だけの問題でしょうか？

もし別の環境でも再現するようようでしたら、"Brief"列だけでなく、ほかのカラムであったり、ほかのページのソートも見たほうがいいのかもしれません。

**Comment by ashie** [comment]
今、手元の環境ではBriefが同じ名前で埋め尽くされているのでホスト名の方で確認しましたが、
やはり再現します。現状の処理の流れ的にも、やはりそうなるものと思われます。
これは明らかにバグですね。ご報告ありがとうございます。

**Comment by t-miyazawa** [comment]
#1311 でソート可能なカラムを時間のみにし、ソートインジケータとソート順が一致するようにしました。

**Comment by Mnakagawa** [comment]
クローズ忘れだったのでクローズ
