### ISSUE TITLE
Updated value of "project id" column of incident tracking servers, but "project id" was not changed

### ISSUE THREAD

**Issue by miyashita-k** [project-hatohol/hatohol#954]
Updated value of "project id" column of incident tracking servers, but "project id" was not changed.

When is incident tracking servers setting changed?

**Comment by miyashita-k** [comment]
インシデントトラッキングサーバ設定でプロジェクトidを「A」ですでに設定しており、運用しています。

投稿されるプロジェクトidを「A」から「B」に変更したいです。
しかし、「A」から「B」に変更しても、「A」にインシデントの投稿が続いています。

インシデントトラッキング設定は画面上では「B」に変更されているように見えます。

インシデントトラッキングサーバの設定変更はどのタイミングで反映されるのでしょうか？

**Comment by ashie** [comment]
現在の実装では、Hatoholサーバをリスタートしないと反映されません。

**Comment by cosmo0920** [comment]
インシデント管理サーバーの設定を変更するとインシデントの投稿先が変更されるpull requestと、インシデント管理サーバーの設定が削除された場合にインシデント投稿スレッドを止める対応がmasterにマージされたので本件はクローズさせて頂きます。
何か問題がありましたらこのissueをreopenしてください。
