### ISSUE TITLE
Start of the process failed when input a wrong value of "Base URL" column in incident tracking servers

### ISSUE THREAD

**Issue by miyashita-k** [project-hatohol/hatohol#955]
Start of the process failed when input a wrong value of "Base URL" column in incident tracking servers.

What is the operation for recovery?

**Comment by miyashita-k** [comment]
インシデントトラッキングサーバのベースURLは本来、

http://server2
と設定したかったのですが、


htt:server2
というように間違って設定してしまいました。

Hatoholを停止すると、次回以降、Hatoholが起動しなくなりました。

URLを修正したいのですが、起動しないため修正できません。
このようなケースに陥ったとき、まずは起動させる暫定対処などありましたら、ご教示いただけないでしょうか？

また、起動しない理由をご教示いただけないでしょうか？

**Comment by bynnchapu** [comment]
> Hatoholを停止すると、次回以降、Hatoholが起動しなくなりました。

エラーメッセージは出力されていますか？

**Comment by ashie** [comment]
14.12では不正なURIを入力できないようにしていましたが、URLのチェックとしては不完全なので、
確かにhtt:server2は入力できてしまうようです。

> このようなケースに陥ったとき、まずは起動させる暫定対処などありましたら、ご教示いただけないでしょうか？

現状ではDBから直接同レコードを削除するしかありません。
```sql
mysql> select * from incident_trackers;
+----+------+----------+---------------------------+------------+------------+-----------+----------+
| id | type | nickname | base_url                  | project_id | tracker_id | user_name | password |
+----+------+----------+---------------------------+------------+------------+-----------+----------+
|  1 |    0 | Redmin   | http://lolcahost/redmine/ | 1          |            | ****      |          |
|  3 |    0 | hoge     | htt:server2               | hoge       |            | ****      |          |
+----+------+----------+---------------------------+------------+------------+-----------+----------+
2 rows in set (0.00 sec)

mysql> delete from incident_trackers where id=3;
Query OK, 1 row affected (0.00 sec)
```

**Comment by ashie** [comment]
> また、起動しない理由をご教示いただけないでしょうか？

インシデント同期用のスレッドを起動する時のチェックを入力時と同じチェック方法に依っていましたが、
このチェックが通ってしまい、最終的にクラッシュしているようです。
すみません、チェックが甘かったです。修正します。

**Comment by miyashita-k** [comment]
@bynnchapu san

> エラーメッセージは出力されていますか？

早々にコメントくださり、ありがとうございます。
もしかすると手元の環境だけの問題かもしれませんので、まずは再現するか試していただくことはできますでしょうか？

ベースURLに上記に記載のものをご入力いただければ、それ以外の項目は任意に設定していただければと思います。
お手数をおかけして申し訳ありません。

**Comment by miyashita-k** [comment]
@ashie san

> 現状ではDBから直接同レコードを削除するしかありません。

レコードを削除して起動するようになりました。
ご教示いただき、ありがとうございました。

**Comment by ashie** [comment]
クラッシュの問題は #972 で修正。
入力値のvalidationも修正したいので、本issueは開いたままにしておく。

**Comment by ashie** [comment]
> 入力値のvalidationも修正したいので、本issueは開いたままにしておく。

別のissueとして扱うべきなのでcloseします。

既存のissueでは #120 が該当する。
