### ISSUE TITLE
First event and third event are not displayed in "Events" page

### ISSUE THREAD

**Issue by miyashita-k** [project-hatohol/hatohol#961]
First event and third event are not displayed in "Events" page.

What is the reason of this behavior?

hatohol:
![_015-1](https://cloud.githubusercontent.com/assets/8952002/5952278/f13579a2-a7b6-11e4-85b1-e4bb61af2763.png)

zabbix:
![_015-2](https://cloud.githubusercontent.com/assets/8952002/5952281/f4d74176-a7b6-11e4-9a9e-dff0dc56af60.png)

**Comment by miyashita-k** [comment]
昨日、zabbixを登録しました。この時点でイベントは0件でした。
本日、zabbixでイベントが3件、発生しました。

しかし、Hatoholのイベント画面では2件目だけ表示されています。
1件目と3件目のイベントが表示されません。

以前会議のときに、デフォルトではモニタリングサーバの登録時は過去のイベントは取得されず、
登録のあとから発生したイベントを取得する仕様になっているとお伺いした覚えがあります。

zabbixを登録したあとに、イベントが3件、発生したにも関わらず、
1件目のイベントが表示されない理由をご教示いただけないでしょうか？

また、3件目のイベントが表示されない理由も同様でしょうか？
それとも1件目とは別の理由でしょうか？

**Comment by ashie** [comment]
口頭で確認: 開始時にはHatoholもZabbixもイベントは空の状態だったとのこと

いまの実装だと、Hatohol側のイベントテーブルが空の場合、Zabbixからもっとも
Event IDが大きいイベントを一個だけ取ってくるという動作になります。
Event IDは必ずしも時間順にはならないので、この場合はHatohol側に登録された
イベントがもっともIDが大きいイベントだったということだったと思われます。

さらに、開始時点ではZabbix側にもイベントが無かったので、Zabbix側で3つの
イベントがほぼ同時期に発生したあと、Hatohol側のポーリングが動作し、上記の
条件で取得してしまったのだと思われます。

望ましい動作とは言えないので、もうちょっと実装を見直した方がよさそうです。

**Comment by Mnakagawa** [comment]
監視サーバー登録以前のイベントは一切取得しない仕様(hap2)になったのでクローズ

**Comment by ashie** [comment]
"--load-old-events"オプションってまだ残ってますよね?

> 監視サーバー登録以前のイベントは一切取得しない仕様(hap2)になったのでクローズ

しないし、できなくなったので、このオプション消した方が良さそう。
別issue立てる?

**Comment by Mnakagawa** [comment]
#2240 立てました
