### ISSUE TITLE
Number of issue of redmine in "Incident" column was not a consecutive number on "Events" page

### ISSUE THREAD

**Issue by miyashita-k** [project-hatohol/hatohol#963]
Number of issue of redmine in "Incident" column was not a consecutive number on "Events" page.

"Events" page:
![_016-2](https://cloud.githubusercontent.com/assets/8952002/5953422/ef4ae5c6-a7cc-11e4-8190-4edcb3d284fa.png)

Incident column:
```
http://192.168.1.3/issues/540
http://192.168.1.3/issues/541
http://192.168.1.3/issues/537
http://192.168.1.3/issues/538
http://192.168.1.3/issues/539
```

**Comment by miyashita-k** [comment]
イベント画面のRedmineのissueの番号が連番になっていません。

古い時間のイベントでもRedmineのissueの番号が大きかったり、新しい時間のイベントでもRedmineのissueの番号が小さかったりしているようです。

古いイベントから順々に、Redmineにインシデント連携するような処理が走り、
issueの番号も順々に大きくなって、新しいイベントほど、Redmineのissueの番号も大きくなると予想していましたが、
現状、そのような仕様になっていないのでしょうか？

イベント画面における時間とRedmineのissueの番号の順番は、どのような規則性になっているかご教示いただけないでしょうか？

**Comment by ashie** [comment]
インシデントの登録(アクションも同じ)は、イベントの時間順ではなく、イベントのID順に
行われます。ZabbixのIDは時間順に並んでいるとは限らないため、必ずしも時間順に並ぶ
わけではありません。

ただ、もしかしたら私の方で何か見落としがあって、他にも何か順番に影響する要素がある
かもしれません。

**Comment by miyashita-k** [comment]
インシデントが連携される順番について理解できました。
コメントいただき、ありがとうございます。
