### ISSUE TITLE
[client] Add expires and no-cache in the response

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/hatohol#979]
YOSHIFUJI-san said that 'Log out' doesn't work when IE (operator side) and apache are used.
And he thinks some caching mechanism causes the problem and asked me how to add expires and no-cache in an HTML header.

**Comment by kz0817** [comment]
I think
For HTML files, they should be inserted into client/viewer/base_ajax.html
For APIs to Hatohol server, we should fix client/hatohol/forwardview.py

**Comment by kz0817** [comment]
The header elements on the Django's framework seems to be inserted as below according to http://www.djangoproject.jp/doc/ja/1.0/ref/request-response.html#django.http.HttpResponse
>>> response = HttpResponse()
>>> response['Pragma'] = 'no-cache'

**Comment by yoshfuji** [comment]
Thank you.  So far, I use mod_expires apache module as follows:
ExpireDefault "now"
ExpireActive on

**Comment by cosmo0920** [comment]
For now, #994 and #1001 are merged into master.
This issue is fixed?
Or, there is an issue?
