### ISSUE TITLE
[web] Noisy log "A logger: viewer.userconfig has been created."

### ISSUE THREAD

**Issue by yoshfuji** [project-hatohol/hatohol#987]
If hatohol runs with Apache, we see tons of
| [:error] [pid xxxx] A logger: viewer.userconfig has been created.

I think this is too noisy for ordinal users.

We have several options.
1) Just remove such lines in userconfig.py
2) Change level from INFO to DEBUG (userconfig).
3) Do not emit INFO to console (django).

**Comment by ashie** [comment]
client/viewer/userconfig.py:

```python
     28 logger = logging.getLogger(__name__)
     29 logger.info('A logger: %s has been created' % __name__)
```
