### ISSUE TITLE
"Number of hosts" of Nagios is not display correctly in Dashboard.

### ISSUE THREAD

**Issue by o-wakabayashi** [project-hatohol/hatohol#993]
![counterror](https://cloud.githubusercontent.com/assets/8002282/6072908/a81d4684-adea-11e4-82df-201505ca302b.png)

->Number of count "5" is correct value.

mysql> select * from hosts where server_id=6;
+----+-----------+----------------------+--------------+----------+
| id | server_id | host_id              | host_name    | validity |
+----+-----------+----------------------+--------------+----------+
| 36 |         6 |                   48 | machine9_2   |        6 |
| 37 |         6 |                   59 | machine9_3   |        6 |
| 38 |         6 |                   60 | machine9_4   |        6 |
| 39 |         6 |                   61 | machine9_5   |        6 |
| 35 |         6 |                   88 | machine9_1   |        6 |
| 40 |         6 | 18446744073709551612 | Nagios1_SELF |        3 |
+----+-----------+----------------------+--------------+----------+
6 rows in set (0.00 sec)

The value of "validity" is incorrect.

**Comment by ashie** [comment]
#995
